- sqlglot/dialects.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/test_dialects.py
Presto: https://prestodb.io/docs/current/functions/datetime.html#month
does not accept varchar, but accepts timestamp or date
Duckdb:
https://duckdb.org/docs/sql/functions/timestamp
does not accept string, but accepts timestamp or date
Hive/Spark:
accept string, date or timestamp
But we saw users using string
> Support Month function

- README.md
- sqlglot/dialects.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/rewriter.py
- sqlglot/tokens.py
- tests/test_dialects.py
- tests/test_parser.py
- tests/test_transpile.py
This is a proposal to improve the validation for number of arguments passed into functions. With this change the following invalid expression fails:
```python
>>> sqlglot.parse("IF(a > 0, a, b, c)")
...
sqlglot.errors.ParseError: The number of provided arguments (4) is greater than the maximum number of supported arguments (3). Line 0, Col: 17.
IF(a > 0, a, b, c)
```
We still preserve support for expressions with variable length arguments:
```python
>>> sqlglot.parse("ARRAY(a, b, c)")
expressions
[(COLUMN this: a, db: , table: , fields: ), (COLUMN this: b, db: , table: , fields: ), (COLUMN this: c, db: , table: , fields: )]
[(ARRAY expressions:
(COLUMN this: a, db: , table: , fields: ),
(COLUMN this: b, db: , table: , fields: ),
(COLUMN this: c, db: , table: , fields: …
```
> Improve validation of number of arguments passed into a function. Improve support for functions with variable length arguments

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
Decided to get rid of the TokenType in a tree completely.
> Simplify the Literal expression by removing the token type

- sqlglot/dialects.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/test_dialects.py
- tests/test_expressions.py
https://duckdb.org/docs/sql/functions/timestamp
duckdb returns a ts if input is a ts
duckdb returns a date if input is a date
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-DateFunctions
hive always returns a date even if the input is ts, date or ts
https://prestodb.io/docs/current/functions/datetime.html#date_add
presto returns a ts if input is a ts
presto returns a date if input is a date
Let's add a new expression called `TsOrDsAdd`
> Add TsOrDsAdd

- sqlglot/generator.py
- sqlglot/tokens.py
- tests/test_dialects.py
hive uses backslash as an escape from both quotes and backslashes,
this is common in regexes and needs to be removed.
hive
select '\\hi'
presto
select '\hi'
even more confusing is that hive ignores odd numbers of backslashes
hive
select '\hi'
the backslash is ignored, i'm choosing to treat this as user error and
ignore this case
> handle backslash escapes

- sqlglot/__init__.py
- sqlglot/tokens.py
- tests/test_dialects.py
Thanks so much for implementing this so quickly re: #58 
I've tested your changes against more complex SQL statements, and it all looks great with one tiny bug - the tokeniser keeps consuming tokens forever when encountering a literal.  
Example of error:
```
sql = """
POW(2S, 3)
"""
sqlglot.parse_one(sql, read="spark").sql(dialect="duckdb")
```
Here's a proposed fix, and associated test.
> Fix numeric literal tokeniser

- README.md
on line 45 of the readme file in the example there is a typo (an extra parenthesis). 
As a result the example gives a syntax error.
```python
sqlglot.transpile(sql, write='spark', identify=True, pretty=True)[0])
```
just fixing it so the example works
> typo on Readme code example

- README.md
- sqlglot/__main__.py
- sqlglot/dialects.py
- sqlglot/generator.py
- sqlglot/time.py
- tests/test_dialects.py
- tests/test_time.py
- tests/test_transpile.py
longstanding tough issue, i finally fixed it
sqlglot parses time formats into python syntax, generator turns python syntax into target dialect
> add time formats fixes #1

- sqlglot/dialects.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
The [`left`](https://spark.apache.org/docs/latest/api/sql/index.html#left) and [`right`](https://spark.apache.org/docs/latest/api/sql/index.html#right) functions are missing from the Spark dialect.
I've tried to implement the `left` and `right` functions in a way that's consistent with the rest of the codebase.
Separate to their implementation, a challenge is the collision between the `left` and `right` keywords, and the Spark functions with the same name. 
Totally understand if you would rather not introduce additional complexity into the tokeniser to resolve this ambiguity i.e. would rather just close this PR and not support the Spark-specific `left` and `right` SQL functions.  If so, at least I understand the codebase better and hopefully can provide future similar PRs for functions …
> Add support for Spark left and right fns

- benchmarks/bench.py
- setup.py
- sqlglot/expressions.py
- tests/test_expressions.py
When using `expression.transform`, we often pass in a function. It would be more flexible if we can allow users to pass in additional arguments to the function to override certain behaviors.
@tobymao, PTAL
> Allow additional function arguments in transform

- README.md
- sqlglot/__init__.py
- sqlglot/expressions.py
- tests/test_build.py
Here's a stab at builders for logical expressions.
It supports both ways we discussed:
```python
from sqlglot import and_, or_, condition
and_("a=1", "b=1", or_("c=1", "d=1")
condition("c=1").or_("d=1").and_("b=1", "a=1")
```
@nolamesa @tobymao
> Logical expression builders

- sqlglot/dialects.py
- tests/test_dialects.py
This PR added COALESCE and COUNT SQL transform for Tableau dialect
Note: Tableau does not support COALESCE func, transform to use IFNULL instead.
Reviewers:
@tobymao
> add COALESCE and COUNT SQL transform for Tableau dialect

- sqlglot/parser.py
- tests/test_parser.py
Parsing was raising an `AttributeError: 'NoneType' object has no attribute 'arg_types'` error is _parse_statement returned `None`.
This raises a proper ParseError instead.
@tobymao
> Properly catch parse error when no statement follows CTE

- tests/test_parser.py
Currently sqlglot parses incorrectly qualified table names such as .foo
properly. Added a test to make sure this is a feature instead of a bug.
It can be very useful when people define tables with interpolation such
as "{database}.{table_name}" where database is empty string
> Added tests for table parsing

- sqlglot/expressions.py
- sqlglot/helper.py
- sqlglot/parser.py
- tests/test_build.py
* join('table')
* join('select x from table')
* join('x on a = b')
* join('join x on a = b')
* join (Join|Select|Table|Subquery)
> Support more cases for join builder:

- sqlglot/optimizer/projection_pushdown.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/projection_pushdown.sql
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/qualify_columns__invalid.sql
I had some bugs with correlated subqueries.
I think this is a cleaner way of handling them.
@tobymao This removes "correlated_selectables". I know you need it in your other branch. However, this introduces "is_correlated_subquery", which I think will be better for you.
> fix(optimizer): correlated subqueries are hard

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/tcp-h.sql
This seems to work.
I'm not too sure what we should for this case though:
```sql
SELECT a, b FROM x ORDER BY a;
-- this PR resolve this to:
SELECT x.a AS a, x.b AS b FROM x ORDER BY a;
-- but maybe it should be?:
SELECT x.a AS a, x.b AS b FROM x ORDER BY x.a;
```
> Allow GROUP BY and ORDER BY to reference output columns

- sqlglot/dialects.py
- sqlglot/expressions.py
- tests/test_dialects.py
I'm hoping you're still open to accepting random PRs.
This one adds support for the `levenshtein` function, which would be a great help for us within `splink`.
For example:
`sqlglot.transpile("levenshtein(a, b)", read=None, write="presto")` -> `LEVENSHTEIN_DISTANCE(a, b)`
`sqlglot.transpile("levenshtein(a, b)", read=None, write="sqlite")` -> `EDITDIST3(a, b)`
=============================================================================
For completeness, here are my notes and links for available **levenshtein** functions within your supported SQL dialects:
* Duckdb - Levenshtein
* Hive - Levenshtein
* MySQL - Doesn’t appear to be implemented
* Postgres - Levenshtein
* Presto - Levenshtein_distance
* Spark - Levenshtein
* SQLite - under the alias editdist3
Duckdb: …
> Transpile levenshtein

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
This fixes that qualify_columns bug for tcph-20.
I don't know if the resulting tcph-20 query is right - seems to have a bug in decorrelating subqueries. So I left that test out of this PR.
> fix: nested correlated subqueries

- sqlglot/expressions.py
Fix `alias_` docstring for `table` parameter
> Fix alias_ docstring for `table` parameter

- sqlglot/dialects.py
- sqlglot/tokens.py
- tests/test_dialects.py
- Mappings between INT64 and INT, BIGINT, SMALLINT, TINYINT with unit tests
- Mappings between FLOAT64 and FLOAT, DOUBLE with unit tests
- Mappings between NUMERIC and DECIMAL with unit tests
- Mappings between STRING and TEXT with unit tests
Haven't added support for other types of casting (e.g. CHAR/VARCHAR/BYTES/TIMESTAMPTZ) due to additional overhead.
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
> feat(gh-203): Add support for BigQuery.

- sqlglot/__init__.py
- sqlglot/diff.py
- sqlglot/errors.py
- tests/test_diff.py
Previous:
> The implementation relies on a variance of the Myers algorithm with additional heuristics. To apply the Myers algorithm both input expression trees are first unfolded into their list representation using the topological order. 
> 
> To make the output cleaner we apply the following heuristics when checking the equality of individual nodes:
> 1. If both nodes are a `Column`, `Literal`, `Table` or `TableAlias` we do full equality check.
> 2. For `Anonymous` and `DataType` nodes we only check the "this" attribute for equality.
> 3. For all other nodes we only check whether they have a matching type. 
> 
> Thus if the number of arguments changed for a particular node the algorithm doesn't interpret this as a change to this particular node. Instead we expect this change to be …
> Introduce ability to calculate changes between two expression trees (diff)

- sqlglot/optimizer/qualify_columns.py
When you select a column but it's not in the schema. 
Before this the optimizer said "Ambiguous column" and now it says "Unknown column"
Not sure if you want to add this.
> Unknown column (not in schema)

- sqlglot/dialects/presto.py
- sqlglot/dialects/spark.py
- tests/test_dialects.py
`ARRAY_FILTER` is called `FILTER` in spark. So I did a rename in the generator for Spark so it refers to the function correctly.
> Add support for Spark's filter function

- sqlglot/dialects/duckdb.py
- tests/test_dialects.py
Duckdb dialect transpiles `DATE_DIFF` to `DATE_0 - DATE_1` which is an interval
`DATE_DIFF` exists in duckdb: https://duckdb.org/docs/sql/functions/date and returns an int as expected
> Use date_diff in duckdb

- sqlglot/generator.py
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
- tests/fixtures/optimizer/unnest_subqueries.sql
- tests/test_dialects.py
It looks like the code originally intended to have this behavior but was doing a length check on a string when it looks like the author thought it was a list. I confirmed that Spark and Presto prefer this syntax.
> Fix bug with parenthesis on single lambda variable

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/test_dialects.py
Snowflake's `TO_TIMESTAMP` function can be used in multiple different ways (corresponding to both of `sqlglot`'s `StrToTime` and `UnixToTime`); this PR adds support for parsing that function.
> Support for Snowflake TO_TIMESTAMP function

- sqlglot/generator.py
- tests/test_dialects.py
i've changed references generator because it was raising syntax error both on postgres and sqlite
```
sqlite> create table a (id INTEGER PRIMARY KEY);
sqlite> create table b (id integer primary key, a_id integer, foreign key (a_id) references a(id));
sqlite> create table c (id integer primary key, a_id integer, foreign key (a_id) references (a) (id));
Parse error: near "(": syntax error
key, a_id integer, foreign key (a_id) references (a) (id));
error here ---^
```
If theres a dialect which uses `REFERENCES (table) (id)`, how can i add that?
> change references generator

- sqlglot/dialects/postgres.py
- tests/test_dialects.py
This PR implements the necessary bits to translate [`TO_CHAR` format strings](https://www.postgresql.org/docs/current/functions-formatting.html)
into Python strftime format strings, enabling transpilation across the various
sqlglot dialects.
> Implement `TO_CHAR` format string translation

- sqlglot/dialects/spark.py
- tests/test_dialects.py
ARRAY[BYTE] isn't even valid spark sql (it should be ARRAY<BYTE>),
and it's not the same type as BINARY.
https://spark.apache.org/docs/latest/sql-ref-datatypes.html
> Fix spark binary type

- sqlglot/errors.py
- sqlglot/parser.py
- tests/helpers.py
- tests/test_parser.py
- tests/test_transpile.py
This is a big change, so let's think about it.
This raises a "super error" if error level is RAISE. That's still the default, so users will start getting larger error messages.
Other options:
1. Change RAISE to only raise the first error and log the rest
- I'm not sure why a user would want this behavior
2. Make IMMEDIATE the default
3. Remove IMMEDIATE and make RAISE raise immediately
> ErrorLevel.IMMEDIATE

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
- tests/test_dialects.py
According to https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators, for the UNION command in BigQuery, "You must specify ALL or DISTINCT". 
This updates the BigQuery dialect generator to output `UNION DISTINCT` rather than `UNION` when distinct is True.
> Generate UNION DISTINCT correctly for BigQuery syntax

- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- tests/test_dialects.py
In #307, I added support for Snowflake's TO_TIMESTAMP function, which includes the ability to parse timestamps with scale (seconds, milliseconds, or microseconds), where the parsing was done by using integer division to store the timestamp with adjusted scale.
This pull request modifies that to store the scale as a separate parameter. This means that generators for other dialects can choose the correct function based on scale (e.g., Spark has `TIMESTAMP_SECONDS`, `TIMESTAMP_MILLIS`, and `TIMESTAMP_MICROS`); doing it this way avoids lossiness in timestamps and also does not break when placeholders in prepared statements are passed as the timestamp itself.
> Better unix timestamp with scale argument for Snowflake and Spark

- sqlglot/dialects/snowflake.py
- tests/test_dialects.py
Snowflake uses both ARRAY_AGG and ARRAYAGG (https://docs.snowflake.com/en/sql-reference/functions/array_agg.html); this PR adds support to properly parse the latter.
> Add parsing for Snowflake ARRAYAGG to ArrayAgg

- sqlglot/tokens.py
> Missing backslash on CRLF whitespace in tokenizer

- README.md
- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
And doc incompatibility with sqlglot annotations when reading the MySQL dialect.
Reference:
https://dev.mysql.com/doc/refman/8.0/en/comments.html
* "From a # character to the end of the line."
(And there's a small divergence from the SQL standard on `--`)
> Add MySQL-dialect `#` comment extension

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
add support for table and column check constraints. fixes https://github.com/tobymao/sqlglot/issues/389
references:
https://www.postgresql.org/docs/current/sql-createtable.html
https://www.sqlite.org/syntax/column-constraint.html
https://dev.mysql.com/doc/refman/8.0/en/create-table.html
> add support for table and column check constraints

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_build.py
We already have SORT & CLUSTER expression and SORT_BY & CLUSTER_BY tokens, they are currently used in DDLs but they can also be used in expression builder. This PR adds that support.
> feat: Add sort_by and cluster_by to expression builder

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
- Added support for Snowflake's [dollar-quoted string constants](https://docs.snowflake.com/en/sql-reference/data-types-text.html#label-dollar-quoted-string-constants).
- Added string escape config for Snowflake. Snowflake supports single-quote as an escape character, but only for single-quote characters.
- Added a test case including a few escape sequences, adopted from the Snowflake documentation.
> Snowflake string literals

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_transpile.py
Added support for nested double-colon cast.
Example
```
SELECT expr::INT::BOOLEAN
```
> Add support for nested double-colon cast

- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
- tests/test_expressions.py
Implemented the trim function based (mostly) on [this](https://www.w3resource.com/sql/character-functions/trim.php).
- As I understand, Hive supports the syntax `[L|R]TRIM(target)`. If that's true, this implementation doesn't cover Hive.
- Do we generally want to provide links in comments (eg. for sources), like I did in `_parse_trim`?
fixes #425
> Add trim function

- sqlglot/parser.py
- tests/dialects/test_dialect.py
This aims to fix the following issue (mentioned in [this](https://github.com/tobymao/sqlglot/discussions/431) discussions post):
Example (valid sql):
```
SELECT * FROM foo WHERE some.column LIKE 'foo' || another.column || 'bar'
```
Result:
```
Invalid expression / Unexpected token. Line 1, Col: 48.
SELECT * FROM foo WHERE some.column LIKE 'foo' || another.column || 'bar'
~~
```
> Support concatenation in like expressions

- sqlglot/dialects/oracle.py
- tests/dialects/test_dialect.py
oracle does not allow "AS" between table and alias
https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10002.htm#i2126863
> fix oracle table alias

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
This PR aims to add support for the "joined tables" or "join construct" form that uses parentheses. Example:
```
SELECT * FROM (table1 LEFT JOIN table2 ON 1 = 1)
```
Sources:
- https://www.postgresql.org/docs/current/queries-table-expressions.html
- https://dev.mysql.com/doc/refman/8.0/en/join.html
fixes #423
> Add support for parenthesized joined tables

- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
The following form is allowed by postgres but is not currently supported. This PR aims to fix that.
```
SELECT p1.id, p2.id, v1, v2
FROM polygons p1, polygons p2,
LATERAL vertices(p1.poly) v1,
LATERAL vertices(p2.poly) v2
WHERE (v1 <-> v2) < 10 AND p1.id != p2.id;
```
Source (7.2.1.5 LATERAL Subqueries): https://www.postgresql.org/docs/current/queries-table-expressions.html
> Support functions after lateral & add distance op for postgres

- sqlglot/generator.py
- tests/test_transpile.py
Some folks have a preference for leading commas, ex:
```sql
SELECT
foo
, bar
, baz
```
instead of the current behavior, which is trailing commas:
```sql
SELECT 
foo,
bar,
baz
```
this creates an option for leading commas
> Add support for `SELECT` leading commas in SQL generation

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
This PR expands Snowflake dialect support for Snowflake-specific timestamp types and timestamp-related functions.
1. `EXTRACT` as a synonym for `DATE_PART`
Snowflake supports both `EXTRACT` and `DATE_PART`. The `FROM` and comma-delimited invocation style are supported for both. I confirmed all of the following are valid in Snowflake:
```
SELECT   EXTRACT( month from '2022-09-01'::DATETIME);
SELECT   EXTRACT( month,     '2022-09-01'::DATETIME);
SELECT   EXTRACT('month',    '2022-09-01'::DATETIME);
SELECT DATE_PART('month',    '2022-09-01'::DATETIME);
SELECT DATE_PART( month,     '2022-09-01'::DATETIME);
SELECT DATE_PART( month FROM '2022-09-01'::DATETIME);
```
2. `TIMESTAMPLTZ` type
Added support for Snowflake's relatively unique `TIMESTAMP WITH LOCAL TIME ZONE`.
3. `TIMESTAMP` type …
> Snowflake timestamps

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
This can probably be written in a better way. I tried making the intent clearer by doing `if expression.is_var_len_args`, but apparently it doesn't work because the BitwiseLeft/RightShift tests fail:
```
ERROR: test_bits (tests.dialects.test_hive.TestHive) [x >> 1 -> spark]
...
if expression.is_var_len_args
AttributeError: 'BitwiseRightShift' object has no attribute 'is_var_len_args'
```
Fixes #474
> Fix rename_func so it handles var len arg functions

- sqlglot/expressions.py
- tests/test_expressions.py
Inspired by [this](https://github.com/tobymao/sqlglot/discussions/462) discussion.
Demo:
```python
from sqlglot import exp, parse_one
expression_tree = parse_one("SELECT a, b FROM x")
def fun(node):
if isinstance(node, exp.Column) and node.name == "b":
return None
return node
transformed_tree = expression_tree.transform(fun)
transformed_tree.sql()
```
Which outputs:
```python
SELECT a FROM x
```
Allowing node deletion could certainly lead to problems, eg. removing the only condition in a where clause, although the same thing could be said about other transformations too, so this seems like a useful feature to have.
> Add support for removing AST nodes using transform

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
BigQuery doesn't support `VALUES` for statically creating a table with values but it does support the same functionality using `UNNEST` on a struct. One tricky part is that it requires that the `UNNEST` not be a subquery like what `VALUES` commonly is. Therefore on BigQuery I check if the target of a subquery is a VALUES expression and if not then I parse it like normal otherwise I convert the subquery to an `UNNEST`.
> Add values to unnest support for bigquery

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_columns.sql
Currently if someone has a BROADCAST hint in their SQL and wants to optimize the SQL sqlglot will error since it will say that the referenced "column" does not exist. The column is actually a table. The solution in the PR is to exclude that column from the list of columns in the scope so it does not get checked as being a valid column.
> Ignore column references in hints

- sqlglot/parser.py
- tests/fixtures/identity.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_columns.sql
Currently the lambda parser treats the lambda variables as columns when they really are identifiers. This issues becomes more clear when using the optimizer since it would look for the definitions of those columns in sources and the wouldn't exist.
> Have parser convert lambda variables to identifiers

- sqlglot/dialects/starrocks.py
- tests/dialects/test_dialect.py
While doing some testing against starrocks i noticed a couple of functions were not properly wired up. 
Specifically a couple of date parsing and unix time parsing functions. I didn't test all of them but fixed the ones I encountered.
> Wire up a couple of time utilities to starrocks

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
It is the flavor of datetime which "aligns with the SQL Standard".
Docs: https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=azure-sqldw-latest&preserve-view=true
> Use DATETIME2 in TSQL as default timestamp type

- sqlglot/__init__.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/fixtures/identity.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/pushdown_projections.sql
Some naunces about values that I figured out while working on this:
Values with parenthesis around them is valid but the tab alias assigned cannot be used in the select expression if you have the parentheses around them. It does work correctly though if there is no parentheses around values so we remove them by default now.
You cannot put double quotes around the column names in `tab(<col>)` alias and they cannot have quotes in the select expression. There will be a follow up PR to ensure snowflake doesn't do that when using optimize to add the quotes.
> Classify Values as a Derived Table

- README.md
The README example differs from the current output of `transpile`:
```python
>>> sqlglot.transpile("SELECT EPOCH_MS(1618088028295)", read='duckdb', write='hive')
['SELECT FROM_UNIXTIME(1618088028295 / 1000)']
```
> Fix transpilation example in README

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/mysql.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_hive.py
Currently sqlglot does not render the unit argument in `DATE_DIFF`, which is a required argument in BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_diff.
Note: some dialects, like MySQL, don't support a unit argument. In those cases, arguably we should multiply or divide to fix the units, i.e. `DATE_DIFF(start, end, MINUTE)` in BigQuery should become `1440 * DATEDIFF(start, end)` in MySQL. I did not attempt to implement that in this diff.
> Fix DATE_DIFF rendering in BigQuery

- sqlglot/expressions.py
- tests/dialects/test_bigquery.py
- tests/test_build.py
Not sure if this is the correct approach for this, but the idea was to follow the parser's output:
```python
>>> sqlglot.parse_one("RANK() OVER (y PARTITION BY a, b ORDER BY x DESC) AS foo")
(ALIAS this: # <~~~~ For the AS <alias_name> form, we get an ALIAS node
(WINDOW this:
(ANONYMOUS this: RANK), partition_by:
(COLUMN this:
(IDENTIFIER this: a, quoted: False)),
(COLUMN this:
(IDENTIFIER this: b, quoted: False)), order:
(ORDER expressions:
(ORDERED this:
(COLUMN this:
(IDENTIFIER this: x, quoted: False)), desc: True, nulls_first: False)), alias:
(IDENTIFIER this: y, quoted: False)), alias: # <~~~~ For a named_window alias, we get the IDENTIFIER node
(IDENTIFIER this: foo, quoted: False))
```
I think that we only use the alias inside the parentheses (here: y) for the BigQuery dialect, so …
> Fix alias builder for window expressions

- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/merge_subqueries.py
- sqlglot/optimizer/scope.py
- sqlglot/parser.py
- tests/dialects/test_spark.py
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/test_optimizer.py
Prior to this change hints that contain tables would actually parse them into a column instead of a table. The initial change here is to have them properly parse into tables. The next change is in the optimizer where we tell the `merge_subqueries` rule that it can merge hints and then provided a function to do that merge. 
Hints that are not "JoinHints" are left untouched in this PR since they parse into columns and are handled correctly by default.
> Add table hint and support it in optimizer

- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
[This source](https://blog.andreiavram.ro/postgresql-null-composite-type/) says that the following query:
```sql
select id, email, deleted::text from users where not deleted isnull
```
behaves differently than these two:
```sql
select id, email, deleted::text from users where deleted notnull
select id, email, deleted::text from users where deleted is not null
```
Do we want to add an `IsNull` expression node and generate `.. WHERE NOT deleted ISNULL` for the first one which is the semantically correct output?
Fixes #569
> Add support for postgres notnull, isnull syntax

- sqlglot/optimizer/eliminate_joins.py
- tests/fixtures/optimizer/eliminate_joins.sql
We can also remove cross joins if we know the inner query only has one output row.
> Optimizer: Eliminate cross joins

- sqlglot/dialects/duckdb.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
https://duckdb.org/docs/sql/data_types/overview
DuckDB expects that array are declared using `INTERIOR[]` instead of `ARRAY<INTERIOR>`.
> Fix duckdb array type

- sqlglot/expressions.py
- tests/test_expressions.py
Pulled this out of https://github.com/tobymao/sqlglot/pull/568 since I need this immediately in another project.
Given a sql table name is return a table expression.
> Add to_table helper

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_hive.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
I don't see anywhere in the DuckDB documentation that it says that you can define any table properties. It also doesn't support partitioning. So this PR removes all table properties from DuckDB generated DDL statements.
> Remove table properties from duckdb

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
Reference documentation:
https://duckdb.org/docs/sql/functions/dateformat
https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html
https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements
https://prestodb.io/docs/current/functions/datetime.html
[Issue](https://github.com/tobymao/sqlglot/issues/606) to support remaining BigQuery functions
> Add support for DuckDB's unique time format patterns

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
Attempt to qualify order by references that appear to be column references and not aliases.
This helps in Minerva SQL as we need columns to be qualified to aid in rewriting queries. There is also value in doing this optimization to remove some inconsistency with how different engines handle this case of an ambiguous alias/column reference in an order by clause.
> determine order by references when qualifying columns

- sqlglot/__main__.py
- sqlglot/parser.py
- tests/test_parser.py
errorlevel.RAISE kind of sucks, i think going to immediate is better, and we're bumping version 9 tomorrow anyways, thoughts?
> change default error level to immediate

- sqlglot/dataframe/sql/column.py
- sqlglot/dataframe/sql/functions.py
- sqlglot/expressions.py
- sqlglot/helper.py
- sqlglot/time.py
- tests/dataframe/unit/test_functions.py
- tests/test_time.py
Thanks to the test @tobymao added we can now identify when we are using an anonymous function when there is actually a SQLGlot function we should be using. This PR addresses all of those cases. 
In addition I also cheated a bit with the initial implementation of the functions with lambdas but assuming the variable names of the lambdas and then providing overrides to those that weren't compatible with the PySpark API. This removes all of that and also cleans up the lambda implementation a lot. 
Finally this also removes some excessive function calls.
> Cleanup of DataFrame API Functions

- sqlglot/dataframe/sql/functions.py
We don't need to do the convert here since it will be converted later as the value is cast to a DataFrame column.
> Remove extra function

- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
only qualify non-alias column references in the having clause.. This attempts to recreate the mysql resolution algorithm from tests performed.
> only qualify non-alias column references in the having clause

- sqlglot/expressions.py
- tests/test_build.py
> Add using for join builder, update some comments

- sqlglot/dialects/__init__.py
- sqlglot/dialects/databricks.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_databricks.py
- tests/dialects/test_tsql.py
I'm currently trying to go towards databricks and while dealing with datediff and date_add noticed that databricks is not limited to just the spark sql language.
It has implemented some functions in the TSQL style. DATEDIFF(unit, int, datetime) and DATEDIFF(datetime, datetime) both exist in databricks. As well as DATE_ADD(datetime, int) and DATEADD(unit, int, datetime). 
The spark transpiler should not deal with this since the TSQL like functions do not exist in spark (as far as I am aware of).
Spark Date functions : https://spark.apache.org/docs/2.3.0/api/sql/search.html?q=date
Databricks TSQL DATEDIFF: https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual/functions/datediff3
Datebricks spark DATEDIFF: https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual …
> Add (Azure) Databricks dialect

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_tsql.py
Added support for the CROSS APPLY and OUTER APPLY from T-SQL. In order to achieve this I had to add the "view" attribute to make the distinction between LATERAL VIEW and LATERAL JOINS.
> TSQL support for lateral joins

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
Allow valid parsing of `CREATE ... TRANSIENT ... TABLE` statement in Snowflake.
Proposed behavior for transpiling to other dialects is to simply omit it. Did this with class attribute on the Snowflake dialect `Generator` + a janky-ish check in `generator.create_sql`. If more preferred way, happy to change.
> Allow CREATE ... TRANSIENT ... TABLE for Snowflake

- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Adding TOP for T-SQL
Added the token to the TSQL dialect because by adding it in the generic one it interfered with the transpiler test 'select TOP.x' as TOP can be a seen as a table name there.
> adding top for tsql

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/time.py
- tests/dialects/test_tsql.py
Attempt at TSQL format, format is quite versatile in that it can format any input type.
I am not fond of the regex but it does the trick in sort of safely switching between number formatting and date formatting.
The switch is needed since most target dialects will not have a versatile format like TSQL.
> TSQL format

- sqlglot/tokens.py
- tests/test_tokens.py
This PR aims to pave the way for changing how we handle comments; instead of discarding them, keep them so that maybe they can be used later on meaningfully.
One such example is trying to preserve comments during SQL formatting. Ideally, we'd like to support the following:
```python
>>>
>>> sql = """
... SELECT -- comment
...   x, -- comment
...   y, -- comment
... FROM foo"""
>>>
>>> print(sqlglot.transpile(sql, pretty=True)[0])
SELECT -- comment
x, -- comment
y, -- comment
FROM foo
```
The problem of handling comments correctly after we parse SQL into an AST is not a simple one, but we may manage to come up with some heuristics / best-effort approaches that work fine for our needs. Feedback is very welcome!
Sources:
- …
> Attach comments to tokens

- sqlglot/schema.py
- tests/test_schema.py
When using qualified table names like database.table, the retrieval from the schema dictionary failed. 
I changed the way the lookup takes place by taking into account the depth of the schema.
> Correction in column type retrieval in case of qualified table names

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- tests/dialects/test_dialect.py
- tests/fixtures/optimizer/qualify_columns.sql
The current sqlglot implementation of DATE_TRUNC assumes the timestamp is the first argument, but many dialects implement a version where the arguments are reversed as well as having the "unit" argument being just a string.
Since only bigquery uses the existing signature, we will use the new signature format as the default and implement a custom parser for bigquery where the arguments are reversed.
> support alternate implementation of DateTrunc function

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
MySQL SET commands.
This also adds MySQL's session parameters: @@
> SET commands

- sqlglot/optimizer/annotate_types.py
- tests/test_optimizer.py
Made a new function to support type inheritance for specific functions that should only inherit from specific attributes. The function allows one of the following parameters:
- A string and that will refer to an entry within the args dictionary, the array of expressions or its single expression will be included in the inheritance of datatypes;
- An expression;
- An list of expressions.
From the list of expressions applicable, the datatype will be inherited.
> Type inheritance for functions based on args

- README.md
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
- tests/fixtures/identity.sql
- tests/fixtures/pretty.sql
- tests/test_expressions.py
- tests/test_parser.py
- tests/test_transpile.py
- `select 1 /* comment */ + 1`.
- `select * from x --comment`.
> Replace annotations with SQL comments

- sqlglot/optimizer/pushdown_predicates.py
I have a test in minerva that demonstrates why this needs to be copied, but I couldn't think of a way to do it with your existing tests. Basically the parent references are incorrect after pushing down eg
```
select a from (select a from x) x where a > 0 and a < 2
```
I can add a custom test if you'd like or if you can think of one I can add it
> copy column during replace

- sqlglot/parser.py
- tests/dialects/test_dialect.py
- tests/dialects/test_starrocks.py
- tests/test_parser.py
the current implementation is overly permissive for what it parses as a data type. this change tries to further disambiguate type literals of the form `TIMESTAMP(3) '2022-01-01'` | `DATE(1) '2022-01-01'` from functions `TIMESTAMP('2022-01-01')` | `DATE('2022-01-01')` | `BOOLEAN(1)` etc.
> optionally check whether value is a function when parsing data type

- sqlglot/dialects/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- tests/dialects/test_dialect.py
- tests/dialects/test_drill.py
This PR adds a dialect for Apache Drill to SQLGlot. 
Remaining work:
> Add Apache Drill Dialect to SqlGlot

- sqlglot/generator.py
- tests/fixtures/pretty.sql
This doesn't address a serious issue; it's more of a "formatting one". It aims to address examples similar to the following:
```python
>>> sql = """
... select
...   * /* multi
... line */
... """
>>> print(sqlglot.transpile(sql, pretty=True)[0])
SELECT
*/* multi
line */
```
With this change, it's instead formatted as:
```python
SELECT
* /* multi
line */
```
> Small comment formatting fixup

- sqlglot/planner.py
Steps to reproduce bug caused by [this](https://github.com/tobymao/sqlglot/blob/main/sqlglot/planner.py#L142) line:
```python
>>> from sqlglot.planner import Plan
>>> sql = """
... SELECT
...   x.a,
...   SUM(x + 1)
... FROM x AS x
... JOIN y AS y
...   ON x.a = y.a
... GROUP BY x.a
... """
>>> expr = sqlglot.parse_one(sql)
>>> plan = Plan(expr)
>>> print(expr.sql(pretty=True))
SELECT
x.a,
SUM("_a_0")
FROM x AS x
JOIN y AS y
ON x.a = y.a
GROUP BY
x.a
```
> Fix mutation bug in planner

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_hive.py
- tests/dialects/test_redshift.py
- tests/dialects/test_spark.py
- tests/test_expressions.py
Opening this for some early feedback. The end goal is to simplify the way properties are handled, so that we don't need to store each prop name in `this`. The parser can also be simplified because all properties are more or less parsed according to the same logic: `PROP_NAME [=] PROP_VALUE`.
> Refactor properties

- README.md
- sqlglot/errors.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/test_parser.py
- tests/test_transpile.py
Proposing attaching structured properties to `ParseError` for convenient programmatic access and formatting for arbitrary frontends.  
First proposed `sqlglot` PR, so please let me know of any style issues or conventions I may I have overlooked.
> Add structured ParseError properties

- sqlglot/generator.py
- sqlglot/parser.py
Now comments after "FROM" or "=" will no longer be discarded, though the order is currently messed up.
```sql
/*a*/SELECT/*b*/*/*c*/FROM/*d*/tbl/*e*/WHERE/*f*/1/*g*/=/*h*/2/*i*/--j
```
would previously translate to
``/* a */ /* b */ SELECT * /* c */ FROM tbl /* e */ WHERE 1 /* g */ = 2 /* i */ /* j */  ``
missing comments ``d, f, and h``
with this PR the above SQL parses and translates to
```
(SELECT expressions:
(STAR comments: ['c']), from:
(FROM expressions:
(TABLE this:
(IDENTIFIER this: tbl, quoted: False), comments: ['e']), comments: ['d']), where:
(WHERE this:
(EQ this:
(LITERAL this: 1, is_string: False, comments: ['g']), expression:
(LITERAL this: 2, is_string: False, comments: ['i', 'j']), comments: ['h'])), comments: ['a', 'b'])
/* a */ /* b */ SELECT * /* c */ FROM tbl /* e */ …
```
> improve comment parsing

- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
> Allow variable length arguments in duckdb's ARRAY_SIZE

- sqlglot/dialects/postgres.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
- tests/dialects/test_tsql.py
Fixes https://github.com/tobymao/sqlglot/discussions/754
This seems to do the trick, although I'll take a look an try to simplify/refactor things in a bit.
> Add support for STRING_AGG <-> GROUP_CONCAT transpilation

- sqlglot/dialects/postgres.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
The `DISTINCT` keyword is supported for postgres after all (it wasn't clear from the docs, but works just fine in postgres15).
As an extra, I fixed postgres array generation because the `ARRAY(...)` form isn't supported, I think.
Source on this: https://www.postgresql.org/docs/current/arrays.html
> Fix postgres string_agg parsing & array generation

- sqlglot/dialects/dialect.py
- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_hive.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
Snowflake does not support types associated with their MAP (OBJECT) and ARRAY types. Also Snowflake is limited in options for constructing maps and therefore you must use a function (`OBJECT_CONSTRUCT`) to create the MAP.
> Improve Snowflake array and map support

- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_redshift.py
https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html
Originally I thought I could just map ENCODE to TokenType.CONSTRAINT in redshift.py but that wouldn't be correct and wouldn't generate properly.
I also tried creating tokentype.ENCODE but that messes up existing parsing for ENCODE for other dialects, which is very different.
So instead I opted for creating tokentype.COMPRESSION and mapping ENCODE to COMPRESSION in redshift.py. 
https://docs.aws.amazon.com/redshift/latest/dg/c_choosing_dist_sort.html
I also made some very minor changes to how distkey, sortkey and diststyle are parsed. In particular, one of the default options for diststyle is 'all' which _parse_var can't handle, so I changed it to _parse_id_var. I decided to do the same for distkey and sortkey …
> added support for redshift ENCODE, fix parsing for DISTSTYLE ALL

- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_redshift.py
https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html
In Redshift you can have NULL explicitly as a column constraint, as opposed to NOT NULL.
Also, NVL and COALESCE are equivalent in Redshift: Redshift NVL accepts variable length arguments as opposed to just two. So I map NVL to COALESCE, and use .from_arg_list. (both nvl and coalesce are valid in Redshift though, so I didn't use rename_func).
One thing I just wanted to clarify: is function_fall_back_sql how functions are generated in generator.py? I couldn't find anything specifically for functions like COALESCE so I guess there's a general generator for the func class.
> Added NULL column constraint and NVL-COALESCE mapping for Redshift

- sqlglot/parser.py
- tests/dialects/test_postgres.py
https://www.postgresql.org/docs/current/sql-update.html
This seems like a Postgres exclusive feature that allows the syntax 'UPDATE TABLE1 T1 SET T1.SOME_COL = SOME_VALUE'.
Schema = True was preventing the alias from ever getting parsed. I don't think the schema is ever an argument for UPDATE in any dialects (correct me if I'm wrong) 
Just one other thing: what does the line `table = (not schema and self._parse_function()) or self._parse_id_var(False)` mean? In particular, what actually does id_var represent?
> Enable table aliasing for UPDATE

- sqlglot/dialects/hive.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_tsql.py
- tests/test_parser.py
Added a class variable at the parser class to make a distinction between dialects on parsing table or column aliases. This is due to the fact that at postgresql in case of a lateral join on a function, no table alias is expected.
Also changed the order of query modifiers in order to have columns available which can be used at laterals. This also required a fix in a test case in test_parser.py
Also added support for unicode literal strings at T-SQL along with a type translation for DATETIME to TIMESTAMP in Hive.
> Qualified lateral functions

- sqlglot/__init__.py
- sqlglot/expressions.py
- tests/test_build.py
Prior to this change the values builder would only support values with an alias. Now you can provide types and column names. This allows you to create a values expression that will match a desired table definition which includes the column names and types. 
Edit: Removed types support since it would make the expressions too long. Use a subquery if you want to type.
> Improve values builder to support names and types

- sqlglot/expressions.py
- tests/test_build.py
You can actually have None for a value in values and it will be converted to null. So typing and tests were updated to make it clear this functionality is supported.
> Fix values type

- sqlglot/expressions.py
We use the convert method to cast the values into their static SQL equivalent. Currently this convert function is not typed so just removing the type on this until we type the convert method. 
https://github.com/tobymao/sqlglot/blob/7e627b4c68cb453143d8eccd943efe4cc4b30d09/sqlglot/expressions.py#L3714
> Make values Any

- .gitignore
- .vscode/settings.json
- README.md
- pdoc/docs/expressions.md
- sqlglot/dataframe/__init__.py
- sqlglot/diff.py
- sqlglot/expressions.py
- sqlglot/optimizer/pushdown_projections.py
Wrote a first draft about sqlglot's expressions & did some minor fixes here and there, mostly related to the README.
The idea is to create an index for helper expression methods in a later PR.
> Add docs for expressions, minor cleanups

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
DuckDB's alias for ARRAY is `LIST_VALUE`, *except* when the argument to ARRAY is a `SELECT` expression.
---
#847 fixed the parse error, but this error remained. To demonstrate:
**Passing a SELECT expression:**
```
D WITH t AS (SELECT 1 AS id UNION ALL SELECT 2)
> SELECT ARRAY(SELECT id FROM t);
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (SELECT CASE  WHEN ((array_agg(__subquery.__arr_element) IS NULL)) THEN (list_value()) ELSE array_agg(__subquery.__arr_element) END FROM (SELECT id FROM t) AS __subquery(__arr_element)) │
│                                                                                          int32[] …
```
> ARRAY(SELECT ...]) shouldn't use the LIST_VALUE alias for DuckDB.

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Porting Postgres fix for https://github.com/tobymao/sqlglot/issues/838 to DuckDB.
> `123::CHARACTER VARYING` should parse in DuckDB.

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_build.py
A few comments about this PR:
* The argument to Select used everywhere else in the code was `windows`, so I updated `QUERY_MODIFIERS` to reflect that.
* I had `window(...)` follow the same pattern as other builders of lists of expressions.
* I needed a parse function that would return one named `Window` expression.
* So I split out `_parse_named_window(...)` for that purpose -- and it's the registered parser for Window expressions. Which might be confusing -- given that window expressions can take a lot of forms.
In the future it might make sense to have `NamedWindow` as a separate expression, or `WindowClause` or something of the sort. Not sure if you want to do that now, or if this is sufficient.
> Add a window clause builder to Select.

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
For posterity: I added a docstring to the `bigquery` dialect module stating that it is meant to support Standard SQL.
`GROUP_CONCAT` is only supported in BigQuery's Legacy SQL.
> Use STRING_AGG instead of GROUP_CONCAT in BigQuery.

- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
BigQuery uses `LOGICAL_OR`, DuckDB uses `BOOL_OR`, not entirely sure what other dialects do.
> Add LOGICAL_OR/BOOL_OR function and a generator for DuckDB.

- sqlglot/expressions.py
- tests/test_expressions.py
Prior to this change `nan` values would be translated as `nan` when converted to SQL values but now they will be converted to `NULL`.
> Support nan values in convert

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Snowflake has a bug (I created a ticket) where it can't execute table aliases for VALUES expressions that have quotes around the column names. Since the usage of quotes has to be consistent that also means you can't quote these columns when you reference them throughout your query.
This PR changes the Snowflake generator so that way it properly unquotes these columns.
> Have snowflake generate values columns without quotes

- sqlglot/dialects/postgres.py
- tests/dialects/test_databricks.py
This is a WIP -- thought I'd start a PR early to get some feedback and iterate faster. The units "week", "month", "quarter" and "year" are currently missing from the implementation, but I'll add them soon. I'm trying to figure out how to reduce code duplication as much as possible for them.
Regarding my current approach, I'm unsure whether hardcoding the mult / div operators as strings is the way to go. An alternative could be to return a tuple that contains the factor and a flag that determines whether to multiply or to divide, although it's not necessary cleaner.
cc: @tobymao
> Transpile DATEDIFF to postgres

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Reference: https://docs.snowflake.com/en/sql-reference/data-types-text.html#single-quoted-string-constants
> Add single quote to snowflake's tokenizer escape characters

- sqlglot/__main__.py
Hey! The CLI is missing a way to read files or output from other tools, which is essential for my use case (statements with hundreds of LOC). My contribution is a pretty low effort way to add it.
I decided to use `-` as a sentinel value [1] to indicate that the CLI should parse the stdin instead of argv for two reasons:
1. It's an established convention in many of GNU coreutil tools [2].
2. I don't think there's a dialect for which `-` would parse successfully.
[1] https://en.wikipedia.org/wiki/Sentinel_value
[2] https://www.gnu.org/software/coreutils/manual/coreutils.html#Common-options
> Add support for parsing stdin in CLI

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Snowflake requires that `DESCRIBE TABLE <target>` be used instead of `DESCRIBE <target>`. Therefore I added a `kind` to describe to capture this input if provided. Prior to this change `DESCRIBE TABLE <target>` would have a parsing error. 
If kind is not provided then we will generate incorrect Snowflake SQL by generating `DESCRIBE <target>` but since kind isn't provided we would have to guess at the kind so this feels like the best option.
> Add support for describe with kind

- README.md
- sqlglot/optimizer/optimizer.py
- sqlglot/schema.py
- tests/test_schema.py
This PR introduces a way to normalize schemas, by converting their column's names to lowercase, unless they're quoted. The problem it aims to fix is the following:
In the current main branch, the optimizer fails for the query below due to the inconsistency between schema column names and those produced by the `lower_identities` rule in the optimizer.
```python
import sqlglot
from sqlglot.optimizer import optimize
print(
optimize(
sqlglot.parse_one("""
SELECT A OR (B OR (C AND D))
FROM x
WHERE Z = date '2021-01-01' + INTERVAL '1' month OR 1 = 0
"""),
schema={"x": {"A": "INT", "B": "INT", "C": "INT", "D": "INT", "Z": "STRING"}}
).sql(pretty=True)
)
```
> Schema normalization: lower() column names if not quoted

- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
Fixes #901 
Reference: https://www.postgresql.org/docs/current/datatype-datetime.html
> The time-of-day types are time [ (p) ] without time zone and time [ (p) ] with time zone. time alone is equivalent to time without time zone.
> Fix time without time zone parsing

- sqlglot/helper.py
- sqlglot/parser.py
I made an attempt to add some type hints to the parser module. The "match" methods haven't been typed yet, because they cause a lot of errors. I may take another pass and see if I can type them too.
I've probably made some mistakes since there were a lot of changes involved, so please let me know if you find anything and I'll try to fix it.
On a side note: I'm not sure if the ROI is worth it for adding python types, in the end. It might be good for some other modules, but for the parser it didn't feel natural; returning the most general type "Expression" for most methods doesn't provide much information. Thoughts on this? (Besides that, it's definitely a frustrating process :-))
> Add python type hints to parser.py

- sqlglot/expressions.py
- tests/dialects/test_spark.py
> Allow unix_timestamp to be called without args

- setup.py
- sqlglot/dialects/hive.py
- sqlglot/serde.py
- sqlglot/tokens.py
- tests/dialects/test_hive.py
> Fix: hive/spark identifiers can now begin with a digit

- sqlglot/dialects/bigquery.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_presto.py
- tests/test_expressions.py
- tests/test_transforms.py
Main changes:
1. BigQuery does not allow precision on parameterized types when doing casts. Therefore added a transformer to remove these when casts are detected.
2. When doing an `UNNEST(...` (similar to `VALUES` but for BigQuery) BigQuery auto detects types from the first row of values. If one of those values are a null then it will potentially select the wrong type. Therefore updated values to accept column names and types and if types are provided then the first row is casted to the desired type to make sure type inference works correctly.
> BigQuery Fixes

- sqlglot/optimizer/optimizer.py
Too many folks remove qualify_tables/columns.
We should eventually have more robust checking (e.g. checking [`Scope.unqualified_columns`](https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/scope.py#L322) in rules that depend on it), but I at least wanted to add a warning for now.
> Warn about qualify_tabes/columns

- sqlglot/dialects/sqlite.py
- tests/dialects/test_dialect.py
sqlite does not support the sql 2008 standard "FETCH FIRST" syntax, thus "FETCH" must be transformed to LIMIT.
> transform fetch to limit for sqlite

- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
- tests/dialects/test_redshift.py
- tests/test_expressions.py
- tests/test_parser.py
Key changes:
1. Redshift doesn't support values outside of an `INSERT INTO` expression. Therefore we convert this to a union and have a warning about the poor performance with unioning a lot of values
2. This adds support for `ALTER TABLE ... RENAME TO...`. Some engines support a more direct `RENAME TABLE` syntax but I didn't tackle that here
3. Redshift puts the `LIKE` expression in paranthesis and the rest at root. I handle this by having `WITH` properties drop list (`WITH` isn't supported by Redshift).
4. Redshift converts `TEXT` to `VARCHAR(255)` which is strange since the max size is much larger. So we override this to make `TEXT` be `VARCHAR(max)`. That is generally what is meant by other engines when they say `TEXT`/`STRING` without precision.
> Redshift Improvements

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
Write out `bool_or` instead of `logical_or` when generating Spark SQL.
> LOGICAL_OR is BOOL_OR in Spark SQL.

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_redshift.py
There is a way to define views in Redshift that have `WITH NO SCHEMA BINDING` and that "unbinds" the view to underlying table(s) so that allows you to alter/drop the underlying table(s).
> Add no schema binding

- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
This PR changes the "var" tokenizing logic for TSQL, so that the `@` is considered part of the token, instead of tokenizing it as a "parameter". This felt more natural & robust, even though we could already parse names prefixed by @ before.
Also: I don't think that adding the `PARAMETER` token to the `prefix_tokens` parameter of `_parse_id_var` would solve the problem, because there might be places in the codebase where we call `_parse_primary` first and then `_parse_id_var`, meaning that in these cases we'd parse the input as a parameter instead of an identifier.
> Fix variable/identifier tokenization for TSQL to include @

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Fixes (partially) #970
Main items addressed in this PR:
1. Fix the `RETURNS` property, so that it can parse the following forms (some previously unsupported):
- `RETURNS return_data_type`,
- `RETURNS TABLE`,
- `RETURNS @return_variable TABLE`.
2. Modify the `_parse_user_defined_function` parser so that it can consume a `CREATE [PROCEDURE | PROC]` statement which has an unwrapped csv argument list (see tests).
3. Add support for the `RETURN` statement.
4. Refactor `_match` so that it expects an optional `advance` argument.
References:
- https://learn.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver16#examples
Outstanding items (for either …
> Improve handling of TSQL UDFs

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
like mediumtext/longtext, mysql has mediumblob/longblob that, in other db's, should probably just be a sql standard blob
> mysql mediumblob : similar to mediumtext

- sqlglot/expressions.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/pushdown_projections.sql
- tests/fixtures/optimizer/qualify_columns.sql
- tests/test_executor.py
fixes https://github.com/tobymao/sqlglot/issues/999
`Expression.alias_or_name` is a bit too lenient in many cases:
```python
parse_one("1 + 2").alias_or_name
```
So this introduces yet another concept - "output_name". 
I'm not crazy about adding a new method. But this seems safer than mucking with `Expression.alias_or_name`. Happy to hear opinions here.
@tobymao @GeorgeSittas
> Stricter named_selects

- sqlglot/dataframe/sql/session.py
Just to rule out the possibility of collisions as the reason for flaky tests. also I changed the `a` prefix to `r` since `r` will just represent random (either is somewhat arbitrary so just making things potentially a little clearer).
> Use full uuid value

- Makefile
On my machine ```make docs``` fails because Python is not on the local PATH.
```make test``` works fine because the reference to ```python``` is explicit.
So this pull request adds explicit reference to python where currently implicit.
> Remove dependency on local path settings

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_expressions.py
- Bug fixed: due to inheritance, `_sql_names` wasn't updated properly (e.g. `TryCast.sql_names` resulted in `["CAST"]`).
- Created a `validate` method in `Expression`, as it felt more natural. This led to a refactor of `validate_expression`.
- Created a helper function called `func`, which can be used for programmatically building function expressions.
> Implement func builder, refactor expression validation, fix bug

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/fixtures/identity.sql
This PR maps Snowflake's proprietary EXCLUDE and RENAME keywords to standard EXCEPT and REPLACE keywords.
It supports parsing these keywords only when Snowflake is the specified dialect. It does not support using them in sql construction.
example code to test:
```
from sqlglot import exp, parse_one
sql = """
SELECT DISTINCT
TBL1.* EXCLUDE DATE_FIELD, ANOTHER_FIELD RENAME TBL1.BAD_NAME AS GOOD_NAME, C AS D
FROM DATABASE.SCHEMA.TABLE TBL1
JOIN DB.SC.TBL AS TBL2 ON TBL1.ID = TBL2.ID
WHERE INT_FIELD = 55
LIMIT 10
"""
parse_one(sql, read="snowflake")
parse_one(sql, read="snowflake").sql("snowflake")
transpile(sql, read="snowflake", write="snowflake")
```
> Map Snowflake EXCLUDE and RENAME keywords

- sqlglot/transforms.py
- tests/test_transforms.py
fixes https://github.com/tobymao/sqlglot/issues/1052
re-adds the "unnecessary" transformation mentioned here: https://github.com/tobymao/sqlglot/pull/488 . I can add that back in, but it feels like its not worth the added complexity?
cc @eakmanrq
> fix unalias_group

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- sqlglot/tokens.py
Tried to clean up `PROPERTY_PARSERS` once again, so that we now only use strings instead of mixing them up with tokens.
> Only match on property texts, remove some prop tokens

- sqlglot/__init__.py
The goal for this was to improve typing so that if someone provides a type for `into` then we know that type is returned so now mypy will recognize the type as the return type.
[Reference discussion on the complexities of doing this](https://github.com/python/mypy/issues/3737)
> Improve typing if using into

- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/expressions.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/test_expressions.py
Completed the remaining tasks for https://github.com/tobymao/sqlglot/pull/1081
Fixes #1077 
Note: for the time being, I only handled casting to `timestamp` (if needed). This can be easily refined in the future if we want to include other cases too.
> Fix transpilation of generate_series for trino

- sqlglot/dialects/bigquery.py
- tests/test_transpile.py
this pull request adds the IFNULL function conversion to Coalesce Function.
IFNULL Function hasn't a direct correspondent, but it does the same thing as the coalesce and NVL
**OBS**: is my first PR in repo, please tell me if i did something wrong :)
> add: transpile ifnull from bigquery to coalesce

- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
fixes https://github.com/tobymao/sqlglot/issues/1093
This still leaves a pretty ugly result:
```python
from sqlglot import parse_one
from sqlglot.optimizer import optimize
sql = """
select test_col from test_table
union all select test_col from test_table_1
union all select test_col from test_table_2
"""
schema = {
"test_table": {"test_col": "INT"},
"test_table_1": {"test_col": "INT"},
"test_table_2": {"test_col": "INT"}
}
ast = parse_one(sql)
ast = optimize(ast, schema=schema)
print(ast.sql(pretty=True))
```
```sql
WITH "cte_4" AS (
SELECT
"test_table_1"."test_col" AS "test_col"
FROM "test_table_1" AS "test_table_1"
UNION ALL
SELECT
"test_table_2"."test_col" AS "test_col"
FROM "test_table_2" AS "test_table_2"
)
SELECT
"test_table"."test_col" AS "test_col"
FROM "test_table" AS …
```
> Fix eliminate_subqueries on unions

- sqlglot/tokens.py
- tests/dialects/test_sqlite.py
I encountered a schema using an unsupported `LONGVARCHAR` data type. 
I have not encountered this type before, but it appears to be [a generic JDBC type](https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html#LONGVARCHAR) equivalent to `TEXT`. The type appears to be possibly supported by Oracle (I don't have an installation to test) and [deprecated since 2005 in SQL-Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-data-type-differences?view=sql-server-ver16).
`sqlite` trivially supports `LONGVARCHAR` as it substring matches any type containing `CHAR` as a "text affinity". 
I think it's a question for the `sqlglot` maintainers on whether this type should be supported, but I have tested this addition locally in case it should be. 
e.g. 
```python
from sqlglot …
```
> Add `LONGVARCHAR` data type

- sqlglot/lineage.py
- sqlglot/optimizer/expand_laterals.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/expand_laterals.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/test_optimizer.py
Support for "lateral column alias references" (e.g. https://aws.amazon.com/about-aws/whats-new/2018/08/amazon-redshift-announces-support-for-lateral-column-alias-reference/). These are valid in snowflake, redshift, duckdb, and possibly more.
```sql
SELECT
x.a + 1 AS i,
i + 1 AS j,
j + 1 AS k
FROM x;
-- to
SELECT
x.a + 1 AS i,
x.a + 1 + 1 AS j,
x.a + 1 + 1 + 1 AS k
FROM x;
```
Not crazy about splitting `validate_qualify_columns` out. But this seemed like a practical way to not keep complicating `qualify_columns` logic.
> expand_laterals

- .github/workflows/python-package.yml
I think we publish docs too often.
Let's only publish on new tags.
I'm not sure if this is right.
> only publish docs on tags

- sqlglot/dialects/teradata.py
- tests/dialects/test_teradata.py
Teradata uses MOD instead of % for the modulus operator ("a MOD b" instead of "a % b").
> Teradata: use MOD instead of % for modulus

- tests/fixtures/optimizer/optimizer.sql
- tests/test_optimizer.py
Seems like a DuckDB update broke these tests in main:
```python
ERROR: test_expand_laterals (tests.test_optimizer.TestOptimizer) [(execute) expand alias reference]
----------------------------------------------------------------------
Traceback (most recent call last):
File ".../sqlglot/tests/test_optimizer.py", line 101, in check_file
df1 = self.conn.execute(
duckdb.BinderException: Binder Error: Referenced column "i" not found in FROM clause!
Candidate bindings: "x.a", "x.b"
LINE 1: SELECT x.a + 1 AS i, i + 1 AS j, j + 1 AS k FROM x
^
======================================================================
ERROR: test_expand_laterals (tests.test_optimizer.TestOptimizer) [(execute) subquery]
----------------------------------------------------------------------
Traceback (most recent call …
```
> Disable execution of lateral column tests

- sqlglot/lineage.py
Suggested fix for #1199. Changed the name of the root Table node to `c.sql()` instead of `c.table`
```python
if table not in tables:
tables[table] = Node(name=c.sql(), source=source, expression=source)
node.downstream.append(tables[table])
```
> Change name of lineage root Table node to refer to column name

- .pre-commit-config.yaml
- sqlglot/__init__.py
- sqlglot/dataframe/sql/functions.py
- sqlglot/diff.py
- tests/dataframe/unit/test_functions.py
- tests/dataframe/unit/test_session.py
fixes #1203
Can do this for other packages too if we want consistency.
> Export everything in __init__.py explicitly using aliases

- sqlglot/expressions.py
- tests/test_expressions.py
Summary of changes
- added `_meta` slot to `Expression`, defaults for `None`
- added `self.metadata` property which returns `self._meta`
- added `set_metadata(meta_key, meta_value)` method which:
1. instantiates `self._meta = {}` if needed
2. sets `self._meta[meta_key] = meta_value`
> feature: add _meta slot & meta property for more flexible annotations

- sqlglot/dialects/oracle.py
- sqlglot/expressions.py
- sqlglot/tokens.py
- tests/dialects/test_oracle.py
Fixes https://github.com/tobymao/sqlglot/discussions/648
I only added this in `exp.Column`, because the Oracle docs suggest that it can't be used elsewhere:
> The (+) operator can appear only in the WHERE clause or, in the context of left-correlation (when specifying the TABLE clause) in the FROM clause, and can be applied only to a column of a table or view.
- https://stackoverflow.com/a/1193722
- https://stackoverflow.com/a/26484312
In the future, we could try to transform these old syntax forms into the new ones (i.e. `INNER JOIN`, `LEFT JOIN`, etc).
> Add support for old (+) join syntax

- sqlglot/dataframe/sql/dataframe.py
- sqlglot/dialects/dialect.py
- sqlglot/expressions.py
find methods now return the type of the expression being sought (or a union for multiple types), rather then `Any`.
this means the caller doesn't need to cast the result.
the increased precision revealed some mypy type errors, which I've fixed
> refactor: return more precise types from find methods

- sqlglot/dialects/hive.py
- sqlglot/dialects/spark.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
Fixes #1272
We can probably change hive too here, but I wasn't 100% sure about its semantics.
> Map TIMESTAMPTZ to 'TIMESTAMP' for Spark

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
SQLite doesn't have booleans, so we can simply map these logical OR / AND functions to its MAX / MIN, respectively.
> Fix transpilation of BOOLOR_AGG, BOOLAND_AGG

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/sqlite.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_sqlite.py
Even though the SQLite docs don't mention `current_time`, `current_date` and `current_timestamp` as valid functions, in my system they work just fine (SQLite version 3.37.0 2021-12-09 01:34:53). The "official" way to write the first two of them is `TIME()` and `DATE()`. I didn't find a function as simple as these for timestamp.
- https://www.sqlite.org/lang_datefunc.html
> Transpile current date/time/timestamp correctly for sqlite

- sqlglot/dialects/sqlite.py
- sqlglot/generator.py
- tests/dialects/test_sqlite.py
The change is that `CAST(x AS DATE)` becomes `DATE(x)` for SQLite, since it has no `DATE` type.
In Snowflake, `select cast('2020-03-01 16:03:05' as date)` outputs `2020-03-01`, same as using `DATE(..)` instead of `CAST` for SQLite. I'm not sure if this transformation is generally correct, but for timestamp strings it seems legit. 🤞 
- https://www.sqlite.org/datatype3.html
> Fix transpilation of casting to date in sqlite

- sqlglot/dialects/duckdb.py
- tests/dialects/test_presto.py
Currently `dayofweek()` transpiles to `day_of_week()` in duckdb but this is incorrect, it should be `dayofweek()` as stated in the [docs](https://duckdb.org/docs/sql/functions/datepart.html#part-functions).
> Rename day of week function for duckdb

- sqlglot/parser.py
- tests/dialects/test_duckdb.py
Apparently, DuckDB allows this:
```
>>> import duckdb
>>> duckdb.connect().execute("WITH 'x.y' AS (SELECT 1) SELECT * FROM 'x.y'").fetchdf()
1
0  1
>>> duckdb.connect().execute("WITH 'x' AS (SELECT 1) SELECT * FROM 'x'").fetchdf()
1
0  1
>>> duckdb.connect().execute("WITH 'x' AS (SELECT 1) SELECT * FROM x").fetchdf()
1
0  1
```
This seems non-standard, but it felt innocuous enough to support. The places where I added `self._parse_string()` would lead to an exception without it anyway, in case we weren't able to parse a table.
> Allow parsing strings as table references

- sqlglot/dialects/postgres.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_snowflake.py
- tests/test_transforms.py
Reference: https://docs.snowflake.com/en/sql-reference/constructs/qualify
Tested the Snowflake example:
```sql
SELECT i, p, o FROM qt QUALIFY ROW_NUMBER() OVER (PARTITION BY p ORDER BY o) = 1;
```
Gives same results as what we get by transpiling it in SQLite:
```sql
SELECT i, p, o FROM (SELECT i, p, o, ROW_NUMBER() OVER (PARTITION BY p ORDER BY o NULLS LAST) AS _w_0 FROM qt) WHERE _w_0 = 1;
```
> Implement eliminate_qualify transformation

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/fixtures/identity.sql
- tests/test_parser.py
- Moved a subset of the logic we use for parsing / generating SET statements to the base classes, so that we can parse statements like `SET variable = value` with finer granularity.
- When the base `_parse_set` method fails, the parser will fallback to parsing the input as a command.
cc: @joocer @tobymao @barakalon 
Fixes #1225
> Move SET parsing/generating logic from MySQL to base

- sqlglot/tokens.py
- tests/test_tokens.py
Semicolon gets tokenized as a `TokenType.STRING` instead of `TokenType.SEMICOLON`:
```python
>>> sqlglot.tokens.Tokenizer().tokenize("show;")
[
<Token token_type: TokenType.SHOW, text: show, line: 1, col: 1, comments: []>,
<Token token_type: TokenType.STRING, text: ;, line: 1, col: 5, comments: []>
]
```
> Fix semicolon bug in command tokenizing

- sqlglot/dialects/postgres.py
- tests/dialects/test_dialect.py
Similar to 
https://github.com/tobymao/sqlglot/commit/bade19c02437129d304e543747aa8e0e310f1773
but for postgres
> Add date_trunc support for Postgres

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
Fixes #1315
>  An alternative to tbl_name FROM db_name syntax is db_name.tbl_name. These two statements are equivalent:
```sql
SHOW INDEX FROM mytable FROM mydb;
SHOW INDEX FROM mydb.mytable;
```
- https://dev.mysql.com/doc/refman/8.0/en/show-index.html
> Parse db.table syntax in MySQL's SHOW INDEX statement

- sqlglot/optimizer/annotate_types.py
- tests/test_optimizer.py
There was existing logic for type annotating the other concat methods, however the standard `CONCAT` was missed out
- Implemented string type for `CONCAT`
- Added unit test to cover it
> fix missing concat type annotating

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
Fixes #1327 
Due to Oracle's weird syntax, I opted to parsing hints as raw strings. If needed, we can refactor this in the future, but there are some tricky cases where spaces are used as value separators when we expect commas, e.g. in:
```sql
-- Both function arguments and tuple values are separated by spaces here
SELECT /*+ INDEX(v.j jhist_employee_ix (employee_id start_date)) */ * FROM v;
```
> Parse Oracle SQL hints as raw strings

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
Before:
```python
>>>
>>> optimize("SELECT * FROM x JOIN y USING(id)", schema={"x": {"id": "int"}, "y": {"id": "int"}}).sql()
'SELECT "x"."id" AS "id", "y"."id" AS "id" FROM "x" AS "x" JOIN "y" AS "y" ON "x"."id" = "y"."id"'
```
This transformation doesn't preserve the semantics of the `USING` clause, because it expands `id` into two columns, both named `"id"`, instead of merging them into a single one. For example, in Postgres SQL:
```sql
-- Tables x and y both have a single column named "id", with values 1, 2 and 3.
georgesittas=# SELECT * FROM x JOIN y USING(id);
id
----
1
2
3
(3 rows)
```
After:
```python
>>>
>>> optimize("SELECT * FROM x JOIN y USING(id)", schema={"x": {"id": "int"}, "y": {"id": …
```
> Optimizer: fix star expansion when USING clause is present

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Fixes #1338
This isn't complete, because `~5` is a valid expression, corresponding to the 2's complement of 5. I assume that it's not used as commonly, so maybe it's ok to leave it as is. Otherwise, happy to revisit this and try to fix parsing so that we can recognize it too. Notice that we also had this problem with postgres prior to this PR.
> Parse tilde as REGEXP_MATCHES for DuckDB

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
With this we'll now parse `@x` in `SELECT @x FROM foo` as a parameter, instead of a `Column`.
cc: @10bas10
> Fix tokenizing of T-SQL parameters

- sqlglot/dialects/mysql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
Aims to improve https://github.com/tobymao/sqlglot/pull/1350, since MySQL directly supports `->>`, like postgres.
cc: @jerryleooo
> Fix: generate ->> for JSON_EXTRACT_SCALAR (MySQL)

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/databricks.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
Fixes #1360
References:
- https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log
- https://clickhouse.com/docs/en/sql-reference/functions/math-functions
- https://docs.databricks.com/sql/language-manual/functions/log.html
- https://duckdb.org/docs/sql/functions/numeric.html
- https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
- https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log
- https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions070.htm
- https://www.postgresql.org/docs/9.1/functions-math.html
- https://prestodb.io/docs/current/functions/math.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_LOG.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_LOG.html
- …
> Fix parsing for the logarithm function

- .github/workflows/python-publish.yml
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Upgrade versions of github actions

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_hive.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
Fixed several issues regarding tranpiling from T-SQL to Spark:
- Removed national identifier in hive and depending dialects as its not supported;
- Fixed type mapping for BIT to BOOLEAN in hive and depending dialects;
- Added support current user
> Current user, national, boolean for tsql->hive

- sqlglot/dialects/mysql.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_mysql.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_tsql.py
Fixes #1393
<details><summary>Outdated description, see my next comment.</summary>
- Improved type hints.
- Mapped `"DATE_FORMAT"` to `exp.DateToDateStr` for MySQL, which is also generated back to `"DATE_FORMAT"`.
- Transpiled `exp.DateToDateStr` to `TO_CHAR` for Snowflake.
The last one is tricky.. For the time being I simply used a "hack" to detect whether `'%'` appears in the format string, and if it does I use Snowflake's inverse time mapping to try and get a valid format (see commented doc link for valid formats). This is currently a best-effort approach, as:
1. not all MySQL formats are included in Snowflake's time mapping and
2. there are some duplicate values in this dict, so it's not a 1-1 mapping
Some basic formats are working fine, but others still don't work. Happy to try a …
> Fix: attempt to transpile MySQL DATE_FORMAT to Snowflake

- sqlglot/schema.py
- tests/test_schema.py
This PR aims to make the normalization of names in `MappingSchema` more robust. We're already normalizing names, as introduced in https://github.com/tobymao/sqlglot/pull/891, but that's only limited to the schema constructor. All of the exposed methods (`add_table`, `column_names`, `get_column_type`) don't normalize their input arguments.
cc: @tobymao @barakalon
> Fix: ensure name normalization for schema methods

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
An attempt to make the qualify columns more lenient.
Before:
```python
>>> optimize("SELECT y FROM foo JOIN bar USING(x)", schema={"foo": {"x": "int"}}).sql()
```
After:
```python
>>> optimize("SELECT y FROM foo JOIN bar USING(x)", schema={"foo": {"x": "int"}}).sql()
'SELECT "bar"."y" AS "y" FROM "foo" AS "foo" JOIN "bar" AS "bar" ON "foo"."x" = "bar"."x"'
```
> Feat(optimizer): Make _expand_using more lenient in qualify columns

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
Addresses https://github.com/tobymao/sqlglot/commit/bd96e9613fdcd536e50980130074d2cc9e1a004e#commitcomment-108967287.
cc: @mpf82 let me know if converting `getxmltype` to uppercase (context: `dbms_xmlgen.getxmltype(..)`) is ok. Same goes for the new AST representation, which now uses a `Dot` node instead of a `Table`:
```        
(DOT this:
(VAR this: dbms_xmlgen), expression:
(ANONYMOUS this: getxmltype, expressions:
(LITERAL this: SELECT table_name, column_name, data_default FROM user_tab_columns, is_string: True))), by_ref: False))))
```
> Fix(oracle): parsing bug in _parse_xml_table

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
- duckdb [doesn't support column comments](https://github.com/duckdb/duckdb/discussions/6290)
- ts_or_ds_add wasn't recursively generating the this arg before interpolating
> duckdb fixes

- sqlglot/expressions.py
- sqlglot/lineage.py
- tests/test_lineage.py
This PR
- Recursively expands expressions and extract source aliases as we traverse lineage
- Removes cache of source tables because we were losing columns when a query references multiple columns from the same source table
> Fix: Expand as we traverse lineage

- sqlglot/dialects/hive.py
- sqlglot/generator.py
- tests/dialects/test_hive.py
Fixes #1425
Note: changed some tests because they were incorrect, i.e. `SELECT * FROM x TABLESAMPLE (10)` is incorrect for hive, which also doesn't support different sampling methods like `BERNOULLI` etc.
References:
- https://cwiki.apache.org/confluence/display/hive/languagemanual+sampling
- https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-sampling.html
- https://prestodb.io/docs/current/sql/select.html#tablesample
> Fix(hive, spark): improve transpilation of TABLESAMPLE clause

- sqlglot/dialects/spark.py
From https://spark.apache.org/docs/latest/api/sql/index.html#timestamp:
> Casts the value `expr` to the target data type `timestamp`.
> Add Spark's timestamp function to Parser.FUNCTIONS

- sqlglot/dataframe/sql/column.py
- sqlglot/dataframe/sql/dataframe.py
- tests/dataframe/integration/test_dataframe.py
We check for ambiguous columns after a join and currently we assume all objects in the select are column expressions when they can also be literal expressions. Literals can't be ambiguous so we remove them from the check.
> DataFrame: Fix literal after join

- sqlglot/dialects/databricks.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_teradata.py
Transpile Teradata's `CAST('1/1999' as DATE FORMAT 'yyyy-mm')` to `DATE_FORMAT('1/1999', 'yyyy-mm')` for spark, databricks, and mysql
> Teradata CAST DATE FORMAT to DATE_FORMAT()

- sqlglot/lineage.py
- tests/test_lineage.py
This PR fixes a couple of issues with `lineage.py:to_node`. Specifically, it handles two edge cases:
* If the lineage maps to a CTE with a `SELECT *`, the node is correctly generated
* If the lineage maps to an external source _not specified_ in the `sources` map, the node gracefully falls back to a placeholder value
While I was here, I also added some inline comments to help grok the code.
If the last node came from a CTE with a `SELECT *`, the function failed with
```
pytest -vv tests/test_lineage.py -k test_lineage_source_with_star
...
>       select = next(select for select in scope.selects if select.alias_or_name == column_name)
E       StopIteration
sqlglot/lineage.py:97: StopIteration
```
This is now handled correctly.
If the lineage involves a source that was not specified in the …
> [fix] edge cases for lineage node generation

- sqlglot/tokens.py
- tests/test_tokens.py
- tests/test_transpile.py
> Fix: skip the comment start when tokenizing a delimited comment

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix: allow column values in INTERVAL expressions

- sqlglot/parser.py
- tests/dialects/test_mysql.py
> Fix: fallback to _parse_term when parsing INTERVAL values

- sqlglot/lineage.py
- tests/test_lineage.py
Currently, lineage raises an exception when it encounters non-select expressions in a scope. For example,
```python
lineage(
"a",
"SELECT a FROM y",
sources={"y": "SELECT a FROM (VALUES (1), (2)) AS t (a)"},
)
```
results in the following error
```
File lib/python3.10/site-packages/sqlglot/lineage.py:111, in lineage.<locals>.to_node(column_name, scope, scope_name, upstream, alias)
105     raise ValueError(f"Could not find {column_name} in {scope.expression}")
107 # For better ergonomics in our node labels, replace the full select with a version that
108 # has only the column we care about.
109 #   "x", SELECT x, y FROM foo
110 #     => "x", SELECT x FROM foo
--> 111 source = optimize(scope.expression.select(select, append=False), schema=schema, rules=rules)
112 select = source.selects[0] …
```
> Handle non-select expressions in lineage

- sqlglot/dialects/presto.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_presto.py
Fixes #1495
cc: @vegarsti I included the test cases you've added to the harmonizer repo, adapted appropriately.
> Feat(presto): transpile explode/posexplode into (cross join) unnest

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
BigQuery does not have a `TIMESTAMPTZ` type. A timestamp with time zone maps to the [`TIMESTAMP`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type) type and one without a timezone maps to [`DATETIME`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type).
> fix: BigQuery `TIMESTAMP` and `TIMESTAMPTZ` types

- sqlglot/dataframe/README.md
- sqlglot/dataframe/sql/dataframe.py
- tests/dataframe/integration/test_dataframe.py
This also fixes an issue where the join columns were assumed to be expression in left -> right order. 
The DataFrame API will now return multiple columns with the same name if a select is not provided to make it clear which one you want. This matches Spark behavior (as proven by the tests). 
Resolves: https://github.com/tobymao/sqlglot/issues/1500
> Fix Dataframe Triple Join issue

- sqlglot/dialects/starrocks.py
- tests/dialects/test_starrocks.py
Support regex in Starrocks
Function is documented at https://docs.starrocks.io/en-us/2.4/sql-reference/sql-functions/like_predicate-functions/regexp
MySQL uses `REGEXP_LIKE`
https://dev.mysql.com/doc/refman/8.0/en/regexp.html
> Support regex function in Starrocks

- sqlglot/dialects/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
This PR originally aimed to improve the transpilation of `DATEDIFF` for Spark and Databricks, which both inherit from Hive. It turns out that this function can also receive a "unit" argument in (at least) v3.3.1 Spark, similar to other dialects. This isn't documented in Spark's docs (it is in Databricks'), but one can easily test this using for example `spark-sql`:
```
spark-sql> SELECT DATEDIFF(MONTH, '2020-01-01', '2020-03-05'); -- v3.3.1
timestampdiff(MONTH, 2020-01-01, 2020-03-05)
2
Time taken: 0.143 seconds, Fetched 1 row(s)
```
Note that this is **NOT** supported in v2 Spark. So, if we just parsed the unit correctly, without changing the generation logic of `DATEDIFF`, we'd get the following query after transpiling to the current Hive / Spark / Databricks dialects:
```sql
SELECT …
```
> Feat(spark): new Spark2 dialect, improve DATEDIFF sql generation BREAKING

- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_spark.py
Sorry, thought I'd added all these! Same as https://github.com/tobymao/sqlglot/pull/1494 etc.
> Fix(Spark): Add DOUBLE, FLOAT cast functions

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
> Fix(oracle): allow parsing of @dblink in table names

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/oracle.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
- tests/dialects/test_snowflake.py
> Fix(oracle): set post_tablesample_alias=True to fix alias parsing

- sqlglot/dialects/spark2.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
- tests/dialects/test_snowflake.py
- tests/test_transpile.py
> Fix(spark): cast UnixToTime to TIMESTAMP BREAKING

- sqlglot/dialects/presto.py
- sqlglot/dialects/spark2.py
- sqlglot/transforms.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
Example usage:
```python
>>> sqlglot.transpile("WITH sales(amount) AS (SELECT * FROM (VALUES (100), (200), (300), (400), (500), (600), (700), (800), (900), (1000)) sales(amount)) SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amount) AS median FROM sales", "postgres", "trino")[0]
'WITH sales(amount) AS (SELECT * FROM (VALUES (100), (200), (300), (400), (500), (600), (700), (800), (900), (1000)) AS sales(amount)) SELECT APPROX_PERCENTILE(amount, 0.5) AS median FROM sales'
```
In Postgres:
```python
georgesittas=# WITH sales(amount) AS (SELECT * FROM (VALUES (100), (200), (300), (400), (500), (600), (700), (800), (900), (1000)) sales(amount)) SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amount) AS median FROM sales;
median
--------
550
(1 row)
```
In Trino:
```python
trino> WITH …
```
> Fix(presto, spark): remove WITHIN GROUP when transpiling percentile_[cont|disc]

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
To be able to parse MATCH_RECOGNIZE in Presto/Trino
Doc is https://trino.io/docs/current/sql/match-recognize.html
> Parse MATCH_RECOGNIZE in Presto/Trino

- sqlglot/optimizer/qualify_columns.py
Mypy was complaining about `dict | Schema` in Python 3.9 and older
> Allow type unions in optimizer.qualify_columns

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Specifying the target table name with a schema/db causes a syntax error in DuckDB.
> Fix rename table expression for DuckDB

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
Small fix: based on the [clickhouse docs](https://clickhouse.com/docs/en/sql-reference/data-types/datetime64), these two are not the same but SQLGlot currently transpiles `DateTime` to `DateTime64`:
```python
>>> sqlglot.transpile("cast(x as datetime)", "clickhouse")
['CAST(x AS DateTime64)']
```
> Unlike `DateTime`, `DateTime64` values are not converted from `String` automatically.
> Fix(clickhouse): make a new token for DateTime64

- sqlglot/parser.py
- tests/fixtures/identity.sql
This enables us to parse queries like the following (T-SQL UDF is used as a source):
```sql
select Dates from dbo.DateRange('M', '2019-01-01', getdate())
```
> Fix(parser): make _parse_table_parts more lenient

- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
- tests/test_optimizer.py
- tests/test_parser.py
Fixes #1587 
If we end up merging this, it will be a breaking change because the AST for data types like `VARCHAR(MAX)` will change.
> Fix(oracle): change the data type parser to allow type specifiers

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Addresses https://github.com/tobymao/sqlglot/pull/1593#issuecomment-1544487194 and improves parsing according to:
```
TTL expr
[DELETE|RECOMPRESS codec_name1|TO DISK 'xxx'|TO VOLUME 'xxx'][, DELETE|RECOMPRESS codec_name2|TO DISK 'aaa'|TO VOLUME 'bbb'] ...
[WHERE conditions]
[GROUP BY key_expr [SET v1 = aggr_func(v1) [, v2 = aggr_func(v2) ...]] ]
```
All examples using TTL from Clickhouse's documentation page are now parseable / pretty-printable even!
Reference: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#mergetree-table-ttl
> Fix(clickhouse): move GROUP BY, SET under TTL parser, improve generator

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Snowflake's [CONVERT_TIMEZONE](https://docs.snowflake.com/en/sql-reference/functions/convert_timezone) has two forms:
```sql
CONVERT_TIMEZONE( <target_tz> , <source_timestamp> )
-- and
CONVERT_TIMEZONE( <source_tz> , <target_tz> , <source_timestamp_ntz> )
```
The second is required if the timestamp doesn't have timezone information. Currently, parsing
```sql
CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', tzcolumn)
```
produces
```sql
CONVERT_TIMEZONE('UTC', 'America/Los_Angeles')
```
when re-rendered, which is invalid. This PR still treats the target-only case as `exp.AtTimeZone`, but parses the source-and-target case as `exp.Anonymous` so that rendering back to Snowflake will be correct.
> Fix(snowflake): Handle form of CONVERT_TIMEZONE with a source TZ

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse): parse ternary operator

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
CH can parse both `LEFT ANY JOIN` and `ANY LEFT JOIN` successfully 
But the canonical order (by the docs) is `LEFT ANY JOIN` 
This PR parses "inverted" order and produces a canonical one
Notes:
- CH uses `ASOF`, `SEMI`, `ANTI`, `ANY` as reserved words. Can be tested by doing something like: 
`FROM t semi SEMI LEFT JOIN` - fails
`FROM t "semi" SEMI LEFT JOIN` - passes
That's why I have removed them from `TABLE_ALIAS_TOKENS`
> Fix(clickhouse): join type/kind ordering issues

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
I.e. both `USING a, b, c` and `USING (a, b, c)` are allowed 
Although the wrapped variant is a canonical one (see docs)
https://clickhouse.com/docs/en/sql-reference/statements/select/join#examples
Unwrapped columns and expression lists are allowed in other places too. Will update later.
> Fix(clickhouse): `USING`, `[PRIMARY|FOREIGN] KEY` allows unwrapped col list

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#table_names
> Feat(bigquery): allow first part of table names to contain dashes

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #1626
Reference: https://docs.snowflake.com/en/sql-reference/sql/create-clone
> Feat(snowflake): add support for the CLONE clause in DDL statements

- sqlglot/dialects/dialect.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/merge_subqueries.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- sqlglot/optimizer/scope.py
- sqlglot/parser.py
- sqlglot/transforms.py
- tests/dialects/test_spark.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_tables.sql
- tests/test_optimizer.py
- tests/test_parser.py
Fixes https://github.com/tobymao/sqlglot/discussions/1449
This PR introduces optimizer logic for handling the PIVOT operator, i.e. explode & qualify the columns of the table it produces where necessary. It's a first draft towards the general solution, which is more difficult because we may have multiple JOINs and / or PIVOTs, UNPIVOTs chained together in non-trivial ways.
We could also try to transform PIVOT operators using `exp.Case` expressions. This seems a bit less straightforward to me if we want to get it right in all cases. For example:
1. What do we `GROUP BY` if there are additional columns besides what's referenced in the `exp.Pivot` expression? 
2. Can we always map the aggregations trivially into projections? How would we handle stuff like `COUNT(*)`?
3. How does this …
> Feat(optimizer): optimize pivots

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/starrocks.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): map ApproxDistinct to uniq, AnyValue to any

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
- tests/dialects/test_oracle.py
Fixes #1641
This is a breaking change because the arguments of the `exp.Lock` expression were changed.
cc: @mpf82
> Feat!(mysql, oracle): improve parsing of lock syntax

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
See https://github.com/tobymao/sqlglot/pull/869 for reference. The following query now executes just fine in Snowflake:
```sql
SELECT "c0", "c1" FROM (VALUES (1, 2), (3, 4)) AS "t0"("c0", "c1");
```
> Chore(snowflake): remove select_sql, values_sql as the bug was resolved

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
> Fix(redshift): handle VALUES clause more robustly

- sqlglot/dialects/snowflake.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
- tests/dialects/test_snowflake.py
This PR replaces generation of [`EXTRACT`](https://docs.snowflake.com/en/sql-reference/functions/date_part) with generation of [`DATE_PART`](https://docs.snowflake.com/en/sql-reference/functions/date_part) in the Snowflake dialect.
The motivation for this change is that, for queries using `DATE_PART` where the first argument is a string, the generated SQL is rejected by Snowflake. Taking an example from the unit tests, if I attempt to run the following on Snowflake:
```sql
SELECT EXTRACT('month' FROM a)
```
I get the following error:
```
SQL compilation error: syntax error line 1 at position 23 unexpected 'FROM'. syntax error line 1 at position 29 unexpected ')'.
```
It succeeds compilation if I remove the quotes around `'month'`.
`EXTRACT(... FROM ...)` only supports unquoted arguments. …
> Generate DATE_PART instead of EXTRACT for Snowflake

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/pushdown_projections.sql
- tests/fixtures/optimizer/qualify_columns.sql
> Fix(optimizer): expand refs in QUALIFY into corresponding projections

- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_teradata.py
Fixes #1674
References:
- https://www.geeksforgeeks.org/how-to-create-volatile-table-in-teradata/
- https://docs.teradata.com/r/SQL-Data-Definition-Language-Syntax-and-Examples/September-2015/Table-Statements/CREATE-TABLE/Examples/Example-AS-...-WITH-DATA-With-a-Nonunique-Secondary-Index
> Fix(teradata): improve post index property parsing

- sqlglot/tokens.py
- tests/test_parser.py
- tests/test_tokens.py
- tests/test_transpile.py
Addresses @mpf82's comment in https://github.com/tobymao/sqlglot/discussions/1673
> Fix(tokenizer): initialize self._col properly to avoid edge case

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/databricks.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/starrocks.py
- sqlglot/dialects/tableau.py
- sqlglot/dialects/teradata.py
- sqlglot/dialects/trino.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_snowflake.py
Fixes #1682
Got rid of several `type: ignore` comments because mypy seems to no longer complain.
The line of interest for #1682 is the following (inside Snowflake's parser):
```python
TIMESTAMPS = parser.Parser.TIMESTAMPS.copy() - {TokenType.TIME}
```
Also moved some `_sql` methods inside of the `Tableau` class instead of having them in `TRANSFORMS`.
> Fix(snowflake): preserve TIME type instead of converting it to TIMESTAMP

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
Fixes #1681
Reference: https://docs.databricks.com/delta/generated-columns.html
> Feat(databricks): add support for GENERATED ALWAYS AS (expr) clause

- sqlglot/dialects/presto.py
- sqlglot/transforms.py
- tests/dialects/test_presto.py
> Feat: implement transform to add column names to recursive CTEs

- sqlglot/__init__.py
- sqlglot/_typing.py
- sqlglot/_typing.pyi
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/starrocks.py
- sqlglot/dialects/tsql.py
- sqlglot/diff.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/helper.py
- sqlglot/parser.py
- sqlglot/planner.py
- sqlglot/schema.py
I did a sweep in the codebase to clean up the type hints. All files under `sqlglot/dialects` should be now fully typed.
This is still a WIP, gonna continue iterating on it tomorrow to do any remaining fixes.
> Chore!: improve python type hints

- sqlglot/_typing.py
- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): allow aliases in tuple function arguments

- sqlglot/schema.py
Minor addition: now we can specify other args besides `dialect` in `ensure_schema`. This can be useful if e.g. we want to instantiate a `MappingSchema` with `normalize=False` or `visible={...}`.
> Feat(schema): allow passing kwargs in ensure_schema

- sqlglot/schema.py
- tests/test_schema.py
This fixes a bug that I missed in https://github.com/tobymao/sqlglot/commit/12d3cca8bab004dc378f6f272be7b07a7e16eaae: `_ensure_table` used to wrap around the `dialect or self.dialect` logic, whereas in my change I just passed in `dialect` to `maybe_parse`. For this reason I reintroduced `_ensure_table`, in order to avoid doing `dialect or self.dialect` inline for every `exp.maybe_parse` call in the schema module.
> Fix(schema): ensure the correct dialect is used in schema methods

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
Fixes #1712
Also added support for the standalone `FROM tbl` expression (see example below) which is used in DuckDB's pivot examples. This is essentially a shorthand for `SELECT * FROM tbl` and it seems useful to support in the base parser. We could also improve the `from_` helper to allow `from_(..., star=True)` as a way to dry up `exp.select("*").from_(...)`. @tobymao thoughts on this?
```python
>>> import duckdb
>>> duckdb.connect().execute("with t as (select 1) select * from (from t)").fetchdf()
1
0  1
>>> duckdb.connect().execute("with t as (select 1) from (from t)").fetchdf()
1
0  1
```
References:
- https://duckdb.org/docs/sql/statements/pivot
- https://duckdb.org/docs/sql/query_syntax/from#examples
> Feat(duckdb): add support for simplified pivot syntax

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Example:
```
> SELECT 1 HASH;
Syntax error: Expected end of input but got keyword HASH at [1:10] 
```
> Fix(bigquery): treat HASH as a reserved keyword

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/optimize_joins.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
Fixes #1722
Also thought of creating a `JoinParts` expression to factor out the `side`, `kind` and `method` args, but didn't end up implementing it because it seemed like a bigger breaking change.
One advantage with this is that `EXPRESSION_PARSERS` could only contain `Expression` type keys, instead of mixed with `str` (i.e. for `"JOIN_TYPE"`). We could also abstract away the accessing of these args by implementing a property that delegates to said `JoinParts` expression's properties.
The disadvantage would be in `set`ting the `JoinParts` manually, because now we can just do `e.set("kind", "foo")` and be done with it. With the `JoinParts` expression there's another expression to instantiate..
> Feat!(duckdb): add support for ASOF joins

- sqlglot/dialects/presto.py
- sqlglot/transforms.py
- tests/dialects/test_presto.py
Fixes #1725
Haven't investigated much, so I'm not sure if this transformation is 100% correct; for the example in #1725 it works fine.
However, one difference is that Spark produces the following when casting `'epoch'` to a timezone:
```
spark-sql (default)> select cast('epoch' as timestamp);
1970-01-01 02:00:00
```
Whereas this transformation yields the following when transpiling the above from Spark to Trino:
```
trino> SELECT TRY_CAST('1970-01-01 00:00:00' AS TIMESTAMP);
_col0          
-------------------------
1970-01-01 00:00:00.000 
(1 row)
```
Not sure why it produces `02:00:00` in the former case.. Maybe it's interpreting the `'epoch'` using a different timezone?
> Feat(presto): transpile 'epoch' to '1970-01-01 00:00:00' in time-like casts

- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_hive.py
> Fix: conditionally quote identifiers that start with a digit

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tableau.py
- sqlglot/dialects/teradata.py
- sqlglot/dialects/tsql.py
- sqlglot/executor/env.py
- sqlglot/executor/python.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/annotate_types.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_oracle.py
- tests/test_expressions.py
- Dialect properties like `time_mapping` have been converted to uppercase for consistency, i.e. `TIME_MAPPING`.
- Dialect properties removed from constructors; they're now set using metaprogramming in the `_Dialect` class.
- Generator `normalize_functions` arg has changed: now `False` means "don't normalize", `True` is equiv. to `"upper"`.
- Removed the `IfNull` expression in favor of adding `IFNULL` as a `_sql_name` in `Coalesce`.
- Renamed `IS_BOOL` generator flag to `IS_BOOL_ALLOWED` for clarity.
- Tried to replace some Expression constructors with the corresponding helpers in some places.
- Did some manual formatting by adding whitespace to reduce visual noise, unwrapped some multi-line expressions.
- Improved type hints in the Parser.
- Cleaned up some comments.
- Made …
> Refactor!: misc. improvements in formatting, type hints, dialect class variables

- sqlglot/dialects/snowflake.py
- sqlglot/tokens.py
- tests/test_tokens.py
- tests/test_transpile.py
Fixes #1763 
This also fixes a tokenizer bug related to Jinja comments (`{# ... #}`). In some dialects we've overridden the `COMMENTS` tokenizer list, excluding these delimiters, but we actually want to recognize them in all dialects.
Current behavior (note that BigQuery uses `#` as a comment delimiter):
```python
>>> from sqlglot.dialects import BigQuery
>>> for tok in BigQuery.Tokenizer().tokenize("SELECT 1 {# this is a comment #}"):
...     print(tok)
...
<Token token_type: TokenType.SELECT, text: SELECT, line: 1, col: 6, start: 0, end: 5, comments: []>
<Token token_type: TokenType.NUMBER, text: 1, line: 1, col: 8, start: 7, end: 7, comments: []>
<Token token_type: TokenType.L_BRACE, text: {, line: 1, col: 10, start: 9, end: 9, comments: [' this is a comment #}']>
```
With the fix …
> Feat(snowflake): add support for // comments

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Bonus: reordered some tests to partition them into validate_all / validate_identity & sorted functions in alphabetical order
> Fix(bigquery): allow SPLIT call with 1 argument

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
> Fix(Postgres): Set INDEX_OFFSET to 1

- sqlglot/dialects/duckdb.py
- sqlglot/generator.py
- tests/dialects/test_duckdb.py
Ran all tests in the corresponding engines, they look good.
Note: the tweak I made in the Generator class was to enable the overriding of some (previously) tuple attributes.
References:
- https://duckdb.org/docs/sql/functions/interval.html
- https://duckdb.org/docs/sql/functions/datepart#usable-in-date-part-specifiers-only
Fixes #1779
> Fix!(duckdb): wrap negations, transpile week, quarter to multiplication

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
> Fix(parser): cast coalesce arg to text in the context of a CONCAT call

- sqlglot/__init__.py
Fixes #1796
The idea is that there's no point for all the different overloads, since the only thing we're interested in is matching `into`'s type with the return type.
> Refactor!: simplify mypy type hints for parse_one

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_presto.py
- Accepts SQL value
- Accepts JSON value
Wasn't sure what to do about the `pretty_print` arg (does not seem compatible with the options in `exp.JSONFormat`) - let me know what you think.
---
Ref: [TO_JSON_STRING docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#to_json_string)
Ref: [TO_JSON_STRING accepted types](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_encodings)
> feat(bigquery): support TO_JSON_STRING

- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_expressions.py
Example from information schema: 
```
SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'table' AND table_schema = 'schema';
id                                | bigint
custom_col                        | USER-DEFINED
ds                                | text
```
> Feat: Add Postgres user-defined type support

- sqlglot/dialects/hive.py
- tests/dialects/test_presto.py
Related discussion: https://github.com/tobymao/sqlglot/pull/1803#discussion_r1234287657
This is a best-effort approach, so it might not be complete. The difficulty of transpiling these JSON calls correctly stems from the fact that Hive / Spark work with JSON values using only their  *string* representation, whereas Trino and Presto have native support for them, using a `JSON` type.
Note: all changed tests were previously failing in Spark. The new ones work and have the same semantics as in Trino.
References:
- https://trino.io/docs/current/functions/json.html
- https://spark.apache.org/docs/latest/api/sql/index.html#from_json
- https://spark.apache.org/docs/latest/api/sql/index.html#schema_of_json
- https://spark.apache.org/docs/latest/api/sql/index.html#to_json
- …
> Refactor!(hive): improve transpilation of TO_JSON

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #1818
Reference: https://docs.snowflake.com/en/sql-reference/data-types-numeric#int-integer-bigint-smallint-tinyint-byteint
> Feat(snowflake): add support for BYTEINT type

- sqlglot/optimizer/qualify_columns.py
- tests/test_optimizer.py
Bigquery has pseudocolumns for time ingestion partitioned tables. These pseudocolumns are `_PARTITIONTIME` and `PARTITIONDATE`. Both of these are reserved identifiers, furthermore neither are returned in * expansion by bigquery. So we should respect that during the optimizer's star expansion. To not do so would break a valid query (by adding reserved idents to the projection).
> Fix: dont expand bq pseudocolumns in optimizer star expansion

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
> Fix(mysql): convert (U)BIGINT to (UN)SIGNED in CAST expressions

- sqlglot/dialects/tsql.py
- tests/test_schema.py
Tested in SQL Fiddle:
```
CREATE TABLE "FoOOo" (id INT);
INSERT INTO foooo VALUES (1);  -- works
SELECT * FROM "foooO";  -- works
with "CtE"(foo) as (select 1) select * from cte;  -- works
```
References:
- https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16#Server-level-collations
> Feat!(tsql): treat all identifiers as case insensitive

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Fixes #1858
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#any_value
> Feat(bigquery): support the full syntax of ANY_VALUE

- sqlglot/executor/python.py
Notice how `running` isn't mutated anywhere besides the main executor loop (it's not passed by reference anywhere):
```python
running.add(node)
if isinstance(node, planner.Scan):
contexts[node] = self.scan(node, context)
elif isinstance(node, planner.Aggregate):
contexts[node] = self.aggregate(node, context)
elif isinstance(node, planner.Join):
contexts[node] = self.join(node, context)
elif isinstance(node, planner.Sort):
contexts[node] = self.sort(node, context)
elif isinstance(node, planner.SetOperation):
contexts[node] = self.set_operation(node, context)
else:
raise NotImplementedError
running.remove(node)
```
This means that it will always be empty after the `remove` call, and so the condition `dep not in running` will be trivially true. Hence, `running` is not actually needed in the …
> Refactor(executor): get rid of 'running' set

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Fixes #1862
References:
- https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html
- https://dev.mysql.com/doc/refman/5.7/en/insert-select.html
- https://www.mysqltutorial.org/mysql-insert-ignore/
> Fix(mysql): improve parsing of INSERT .. SELECT statement

- sqlglot/dialects/bigquery.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Fixes #1870
References:
- https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions#cast
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#parse_timestamp
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#parse_date
> Fix(bigquery): improve support for cast to timestamp with format, time zone

- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_hive.py
- tests/dialects/test_presto.py
- tests/dialects/test_sqlite.py
- tests/dialects/test_tsql.py
Update test coverage, update tsql to spark mappings for more 1-to-1 mappings on INT, TINYINT, BIGINT etc.
> Feat!(spark): better coverage for decimals, strings, datetime, bin types

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
add support for `&&` and `xor`
refs: https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_and
> Fix(mysql): add support some logical operators

- sqlglot/dialects/hive.py
- tests/dialects/test_tsql.py
Hive/Spark2/Spark don't support FLOAT(n) data type.
This feat maps FLOAT(n) to float if n <= 32 and double otherwise
> feat: Add FLOAT(n) mappings to Hive

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
References:
- https://docs.snowflake.com/en/sql-reference/functions/regexp_substr
- https://spark.apache.org/docs/latest/api/sql/index.html#regexp_extract
- https://prestodb.io/docs/current/functions/regexp.html#id0
- https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract
- https://duckdb.org/docs/sql/functions/patternmatching.html
> Fix: improve parsing / generation of REGEXP_EXTRACT

- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_spark.py
Formatting changes: sorted spark functions alphabetically
References:
- https://docs.snowflake.com/en/sql-reference/functions/regexp_like
- https://spark.apache.org/docs/latest/api/sql/index.html#rlike
- https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
> Fix(spark): add support for RLIKE function

- sqlglot/dataframe/sql/column.py
- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- tests/dataframe/unit/test_functions.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_spark.py
Fixes #1928
References:
- https://spark.apache.org/docs/latest/api/sql/index.html#datediff
- https://duckdb.org/docs/sql/functions/timestamp.html
- https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
> Fix(spark,duckdb): transpile TO_TIMESTAMP, MONTHS_BETWEEN correctly

- sqlglot/tokens.py
- tests/dialects/test_bigquery.py
- tests/test_tokens.py
I don't know what was the motivation behind raising a `ValueError` in the tokenizer module, but it doesn't feel right. This PR changes this to ensure consistency with the other modules.
Note how prior to this PR the `TokenError` exception type was also practically unused.
> Refactor!(tokenizer): raise TokenError instead of RuntimeError

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_clickhouse.py
Fixes #1936
References:
- https://clickhouse.com/docs/en/sql-reference/functions/logical-functions#xor
- https://dev.mysql.com/doc/refman/5.7/en/logical-operators.html#operator_xor
> Feat(clickhouse): add support for the logical xor function

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_spark.py
- tests/test_expressions.py
Fixes #1933
References:
- https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Transform
- https://spark.apache.org/docs/3.1.2/sql-ref-syntax-qry-select-transform.html
- https://spark.apache.org/docs/3.1.2/sql-ref-syntax-hive-format.html
- https://spark.apache.org/docs/latest/api/sql/index.html#transform
> Feat(hive): add support for the query TRANSFORM clause

- sqlglot/dialects/spark2.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_tsql.py
@dmoore247 this covers most of the tests you wrote, but I haven't done something about table vars yet. Could continue in a future PR or feel free to take a stab yourself too.
Also considered creating a couple of new expressions instead of adding new args in `Identifier`, but the resulting code with this approach looked a bit cleaner I think. Don't feel strongly about it, so happy to pivot if needed.
> Feat(tsql): improve transpilation of temp table DDLs

- sqlglot/dialects/presto.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_presto.py
That's my first PR here, would be glad for any corrections.
Thank you!
Documentation: https://prestodb.io/docs/current/language/types.html?highlight=ipaddress#ipaddress
> Feat(presto): add IPADDRESS/IPPREFIX data types

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_mysql.py
Fixes #1959 -- still a WIP. An alternative I considered for _index_options_ was to create a separate class for each option. That way we'd avoid the if checks in the generator, but we'd have a handful more expression types to deal with, so wasn't sure and went ahead with this approach instead because it felt simple. Will refine & add more tests tomorrow morning.
Reference: https://dev.mysql.com/doc/refman/8.0/en/create-table.html
> Feat(mysql): improve support for DDL index column constraints

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Reverts the piece of logic specific to floats, introduced in #1967. Ensures that we don't break valid T-SQL code, at least.
cc: @dmoore247
> Fix(tsql): revert float-to-datetime coercions

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- tests/dialects/test_mysql.py
MySQL prohibits complex expressions in the `LIMIT` and `OFFSET` clauses, so we need to simplify them.
For example, the following query is invalid in MySQL:
```sql
SELECT 1 LIMIT 0 + 1
```
> Fix(mysql): simplify LIMIT, OFFSET when their expression is complex

- sqlglot/expressions.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns_ddl.sql
- tests/test_optimizer.py
cc @gtoonstra
Maybe the name `DDL` isn't the best for this, given that `INSERT` is actually in the DML category..
> Refactor(optimizer): improve handling of DDL optimization

- sqlglot/dialects/hive.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
References:
- https://cwiki.apache.org/confluence/display/hive/languagemanual+udf
- https://spark.apache.org/docs/latest/api/sql/index.html#extract
> Fix: control whether quotes are generated for extract's date part

- sqlglot/dialects/clickhouse.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_drill.py
Fixes #1982
Some case-sensitive clickhouse functions have a corresponding `Expression` class and so when we parse them, their original name is discarded and we use whatever we have in `_sql_names` at generation time, which is not valid.
Changing all `Func`s to store their name in `this` like we do for `Anonymous` is cumbersome, because we have many `Func`s that reserve `this` to represent an argument. Instead, in this approach I used the `Expression._meta` attribute to preserve the original name, because it felt like the least intrusive way to fix this issue.
cc: @cpcloud
> Fix!(clickhouse): preserve original function names instead of uppercasing

- sqlglot/transforms.py
- tests/test_transforms.py
Introducing duplicate projections could lead to problems, e.g. if the query is used in a CTAS statement.
> Fix: ensure eliminate_qualify won't introduce duplicate projections

- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_parser.py
One of the most common operations we perform in queries other than casting is coalescing. Offering a terse syntax available to all dialects just as you do with the `::` casting is hugely beneficial. This feature is also immediately attractive within a SQLMesh project and is just generally a pretty neat showcase of the power of sqlglot.
`SELECT x ?? y FROM z` -> `SELECT COALESCE(x, y) FROM z`
`"SELECT a, b ?? 'No Data' FROM z"` -> `SELECT a, COALESCE(b, 'No Data') FROM z`
cc: @tobymao
> Feat: add terse coalesce operator

- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
I wanted to avoid changing the base parser for this as it seems very non-standard (?). I also considered overriding `_parse_select` which made the most sense at first, but it always calls `_parse_set_operations` at the end, which means we'd need to actually run a transform and search for `exp.Select`, which could be costly for deeply nested UNIONs, for example.
> Fix!(tsql): parse alias = expression into an Alias

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Redshift also supports using `DATE_ADD` as an alias of `DATEADD`. Right now, they both functions are parsed differently:
```
sql = "SELECT DATE_ADD('day', 1, date('2023-01-01'))"
sqlglot.transpile(sql, read='redshift', write='redshift')
> ["SELECT DATEADD(day, 1, 'day')"]
sql = "SELECT DATEADD('day', 1, date('2023-01-01'))"
sqlglot.transpile(sql, read='redshift', write='redshift')
> ["SELECT DATEADD(day, 1, DATE('2023-01-01'))
```
Added the same parser used on DATEADD to fix this difference.
> fix(parser, redshift): parse dateadd alias date_add

- sqlglot/dialects/starrocks.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_starrocks.py
See:
- https://github.com/tobymao/sqlglot/pull/2006#discussion_r1287176192
- https://github.com/tobymao/sqlglot/pull/2006#discussion_r1287181377
References:
- https://docs.starrocks.io/en-us/3.0/sql-reference/sql-functions/like_predicate-functions/regexp
- https://docs.starrocks.io/en-us/3.0/sql-reference/sql-functions/date-time-functions/datediff
- https://docs.starrocks.io/en-us/3.0/sql-reference/sql-functions/date-time-functions/date_diff
> Fix!(starrocks): parse regexp, datediff correctly, fix datediff generation

- sqlglot/executor/__init__.py
- sqlglot/executor/table.py
- sqlglot/schema.py
- tests/test_executor.py
FYI there was probably a change related to the normalization logic, which broke the case mentioned in https://github.com/tobymao/sqlglot/issues/1676 (for which we didn't have a unit test, it seems). We were never hitting the section where we try to parse `DICT` as a `DataType`, so this bug was hidden at the time the issue was marked as resolved.
> Fix(executor): add table normalization, fix python type mapping

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
This is a tricky one.
I don't think this is necessarily simpler _semantically_. But it does remove COALESCE functions, which is kind of a normalization.
And it _does_ optimize queries for StarRocks. Not sure about other engines.
> feat: simplify COALESCE

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
Fixes #2020
Reference: https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-unpivot.html#syntax
> Feat(databricks): add support for UNPIVOT nulls option

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
Fixes #2022
Still investigating about the `TIMESTAMP_*` types.
> Feat(duckdb): improve support for INT128, HUGEINT, NUMERIC

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/optimizer/simplify.py
- tests/dialects/test_mysql.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/simplify.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/test_optimizer.py
This PR implements a new transformation for simplifying `CONCAT(...)` calls by reducing _groups_ of consecutive string literal arguments into single string literals.
Before:
```python
CONCAT('a', 'b', 'c') --> CONCAT('a', 'b', 'c')
```
After:
```python
CONCAT('a', 'b', 'c') --> 'abc'
```
Additionally, I fixed a bug in the MySQL dialect, where `||` was wrongly interpreted as a string concatenation operator, when it's actually a synonym to the [logical OR operator](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or).
> Feat!(optimizer): simplify concat

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_presto.py
> Feat(presto,oracle): add support for INTERVAL span types

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/doris.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_dialect.py
- tests/dialects/test_doris.py
- tests/dialects/test_snowflake.py
- Convert `NVL2` to `CASE` expression for dialects that don't support it
- Stop transforming `COALESCE` into `NVL` for Doris dialect, because the [latter](https://doris.apache.org/docs/dev/sql-manual/sql-functions/conditional-functions/nvl) is more restrictive (only 2 args).
Tested directly in the engine where it was easy to do + consulted docs for each dialect.
> Feat: improve support for NVL2 function

- sqlglot/parser.py
- tests/fixtures/identity.sql
- tests/test_parser.py
There was a regression due to https://github.com/tobymao/sqlglot/commit/0b4c6c859339d012f8302ff7fcb21195587ac428:
```python
>>> sqlglot.parse_one('SELECT "case"')
sqlglot.errors.ParseError: Expected END after CASE. Line 1, Col: 13.
SELECT "case"
~~~~
```
This is because we use the text of `"CASE"` to do a dict lookup in `NO_PAREN_FUNCTION_PARSERS` and so instead of parsing an identifier we hit the above error in `_parse_case`.
> Fix(parser): ensure identifiers aren't treated as NO_PAREN_FUNCTIONS

- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/expressions.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
Fixes #2050
References:
- https://trino.io/docs/current/functions/string.html?highlight=split_to_map#split_to_map
- https://spark.apache.org/docs/latest/api/sql/index.html#str_to_map
> Feat(presto, spark): improve support for STR_TO_MAP, SPLIT_TO_MAP

- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_presto.py
Small improvement: transpile `ANY_VALUE` to a few more dialects that don't support it or other functions that can be used similarly (e.g. without `OVER (...)` clauses associated with them, like T-SQL's `FIRST_VALUE`).
> Feat: convert ANY_VALUE to MAX for some dialects

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
The native string type for clickhouse is `String` which has the following aliases: 
- `LONGTEXT`
- `MEDIUMTEXT` 
- `TINYTEXT` 
- `TEXT` 
- `LONGBLOB` 
- `MEDIUMBLOB`
- `TINYBLOB` 
- `BLOB`
- `VARCHAR`
- `CHAR`
Relevant documentation section: https://clickhouse.com/docs/en/sql-reference/data-types/string
> Fix!(clickhouse): prefer `String` datatype instead of `TEXT` when generating SQL

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/oracle.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
Fixes #2080
```python
>>> sqlglot.parse_one("cast(x as struct(number bigint))", "duckdb")
(CAST this:
(COLUMN this:
(IDENTIFIER this: x, quoted: False)), to:
(DATATYPE this: Type.STRUCT, expressions:
(COLUMNDEF this:
(IDENTIFIER this: number, quoted: False), kind:
(DATATYPE this: Type.BIGINT, nested: False, prefix: False)), nested: True, prefix: False))
>>> sqlglot.transpile("cast(x as struct(number bigint))", "duckdb")
['CAST(x AS STRUCT(number BIGINT))']
```
cc: @cpcloud
> Fix(duckdb): improve struct kwarg parsing

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Fixes #2065
Right now, transpiling `CREATE SCHEMA IF NOT EXISTS <name>` to T-SQL produces invalid code. This PR aims to address simple cases like this by transpiling them into dynamic SQL that checks whether the schema exists with an `IF` statement and if it doesn't it creates it with an `EXEC` call.
This seems to be a needed workaround because of T-SQL's [constraints](https://stackoverflow.com/a/5748107) around schema creation (see the corresponding issue for more context).
cc: @deschman
> Feat(tsql): transpile CREATE SCHEMA IF NOT EXISTS to dynamic SQL

- sqlglot/dialects/spark2.py
- tests/dialects/test_spark.py
This syntax is what I have used in the past (with Spark 2.4) and confirmed that this works with Spark 3.2 and latest Databricks release. Newer releases of Databricks (and likely Spark) do support having the CTE after the INSERT but this format is more universally supported.
> Fix!: Have Spark put CTE at front of insert

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
Fixes #2090
Reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-05F1B577-C08C-4DB9-925A-8799C76ADFF4
> Feat(oracle): add support for $, # symbols

- sqlglot/dataframe/README.md
- sqlglot/dataframe/sql/column.py
- sqlglot/dataframe/sql/dataframe.py
- sqlglot/dataframe/sql/normalize.py
- sqlglot/dataframe/sql/readwriter.py
- sqlglot/dataframe/sql/session.py
- sqlglot/dataframe/sql/window.py
- sqlglot/helper.py
- tests/dataframe/unit/dataframe_sql_validator.py
- tests/dataframe/unit/dataframe_test_base.py
- tests/dataframe/unit/test_session.py
- tests/dataframe/unit/test_session_case_sensitivity.py
- tests/dataframe/unit/test_window.py
Slack thread that prompted this change: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1692679901587439?thread_ts=1692679773.389409&cid=C0448SFS3PF
Prior to this change all input was assumed to be Spark and then you could transpile that final query to whatever dialect you wanted. One challenge with this approach is when the user wants to do something that isn't natively supported by Spark. This example was that the user wanted case-sensitive columns but all column input into the Dataframe was assumed to be Spark and therefore case-insensitive. 
This change makes it so that the SparkSession can be configured for a specific dialect and therefore that dialect would be used for parsing all user input. As shown by the tests, this then support case-sensitive input if the target engine is …
> Feat: Support dialect across all Dataframe Operations

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Fixes #2126
References:
- https://learn.microsoft.com/en-us/answers/questions/448821/create-table-in-sql-server
- https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15
- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/
> Fix(tsql): generate IDENTITY instead of AUTO_INCREMENT

- sqlglot/dialects/dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_spark.py
The issue here was:
```python
>>> sqlglot.parse_one("STRUCT_EXTRACT(foo, bar)").sql(dialect="spark")
'foo.``'
```
Notice how `bar` is dropped. The reason is that the identifier created in the following lines has an incorrect AST: there's a `Column` under the `Indentifier` node:
https://github.com/tobymao/sqlglot/blob/cc0a6e2f362af447db990825357f00d4f512e805/sqlglot/dialects/dialect.py#L416-L419
> Fix: create the struct key properly in struct_extract_sql

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
This PR fixes the different JSON_OBJECT function in BigQuery. See https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_object
I only fixed it for Signature 1 as it is relatively easy. For Signature 2 I think there needs be some changes to incorporate this syntax in the parser.
> Fix(bigquery): parse JSON_OBJECT properly for key-value pairs

- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Most dialects repeat `ADD COLUMN` for every column being added: `ALTER TABLE a ADD COLUMN b INT, ADD COLUMN c INT`
tsql only puts `ADD` at the beginning of the column list: `ALTER TABLE a ADD b INT, c INT`
> Fix(tsql): support adding multiple columns with ALTER TABLE

- sqlglot/dialects/databricks.py
- tests/dialects/test_bigquery.py
This PR aims to improve compatibility on datetime functions when transpiling from BigQuery to Databricks SQL. 
I've tested the results on both engines and noticed the difference that the datetime results on BQ are in  ISO 8601 (with the T between date and time), while the proposed changes are not. This behavior should be acceptable for my current flows, but if you think there is a better way to do this (or any other part), I'll be happy to adjust!
BigQuery:
Databricks:
> Feat: add support for transpiling some datetime functions from bq to databricks

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_presto.py
This PR was motivated by https://github.com/tobymao/sqlglot/pull/2136. It seems like `CAST(... AS JSON)` is not valid in BQ, at least for the examples I tried:
```sql
SELECT CAST(1 AS JSON) AS foo  -- Invalid cast from INT64 to JSON at [1:13]
SELECT CAST('"foo"' AS JSON) AS foo  -- Invalid cast from STRING to JSON at [1:13]
SELECT CAST('foo' AS JSON) AS foo  -- Invalid cast from STRING to JSON at [1:13]
```
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_object
cc: @middagj
> Feat!(bigquery): improve handling of array JSON_OBJECT syntax

- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
Related to #848
This PR adds support for Postgres Object Identifier Types. 
https://www.postgresql.org/docs/8.1/datatype-oid.html
This fixes the exceptions when parsing schemas like this:
```sql
ALTER TABLE 
public.active_rule_parameters
ALTER COLUMN
id
SET 
DEFAULT nextval('public.active_rule_parameters_id_seq' :: regclass);
```
> Add postgres Object Identifier Types

- sqlglot/dialects/hive.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_hive.py
- tests/dialects/test_spark.py
Fixes #2123
Tested in https://demo.gethue.com/hue/editor/?type=hiv (enter `demo` for both the username and the password):
The date parts were chosen based on Hive's [docs](https://cwiki.apache.org/confluence/display/hive/languagemanual+types#LanguageManualTypes-Intervals) for the interval type:
> Fix(hive): parse <number> <date_part> as an interval instead of an alias

- sqlglot/dialects/hive.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_hive.py
- tests/dialects/test_spark.py
Turns out these changes were incorrect because we don't examine the surrounding context of the number being parsed, and so something like:
```python
INTERVAL 1 DAY
```
is currently converted into
```python
INTERVAL (INTERVAL 1 DAY)
```
I think that fixing this case would require us to look back 2 tokens (because `self._prev` is the number token itself), which means we'd need to pollute the number parsing logic even more. I don't think the ROI is worth it anymore, so I decided to simply revert, at least for now.
> Revert <number> <date_part> changes

- sqlglot/parser.py
- tests/test_parser.py
Fixes #2154
Before:
```python
>>> expression1 = sqlglot.parse_one("select a from tbl where a <= date '1998-12-01' - interval '71 days' group by b")
>>> expression2 = sqlglot.parse_one("select a from tbl where a <= date '1998-12-01' - interval '71 days'")
>>> expression1
...
(INTERVAL this:
(LITERAL this: 71 days, is_string: True))))), group:
...
>>> expression2
...
(INTERVAL this:
(LITERAL this: 71, is_string: True), unit:
(VAR this: days))))))
```
After:
```python
>>> expression1 = sqlglot.parse_one("select a from tbl where a <= date '1998-12-01' - interval '71 days' group by b")
>>> expression2 = sqlglot.parse_one("select a from tbl where a <= date '1998-12-01' - interval '71 days'")
>>> expression1
...
(INTERVAL this:
(LITERAL this: 71, is_string: …
```
> Fix(parser): solve interval parsing bug

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #2148
cc @tobymao had already started working on this; it doesn't parse all `SHOW` variants, but it solves the original issue and falls back to parsing `SHOW ...` as a `Command` in all other cases. It also serves as a foundation for completing the parsing of `SHOW` statements if we ever need to extend it.
Reference: https://docs.snowflake.com/en/sql-reference/sql/show-primary-keys
> Feat!(snowflake): improve parsing for SHOW statement

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
> Feat(spark): add support for raw strings

- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_teradata.py
> Feat(teradata): add support for the SAMPLE clause

- setup.py
Fixes #2168
Reference: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires
> Chore: add minimum python version required to setup.py

- sqlglot/dialects/doris.py
- sqlglot/dialects/mysql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
Correctly maps `TIMESTAMP` -> `DATETIME` and uses `TIMESTAMP` function when creating the timestamp types.
> Fix!: MySQL Timestamp Data Types

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
There is no `VARIANCE_POP` function in DuckDB, only `var_pop`
> fix(duckdb): rename VariancePop -> var_pop in DuckDB

- sqlglot/optimizer/merge_subqueries.py
- tests/fixtures/optimizer/merge_subqueries.sql
This check was using the CTE name, but that name can be aliased in the outer scope.
> fix(optimizer): merge subqueries should use alias from outer scope

- sqlglot/dialects/oracle.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
Fixes item 3 of #2187
References:
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_ARRAY.html
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_OBJECT.html
> Feat!(oracle): refactor parsing of 'FORMAT JSON', add support for JSON_ARRAY

- sqlglot/dialects/oracle.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
Fixes #2187
Note that the `COLUMNS` clause requires parentheses according to Oracle's spec, so right now the form `COLUMNS ...` without parentheses fails, cc @sashindeitidata are you sure your queries are valid Oracle SQL w.r.t. this? If they are, then this should be an easy fix (i.e. not requiring parens).
The `JSON_TABLE` hasn't been fully implemented, and also `JSON_VALUE` is still parsed into an `Anonymous`. I believe the issue should be addressed with these PRs. We'll be happy to accept contributions related to improving support for these functions. I think adding full support is out of scope for the time being.
Reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_TABLE.html
> Feat(oracle): add support for JSON_TABLE

- sqlglot/dialects/dialect.py
- sqlglot/dialects/redshift.py
- sqlglot/parser.py
- tests/dialects/test_redshift.py
- tests/test_parser.py
Redshift doesn't natively support `CONCAT_WS` so this adds support using double pipe. It also adds an explicit parser for `CONCAT_WS` in order to support the `CONCAT_NULL_OUTPUTS_STRING` flag.
> Feat: Add redshift concat_ws support

- sqlglot/dialects/tsql.py
- tests/dialects/test_mysql.py
it seems like T-SQL doesn't support locking reads, at least by default.
> Fix!(tsql): get rid of locking reads

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
IS NULL seems more standard than the ISNULL function.
I've wrapped it in parenthesis because I'm scared of operator precedence issues.
> fix(mysql): transpile ISNULL to IS NULL

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/generator.py
- sqlglot/transforms.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
- Made a few corrections on the `unnest_sql` override, so that Snowflake can [generate the array index](https://docs.snowflake.com/en/sql-reference/functions/flatten#output) when the `offset` arg is set.
- Made sure `IFF` [always has three arguments](https://docs.snowflake.com/en/sql-reference/functions/iff).
The `UNNEST([1, 2, 3])` duckdb -> snowflake case needs a bit more work but I couldn't figure out what was wrong with a quick eyeball, cc @tobymao can you take a look at the Snowflake query below (result of transpilation) and see if I missed something?
> Fix(snowflake): rename GenerateSeries, include offset in unnest_sql

- sqlglot/dataframe/sql/column.py
- tests/dataframe/unit/test_session_case_sensitivity.py
The issue here was that 1) `name` was parsed according to Spark, instead of using the session's dialect 2) if quotes were present in `name`, the whole alias name would be treated as an "unsafe identifier" in `to_identifier`, which resulted in adding more quotes and thus generating incorrect SQL.
> Fix(dataframe): ensure Column.alias preserves quotes

- sqlglot/parser.py
- tests/dialects/test_postgres.py
Postgres supports `CASCADE` and `RESTRICT` constrain actions. 
`CASCADE` is parsed by the library without problems, but `RESTRICT` is not. 
This PR fixes this
**Docs**
https://www.postgresql.org/docs/current/ddl-constraints.html
> fix(postgres): parse RESTRICT constrain action

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix(bigquery): allow overlaps to be used as an identifier

- setup.py
- sqlglot/_typing.py
- sqlglot/expressions.py
- sqlglot/helper.py
- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
- tests/test_helper.py
Simplify DATE_TRUNC functions.
This is particularly useful because of date partitioned tables.
```sql
SELECT
DATE_TRUNC('week', CAST(ts AS DATE)) AS week,
SUM(measure) AS metric
FROM fact
WHERE DATE_TRUNC('week', CAST(ts AS DATE)) >= CAST('2023-01-01' AS DATE)
GROUP BY 1
```
The WHERE predicate is kind of silly, but it happens. Especially by programmatically generated queries.
Some engines don't have this optimization, in which case partition pruning will fail.
> feat(optimizer): simplify date_trunc

- sqlglot/expressions.py
- sqlglot/helper.py
- tests/test_expressions.py
Before:
```python
>>> for x in sqlglot.parse_one("select 1"):
...     pass
...
<infinite loop - hangs>
```
After:
```python
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "sqlglot/expressions.py", line 764, in __iter__
raise TypeError(f"'{self.__class__.__name__}' object is not iterable")
TypeError: 'Select' object is not iterable
```
> Fix: ensure Expression is not an iterable to avoid inf. loops

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/fixtures/identity.sql
KILL statement.
This is based on MySQL's.
There are versions of TSQL's KILL statement for which this won't work: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/kill-transact-sql?view=sql-server-ver16
But those should be failing today anyways.
> feat: kill

- sqlglot/generator.py
- tests/dialects/test_redshift.py
Before this fix, it wasn't possible to transpile a 10k sized `VALUES` clause into Redshift without increasing the recursion limit, due to the deep nesting of the generated `exp.Union` expressions.
> Fix: improve performance of VALUES -> UNION ALL transpilation

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_tsql.py
> fix(bigquery): preserve log argument order when parsing and generation dialects match

- sqlglot/generator.py
- tests/dialects/test_redshift.py
We're currently using the raw alias name when converting `VALUES` to `UNION ALL`, so we drop any quotes:
```python
>>> sqlglot.transpile('select * from (values (1)) as `t`(a)', 'spark', 'redshift')
['SELECT * FROM (SELECT 1 AS a) AS t']
```
> Fix(redshift): generate correct SQL VALUES clause alias

- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Fix #2290
Not sure if this is the cleanest way to solve this... The issue with `_parse_statement` in the section I changed is that it parses the string and then `OPTIONS` becomes an alias.
> Fix(bigquery): anticipate OPTION property after JS UDF definition

- sqlglot/dialects/spark.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
Fixes #2301
References:
- https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-table-using.html
- https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
- https://github.com/apache/spark/pull/38823
> Fix!(spark): parse computed column constraints appropriately

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_snowflake.py
BigQuery supports both `CREATE ... COPY ...` and `CREATE ... CLONE ...` and they have different semantics. I was unaware of this when I merged https://github.com/tobymao/sqlglot/commit/8ed0a810ef4ec36ca648ad55b7a873ce04b8da30 and accidentally broke a SQLMesh test.
References:
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_clone_statement
- https://tsaiprabhanj.medium.com/bigquery-copy-vs-clone-table-d4a57c6de422
- https://docs.snowflake.com/en/sql-reference/sql/create-clone
> Fix!(bigquery): preserve the correct exp.Clone keyword

- sqlglot/dialects/databricks.py
- tests/dialects/test_tsql.py
Only BIGINT column type is supported on Databricks as IDENTITY column.
It's harmless to upgrade INT to BIGINT for identity columns and is what a human transpiler would do.
a INT column type will generate a parse exception in spark/databricks.
**Official Documentation**
https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-table-using.html#parameters
GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( [ START WITH start ] [ INCREMENT BY step ] ) ]
Applies to: check marked yes Databricks SQL check marked yes Databricks Runtime 10.3 and above
Defines an identity column. When you write to the table, and do not provide values for the identity column, it will be automatically assigned a unique and statistically increasing (or decreasing if step is negative) value. This …
> Fix!(databricks): upgrade IDENTITY column type to BIGINT if INT 

- sqlglot/expressions.py
- tests/dialects/test_postgres.py
Fixes the issue mentioned in https://github.com/tobymao/sqlglot/pull/2277#issuecomment-1733901567
> Fix!: make ObjectIdentifier, IntervalSpan and PseudoType DataTypes

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #2278 (completely)
Reference: https://www.postgresql.org/docs/current/indexes-opclass.html
Note: I couldn't find any example that documented the usage of `opclass_options`, so I decided to ignore them for now. It should be easy to add support for them later when a use case arises.
> Feat(postgres): add support for operator classes in CREATE INDEX DDL

- sqlglot/optimizer/canonicalize.py
- tests/fixtures/optimizer/canonicalize.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
`SELECT COALESCE(TRUE, 0)` breaks trino:
```
trino error: line 1:23: All COALESCE operands must be the same type or coercible to a common type. Cannot find common type between boolean and integer, all types (without duplicates): [boolean, integer]
```
Conversely, mysql doesn't have a boolean type, so we see predicates like `SELECT ... WHERE COALESCE(..., 0)`
> feat(optimizer): ensure boolean predicates on CASE statement

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
Spark's create temporary table needs provider (`using parquet`)
> Fix!(spark): create temporary table needs provider

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/postgres.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
Fixes #2316 - planning to do another pass on this and double-check some changed tests etc.
cc: @pkit
References:
- https://clickhouse.com/docs/en/sql-reference/syntax#heredoc
- https://www.postgresql.org/docs/8.1/sql-syntax.html (see «Dollar-Quoted String Constants» section)
> Feat!: add support for heredoc strings (Postgres, ClickHouse)

- sqlglot/dialects/clickhouse.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Addresses https://github.com/tobymao/sqlglot/issues/2323#issuecomment-1736991605 and fixes another generation bug.
References:
- https://clickhouse.com/docs/en/sql-reference/statements/select/sample
- https://play.clickhouse.com/play?user=play#U0VMRUNUIHN1bShmb28gKiBiYXIpIEZST00gYmxhIFNBTVBMRSAoMTAwMDAwMDAp
> Fix(clickhouse): don't generate parentheses, match R_PAREN conditionally

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
This PR reverts https://github.com/tobymao/sqlglot/commit/66aadfc60b9bffe914b89043b293a3e7357d5dde#, because my understanding of the intended "escaping" semantics at the time was incorrect.
Phillip's original BQ query in #2225 was `SELECT '\a\b\f\n\r\t\v'`, i.e. this is what one would type verbatim in BQ's editor to run it against the engine. However, the python string `"SELECT '\a\b\f\n\r\t\v'"` that was fed into `transpile` is not the "correct" representation of the above query, because it's not what one would get if they were to read that query from a file, i.e. the source of truth for what the SQL means, in python:
```
➜ cat test.sql
SELECT '\a\b\f\n\r\t\v'
➜ python
Python 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", …
```
> Fix!: revert escape sequence changes introduced in #2230

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #2335
It doesn't seem like Snowflake supports Postgres' `FROM x WINDOW y AS (...)` syntax, e.g. this is invalid in Snowflake:
```sql
SELECT SUM(x) OVER a, SUM(y) OVER b FROM c WINDOW a AS (PARTITION BY d), b AS (PARTITION BY e)
```
I also checked their docs and didn't find an example with `WINDOW` having special meaning after a table reference in the `FROM` or `JOIN` clause.
References:
- https://docs.snowflake.com/en/sql-reference/functions-analytic#window-syntax-and-usage
- https://community.snowflake.com/s/question/0D50Z00008fZVLZSA4/is-there-a-way-to-reuse-a-partition-by-clause-
> Fix(snowflake): allow window to be used as a table alias

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
In MySQL, the `DECIMAL` type can also be unsigned. 
```
[DECIMAL[(M[,D])] [UNSIGNED] [ZEROFILL]]
```
This PR adds a `UDECIMAL` type.
docs: https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
> Feat(mysql): add unsigned decimal type

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_dialect.py
Add `eliminate_qualify` to dialects that support window functions but not `QUALIFY` syntax
> feat: add `eliminate_qualify` to clickhouse, mysql, oracle, postgres, and tsql dialects

- sqlglot/dialects/spark2.py
- sqlglot/executor/env.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/test_executor.py
Closes #2341
It seems like we weren't parsing the arguments in the correct order for Snowflake and BigQuery, because the CSV parsing was taking into account only Spark's syntax which expects the trim pattern first and then the actual value.
References:
- https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#trim
- https://docs.snowflake.com/en/sql-reference/functions/trim
- https://spark.apache.org/docs/2.4.4/api/sql/#trim
> Feat(executor): add support for TRIM, fix TRIM CSV-style parsing order

- sqlglot/expressions.py
- tests/test_expressions.py
Before:
```python
>>> expr = sqlglot.parse_one("select * from '@foo/bar'", "snowflake")
>>> sqlglot.exp.table_name(expr.find(sqlglot.exp.Table))
''
```
After:
```python
>>> expr = sqlglot.parse_one("select * from '@foo/bar'", "snowflake")
>>> sqlglot.exp.table_name(expr.find(sqlglot.exp.Table))
"'@foo/bar'"
```
> Fix: handle strings in Table.parts, use dialect for parsing in table_name

- sqlglot/dialects/hive.py
- sqlglot/dialects/oracle.py
- sqlglot/generator.py
- tests/dialects/test_oracle.py
Fixes #2356
This shouldn't be breaking, I remember adding support for the `expression` argument only to handle Oracle's `BYTE`, `CHAR` type specifiers, see https://github.com/tobymao/sqlglot/commit/3ee16c5e8
> Fix(hive): don't generate BYTE when transpiling Oracle's VARCHAR(5 BYTE)

- sqlglot/optimizer/merge_subqueries.py
- tests/fixtures/optimizer/optimizer.sql
Before:
```python
>>> query = """
... SELECT Name,
...        FruitStruct.`$id`,
...        FruitStruct.value
...   FROM
...        (SELECT Name,
...                explode(Fruits) as FruitStruct
...           FROM fruits_table)
... """
>>> print(optimize(query, dialect="spark").sql(dialect="spark", pretty=True))
SELECT
`fruits_table`.`name` AS `name`,
EXPLODE(`fruits_table`.`fruits`).`$id` AS `$id`,
EXPLODE(`fruits_table`.`fruits`).`value` AS `value`
FROM `fruits_table` AS `fruits_table`
```
Spark doesn't like ``` EXPLODE(...).`$id` ``` apparently, so this PR aims to fix this issue:
```
spark-sql (default)> SELECT EXPLODE(ARRAY(CAST(STRUCT('fooo') AS STRUCT<a: STRING>))).a;
[FIELD_NOT_FOUND] No such struct field `a` in `col`.
spark-sql …
```
> Fix(optimizer): don't merge CTEs with EXPLODE projections into outer scopes

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Fixes a bug in transalation of population variance and also translates sample variance into `var_samp` which is compatible with datafusion postgres.
> fix(postgres): translate variance_pop to var_pop and variance to var_samp

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
tsql does not have a DOUBLE data type, MS maps to FLOAT in .NET
https://learn.microsoft.com/en-us/dotnet/api/system.data.sqldbtype?view=net-7.0&redirectedfrom=MSDN
> Fix(tsql): double datatype to float

- sqlglot/parser.py
- tests/dialects/test_mysql.py
Fixes #2376
TL;DR the issue is that MySQL overrides the `SCHEMA_UNNAMED_CONSTRAINTS` and adds `KEY` to it, so the ``` `key` ``` identifier's text unfortunately matches that and we eagerly consume it as an unnamed constraint even though we shouldn't.
Not sure if this is the correct approach.. I also thought about not matching identifiers in `_match_texts` but that's a change with a bigger impact and I wanted to discuss about it first.
cc @tobymao what do you think?
> Fix(parser): don't consume identifier in unnamed constraint parser

- sqlglot/schema.py
- tests/test_schema.py
Thought something like this might be an improvement to the API
> Feat(schema): add method to check if column exists

- tests/test_executor.py
This can also be fixed at the executor level, but that would be a breaking change and I wasn't sure if we even want to change the representation of `NULL` values. See also: https://github.com/pandas-dev/pandas/pull/52081.
The warning can be seen [here](https://github.com/tobymao/sqlglot/actions/runs/6439453133/job/17487149707) (corresponding to the latest commit in main):
> Fix: silence Pandas warning by replacing executor None values with np.NaN

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
This PR:
- Fixes a typo in the optimizer (~which is a breaking change, I guess~): compliments -> complements 😄 
- Improves `simplify_concat` by extending it to also handle `CONCAT_WS`
Regarding the second point, a core assumption here is that the separator always comes first in the argument list of `CONCAT_WS`. This is the case in several dialects I checked (*), and is also reinforced by the tests we have. In any case, I think the optimization is valid and if there's ever an exception to this then it should be probably handled at parse time in order to facilitate transpilation too.
(*): Postgres, MySQL, DuckDB, Spark, Presto, Trino, Snowflake, T-SQL
> Feat(optimizer): simplify CONCAT_WS

- sqlglot/schema.py
In SQLMesh we use the `MappingSchema` to store `DataType`s and it works just fine. Not sure why we restricted the type hint to just `str` for the types to begin with.
> Fix(schema): don't specialize type variable in MappingSchema

- sqlglot/optimizer/scope.py
- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
This PR adds support for a `prune` callback argument in `walk_in_scope`, similar to how `walk` works. It then leverages it to fix the bug demonstrated below:
Before:
```python
>>> from sqlglot.optimizer.simplify import simplify
>>>
>>> simplify(parse_one("x = 1 and case when x = 5 then false else true end"), constant_propagation=True).sql()
'FALSE'
```
After:
```python
>>> from sqlglot.optimizer.simplify import simplify
>>>
>>> simplify(parse_one("x = 1 and case when x = 5 then false else true end"), constant_propagation=True).sql()
'x = 1 AND CASE WHEN FALSE THEN FALSE ELSE TRUE END'
```
One obvious improvement that can be made in a followup PR (I plan to do this soon) is to reduce conditional expressions such as `IF` …
> Fix(optimizer): don't propagate equality constraints from IF/CASE outwards

- sqlglot/executor/table.py
- sqlglot/schema.py
Context: https://github.com/tobymao/sqlglot/pull/2394#discussion_r1353226696
Marked as breaking because client code that specializes the schema type won't work without the generic AFAICT.
> Chore!: remove generic schema type

- sqlglot/expressions.py
- tests/dialects/test_postgres.py
Maybe I'm missing something, but this looks like a simple omission to me - `RegexpLike` is a subclass of `Binary`, so I guess `RegexpILike` should be too.
Thanks so much for sqlglot by the way, it's awesome. Let me know if I can sponsor you.
> Fix: make `RegexpILike` a subclass of `Binary` as well as `Func`

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
Fixes #2406
Couldn't find another variant for case-insensitive matching. There's `ILIKE` but I don't think it works with regex patterns?
Reference: https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions
> Fix(clickhouse): map RegexpILike to match

- .pre-commit-config.yaml
- sqlglot/expressions.py
- sqlglot/optimizer/simplify.py
- sqlglot/planner.py
I had quite a lot of `cast`s in my code, this should remove most of them.
It's a shame we can't mark `expression.this` as a `Expression` which is always seems to be for me, but in you code you have some places where you're assuming it's a `str`, so I assume it's not always an `Expression`.
> add some more types

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
Snowflake has a unique "ALTER TABLE a SWAP WITH b" syntax, this adds supports analogous to "ALTER TABLE a RENAME TO b".
> Feat(snowflake): support for ALTER TABLE SWAP WITH

- sqlglot/lineage.py
- tests/test_lineage.py
This is the second part to solve extracting a full lineage from a `LATERAL FLATTEN(...` statement in Snowflake #2413, and adds support for getting all columns used in a UDTF to then build downstream nodes for those columns. 
This extends the set of columns generated by doing a `select.find_all(exp.Column)` with any columns found by searching `source.find_all(exp.Column)`, when the source is an instance of `exp.UDTF`. I'm not 100% that's the best way to implement it -- will select.find_all(...) ever return other columns when reading from a UDTF? -- if not this should probably be an `if isinstance(source, exp.UDTF)...else...` instead.
> Feat(lineage): lineage from UDTFs that use columns

- sqlglot/dialects/tsql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_tsql.py
tsql's `TEXT` data type is both [deprecated](https://learn.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver16) and has a number of functional limitations (can't be used as primary key/index or compared with `=`). 
Microsoft explicitly instructs people to use VARCHAR(max) instead.
> Feat!(tsql): map TEXT datatype to VARCHAR(MAX)

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Fixes #2442, following the example of how the Trino dialect overrides the naming for this function.
> Fix(redshift): don't rewrite JSON_PARSE to PARSE_JSON

- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
- tests/test_expressions.py
> Fix!: unnabreviate units, e.g. ms to millisecond

- sqlglot/expressions.py
- sqlglot/lineage.py
- tests/test_lineage.py
Building lineage when unions have a `SELECT *` statement fails with a StopIteration error because there is no fallback case if the exact column is not found in the Union's select expressions. This adds a fallback case to handle these selects when building the lineage from the union.
> Fix(lineage): handle unions with SELECT STAR

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- tests/dialects/test_presto.py
Fixes #2453
References:
- https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/argmin
- https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/argmax
- https://trino.io/docs/current/functions/aggregate.html?highlight=max_by#max_by
- https://duckdb.org/docs/sql/aggregates.html
- https://spark.apache.org/docs/latest/api/sql/index.html
- https://teradata.github.io/presto/docs/0.167-t/functions/aggregate.html
- https://docs.snowflake.com/en/sql-reference/functions/min_by
- https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#max_by
> Feat: add ArgMax, ArgMin expressions, fix their transpilation

- sqlglot/lineage.py
- tests/test_lineage.py
adds final nodes to lineage trees when a `select *` expression is found named "*" with the source set to each table in the select * scope.
> feat(lineage): terminal table node for select star

- sqlglot/generator.py
- tests/dialects/test_bigquery.py
Fixes #2455
This is probably not the most robust way to solve the issue, but not sure. What do you think @tobymao?
```
D WITH Sequences AS (
>     SELECT 1 AS id, [0, 1, 1, 2, 3, 5] AS some_numbers UNION ALL
>     SELECT 2 AS id, [2, 4, 8, 16, 32] AS some_numbers UNION ALL
>     SELECT 3 AS id, [5, 10] AS some_numbers
> )
> SELECT
>   id AS matching_rows
> FROM Sequences
> WHERE EXISTS(
>   SELECT * FROM UNNEST(some_numbers) AS _t(x) WHERE x > 5
> );
┌───────────────┐
│ matching_rows │
│     int32     │
├───────────────┤
│             2 │
│             3 │
└───────────────┘
```
> Fix: add table alias in unnest with columns only

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Currently the Postgres dialect doesn't handle this Postgres extension syntax. It is the same as BigQuery and Drill etc.
https://www.postgresql.org/docs/current/sql-createtable.html
> feat(postgres): support `PARTITION BY`

- sqlglot/dialects/mysql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
Transpiling `STR_TO_DATE(x, '%Y-%m-%dT%T')` to `CAST(DATE_PARSE(x, '%Y-%m-%dT%T') AS DATE)` is wrong.
From [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date):
> STR_TO_DATE() returns a [DATETIME](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) value if the format string contains both date and time parts, or a [DATE](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) or [TIME](https://dev.mysql.com/doc/refman/8.0/en/time.html) value if the string contains only date or time parts
I don't love doing this with a regex at parse time... open to other ideas.
> fix(mysql): str_to_date for datetime

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Addresses https://github.com/tobymao/sqlglot/issues/2069#issuecomment-1783424741
For more context, this was first added in: https://github.com/tobymao/sqlglot/commit/8532f465b
> Fix(snowflake): don't add time format in TO_TIMESTAMP if not supplied

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Seems like Redshift also supports this variant but doesn't document it. The only source I found on it was a [SO thread](https://stackoverflow.com/questions/67197117/redshift-datediff-vs-date-diff). I managed to execute queries that contain it successfully on their engine - it seems that the unit must be a string.
> Feat(redshift): add support for DATE_DIFF

- sqlglot/dialects/teradata.py
- tests/dialects/test_teradata.py
See
https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Manipulation-Language/Statement-Syntax/UPDATE/UPDATE-Syntax-Joined-Tables-Form and https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Manipulation-Language/Statement-Syntax/DELETE/DELETE-Syntax
> Fix(teradata): add UPD and DEL abbreviations

- sqlglot/dialects/teradata.py
- tests/dialects/test_teradata.py
See https://docs.teradata.com/r/SQL-Functions-Operators-Expressions-and-Predicates/June-2017/Data-Type-Conversions/TRYCAST
> Fix(teradata): support `TRYCAST`

- sqlglot/dialects/postgres.py
- sqlglot/dialects/teradata.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_teradata.py
See https://docs.teradata.com/r/SQL-Functions-Operators-Expressions-and-Predicates/June-2017/Arithmetic-Trigonometric-Hyperbolic-Operators/Functions
> Fix(teradata): support `**` for exponent

- sqlglot/planner.py
Change-Id: I72e57b11dc6d214a8cd13f18eb602b31ec5a6155
The plan of `select ... from (<subquery>) as t` is missing the step of `<subquery>`.
```python
import sqlglot
from sqlglot.planner import Plan
print(Plan(sqlglot.parse_one('select tmp.a from (select t1.a from t1 join t2) tmp')))
```
Before, no subquery projection `t1.a` and the root step is a `Join`(fusion with the inner subquery):
```yaml
- Join: tmp (4392910480)
Context:
t2: INNER
On: TRUE AND TRUE
Projections:
- tmp.a
Dependencies:
- Scan: t1 (4392621456)
Context:
Source: t1
Projections:
- Scan: t2 (4393026960)
Context:
Source: t2
Projections:
```
After this PR:
```yaml
- Scan: tmp (4354970896)
Context:
Source: tmp
Projections:
- tmp.a
Dependencies:
- Join: tmp (4355246608)
Context:
t2: INNER
On: TRUE AND TRUE
Projections:
- t1.a …
```
> fix(planner): missing step of subquery

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
Fixes #2517
Reference: https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions180.htm
> Fix(oracle): parse TO_CHAR using format_time_lambda

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
Here's an actual predicate from Tableau we're dealing with:
```sql
(
CASE 
WHEN (
IFNULL(
DATE('2050-01-01'),
STR_TO_DATE('2050-01-01','%b %e %Y')
) = DATE('2023-10-01')) 
THEN DATE(DATE_ADD(date_trunc('month', CURDATE()), INTERVAL -1 MONTH)) 
ELSE DATE(DATE('2023-10-01')) END
) = date_trunc('month', `Custom SQL Query`.`Date`)
```
This breaks partition pruning.
With this change, we get
```sql
`Custom SQL Query`.`Date` < CAST('2023-11-01' AS DATE) 
AND `Custom SQL Query`.`Date` >= CAST('2023-10-01' AS DATE)
```
> fix(optimizer): more support for date literals in simplify

- sqlglot/dialects/snowflake.py
- tests/fixtures/optimizer/quote_identifiers.sql
- tests/test_optimizer.py
Snowflake treats `DUAL` in a special way when it's used in a `FROM` clause, and quoting it breaks queries.
For example:
```
CREATE TABLE "DUAL" (a DOUBLE);
SELECT * FROM "DUAL";
```
```
SELECT * FROM DUAL;
```
> Fix!(snowflake): don't quote DUAL table because it has special meaning

- sqlglot/dialects/tsql.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/transforms.py
- tests/dialects/test_dialect.py
- tests/dialects/test_redshift.py
- tests/dialects/test_tsql.py
This aims to fix a bug where T-SQL projections are left unnamed for derived tables, which MSSQL doesn't like:
```
1> with t as (select 1) select * from t
2> go
...
No column name was specified for column 1 of 't'.
1> with t as (select 1 as c) select * from t
2> go
c
-----------
1
(1 rows affected)
1> select * from (select 1) subq
2> go
...
No column name was specified for column 1 of 'subq'.
1> select * from (select 1 as c) subq
2> go
c
-----------
1
(1 rows affected)
```
> Fix!(tsql): ensure derived table projections are named / have aliases

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
References:
- https://learn.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/t-sql/statements/delete-transact-sql?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver16
- https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-cte.html
> Fix: don't bubble up CTEs for the CREATE DDL statement

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
From Snowflake's [docs](https://docs.snowflake.com/en/sql-reference/functions/try_cast):
> Fix(snowflake): only generate TRY_CAST if cast value is of text type

- sqlglot/dialects/snowflake.py
- sqlglot/executor/env.py
- sqlglot/expressions.py
- tests/test_executor.py
https://docs.snowflake.com/en/sql-reference/functions/array_unique_agg 
> The function ignores NULL values in column. If column contains only NULL values or the table containing column is empty, the function returns an empty ARRAY.
> Feat(executor): add support for array_unique_agg

- sqlglot/optimizer/annotate_types.py
- tests/fixtures/optimizer/canonicalize.sql
- tests/test_optimizer.py
BigQuery, ClickHouse, DuckDB, Trino, Presto: int + str fails for both 1 + ‘1’ and 1 + ‘a’
Postgres, Redshift, Snowflake, T-SQL: int + str fails only for 1 + ‘a’, yields 2 for 1 + ‘1’
Hive (, Spark2?): 1 + ‘1’ yields 2, 1 + ‘a’ yields null
Spark (, Databricks?): 1 + '1' yields 2.0, 1 + 'a' yields null
MySQL, SQLite: 1 + ‘1’ yields 2, 1 + ‘a’ yields 1
Note that Spark (at least ≥v3.4.0, which I'm testing with) infers the type of `1 + '1'` to be `double` (see below). I haven't taken this into account in this PR since it seems to be the exception to the rule, but happy to discuss more about it.
```python
>>> spark.sql("select 1 + '1'")
DataFrame[(1 + 1): double]
```
> Fix!(optimizer): annotate text + numeric using the numeric type

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Fixes #2581 
Reference: https://learn.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver16#rules-for-regular-identifiers
> Fix(tsql): add special chars in single var tokens

- sqlglot/dialects/duckdb.py
- sqlglot/transforms.py
- tests/dialects/test_duckdb.py
DuckDB doesn't allow qualified columns inside of PIVOT expressions, for example:
```
D WITH Produce AS (
>   SELECT 'Kale' as product, 51 as sales, 'Q1' as quarter, 2020 as year
> )
> SELECT * FROM Produce PIVOT(SUM(Produce.sales) FOR Produce.quarter IN ('Q1', 'Q2', 'Q3', 'Q4'));
Error: Binder Error: PIVOT expression cannot contain qualified columns
D WITH Produce AS (
>   SELECT 'Kale' as product, 51 as sales, 'Q1' as quarter, 2020 as year
> )
> SELECT * FROM Produce PIVOT(SUM(sales) FOR quarter IN ('Q1', 'Q2', 'Q3', 'Q4'));
┌─────────┬───────┬────────┬────────┬────────┬────────┐
│ product │ year  │   Q1   │   Q2   │   Q3   │   Q4   │
│ varchar │ int32 │ int128 │ int128 │ int128 │ int128 │
├─────────┼───────┼────────┼────────┼────────┼────────┤
│ Kale    │  2020 │     51 │        │ …
```
> Fix(duckdb): unqualify columns under Pivot

- sqlglot/dialects/hive.py
- tests/dialects/test_redshift.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
Before:
```python
>>> sqlglot.transpile("SELECT DATEDIFF(week, '2020-01-01', '2020-12-31')", "spark", "hive")
["SELECT DATEDIFF(TO_DATE('2020-12-31'), TO_DATE('2020-01-01')) / 7"]
```
Spark yields:
```
spark-sql (default)> SELECT DATEDIFF(week, '2020-01-01', '2020-12-31');
52
Time taken: 4.038 seconds, Fetched 1 row(s)
```
But the transpiled Hive query yields:
After:
```python
>>> sqlglot.transpile("SELECT DATEDIFF(week, '2020-01-01', '2020-12-31')", "spark", "hive")
["SELECT CAST(DATEDIFF(TO_DATE('2020-12-31'), TO_DATE('2020-01-01')) / 7 AS INT)"]
```
> Fix!(hive): truncate division result in _date_diff_sql

- sqlglot/time.py
- tests/dialects/test_mysql.py
Fixes #2597
This one is tricky, not 100% sure this is the correct approach. We map `%H:%i:00.0000` to `%H:%M:00.0000` and `%H:%M:` is recognized as a valid prefix because `%H:%M:%S` is in the inverse time trie due to the`"%T": "%H:%M:%S"` entry, but when we hit `0` we get a trie lookup failure and so we make a “chunk” out of `%H:%M:` . This leads to us mapping it back to itself later instead of mapping its `%M` back to `%i`.
> Fix: time format chunk misses from mapping, but its constituent parts are not

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
projections may not exist in dialects like spark making optimizations like this illegal
```sql
with x AS (select 1 a, 2 b)
SELECT DISTINCT x.a AS c, x.b AS d
FROM x
ORDER by x.a
```
> fix!: expand positional args in order by as aliases

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
> Fix: treat parameters as primary expressions

- sqlglot/parser.py
Treating parameters as primary expressions was a breaking change for SQLMesh, so I decided to revert and implement a low-impact fix for https://github.com/tobymao/sqlglot/issues/2604
> Fix: revert 568ddd12, parse placeholder in sample instead

- sqlglot/dialects/snowflake.py
- sqlglot/generator.py
- tests/test_transpile.py
This fixes the following bug:
```python
>>> print(sqlglot.transpile("SELECT 'foo\nbar'", unsupported_level=sqlglot.errors.ErrorLevel.IGNORE, pretty=True)[0])
SELECT
'foo__SQLGLOT__LB__bar'
```
Bonus: cleaned up the `generate` command a bit because the preprocessing steps were noisy..
> Fix: always expand sentinel line break in pretty mode

- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
Fixes #2609
Note that the associativity is as follows:
```
georgesittas=# select 1 operator(+) 2 operator(*) 3;
?column?
----------
9
(1 row)
```
> Feat(postgres): add support for operators with schema path

- sqlglot/transforms.py
- tests/dialects/test_snowflake.py
Addresses https://github.com/tobymao/sqlglot/issues/2607#issuecomment-1834410405
cc @cpcloud
> Fix: preserve alias quotes in explode_to_unnest

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
> Fix(duckdb): arrays are 1-indexed

- sqlglot/tokens.py
- tests/test_tokens.py
We always check against a single character (`self._char`), so we'll never have a lookup hit for `"\r\n"` in `WHITE_SPACE`.
This means that that in systems that encode line breaks a `\r\n`, the lines stored in the tokens will be incorrect and so the errors will display misleading line numbers as well. This is showcased in the example below:
```python
>>> from sqlglot.tokens import Tokenizer
>>> for tok in Tokenizer().tokenize("select\r\n  1,\r\n  2"):
...     print(tok)
...
<Token token_type: TokenType.SELECT, text: select, line: 1, col: 6, start: 0, end: 5, comments: []>
<Token token_type: TokenType.NUMBER, text: 1, line: 3, col: 2, start: 10, end: 10, comments: []>
<Token token_type: TokenType.COMMA, text: ,, line: 3, col: 3, start: 11, end: 11, comments: []>
<Token token_type: …
```
> Fix: tokenize CRLF sequence correctly

- Makefile
- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
This PR adds a flag which controls whether to use the native tokenizer or the Python one. It also enables the continuous testing of the native implementation using the existing test suite.
> Enable tests for the Rust tokenizer

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
Take 2.
I'm scared to put this in the optimizer, since we don't handle intervals very well, and there seems to be quite a bit of differences between dialects. I don't love putting it in the generator, but it seems safe:
```
SELECT DATE_ADD('DAY', 1.0, CAST('2023-01-01' AS DATE))
...
trino error: line 1:8: Unexpected parameters (varchar(3), double, date) for function date_add. Expected: date_add(varchar(x), bigint, date), date_add(varchar(x), bigint, time(p) with time zone), date_add(varchar(x), bigint, time(p)), date_add(varchar(x), bigint, timestamp(p) with time zone), date_add(varchar(x), bigint, timestamp(p))
```
> fix(presto): coerce DATEADD expression to BIGINT

- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/test_tokens.py
- tests/test_transpile.py
> Fix(tokenizer): advance self._start by a character when we encounter CRLF

- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
Fixes #2655
Reference: https://duckdb.org/docs/sql/functions/timestamp#timestamp-functions
> Fix(duckdb): support the 6 arg. variant of make_timestamp

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_ctes.sql
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/test_optimizer.py
We need to maintain references to CTE scopes. 
```sql
WITH q AS (
SELECT
a
FROM y
)
SELECT
a
FROM x AS q  -- q is overridden in this scope
WHERE
a IN (
SELECT
a
FROM q  -- this is a new subquery scope, but q should still be the CTE
);
```
> fix(optimizer): CTE aliases overridden in FROM

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes #2699
Reference: https://clickhouse.com/docs/en/sql-reference/statements/select/order-by#order-by-expr-with-fill-modifier
> Feat(clickhouse): add support for WITH FILL, INTERPOLATED clauses

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
I realized that Snowflake's [TO_ARRAY](https://docs.snowflake.com/en/sql-reference/functions/to_array) function has a few edge cases that don't make it easy to parse it into `exp.Array`, so this PR introduces a new expression type to represent it in a way as to make it easy to preserve it on identity transpilation and follow a best-effort approach when transpiling to other dialects. I think the only cases that we'll fail to transpile are when we have a JSON null argument and a `VARIANT` that wraps around an array.
> Fix(snowflake): use ToArray expression to preserve TO_ARRAY in snowflake

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
https://prestodb.io/docs/current/sql/create-table.html
https://trino.io/docs/current/sql/create-table.html
> Fix(presto): remove equals sign from CREATE TABLE comment

- sqlglot/generator.py
- tests/dialects/test_presto.py
Fixes #2702
References:
- https://trino.io/docs/current/language/types.html#varchar
- https://spark.apache.org/docs/latest/sql-ref-literals.html#parameters
- https://docs.snowflake.com/en/sql-reference/data-types-text#escape-sequences-in-single-quoted-string-constants
> Feat: transpile Trino unicode to \u... strings (Spark, Snowflake)

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
BigQuery allows `JSON_EXTRACT_SCALAR` to get only a single argument, where the expression defaults to '$', as can be seen [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_extract_scalar).
So I added a change that will automatically add this default.
In my change after converting back to SQL the '$' parameter will be explicitly added - I thought it makes sense but please let me know if not.
> allow JSON_EXTRACT_SCALAR in BQ to pass a single argument

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/snowflake.py
- tests/dialects/test_bigquery.py
References:
- https://duckdb.org/docs/sql/functions/timestamp.html
- https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_diff
- https://docs.snowflake.com/en/sql-reference/functions/timestampdiff
> Fix(snowflake, duckdb): generate TimestampDiff correctly

- README.md
- posts/ast_primer.md
- sqlglot/expressions.py
As [discussed on slack](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1703632977455049):
The current format can be really hard to read.
```python
from sqlglot import parse_one
ast = parse_one("SELECT a, b FROM (SELECT a, b FROM x) AS x")
print(repr(ast))
```
```
(SELECT expressions: **[1]** **[3]**
(COLUMN this: 
(IDENTIFIER this: a, quoted: False)),
(COLUMN this:
(IDENTIFIER this: b, quoted: False)), from: **[2]**
(FROM this:
(SUBQUERY this:
(SELECT expressions:
(COLUMN this:
(IDENTIFIER this: a, quoted: False)),
(COLUMN this:
(IDENTIFIER this: b, quoted: False)), from:
(FROM this: 
(TABLE this: 
(IDENTIFIER this: x, quoted: False)))), alias: 
(TABLEALIAS this: 
(IDENTIFIER this: x, quoted: False)))))
```
Some problems of this format:
[1] No delineator for lists make it unclear …
> feat!: Change Expression.__repr__ format

- sqlglot/expressions.py
We currently show empty lists when `repr`ing an AST. This can become noisy because we construct empty lists all over the place due to the `_parse_csv` methods, so this PR hides them (the commented args below won't show up at all).
```python
>>> sqlglot.parse_one("CREATE TABLE z (a INT, b VARCHAR COMMENT 'z')")
Create(
this=Schema(
this=Table(
this=Identifier(this=z, quoted=False)),
expressions=[
ColumnDef(
this=Identifier(this=a, quoted=False),
kind=DataType(this=Type.INT, nested=False, prefix=False),
constraints=[  # <----- case no. 1
]),
ColumnDef(
this=Identifier(this=b, quoted=False),
kind=DataType(this=Type.VARCHAR, nested=False, prefix=False),
constraints=[
ColumnConstraint(
kind=CommentColumnConstraint(
this=Literal(this=z, is_string=True)))])]),
kind=TABLE, …
```
> Fix: include empty lists in the hide_missing repr check

- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
The correct SQL to emit is as follows:
ALTER TABLE <[name](https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-PARMS-NAME)> RENAME TO <[new_name](https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-PARMS-NEW-NAME)>`
Note the subtle difference in terminology. Its not explicitly called out as a gotcha which would be nice in the postgres docs.
> Fix: alter table rename should not qualify with db in postgres

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
Fixes #2747
- DuckDB uses `USING SAMPLE` to sample the whole resulting relation in a query, and `TABLESAMPLE` for sampling just a simple intermediate result. See https://duckdb.org/docs/sql/samples.html
- Snowflake treats `SAMPLE` and `TABLESAMPLE` as synonyms, see https://docs.snowflake.com/en/sql-reference/constructs/sample
> Refactor!: set sample clause keyword(s) as class constant to enable transpilation

- sqlglot/dialects/dialect.py
- tests/dialects/test_dialect.py
I've typed `duckbd` instead of `duckdb` so many times and it's finally occurred to me that the UX can be improved a bit :D
Reference: https://docs.python.org/3/library/difflib.html#difflib.get_close_matches
> Feat: guess the correct dialect in case we get an unknown one

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #2751
Checked almost all major dialects - none of them directly supports a concept like this one so I decided to do a simple fix. If we ever need to transpile `TIMESTAMP_FROM_PARTS(date, time)` in the future, the only way I can think of right now would be to do it through some kind of `TIMESTAMP + TIMESTAMP` function but this also might not be possible in all dialects.
Reference: https://docs.snowflake.com/en/sql-reference/functions/timestamp_from_parts
> Fix(snowflake): parse two argument version of TIMESTAMP_FROM_PARTS

- sqlglot/optimizer/qualify.py
- sqlglot/optimizer/qualify_columns.py
- tests/test_optimizer.py
People have [asked](https://github.com/tobymao/sqlglot/issues/2760#issuecomment-1875664452) for the star expansion to be optionally turned off a few times already, so I thought it wouldn't hurt if we exposed an option for that.
> Feat(optimizer): allow star expansion to be turned off

- sqlglot/schema.py
it's expensive to parse the schema even when it's already normalized
> fix: don't normalize schema if normalize is set to false

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
The motivation behind this PR is that T-SQL requires the session parameter `QUOTED_IDENTIFIER` to be set to `ON` for double quotes to work when used around db objects. For example:
```
1> SET QUOTED_IDENTIFIER ON
2> WITH "t" AS (SELECT 1 AS c) SELECT * FROM "t"
3> GO
c          
-----------
1
(1 rows affected)
1> WITH [t] AS (SELECT 1 AS c) SELECT * FROM [t]
2> GO
c          
-----------
1
(1 rows affected)
1> SET QUOTED_IDENTIFIER OFF
2> WITH "t" AS (SELECT 1 AS c) SELECT * FROM "t"
3> GO
Msg 102, Level 15, State 1, Server 58a9c7ad0aac, Line 2
Incorrect syntax near 't'.
Msg 102, Level 15, State 1, Server 58a9c7ad0aac, Line 2
Incorrect syntax near 't'.
1> WITH [t] AS (SELECT 1 AS c) SELECT * FROM [t]
2> GO
c          
-----------
1
(1 rows affected)
```
This showcases that depending on …
> Fix!(tsql): use square bracket quotes by default, not quotes

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/fixtures/optimizer/optimizer.sql
Still need to test a few more engines but this should be a good start (will iterate on this PR).
References:
- https://docs.snowflake.com/en/sql-reference/constructs/unpivot
- https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unpivot_operator
- https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-unpivot.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_FROM_clause-pivot-unpivot-examples.html#r_FROM_clause-unpivot-examples
- https://learn.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver16
> Feat(optimizer): add support for the UNPIVOT operator

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Motivation behind this PR is this optimizer error:
```python
>>> optimize("select struct_pack(a := 1)", dialect="duckdb")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "sqlglot/optimizer/optimizer.py", line 92, in optimize
expression = rule(expression, **rule_kwargs)
File "sqlglot/optimizer/qualify.py", line 90, in qualify
validate_qualify_columns_func(expression)
File "sqlglot/optimizer/qualify_columns.py", line 87, in validate_qualify_columns
raise OptimizeError(f"Column '{column}' could not be resolved{for_table}")
sqlglot.errors.OptimizeError: Column 'a' could not be resolved
```
> Fix!(duckdb): parse STRUCT_PACK names to identifiers instead of columns

- sqlglot/dialects/dialect.py
- tests/dialects/test_duckdb.py
When transpiling from a language that supports `SAFE_DIVIDE` to one that does not where the arguments are nested, it is possible to cause incorrect behaviour. For instance, the following yields an incorrect query result, going from BigQuery (`SAFE_DIVIDE` supported) to DuckDB (unsupported). Observe that the `IF` condition has an ambiguous argument, and that the same is true after a round trip through the transpiler:
```py
In [15]: print(bq)                                                                                                                                                                                                                       
(
SAFE_DIVIDE(
commanded_curvature - LAG(commanded_curvature) OVER (ORDER BY header_timestamp ASC), 
header_timestamp - …
```
> fix: add parentheses to no_safe_divide args

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
See https://clickhouse.com/docs/en/sql-reference/data-types/ipv4 and https://clickhouse.com/docs/en/sql-reference/data-types/ipv6
It's pretty similar to Presto `IPADDRESS` type, but sematically different as Presto type is IPV6 with IPV4 convertion.
> Fix(clickhouse): add ipv4/6 data type parser

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
Another one of these strange types. See here: https://clickhouse.com/docs/en/sql-reference/data-types/date32
Semantically and physically it's totally different from `DATE` thus cannot be directly cast...
> Feat(clickhouse): support Date32 type

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
Fixes: #2831
Supporting only `.FF6` is probably too strict. Open to suggestions (python uses 6 digits with padding for `.%f` so...).
> Fix(oracle): TO_TIMESTAMP not parsed as StrToTime

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
The docs have 0, 3, and 9 as examples but it works for all values between 0 and 9, inclusive. This removes the check and instead tries to choose the right scale and defaults to None if it fails.
> fix(snowflake): Support more scale values for Snowflake's to_timestamp function

- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/trino.py
- tests/dialects/test_postgres.py
Some connectors for Trino support merge (like Iceberg and Delta) and, similar to Postgres, they require that there is not an alias defined for target. 
This is not added for Presto since Presto does not support MERGE: https://github.com/prestodb/presto/issues/20578
> feat: remove target alias in Trino merge

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
We currently return `False` in some `match` methods, and `None` in some others. This PR changes the former category to also return `None` for consistency. The motivation for this is to allow e.g. `_match_text_seq` to be used inline when instantiating an expression without having to worry about `False` having special semantics. So, something like:
```python
self.expression(exp.Foo, this=self._match_text_seq(...) and ...)
```
> Refactor!(parser): make text matching return None for consistency

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
these can be used in column definitions:
- AggregateFunction
- SimpleAggregateFunction
See https://clickhouse.com/docs/en/sql-reference/data-types/aggregatefunction and https://clickhouse.com/docs/en/sql-reference/data-types/simpleaggregatefunction
These are pretty peculiar, 'cos the first argument is either a "function identifier" or a "parameterized function identifier".
`sqlglot` has no notion of both, so I've just opted out for usual identifiers/functions, works in my case.
From ClickHouse docs it's not clear where else it can be used except column definitions, probably nowhere.
For expressions they use special functions like `initializeAggregation()` or `finalizeAggregation()`
> Feat(clickhouse): AggregateFunction data type

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_spark.py
Fixes #2846
There's probably a better / more robust solution to this, by parsing `FROM/TO_UTC_TIMESTAMP` into a different node that represents timezone conversion. Will leave this for a future PR since it's gonna take a bit more effort.
> Feat: improve transpilation of Spark's TO_UTC_TIMESTAMP

- sqlglot/optimizer/qualify_tables.py
- tests/fixtures/optimizer/qualify_tables.sql
- tests/test_optimizer.py
As per discussion. We should qualify these table references if passed that particular expression type.
> Fix: qualify alter table table refs in optimizer qualify

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
Fix is thanks to @barakalon who pointed out the AST mangling 🙇
> Fix(optimizer): don't copy projection in qualify_outputs when attaching alias

- sqlglot/schema.py
This seemed like a good method to have in the `Schema` class as an abstract method. Also, since the `trie` parameter isn't used anywhere in the sqlglot codebase I got rid of it - it wouldn't make much sense to have it in the `Schema` signature, since it's mostly related to the abstract mapping schema class.
> Refactor!(schema): make find method abstract, get rid of trie parameter

- sqlglot/dialects/postgres.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
This basically allows the create parser to produce a `Command` when it hasn't consumed the whole token stream, meaning that we'll avoid raising `ParseError`s when e.g. unknown table properties are encountered. Instead, we'll simply accept whatever the user supplies, store it as a string and when https://github.com/tobymao/sqlglot/pull/2874 is in, emit a warning to let them know.
The motivation is to avoid having to add first-class support for DDL clauses that may be too engine-specific and not transpilable. Of course, if we ever need to transpile or switch off specific props or analyze the AST, we'll still have to implement parsing and generation logic for the corresponding properties, but hopefully we should not need that often.
> Feat: make the CREATE parser more lenient

- sqlglot/dialects/redshift.py
This adds `GETDATE` to the parser for Redshift.
> Feat(redshift): parse GETDATE

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
Context: https://github.com/tobymao/sqlglot/issues/2846#issuecomment-1906214954
See also: https://stackoverflow.com/a/53873808
> Fix!(presto): generate AT_TIMEZONE instead of AT TIME ZONE to allow column tzs

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
This addresses two issues:
1. Right now, we parse DuckDB's JSON pointer paths incorrectly, and as a result we also clutter them at generation time:
```python
>>> print(sqlglot.transpile("""SELECT json_extract('{"duck": [1, 2, 3]}', '/duck/0');""", "duckdb")[0])
SELECT '{"duck": [1, 2, 3]}' -> '$["/duck/0"]'
```
2. DuckDB supports a variant of the [JSONPath](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html) syntax spec, where one can access elements from the back of an array using the following syntax:
```sql
SELECT json_extract('{"duck": [1, 2, 3]}', '$.duck[#-1]');
-- 3
```
We currently emit a warning when encountering paths like this which can be noisy, since DuckDB users will probably expect this to _parse normally_.
> Fix(duckdb): fix JSON pointer path parsing, reduce warning noise

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
`SHOW SCHEMAS` is an alias for `SHOW DATABASES`: https://dev.mysql.com/doc/refman/8.0/en/show-databases.html
> fix(mysql): SHOW SCHEMAS

- sqlglot/generator.py
This path isn't ever reached and to my understanding it's very old code; I believe the intention was to allow strings too, but we never really did that, it seems. Thought I'd clean it up so it's clear we can only have callables in `TRANSFORMS`.
> Refactor!: deprecate case where transforms can be plain strs

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_parser.py
Prior to this change table objects which were the target of `CREATE SCHEMA` or `DROP SCHEMA` would set this as the db name and then db as the catalog name (if provided). The rendered SQL is fine but if we call something like `qualify_table` on the expression and try to set a catalog if one does not exist then it will add the catalog when it is not needed since it will see the catalog filed as None when really catalog is set but it is just set in the `db` field.
> fix: have table exclude this if schema target

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_dialect.py
- tests/dialects/test_redshift.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_sqlite.py
Fixes #2922
We can probably transfer this logic to the base generator and control it with a flag, so other dialects besides duckdb can leverage it. Can open a separate PR for it later or do it here, just need a bit more time to investigate.
> Feat: improve transpilation of CREATE TABLE LIKE statement

- sqlglot/_typing.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/executor/python.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
- tests/dialects/test_sqlite.py
Several changes here, not necessarily related to each other:
- Improve parsing / transpilation of clickhouse's `JSONExtractString`, fixes https://github.com/tobymao/sqlglot/issues/2051. Note that clickhouse uses 1-based indexing, so I had to slightly change the logic in some parts to take this into account. Perhaps and interesting observation here is that the dialect offset is not necessarily tied to the JSON path offset.
- Refactored some helpers that concern JSON path parsing and generation and are used by clickhouse, postgres, redshift.
- Fixed some issues related to columns being used in json paths (supported by clickhouse, duckdb, postgres). This involved a change that may need some attention in the parser (I split `_parse_column` into two methods, can elaborate if needed).
- …
> Feat(clickhouse): add support for JSONExtractString, clean up some helpers

- sqlglot/schema.py
Chatted with Barak and realized this method imposes an additional constraint on Schema implementors which is probably unnecessary, so I decided to revert the change and only keep it under `AbstractMappingSchema`.
Context behind the addition of this method: https://github.com/tobymao/sqlglot/pull/2869
> Fix: remove find method from Schema

- sqlglot/dialects/postgres.py
- sqlglot/tokens.py
- sqlglotrs/src/settings.rs
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_clickhouse.py
- tests/dialects/test_postgres.py
Fixes #2931
Postgres requires heredoc tags to follow the same lexical rules as the unquoted identifiers, so a digit after the `HEREDOC_STRING` token (`$`) can unambiguously be assumed to be a parameter number.
Reference: https://www.postgresql.org/docs/current/sql-syntax-lexical.html
> Fix(postgres): fallback to parameter parser if heredoc is untokenizable

- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_hive.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
Spark 3 supports two CREATE TABLE formats:
https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-hiveformat.html
https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-datasource.html
Some of the spark dialect assumes the former, some assumes the latter, and you can easily end up with an invalid statement.
All this DDL transpilation feels very messy to me... I hated this change.
> fix(spark): CREATE TABLE ... PARTITIONED BY fixes

- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- tests/dialects/test_dialect.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
Got rid of the Spark test for `IIF` because it doesn't support it (tried both v2 and v3). The addition to `FUNCTIONS` must have been an oversight, relevant commit is https://github.com/tobymao/sqlglot/commit/e2cdde57b.
Reference: https://www.sqlite.org/lang_corefunc.html#iif
> Feat(sqlite): add support for IIF

- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/teradata.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/fixtures/identity.sql
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
- tests/test_parser.py
- tests/test_transpile.py
Fixes #2957
I investigated a bit and this is what I found for the dialects currently supported by SQLGlot w.r.t. the `VALUES` clause syntax:
- Doesn't have a `VALUES` clause: BQ, Redshift
- '(' needs to follow `VALUES`: ClickHouse, DuckDB, Postgres, Snowflake, SQLite, T-SQL
- 'ROW' needs to follow `VALUES`: MySQL, probably Doris and Starrocks too due to lineage (haven't tested)
- "Anything" can follow `VALUES` (side effect of allowing stuff like `VALUES 1, 2, 3`): DataBricks, Hive, Oracle, Presto, Spark, Teradata, Trino
This PR allows `values` to be parsed into an `Identifier` for the first three categories. For the last one, fixing the parser is a bit more tricky (due to ambiguity) and so we decided to tackle it in a future PR. FWIW Presto and Trino don't seem to allow an unquoted …
> Fix(parser): enable parsing of values into Identifier for some dialects

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/redshift.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_redshift.py
Fixes #2963
Many of the lines changed are just reordered tests - did that to group `validate_identity` and `validate_all` together but can revert if it's too noisy. Will comment inline to point out the changed / added ones.
> Fix: don't treat VALUES as a keyword in BigQuery, Redshift

- sqlglot/lineage.py
- tests/test_lineage.py
Before, we were only tracking source table for the outermost query of sources, but losing that information in any of their CTEs, subqueries, values, etc.
> Feat: Keep track of which source table a lineage node came from

- sqlglot/helper.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/schema.py
We have a virtual table with 100s of thousands of columns.
This type of thing could also be a problem with sqlmesh metrics.
We're trying to avoid copying this massive list of columns, as it can be super slow.
Using `Sequence` for `Schema.column_names` lets us cache and return a sorted set.
> fix(optimizer): more optimizations for qualifying wide tables

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #2971
Based on Postgres' [docs](https://www.postgresql.org/docs/9.3/functions-json.html), the various arrow json operators expect their document operand to be a JSON[B] value.
> [Table 9-40](https://www.postgresql.org/docs/9.3/functions-json.html#FUNCTIONS-JSON-OP-TABLE) shows the operators that are available for use with JSON (see [Section 8.14](https://www.postgresql.org/docs/9.3/datatype-json.html)) data.
Additionally, their function counterparts also work with raw text JSON documents:
```sql
json_extract_path('{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}', 'f4')
```
This means that we can't _always_ produce just _one_ of these two syntax forms: if we produce an arrow then we'll break queries where JSON documents are strings (like above), whereas if we produce a function we'll break …
> Fix(postgres): ensure json extraction can roundtrip unaltered

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
- Add `PARAMETER_TOKEN` to duckdb dialect
- Add `placeholder_sql` to bigquery dialect
Ref: https://cloud.google.com/bigquery/docs/parameterized-queries
Ref: https://duckdb.org/docs/sql/query_syntax/prepared_statements.html#syntax
> Feat: support parameters in BigQuery / DuckDB

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
> Feat: support LEFT JOIN UNNEST in duckdb

- sqlglot/dataframe/sql/functions.py
- sqlglot/expressions.py
- sqlglot/optimizer/annotate_types.py
- tests/dataframe/unit/test_functions.py
- tests/dialects/test_presto.py
Spark has [`SIGNUM`](https://spark.apache.org/docs/latest/api/sql/#signum) and `SIGN`](https://spark.apache.org/docs/latest/api/sql/#sign) functions
but `SIGNUM` does not exist in [Presto](https://trino.io/docs/current/functions/math.html#mathematical-functions), [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#sign), [Starrocks](https://docs.starrocks.io/docs/2.3/sql-reference/sql-functions/math-functions/sign/)
So it seems simpler to always transpile to `SIGN` for all dialects (and to incorrectly parse `SIGNUM` even if the query engines don't support it)
> Convert SIGNUM function to SIGN

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_sqlite.py
Hi,
The following PR aims to address [discussion#2995 ](https://github.com/tobymao/sqlglot/discussions/2995)
Key changes:
- SQLite now explicitly rejects table alias columns. In order to implement the sample query from the discussion which uses this DuckDB feature, SQLite now wraps the output of `exp.GenerateSeries` in a subquery with the proper (i.e first) column reference if a TableAlias is binding to the function call. 
- The AST node `exp.GenerateSeries` now carries one more argument (state) to mark whether the end is inclusive/exclusive, as the same function appears on other dialects and/or in other flavors e.g. DuckDB supports `RANGE` (exclusive end) _and_ `GENERATE_SERIES` (inclusive end). 
Future PRs should hopefully: 
- Aim to support the flavors of `GENERATE_SERIES / RANGE` …
> Feat: Supporting RANGE <-> GENERATE_SERIES between DuckDB & SQLite

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- tests/dialects/test_tsql.py
- tests/test_build.py
I decided to move the `SELECT * FROM (...) LIMIT ...` logic in the `Query` class so that all queries will return a `Select` when limited. This can be useful if you wanna create a `Select` expression in order to use the rest of its builders ([example](https://github.com/TobikoData/sqlmesh/blob/8258d0eb7419f8683cdffc2500a4234f36c6df05/sqlmesh/core/model/definition.py#L428)), not available in `Query`.
I also got rid of the `Subquery.subquery` override because with the `limit` change it'd prove problematic, see:
```python
lambda: parse_one("WITH t AS (SELECT 1) (SELECT 1)").limit(1),
"SELECT * FROM (WITH t AS (SELECT 1) (SELECT 1)) AS _l_0 LIMIT 1",
```
If we don't wrap `Subquery` when calling `subquery`, the above builder will produce:
```sql
SELECT * FROM WITH t AS (SELECT 1) (SELECT 1) AS …
```
> Refactor: move limit method to Query, get rid of Subquery.subquery override

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/generator.py
- sqlglot/optimizer/annotate_types.py
- sqlglot/parser.py
- sqlglot/transforms.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_hive.py
- tests/dialects/test_snowflake.py
closes #3015, allowing presto to have named structs if types are known
> fix!: refactor structs to always be property eqs

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_tsql.py
This is a new implementation of  the OPTION clause parsing, using query modifiers.
Note that in order to use query modifiers, a lot of the tsql specific logic had to be hoisted up to the generic parser.
> Feat(tsql): add support for OPTION clause, select only

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_databricks.py
- tests/dialects/test_dialect.py
- tests/dialects/test_hive.py
- tests/dialects/test_postgres.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
- tests/fixtures/identity.sql
- tests/test_transpile.py
This PR aims to solve [issue 2885](https://github.com/tobymao/sqlglot/issues/2850) by supporting `TRUNCATE` natively in the AST for the following dialects:
BigQuery, Databricks, DuckDB, Clickhouse, Hive, MySQL, Postgres, Spark, Snowflake, Redshift, T-SQL, Presto.
The common / "superset" representation among all previous dialects is the following:
`TRUNCATE [TABLE | DATABASE] [IF EXISTS] [[ONLY] table_name [*], ]* [-- PROPERTIES -- ]`
Where `[-- PROPERTIES -- ]` can be:
- Postgres: `[ RESTART IDENTITY | CONTINUE IDENTITY ] [ CASCADE | RESTRICT ]`
- Databricks / Hive / Spark (similar spec): `[PARTITION partition_spec]`
- T-SQL: `[ WITH ( PARTITIONS ( { <partition_number_expression> | <range> }  [ , ...n ] ) ) ]`
- Clickhouse: `[ON CLUSTER cluster]`
Design Notes:
- Distinguish between the …
> Feat: Support for TRUNCATE TABLE/DATABASE DDL

- sqlglot/dialects/mysql.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/fixtures/identity.sql
The refactor here isn't that important, but I figured I'd open a PR to show how one can use `_parse_var_from_options` with a `raise_unmatched` flag if we need to be lenient.
> Refactor: use _parse_var_from_options for USE statement parser

- sqlglot/expressions.py
- tests/test_expressions.py
Hi there
This library is indispensable, so thank you for all the work you've put in! 🙏 
I ran into this small issue, so figured I'd pass over a quick fix.  
I added a couple of unit tests to highlight the discrepancy.  The first one I added passes just fine (falsy values in args), but the second one (falsy values in kwargs) previously did not.
Thanks again  🏅
> Fix: handle falsy values for replace_placeholders kwargs

- README.md
- sqlglot/dialects/hive.py
In the process of validating the README examples, 2 diffs with current SQLGlot results were found:
1) The first example transpiled `EPOCH_MS (DuckDB) -> FROM_UNIXTIME (Hive)` but the respective AST Node `exp.UnixToTime` was not generating properly in Hive
2) The parse error examples in the existing README have mismatches in the `col` position of the missing token (right parenthesis) and the surrounding context does not seem right. In the latest SQLGLot version, the parse error diagnostics have improved but the examples have not been updated.
> fix: Fix Hive UnixToTime regression, README stale results

- sqlglot/diff.py
- tests/test_diff.py
The Identifier node is too granular for diffing and doesn't posses a relevant context on its own. Because of this the resulting edit scripts are often too noisy and sometimes misleading.
The problem becomes more pronounced when the same identifier is repeated many times throughout a query, which is often the case when projections are fully qualified.
> Fix: Ignore Identifier nodes in the diffing algorithm

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
Fixes #3074 
Extend `parse_insert` to also parse hints as per Oracle syntax
Docs
--------
- https://oracle-base.com/articles/misc/append-hint
- https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/INSERT.html#GUID-903F8043-0254-4EE9-ACC1-CB8AC0AF3423
> feat(oracle): Support for INSERT hint

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Redshift's aggregation function syntax generally expects `[ DISTINCT | ALL ] expression`, but `LISTAGG` is an exception: `[DISTINCT] aggregate_expression [, 'delimiter' ]`.
I didn't address this as a special case, but rather made it so that Redshift doesn't [transpile](https://github.com/tobymao/sqlglot/commit/85073d1538de8ceef3e5c622a901efd9e6bd38e3) multi-arg `DISTINCT` expressions at all. The reason is that I played around and realized that Redshift probably doesn't support tuples ("records"?) in that context, so transpiling a query with a multi-arg `DISTINCT` expression to Redshift would yield invalid SQL anyway:
```sql
-- ERROR: could not identify an equality operator for type record
WITH tbl AS (
SELECT 1 AS id, 'eggy' AS name UNION ALL SELECT NULL AS id, 'jake' AS name
)
SELECT …
```
> Fix(redshift): don't transform multi-arg DISTINCT clause

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
We used to transpile `doc["field"]` into `doc.field` in BQ, because it doesn't support the former syntax for struct values. However, it does support it for JSON values, and so that conversion would break valid queries. This only applies said transpilation if we're sure that the left-hand side of the bracket is a `STRUCT` value.
> Fix!(bigquery): transpile brackets to dot notation less aggressively

- sqlglot/dataframe/sql/dataframe.py
- sqlglot/dataframe/sql/session.py
- tests/dataframe/integration/test_session.py
- tests/dataframe/unit/test_session.py
Prior to this change user inputted queries were not optimized and therefore could lack expected aliases. This is now fixed.
I plan on making a follow up PR to write spark specific rules to optimizer so it will qualify columns based on how spark does it rather than sqlglot's format.
Fixes #3091
> fix: dataframe optimize user input

- sqlglot/expressions.py
- tests/test_expressions.py
- tests/test_optimizer.py
The following behavior was observed after the latest `__deepcopy__`  changes:
```python
>>> from sqlglot.optimizer.simplify import gen
>>> q = parse_one("select x from t")
>>> gen(q)
'select _,_,_,x,_,from t,_,_'
>>> gen(q.copy())
'select x,from t'
```
The root issue here is that we don't copy over arg keys with `None` values anymore due to [using](https://github.com/tobymao/sqlglot/blob/80b23201f9668a5845002c1c21b0a394003847f9/sqlglot/expressions.py#L280) the [set method](https://github.com/tobymao/sqlglot/blob/80b23201f9668a5845002c1c21b0a394003847f9/sqlglot/expressions.py#L326) for leaf nodes, meaning that the original and the copied AST may now have different `args` dicts.
(The `self.assertEqual(query, query.copy())` test passes in main - I added it …
> Fix: copy all arg keys, including those set to None

- sqlglot/dialects/duckdb.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
Fixes #3109
I didn't add `TokenType.POSITIONAL` to `ID_VAR_TOKENS` on purpose since DuckDB treats it as a reserved keyword:
```
D select positional;
Error: Parser Error: syntax error at or near ";"
LINE 1: select positional;
^
D select 1 positional;
Error: Parser Error: syntax error at or near "positional"
LINE 1: select 1 positional;
^
D select 1 as positional;
┌────────────┐
│ positional │
│   int32    │
├────────────┤
│          1 │
└────────────┘
D with t as (select 1 as positional) select positional from t;
Error: Parser Error: syntax error at or near "from"
LINE 1: ...ect 1 as positional) select positional from t;
^
```
> Feat(duckdb): add support for positional joins

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #3097 
The syntax for the `EXCLUDE` table constraint is the following:
```
[CONSTRAINT constraint_name] EXCLUDE [ USING index_method ] ( exclude_element WITH operator [, ... ] ) index_parameters [ WHERE ( predicate ) ]
```
where:
```
<index_method> ::= identifier (see [1])
<exclude_element> ::= { column_name | ( expression ) } [ opclass ] [ ASC | DESC ] [ NULLS { FIRST | LAST } ]
<opclass> ::= identifier (see [2])
<index_parameters> ::=  [ INCLUDE ( column_name [, ... ] ) ] 
[ WITH ( storage_parameter [= value] [, ... ] ) ]
[ USING INDEX TABLESPACE tablespace_name ]
``` 
Design Notes
-----------------
- Added `exp.ExcludeElement` that captures all information from `exclude_element WITH operator [, ... ] `
- This is an exclusively Postgres feature afaik, but the changes are added on …
> feat: Adding EXCLUDE constraint support

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
- tests/dialects/test_snowflake.py
Snowflake added support Iceberg tables and structured types, so now `ARRAY(INT)` is valid. This PR:
- Adds support for `CREATE ICEBERG TABLE ...`
- Fixes the generation of structured types
- Adds support for `CAST( <source_expr> AS <target_data_type> [ RENAME FIELDS | ADD FIELDS ] )`
- Improves transpilation of `STRUCT`-like types _to_ Snowflake
- Fixes an issue with `DROP` - we weren't parsing the data type list properly
References:
- https://docs.snowflake.com/en/sql-reference/functions/cast
- https://docs.snowflake.com/en/user-guide/tables-iceberg-data-types
- https://docs.snowflake.com/en/sql-reference/data-types-structured#constructing-structured-arrays-structured-objects-and-maps
- https://docs.snowflake.com/en/sql-reference/sql/create-iceberg-table
- …
>  Feat!(snowflake): iceberg ddl, structured types, cast rename/keep fields, drop fix

- sqlglot/dialects/dialect.py
- sqlglot/dialects/prql.py
There was a bug where if a class didn't override the nested classes (`Tokenizer`, `Parser`, `Generator`), we could end up overwriting attributes of the nested classes of its parent class. For example, if we got rid of PRQL's empty `Generator` override, we would end up with various broken tests because the metaclass code overwrote `Dialect.generator_class`.
> Fix: don't mutate parent nested classes if undefined in a dialect

- sqlglot/expressions.py
Right now the following results in a mypy error because `Query` doesn't contain all of `Select`'s builders:
```python
from sqlglot import exp
select = exp.select("c").with_(alias="cte", as_="SELECT c FROM t").from_("cte")
```
The fix makes it so that the return type matches the type of `self`.
> Chore: improve type hints of Query methods

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
Fixes #3142 
Change MySQL parsing for `exp.GroupConcat` to reduce/normalize the list of expressions into an `exp.Concat` node, thus making it easily transpilable to other dialects which only accept a single expression.   
Docs
------------
- https://dev.mysql.com/doc/refman/8.3/en/aggregate-functions.html#function_group-concat
> feat(mysql): Support for multi arg GROUP_CONCAT

- sqlglot/parser.py
The way `_parse_limit` is implemented, adding a `skip_limit_token` kwarg forces us to assume 1 of 2 branches (limit/fetch). The direction is, of course, to use the limit code path because our goal is ultimately to enable an optional `@LIMIT` macro in SQLMesh. We achieve this via simple short circuit.
> Feat: add skip limit token kwarg

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
BigQuery supports a table alias when doing unnest (which is used instead of `VALUES`) but it just doesn't support column names in that table alias. This makes it so we still output the table alias.
Looking for feedback on `UNNEST_COLUMN_ONLY`. I don't fully understand the purpose of this flag. My current fix leaves this enabled for BigQuery but makes it work by making the alias a column but this is more of a hack. Just wasn't sure what the best way to fix because I don't fully understand `UNNEST_COLUMN_ONLY`.
> feat: include table alias in bigquery unnest

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes #3161 
Support `INSERT INTO [TABLE] FUNCTION ...` syntax by extending `exp.Insert` with a new `kind` argument, that for now is only filled and generated in case of `[TABLE] FUNCTION`
Docs
-------
- [ClickHouse Table Functions](https://clickhouse.com/docs/en/sql-reference/table-functions)
- [ClickHouse INSERT INTO FUNCTION](https://clickhouse.com/docs/en/sql-reference/statements/insert-into#inserting-using-a-table-function)
> feat(clickhouse): Support for INSERT INTO TABLE FUNCTION

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #3170
Reference: https://www.postgresql.org/docs/current/sql-select.html
> Feat(postgres): add support for materialized CTEs

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #3160
Postfix to allow arbitrary expressions in DATE / TO_DATE / TRY_TO_DATE functions
> fix(snowflake): Allow non-literal expressions too in DATE functions

- sqlglot/parser.py
- tests/test_transpile.py
Fixes https://github.com/TobikoData/sqlmesh/issues/2299
```python
>>>
>>> print(sqlglot.transpile("""
... SELECT
... -- comment
... SOME_FUNC(arg IGNORE NULLS)
...   OVER (PARTITION BY foo ORDER BY bla) AS col
... FROM t
... """, pretty=True)[0])
SELECT
SOME_FUNC(arg IGNORE NULLS) OVER (PARTITION BY foo ORDER BY bla) AS col /* comment */
FROM t
```
> Fix: move comment from window function to Window expression

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes #3176 
Although the `FORMAT` query modifier is already supported in SQLGLot, Clickhouse containts the anti-pattern that it's both a query modifier _and_ a valid identifier (in some cases, as shown below), so before this PR it was parsed as an alias for the query of the issue #3176 . 
However, it seems that it's not allowed in an "implicit" alias i.e without `AS` token, probably in an attempt to disambiguate it in the cases above. For example:
- `SELECT 1 FORMAT <format_val>` -> Valid, `FORMAT` is the query modifier with the following var as value
- `SELECT 1 AS FORMAT` -> Valid, `FORMAT` is the alias identifier of expression `1`
- `SELECT 1 FOO` -> Valid, `FOO` is the "implicit" alias identifier of expression `1`
- `SELECT 1 FORMAT` -> Invalid
This pattern might be present in other …
> fix(clickhouse): Fixing FORMAT being parsed as implicit alias

- sqlglot/expressions.py
- tests/test_expressions.py
> Fix!: allow transformations that mutate the visited node's parent

- sqlglot/dialects/mysql.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Fixes #3186 
Introduce `MODIFY COLUMN` support for MySQL, which is treated as syntactic sugar for existing `ALTER COLUMN` statements. 
Support for the following options `[FIRST | AFTER col_name]` as well as specific `column_definition` properties is not included in this PR as these span multiple statements, but a follow up PR can support these too across MySQL
Docs
--------------
- [MySQL ALTER TABLE statements](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)
- [MySQL column_definition syntax](https://dev.mysql.com/doc/refman/8.0/en/create-table.html)
> feat(mysql): Parse MODIFY COLUMN

- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Fixes #3185 
Fix the following issue by overriding Postgres's `COLUMN_OPERATORS` for `TokenType.ARROW` and `TokenType.DARROW` to build `JsonExtractPath` & `JsonExtractPathScalar` expressions instead of calling `to_json_path`
> fix(postgres): Fix ARROW/DARROW column operators

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Redshift doesn't support `startswith` so this generates a compatible equivalent of it
> feat: redshift starts with support

- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/test_tokens.py
Fixes #3200
We used to increment `i` by 2 inside `_advance`, in order to basically skip the `\r\n` sequence and have the `line` attribute be automatically updated to the right value. However, this didn't take into account an edge case where the SQL string can end in `\r\n` and so it resulted in an off-by-one index error, as reported in the linked issue.
Since the original motivation for this change was to fix the `line` attribute, which was getting incremented twice for every `\r\n` sequence, I changed our approach to simply not increment it when we find the `\r` in the sequence and only do it on the subsequent `\n`.
> Fix(tokenizer): don't increment array cursor by 2 on CRLF

- sqlglot/dialects/duckdb.py
- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_duckdb.py
- tests/dialects/test_postgres.py
It seems like DuckDB also [supports](https://github.com/duckdb/duckdb/pull/10879) heredocs now.
References:
- https://duckdb.org/docs/sql/data_types/literal_types.html#dollar-quoted-string-literals
- https://duckdb.org/docs/api/python/dbapi.html#named-parameters
> Feat(duckdb): add support for heredoc string syntax

- sqlglot/dialects/snowflake.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
Snowflake doesn't support some expressions inside of the `VALUES` clause. For example, the following fails:
```sql
-- Invalid expression [OBJECT_CONSTRUCT('a', 'b')] in VALUES clause
SELECT * FROM (VALUES (OBJECT_CONSTRUCT('a', 'b'))) AS t(x)
```
Related slack [thread](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1711319137491219?thread_ts=1711222433.615919&cid=C044BRE5W4S) and reference: https://docs.snowflake.com/en/sql-reference/constructs/values
> Each expression must be a constant, or an expression that can be evaluated as a constant during compilation of the SQL statement. Most simple arithmetic expressions and string functions can be evaluated at compile time, but most other expressions cannot.
> Fix(snowflake): convert VALUES with invalid expressions into UNION ALL

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
Prior to this change if a query is parsed that contains a `DATETIME` with BigQuery dialect then it would be internally represented as a `DATETIME` data type. BigQuery `DATETIME` directly maps to the SQLGlot `TIMESTAMP` data type (a timestamp without time zone). 
This PR changes this behavior to parse a BigQuery `DATETIME` into SQLGlot `TIMESTAMP`. 
I didn't represent this change as breaking since this should be change to just the SQLGlot representation. Output SQL from BigQuery should remain the same.
> fix: bq datetime to timestamp

- sqlglot/optimizer/pushdown_projections.py
- tests/fixtures/optimizer/pushdown_projections.sql
Fixes #3222 
Introduce support for `UNION [ALL] BY NAME` in `pushdown_projections` rule, which matches referenced columns by name instead of by position:
```
>>> optimize(sqlglot.parse_one("select a from (select 1 a, 2 c union all by name select 3 c, 4 a)")).sql()
'WITH "_q_0" AS (SELECT 1 AS "a" UNION ALL BY NAME SELECT 4 AS "a") SELECT "_q_0"."a" AS "a" FROM "_q_0" AS "_q_0"'
```
```
-- UNION (by position)
D select a from (select 1 a, 2 c union all select 3 c, 4 a);
┌───────┐
│   a   │
│ int32 │
├───────┤
│     1 │
│     3 │
└───────┘
-- UNION BY NAME
D select a from (select 1 a, 2 c union all by name select 3 c, 4 a);
┌───────┐
│   a   │
│ int32 │
├───────┤
│     1 │
│     4 │
└───────┘
-- Optimized UNION BY NAME
D WITH "_q_0" AS (SELECT 1 AS "a" UNION ALL BY NAME SELECT 4 AS "a") …
```
> feat(optimizer): Support for UNION BY NAME

- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/generator.py
- tests/dialects/test_dialect.py
- tests/dialects/test_hive.py
- tests/dialects/test_spark.py
- tests/test_transpile.py
Fixes #3221
There were a couple of issues here. The first one is:
```python
>>> sqlglot.transpile("unix_timestamp()", "hive", "presto")
["TO_UNIXTIME(DATE_PARSE('%Y-%m-%d %T'))"]
```
This `DATE_PARSE` call is invalid in Presto / Trino - we need an argument to parse.
The second one was a bit more nuanced and I don't really like my current solution, but didn't see another way out during my investigation. Basically, `DATE_PARSE` doesn't handle time zone information, and so the following breaks in Presto:
```
-- "2024-03-26 13:52:38.634 UTC" is malformed at ".634 UTC"
select date_parse(cast(current_timestamp as varchar), '%Y-%m-%d %T');
```
The workaround I implemented it basically to try calling both `DATE_PARSE` and `PARSE_DATETIME`, because if the former fails due to …
> Fix!: StrToUnix Hive parsing, Presto generation fixes

- sqlglot/generator.py
- tests/dialects/test_postgres.py
> Fix: don't evaluate Rand twice when ordering by it

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
Fixes #3237 
Oracle supports only `NOCYCLE` as an option parameter after `CONNECT BY`; Other dialects that support connect queries (such as Redshift and Snowflake, from what I could find) do not seem to specify any parameters.
Docs
------------
- [Oracle](https://docs.oracle.com/cd/B13789_01/server.101/b10759/queries003.htm)
- [Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_CONNECT_BY_clause.html)
- [Snowflake](https://docs.snowflake.com/en/sql-reference/constructs/connect-by)
> feat(oracle): Support for CONNECT BY [NOCYCLE]

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/annotate_types.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/test_optimizer.py
Reference: https://duckdb.org/docs/sql/data_types/map.html
> Fix: properly parse/generate duckdb MAP {..} syntax, annotate MAPs

- README.md
As titled. [Apache Superset](https://superset.apache.org/) is the official name.
> docs: Rename Superset to Apache Superset

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes #3243 
Design notes
--------------------
- `ALIAS` is now parsed as `exp.ComputedColumnConstraint`, similarly to T-SQL's computed columns
- `CODEC(...)` is now parsed as `exp.CompressColumnConstraint`
- According to Clickhouse's parser, the index syntax is `INDEX name1 expr TYPE type1(args) GRANULARITY value`. As this is not properly documented yet, I decided to fully separate it from the existing `exp.IndexColumnConstraint` parsing/generation
Docs
---------
- [ALIAS](https://clickhouse.com/docs/en/sql-reference/statements/create/table#alias)
- [CODECs](https://clickhouse.com/docs/en/sql-reference/statements/create/table#column-compression-codecs)
- [Index syntax](https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ParserCreateQuery.h#L646)
> feat(clickhouse): CREATE TABLE computed columns, column compression, index

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
Fixes #3254 
Syntax:
```
SELECT ...
FROM <left_table> ASOF JOIN <right_table>
MATCH_CONDITION (<left_table.timecol> <comparison_operator> <right_table.timecol>)
[ ON <table.col> = <table.col> [ AND ... ] ]
```
From the docs, the important parsing rules of `MATCH_CONDITION`:
- The parentheses are required
- The comparison operator cannot be of equality (thus, `self._parse_comparison` was used for finer granularity)
Docs
----------
- [Snowflake ASOF](https://docs.snowflake.com/en/sql-reference/constructs/asof-join)
> feat(snowflake): MATCH_CONDITION in ASOF JOIN

- sqlglot/dialects/dialect.py
- sqlglot/dialects/presto.py
- tests/dialects/test_dialect.py
- tests/dialects/test_hive.py
- tests/dialects/test_presto.py
Fixes #3259 
Trino and Presto share the same strpos syntax: `strpos(string, substring, instance)`; This is different from all other dialects which use the 3rd argument as the starting position in the `string` to search from e.g. `strpos(string, substring, position)`. In order to preserve the start position semantics, the existing DuckDB - like pattern (wrapping the `string` with `SUBSTR` and offsetting the index by that pos) was utilized. This now correctly transpiles the faulty #3259 query while also preserving the Presto <-> Trino roundtrip if `instance` is used:
- Snowflake -> Trino/Presto (now, result in all 3 engines is 5)
```
>>> sqlglot.transpile("POSITION( 'A','ADFGAC', 3)", read="snowflake", write="presto")
["STRPOS(SUBSTR('ADFGAC', 3), 'A') + 3 - 1"]
```
> fix: Fix STRPOS for Presto & Trino

- .github/workflows/python-publish.yml
Reverts tobymao/sqlglot#3264
Since the deployment issues were most likely related Cargo.lock not being updated, this can be safely reverted.
> Revert "Chore: deploy sqlglot and then sqlglotrs"

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #3282
The `MEASURES` subclause now supports the following syntax:
```
MEASURES  {FINAL | RUNNING} <expr> AS <alias> [, ... ]* 
``` 
Where each individual subclause is stored in a new expression `exp.MatchRecognizeMeasure`
Docs
--------
- [Snowflake MATCH_RECOGNIZE](https://docs.snowflake.com/en/sql-reference/constructs/match_recognize)
> feat(snowflake): FINAL/RUNNING keywords in MATCH_RECOGNIZE MEASURES

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
With postgresql you can add a comment on a materialized view as described in the [documentation](https://www.postgresql.org/docs/current/sql-comment.html), this PR adds this possibility.
> Feat(postgres): add COMMENT ON MATERIALIZED VIEW

- sqlglot/optimizer/scope.py
- tests/test_optimizer.py
Before:
```python
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> sql = """
... with recursive t as (
...   select 1 as x
...   union all
...   select x + 1 from t as child where x < 10
... )
... select * from t
... """
>>>
>>> expr = parse_one(sql)
>>> print(qualify(expr, infer_schema=False).sql(pretty=True))
sqlglot.errors.OptimizeError: Column '"x"' could not be resolved
```
After:
```python
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> sql = """
... with recursive t as (
...   select 1 as x
...   union all
...   select x + 1 from t as child where x < 10
... )
... select * from t
... """
>>>
>>> expr = parse_one(sql)
>>> print(qualify(expr, infer_schema=False).sql(pretty=True))
WITH RECURSIVE "t" …
```
> Fix(optimizer): propagate recursive CTE source to children scopes early

- sqlglot/dialects/teradata.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
- tests/dialects/test_teradata.py
These fixes resolve database/syntax errors encountered when using sql transpiled to the teradata dialect
- Cast doubles to DOUBLE PRECISION to avoid syntax errors
- Use `CURRENT_TIMETAMP` to avoid syntax errors
- Implement `DATE_ADD`/`DATE_SUB` with interval addition/subtraction
- Support week/quarter intervals by translating to multiplications over days
- Support `EXTRACT(QUARTER ...)` by using `TO_CHAR`
> Feat: improve transpilation of datetime functions to Teradata

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
Before:
```python
>>> parse_one("x in (select 1)")
In(
this=Column(
this=Identifier(this=x, quoted=False)),
query=Select(
expressions=[
Literal(this=1, is_string=False)]))
```
After:
```python
>>> parse_one("x in (select 1)")
In(
this=Column(
this=Identifier(this=x, quoted=False)),
query=Subquery(
this=Select(
expressions=[
Literal(this=1, is_string=False)])))
```
> Fix!: parse right-hand side of <value> IN (<query>) as a Subquery

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/optimizer/annotate_types.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_teradata.py
- tests/test_expressions.py
Add a `QUARTER` expression type. I tried to base this off of the places where `exp.Month` is used but may have missed something
Teradata doesn't have a `QUARTER` function to extract the quarter from a date, so transform it to an `EXTRACT(QUARTER ...)` expression. Teradata also doesn't support `EXTRACT(QUARTER ...)`, but this is already handled in `extract_sql`.
> Feat(teradata): handle transpile of quarter function

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/teradata.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_databricks.py
- tests/test_build.py
This addresses the following issue (note the additional `TIMESTAMP` added):
```python
>>> sql = "SELECT DATE_FORMAT(CAST(FROM_UTC_TIMESTAMP(foo::TIMESTAMP, 'America/Los_Angeles') AS TIMESTAMP), 'yyyy-MM-dd HH:mm:ss') AS foo FROM t"
>>> expr.sql("databricks")
"SELECT DATE_FORMAT(CAST(CAST(FROM_UTC_TIMESTAMP(CAST(foo AS TIMESTAMP), 'America/Los_Angeles') AS TIMESTAMP) AS TIMESTAMP), 'yyyy-MM-dd HH:mm:ss') AS foo FROM t"
```
> Fix!: cast less aggressively

- sqlglot/generator.py
- tests/test_transpile.py
This makes it so that SQLGlot will use the following style when formatting with leading comma:
```sql
SELECT
a
, b
, c
FROM t
```
Context: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1712927617277489
> Refactor: get rid of 1st projection pad for leading comma formatting

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/redshift.py
- sqlglot/optimizer/qualify.py
- sqlglot/transforms.py
- tests/fixtures/optimizer/qualify_columns.sql
Before:
```python
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> print(qualify(parse_one("SELECT c.f::VARCHAR(MAX) AS f, e AS e FROM a.b AS c, c.d AS e", "redshift"), dialect="redshift", infer_schema=False).sql("redshift", pretty=True))
SELECT
CAST("c"."f" AS VARCHAR(MAX)) AS "f",
"_q_0"."e" AS "e"
FROM "a"."b" AS "c", "c"."d" AS   "e"
```
After:
```python
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> print(qualify(parse_one("SELECT c.f::VARCHAR(MAX) AS f, e AS e FROM a.b AS c, c.d AS e", "redshift"), dialect="redshift", infer_schema=False).sql("redshift", pretty=True))
SELECT
CAST("c"."f" AS VARCHAR(MAX)) AS "f",
"e" AS "e"
FROM "a"."b" AS "c", "c"."d" AS "e"
```
> Fix(redshift): unqualify unnest columns

- sqlglot/transforms.py
- tests/test_transforms.py
Input:
```python
>>> sql = """
with data as (
select 1 as id, 'a' as name
union all
select 1 AS ID, 'b' as name
)                
select
id,
concat(name, id) new_name,
from data
qualify row_number() over (partition by id order by new_name desc) = 1
"""
```
Before: 
```python
>>> from sqlglot.transforms import eliminate_qualify
>>> print(sqlglot.parse_one(sql, read="bigquery").transform(eliminate_qualify).sql(dialect="bigquery", pretty=True))
SELECT
id,
new_name
FROM (
WITH data AS (
SELECT
1 AS id,
'a' AS name
UNION ALL
SELECT
1 AS ID,
'b' AS name
)
SELECT
id,
CONCAT(name, id) AS new_name,
row_number() OVER (PARTITION BY id ORDER BY new_name DESC) AS _w
FROM data
) AS _t
WHERE
_w = 1
```
Give the generated SQL before the patch to the bigquery console and …
> Fix: transform eliminate_qualify on generated columns

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_hive.py
Fixes #3320 
Extend `_parse_insert()` to also parse Hive's `STORED AS <format>` property. The parseable syntax now conforms to Hive's standard:
```
INSERT OVERWRITE [LOCAL] DIRECTORY directory1 [ROW FORMAT row_format] [STORED AS file_format]  SELECT ... FROM ...
```
Docs
---------
- [Hive: Writing data into the filesystem from queries](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML)
> feat(hive): Add 'STORED AS' option in INSERT DIRECTORY

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
Fixes #3324 
Introduce support for Clickhouses `DATE_FORMAT` (alias of `formatDateTime`)
Docs
-------
- [Clickhouse DATE_FORMAT](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#formatDateTime)
> feat(clickhouse): Add support for DATE_FORMAT / formatDateTime

- sqlglot/parser.py
- tests/test_parser.py
This is mostly a QOL addition, eg. so that we can leverage the `(a,)` syntax in SQLMesh when `[a]` can't be used (T-SQL).
Before:
```python
>>> sqlglot.parse_one("(a,)")
Paren(
this=Column(
this=Identifier(this=a, quoted=False)))
```
After:
```python
>>> sqlglot.parse_one("(a,)")
Tuple(
expressions=[
Column(
this=Identifier(this=a, quoted=False))])
```
> Feat: parse (a,) as a tuple instead of a paren

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_tsql.py
Fixes #3345
In T-SQL:
- Parse `"TIMESTAMP"` into `TokenType.ROWVERSION` as the former is deprecated in favor of the latter
- Explicitly preserve the roundtrip generation of `DataType.ROWVERSION -> "ROWVERSION"`
In all other dialects:
- Convert `DataType.ROWVERSION` to `TokenType.BINARY` by default
[T-SQL Rowversion](https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver16)
> fix(tsql): Convert TIMESTAMP to ROWVERSION, transpile both to BINARY

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
Fixes #3344
Clickhouse defines it's own `_parse_function()` which reuses (and extends) `parser.py::_parse_function()`. The latter will also parse the following window function provided that the next tokens are matched e.g. `aggfunc(...) OVER ...`.
However, for CH's parameterized aggregation functions, the nested params will be _between_ the function call and the rest of the window spec, which will cause `parser.py::_parse_function()` to miss the window specification as it can't match the appropriate window tokens right after the function call. For this case, CH must retry to parse it _after_ having parsed the params.
> feat(clickhouse): Parse window functions in ParameterizedAggFuncs

- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
Fixes #3350
This PR aims to merge the aggregate function from `exp.WithinGroup` with the order by clause, as per DuckDB syntax. 
Although DuckDB still allows `PERCENTILE_CONT` & `PERCENTILE_DIST` to be defined in `WITHIN GROUP`, this PR will also convert them to their logically equivalent modes; This has the benefit that `rename_unless_within_group` is not needed anymore.
Docs
-------
- [DuckDB Aggregate Functions](https://duckdb.org/docs/sql/aggregates#ordered-set-aggregate-functions)
- [Snowflake LISTAGG + WITHIN GROUP](https://docs.snowflake.com/en/sql-reference/functions/listagg)
> fix(duckdb)!: Combine aggregate functions with orderby from WITHIN GROUP

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Context: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1714116556196959
It seems that postgres doesn't support this syntax:
```
georgesittas=# CREATE TABLE app (
id INT COMMENT 'comment 1',
appId VARCHAR(50) COMMENT 'comment 2'
)
COMMENT='app management';
ERROR:  syntax error at or near "COMMENT"
LINE 2:   id INT COMMENT 'comment 1',
^
```
References: https://www.postgresql.org/docs/current/sql-createtable.html
> Fix(postgres): don't generate CommentColumnConstraint

- sqlglot/dialects/databricks.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_databricks.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_tsql.py
- tests/fixtures/identity.sql
Introduce end-to-end support for `COPY TO` / `COPY FROM` statement
Design notes:
- Dialects parse `COPY` parameters parameters using different separators from each other. Introduced a new dialect flag to control that behavior at parse/generation
- Introduce parsing of external location credentials (Snowflake & Redshift). These might appear in other statements e.g. Redshift's `UNLOAD` but I couldn't find existing support
- Copy parameters are parsed in a best effort catch-all manner, as each dialect specifies a long list. There's a fallback to `exp.Command` if current parsing fails to pick up more nuanced options
Docs
------
- [DuckDB](https://duckdb.org/docs/sql/statements/copy.html)
- [T-SQL](https://learn.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-la …
> feat: COPY TO/FROM statement

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Similar to https://github.com/tobymao/sqlglot/pull/3357 - Postgres doesn't support `COMMENT` post-schema properties.
Reference: https://www.postgresql.org/docs/current/sql-createtable.html
> Fix(postgres): don't generate SchemaCommentProperty

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
Fixes #3366
MySQL cannot generate `exp.TimestampTrunc` using an existing function; However, one can simulate it with a combination of date add & diff ([source](https://stackoverflow.com/a/32955740))
Docs for `DATE_TRUNC`
-----------
- [Postgres](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC)
- [Presto](https://prestodb.io/docs/current/functions/datetime.html#date_trunc) 
- [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/date_trunc)
- [Databricks / Spark](https://docs.databricks.com/en/sql/language-manual/functions/date_trunc.html)
> feat(mysql): Transpile TimestampTrunc

- sqlglot/dialects/trino.py
- tests/dialects/test_trino.py
Fixes #3384
Seems like the `TRIM` parser was removed from Presto in https://github.com/tobymao/sqlglot/commit/57eb2ce9c. Presto doesn't seem to like the non-CSV syntax:
```
presto> SELECT TRIM('!' FROM '!foo!');
Query 20240430_215821_00000_x3v83 failed: line 1:17: mismatched input 'FROM'. Expecting: ',', <expression>
SELECT TRIM('!' FROM '!foo!')
```
But Trino does.
References:
- https://trino.io/docs/current/functions/string.html?highlight=trim#trim
- https://prestodb.io/docs/current/functions/string.html#trim
> Fix(trino): bring back TRIM parsing

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
BigQuery supports [correlated join operations](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#correlated_join) which allow join RHS UDTFs to reference columns from the LHS. Example:
```
WITH cte AS (
SELECT 1 AS col
) 
SELECT * FROM cte 
LEFT JOIN UNNEST((
SELECT ARRAY_AGG(DISTINCT x) AS agg FROM UNNEST([1]) AS x WHERE col = 1
));
```
However, UDTFs currently mark their nested scopes as `ScopeType.DERIVED_TABLE` which not only seems semantically incorrect but also blocks the parent/outer scope from collecting & qualifying the `UNNEST` external columns, as would happen in a typical correlated subquery.
> fix(optimizer)!: Mark UDTF child scopes as ScopeType.SUBQUERY

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Fixes #3373
Current `DATE_SUB` support in DuckDB was limited to a [prior BigQuery -> DDB transpilation case](https://github.com/tobymao/sqlglot/pull/1705), in which BQ's interval-based `DATE_SUB` would convert to an equivalent DDB interval expression. 
However, DuckDB supports `DATE_SUB` (also `DATESUB`) natively, which this PR aims to support for it's roundtrip.
> fix(duckdb): Preserve DATE_SUB roundtrip

- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- tests/dialects/test_postgres.py
- tests/dialects/test_snowflake.py
Fixes #3393
Removed `parameters` over `modifiers` which was introduced in https://github.com/tobymao/sqlglot/commit/87efe4183, they both represent the same thing.
> Fix!: get rid of superfluous "parameters" arg in RegexpReplace

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Fixes #3399
FYI I've verified that running `CREATE TABLE [#foo bar] (name VARCHAR)` produces a temp table by querying `select * from tempdb..sysobjects` - see https://stackoverflow.com/a/7075562/17518317.
> Fix(tsql): quote hash sign as well for quoted temporary tables

- sqlglot/parser.py
- tests/dialects/test_postgres.py
The index name can be omitted in the `CREATE INDEX` DDL for Postgres, which is not currently supported by SQLGlot.
Reference: https://www.postgresql.org/docs/current/sql-createindex.html
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1714510786163729?thread_ts=1714460372.303889&cid=C044BRE5W4S
> Feat(postgres): add support for anonymos index DDL syntax

- sqlglot/dialects/snowflake.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #3388
Design notes
---------------
- Snowflake's `FILE_PARAM` option is now parsed & generated on its own to accommodate for the optional `formatTypeOptions` that might come after the `TYPE` opts:
```
FILE_FORMAT = (  
FORMAT_NAME = '[<namespace>.]<file_format_name>' | 
TYPE = { CSV | ... | XML } [ formatTypeOptions ] 
) 
```
- Allowed `parse_primary()` to parse expressions such as `NULL_IF = ()` into empty tuples. That would otherwise try to be parsed in an `exp.Paren` with no expression, which would throw an error
- Refactored the file parsing to also include Snowflake's `@external_file` syntax besides strings 
- Added the issue query and other Snowflake doc examples as test cases
Docs
--------
- [Snowflake COPY](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#synta …
> fix(snowflake): COPY postfix

- sqlglot/dialects/mysql.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Fixes #3423 
From what I was able to find the `REPLACE` statement is supported by MySQL. The different syntax flavors would require intricate parsing, so to unblock the issue (and since it's not a rather popular statement ?) I opted to parse it as command for now.
This PR also fixes the following bug: The base parser's `parser.py::_parse_statement()` function would only check the `tokenizer.py::COMMANDS` set instead of the current dialects tokenizer. This meant that adding/removing tokens from `<dialect>.py::COMMANDS` would yield no difference on the parsing.
After enabling `COMMANDS` to work across all dialects, I also went ahead and removed any unnecessary `_parse_command()` calls, as is the case for T-SQL.
> fix(mysql): Parse REPLACE statement as Command

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #3424 
Introduce Snowflake's `APPROX_PERCENTILE(<expr>, <percentile>)` function & support transpilation with the (existing) Presto/Trino implementation
Docs
------
- [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/approx_percentile)
> feat(snowflake): Support for APPROX_PERCENTILE

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
ClickHouse partition expression syntax differs from the one used in base Parser, documentation reference: https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#how-to-set-partition-expression
> feat(clickhouse): add support for partition expression

- setup.cfg
- setup.py
This is the latest version, see https://github.com/astral-sh/ruff/releases/tag/v0.4.3
> Chore: bump ruff to 0.4.3

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #3435
Note that the two DDLs tested produce slightly different ASTs:
```python
>>> sqlglot.parse_one("CREATE SEQUENCE seq1 WITH START=1 INCREMENT=1 ORDER", "snowflake")
Create(
this=Table(
this=Identifier(this=seq1, quoted=False)),
kind=SEQUENCE,
properties=Properties(
expressions=[
Property(
this=Identifier(this=START, quoted=False),
value=Literal(this=1, is_string=False)),
Property(
this=Identifier(this=INCREMENT, quoted=False),
value=Literal(this=1, is_string=False)),
SequenceProperties(
options=[
Var(this=ORDER)])]))
>>> sqlglot.parse_one("CREATE SEQUENCE seq1 WITH START=1, INCREMENT=1 ORDER", "snowflake")
Create(
this=Table(
this=Identifier(this=seq1, quoted=False)),
kind=SEQUENCE,
properties=Properties(
expressions=[
Property(
this=Identifier(this=START, …
```
> Fix(snowflake): parse CREATE SEQUENCE with commas

- sqlglot/generator.py
- tests/test_generator.py
- tests/test_transpile.py
Problem:
if comment is an empty string pad_comment fails on IndexError on comment[0]. Adding a simple check if comment is not empty
> Fix: handle empty string in connector comment padding

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
Added support for ClickHouse ALTER TABLE REPLACE PARTITION, which is very useful in ETL processes (which my company analyzes using sqlglot). ON CLUSTER support isn't there yet, willing to do that in the near future.
Doc reference:
https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#replace-partition
> feat(clickhouse): add support for ALTER TABLE REPLACE PARTITION statement

- sqlglot/executor/env.py
- tests/test_executor.py
This fixes a warning emitted on python ≥v3.12:
```
sqlglot/sqlglot/executor/env.py:243: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
"UNIXTOTIME": null_if_any(lambda arg: datetime.datetime.utcfromtimestamp(arg))
```
> Fix(executor): use timezone-aware object to represent datetime in UTC

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Added support for `ON` property in `ALTER` and `DROP` statements, so `ON CLUSTER` could be used with the ClickHouse dialect. A little follow-up PR to #3441. 
Documentation reference:
https://clickhouse.com/docs/en/sql-reference/statements/drop
https://clickhouse.com/docs/en/sql-reference/statements/alter/column
> feat: add support for ON property in ALTER and DROP statements

- sqlglot/dialects/hive.py
- sqlglot/dialects/snowflake.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_snowflake.py
Fixes #3434
This PR addresses the following issues:
- COPY would only allow files in the `FROM` clause, extend it to allow subqueries as well
- When parsing staged files such as `@foo` we'd also consume the following parentheses coming from (optional) staged file options such as `SELECT * FROM @foo (FILE_FORMAT => ...)`. However, if there are no options specified we would end up consuming _any_ following `R_PAREN` as well e.g. `SELECT * FROM (SELECT * FROM @foo)`
- For transforming semi-structured data Snowflake specifies the subquery columns as `[<alias>.]$<file_col_num>[.<element>]`. However, the tokenizer always appends the `TokenType.DOT` to following a number e.g. `$1.elem -> $1.e lem`. To solve this issue, the tokenizer will only parse an integer (and not a real) if the number is …
> fix(snowflake): COPY Subquery postfix

- sqlglot/dialects/presto.py
- tests/dialects/test_bigquery.py
Fixes https://github.com/tobymao/sqlglot/issues/3458
Affected functions:
- MD5_DIGEST
- MD5
- SHA
- SHA2
> fix(presto): fix parsing and generating hash functions presto/trino

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
> Fix(duckdb): preserve precedence of json extraction when converting to arrow syntax

- sqlglot/dialects/presto.py
- tests/dialects/test_bigquery.py
- Presto/Trino only support DELETE statement with FROM keyword and only allow to delete data from one table per query.
- Don't allow to have any table alias in the target table which will be deleted.
- https://prestodb.io/docs/current/sql/delete.html
- https://trino.io/docs/current/sql/delete.html
- https://prestodb.io/docs/current/sql/explain.html
- https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#delete_statement
- Looking for **Multi-Table Deletes** in https://dev.mysql.com/doc/refman/8.0/en/delete.html
```bash
echo "connector.name=memory" > memory.properties
docker run -p 8080:8080 -it -v ./memory.properties:/opt/presto-server/etc/catalog/memory.properties --name presto prestodb/presto:latest
docker exec -it presto presto-cli
presto> create table …
```
> fix(presto): fix DELETE DML statement for presto/trino

- sqlglot/parser.py
- tests/fixtures/identity.sql
> Fix: allow rollup to be used as an identifier

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
- tests/dialects/test_snowflake.py
Fixes #3503
This was a low lift so I thought I'd fix it since it's also supported by postgres.
> Feat: add RETURNS NULL ON NULL and STRICT properties

- sqlglot/dialects/databricks.py
- sqlglot/dialects/spark2.py
- tests/dialects/test_databricks.py
- tests/dialects/test_mysql.py
Fixes #3521
- Removed Databricks superfluous `Tokenizer` so it can inherit Spark's `HEX_STRING`.
- Added support for lowercase `x'...'` as DB's docs mention that the prefix is case insensitive.
> feat(databricks): Enable hex string literals

- .gitpod.yml
I encounter some frictions when I try to setup the environment. I tend to use Cloud Development Environment for other open source projects for a few reasons:
1. I don't remember which virtual env works
2. I sometimes work on different computers so I don't have the copies
This PR add a GitPod configuration (similar to .devcontainer for Github Codespace)
- I set the default image as Python 3.11 as I get error related to `setuptools_scm` with Python 3.12 (which is the default and latest support Python version)
Optionally I can also update the `Contributor.md`, but I want to know if you want to accept this PR or not first.
> Add GitPod Config to simplify the contributor workflow

- sqlglot/dialects/postgres.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Feat(postgres): add support for col int[size] column def syntax

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
fix #3551 
Redshift inherits from Postgres and hence haven't added any testcases to Redshift.
> Fix(postgres): setting un-suffixed FLOAT as DOUBLE (#3551)

- .gitpod.yml
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
fix: #3534 
Context:
```python
class AlterColumn(Expression):
arg_types = {
"this": True,
"dtype": False,
"collate": False,
"using": False,
"default": False,
"drop": False,
"comment": False,
}
```
The existing `AlterColumn` expression seems to assume only `SET DEFAULT ` and `NOT DEFAULT` is possible. Therefore is `drop` is True is sufficient to represent `DROP DEFAULT` and when `default` is not null it means set default. This seems to be insufficient to handle statement like `DROP NOT NULL` and `SET NOT NULL`
Few questions:
-  there are many `_match_xxx` functions, is `_match_text_seq` the most suitable one?
- I don't know if I should use things like `_parse_not_constraints` here.
- I figured I should edit the `AlterColumn` expression, but I am not sure how to add a new type for `SET NOT …
> Feat: add support for ALTER COLUMN DROP NOT NULL

- sqlglot/dialects/tsql.py
This is regarding SQLMesh issue: [#2672](https://github.com/TobikoData/sqlmesh/issues/2672)
where running `sqlmesh format`  a few times in the tsql dialect adds superfluous casts. 
This is due to the casting of `timestrtotime_sql`  to `TIMESTAMP` instead of `DATETIME` and this fix addresses it by with a lambda function that sets the type to DATETIME instead.
> Fix(tsql): adapt TimeStrToTime to avoid superfluous casts

- sqlglot/schema.py
- tests/test_schema.py
The motivation behind this is that in SQLMesh we have a mapping schema where types are stored as strings, but [we need them](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/macros.py#L405-L420) to be `DataType`s instead.
I added this here instead of in SQLMesh to leverage the existing in-memory `DataType` cache [used](https://github.com/tobymao/sqlglot/blob/main/sqlglot/schema.py#L447-L448) in the `MappingSchema` definition.
> Feat: add option in schema's find method to ensure types are DataTypes
