sqlglot/schema.py
The `AbstractMappingSchema.find` implementation [guarantees](https://github.com/tobymao/sqlglot/blob/main/sqlglot/schema.py#L178-L187) that we'll end up with a dictionary of depth 1, so the `dict_depth` call was unnecessary.
=> Refactor: get rid of redundant dict_depth check in schema find

sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #3565. This was a bit tricky.
Current behavior in main:
```python
>>> sqlglot.parse_one("select number", "snowflake")
Select(
expressions=[
DataType(
this=Type.DECIMAL,
expressions=[
DataTypeParam(
this=Literal(this=38, is_string=False)),
DataTypeParam(
this=Literal(this=0, is_string=False))],
nested=False)])
```
In this PR:
```python
>>> sqlglot.parse_one("select number", "snowflake")
Select(
expressions=[
Column(
this=Identifier(this=number, quoted=False))])
```
The reason we get a `DataType` node in the main branch is because `_parse_types` now [returns](https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L4397-L4402) a `DECIMAL` type whose `expressions` arg gets set by the corresponding [snowflake type …
=> Fix(parser): edge case where TYPE_CONVERTERS leads to type instead of column

sqlglot/__init__.py, sqlglot/optimizer/optimizer.py, sqlglot/optimizer/qualify.py, sqlglot/optimizer/qualify_columns.py, sqlglot/optimizer/scope.py, tests/fixtures/optimizer/qualify_columns.sql, tests/test_optimizer.py
Fixes #3484
BigQuery supports star expansion such as `foo.bar.*` where `foo` is the table and `bar` is a struct. This is essentially a  _flatten_ operation from the specified struct and down. For example, if `bar` has a nested struct `baz`, then `foo.bar.baz.*` would cause a flatten from `baz` downwards.
In order to replicate this behavior, a DFS traversal starting from the top-level struct gathers the non-struct fields and enqueues the nested structs (if any). At every point, a name / fully qualified path is kept and prefixes the fields at that level. 
**Note**: If any nested field is _not_ aliased, then the star expansion is stopped and the star` is preserved; This is because BigQuery will alias these fields dynamically so it's not possible to qualify/target these fields statically …
=> feat(optimizer)!: Expand stars on BigQuery's tbl.struct_col.* selections

sqlglot/optimizer/qualify_columns.py, tests/fixtures/optimizer/qualify_columns.sql, tests/test_optimizer.py
Let's assume we want to expand the following struct:
```
WITH
tbl1 AS (SELECT STRUCT(1 AS fld1, Struct(3 AS fld2, Struct(4 AS fld3) AS lvl2) AS lvl1) AS col)
SELECT col.* FROM tbl1;
```
The recently merged PR would essentially flatten the struct by exploding the fields through a DFS traversal, i.e it would produce:
```
WITH
tbl1 AS (...) # redacted CTE, same as initial query
SELECT tbl1.col.fld1 AS _f_0, 
tbl1.col.lvl1.fld2 AS _f_2,
tbl1.col.lvl1.lvl2.fld3 AS _f_3,
FROM tbl1
```
Even though the results are similar to what would be produced from the initial query, internally BigQuery only has to expand [the _top level_ expression](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_expression_star) and the rest of the "flattening" is performed implicitly; This …
=> fix(optimizer)!: Refactor struct star expansion in BQ

sqlglot/dialects/clickhouse.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/mysql.py, sqlglot/dialects/prql.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/teradata.py, sqlglot/dialects/tsql.py, sqlglot/parser.py, tests/dialects/test_mysql.py, tests/fixtures/optimizer/simplify.sql
As discussed in Slack:
Seems like all dialects give AND higher precedence than OR.
We're still a bit loose on precedence, and there are certainly other precedence bugs. So longer term, we might want to consider how we configure and parse precedence per dialect.
But for now, AND/OR are of course super common, so patching in this little fix.
=> fix!!: _parse_conjunction -> _parse_connector, AND gets higher precedence than OR

sqlglot/optimizer/normalize.py, tests/test_optimizer.py
Exist normalization distance calculation early, if its already surpassed the max.
Without this, simply estimating large normalization distances takes _really_ long.
=> fix: stop normalization_distance early

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes #3604
Parsing the subquery with `parse_select` would consume the next token as an alias which actually belongs to the copy options. From my testing, adding an alias leads to an error so this PR turns it off.
- [COPY INTO](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#syntax)
- [Querying staged files](https://docs.snowflake.com/en/user-guide/querying-stage)
=> fix(snowflake): Fix COPY INTO with subquery

benchmarks/bench.py, benchmarks/helpers.py, benchmarks/optimize.py, sqlglot/optimizer/normalize.py, sqlglot/optimizer/simplify.py, tests/fixtures/optimizer/simplify.sql
Some of the simplification rules become _very_ expensive on deeply nested conditions (e.g. a1 AND a2 AND ... AND a100)
Here's something that'll probably be controversial - this sets a configurable threshold to not even bother trying to simplify these.
=> fix: optimize absorb_and_eliminate and remove_complements

sqlglot/dialects/spark.py, tests/dialects/test_bigquery.py, tests/dialects/test_redshift.py, tests/dialects/test_spark.py
Fixes #3607
Until now Hive and it's child dialects supported `DATE_ADD(startDate, numDays)` which had "hardcoded" the unit to `DAYS` and returned a `DATE`. 
Spark3 (testing on 3.5.1) and Databricks have introduced support for `DATE_ADD(unit, value, expr)` (alias of `TIMESTAMPADD` and `DATEADD`) which instead returns a `TIMESTAMP`.
Note that the old / 2-arg version is still supported alongside the new one and should be preserved to ensure the `DATE` vs `TIMESTAMP` semantics. 
- [DATE_ADD w/ 2 args](https://docs.databricks.com/en/sql/language-manual/functions/date_add.html)
- [DATE_ADD w/ 3 args](https://docs.databricks.com/en/sql/language-manual/functions/date_add3.html)
=> feat(spark, databricks)!: Support for DATE_ADD functions

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py
Fixes #3601 
This PR introduces support for Postgres's `DIV()` function which performs integer division. It mirrors the BigQuery implementation which stores the args in `exp.IntDiv` and generates it back to the function representation.
[Postgres Div](https://www.postgresqltutorial.com/postgresql-math-functions/postgresql-div/)
=> feat(postgres): Support DIV() func for integer division

sqlglot/dialects/redshift.py, tests/dialects/test_redshift.py
Added support for oracle style join markers `(+)`
Fixes #3611
=> Fix(redshift): add support for Oracle style outer join markers

sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #3619
Snowflake allows any keyword such as `SELECT`, `FROM`, `JOIN` etc to be used as JSON path key. All of these except `SELECT` are captured with the existing `parse_field(any_token=True)`.  
The exception happens because `advance_any(any_token=True)` will _not_ advance if the next token is in `RESERVED_TOKENS` which includes `SINGLE_TOKENS` and `TokenType.SELECT`.
=> fix(snowflake): Allow SELECT keyword as JSON path key

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py, tests/dialects/test_tsql.py
DuckDB has a [single character data type](https://duckdb.org/docs/sql/data_types/text), with aliases CHAR, BPCHAR, STRING, TEXT, VARCHAR.
SQLGlot currently maps these aliases to two different data types, `TEXT` (char, bpchar, text) and `VARCHAR` (string, varchar). Because there is only a single underlying type in DuckDB, this PR maps all aliases to `TEXT`.
We use `TEXT` instead of `VARCHAR` because DuckDB's single type is unlimited length and other sqlglot dialects rely on `TEXT` being unlimited length. 
For example, the duckdb -> tsql transpilation semantics are currently incorrect:
- tsql maps `Type.TEXT` -> `"VARCHAR(max)"` to allow unlimited length.
- Currently, sqlglot transpiles duckdb `"VARCHAR"` -> `Type.VARCHAR` -> tsql `"VARCHAR"`. Because tsql's default is length 1, this …
=> Fix(duckdb)!: map all character data type aliases to TEXT

sqlglot/expressions.py, tests/dialects/test_oracle.py
Fixes #3636
Oracle specifies the following syntax for `TO_DATE`, which renders `format` optional in `exp.StrToDate`:
```
TO_DATE(char [ DEFAULT return_value ON CONVERSION ERROR ] [, fmt [, 'nlsparam' ] ])
```
[Oracle TO_DATE](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/TO_DATE.html)
=> fix(oracle): Allow optional format in TO_DATE

sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/parser.py, tests/dialects/test_duckdb.py
Another improvement based on https://github.com/tobymao/sqlglot/commit/2e434501f50167b30f6e5fd4334fa70c4dde220b
=> Fix(duckdb): get rid of TEXT length to facilitate transpilation

sqlglot/parser.py, tests/test_parser.py
Fixes #3647
If `exp.Unnest` is left to be constructed from arg list then `unnest.expressions` won't be of `list` type. A new entry in `FUNCTIONS` ensures that it stores the internal argument in a `list`.
The other changes are alphabetical sorting
=> fix: Add UNNEST in FUNCTIONS 

sqlglot/dialects/dialect.py, tests/dialects/test_dialect.py
This can be useful if users want to override stuff based on a dialect instance's state, e.g. version, which is currently _not_ stored even though it's extracted from the dialect string.
=> Feat: set misc. dialect settings if available

sqlglot/dialects/dialect.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, tests/dialects/test_redshift.py
Fixes #3651
Normalize Redshift's units from plural/abbreviation to their full singular form during parse time. This is already happening at Snowflake, so the existing infrastructure is moved out to `dialect.py` as most of these mappings are similar between dialects.
=> fix(redshift)!: Normalize time units in their full singular form

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/sqlite.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/optimizer/annotate_types.py, sqlglot/optimizer/canonicalize.py, tests/dialects/test_bigquery.py
The aim of this PR is to extend support for the following time functions in BigQuery and enable transpilation towards DuckDB:
`TIME`:
- Introduce `exp.Time` for `TIME(timestamp, [time_zone])`  roundtrip
- Enable transpilation to other dialects by generating `<timestamp> AT TIME ZONE <time_zone>` 
`TIMESTAMP`:
- Rename `expression` to `zone` as the 2nd parameter is always `time_zone`
`DATETIME`:
- Introduce `exp.Datetime` for `DATETIME(date_expr, [time_expr | time_zone])` roundtrip
- Enable transpilation to other dialects by generating `<date_expr> AT TIME ZONE <time_zone>` if the expression is `time_zone`, otherwise generate `<date_expr> + <time_expr>` 
[BQ TIME](https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time) | [BQ …
=> feat(bigquery)!: Time/Datetime/Timestamp function additions

sqlglot/dialects/databricks.py, sqlglot/dialects/dialect.py, sqlglot/generator.py, sqlglot/jsonpath.py, tests/dialects/test_databricks.py, tests/dialects/test_redshift.py, tests/dialects/test_snowflake.py, tests/test_jsonpath.py
Fixes #3673
This PR aims to preserve the JSON/Variant access in Databricks using operators instead of JSON functions + JSONPath by:
- Adding `IDENTIFIERS` in `jsonpath.py` to be able to parse keys with special chars (see [example](https://docs.databricks.com/en/semi-structured/variant.html#extract-a-top-level-variant-field))
- Manually parsing `GET_JSON_OBJECT()` -> `exp.JSONExtract` 
- Changing the generation of `exp.JSONExtract` & `exp.JSONExtractScalar` (only in DB) to the operator-based syntax
Docs
--------
[DB querying VARIANT](https://docs.databricks.com/en/semi-structured/variant.html#query-variant-data) | [DB path expression](https://docs.databricks.com/en/sql/language-manual/sql-ref-json-path-expression.html) | [DB JSON functions](https://docs.databricks.com/en/sql/language-manual …
=> feat(databricks)!: Preserve JSON/VARIANT path with operators

sqlglot/dialects/oracle.py, tests/dialects/test_dialect.py, tests/dialects/test_oracle.py, tests/dialects/test_redshift.py
Fixes #3684
Oracle specifies that `NULLS LAST` is the default for _ascending_ order and `NULLS FIRST` for _descending_ order i.e nulls are larger than non-nulls (dialects are default initialized with `NULL_ORDERING = "nulls_are_small"`). With this PR the new mapping in Oracle is:
```SQL
ASC NULLS LAST -> ASC
DESC NULLS FIRST -> DESC
ASC NULLS FIRST -> ASC NULLS FIRST
DESC NULLS LAST -> DESC NULLS LAST
```
[Oracle ORDER BY clause](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__I2171079)
=> fix(oracle): Fix default NULL_ORDERING

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, tests/dialects/test_clickhouse.py
Fixes #3679
This PR aims to fix the roundtrip for the following CH datetime functions and their aliases:
`DATE_SUB`, `DATE_ADD`, `DATE_DIFF`, `TIMESTAMP_ADD`, `TIMESTAMP_SUB`
These functions (except `DATE_DIFF`) support either one or both of the following versions
- 2-arg based version `<func>(date, INTERVAL unit)`, supported by `DATE_ADD`, `DATE_SUB`, `TIMESTAMP_SUB`
- 3-arg based version `<func>(unit, value, date)`, supported by `DATE_ADD`, `DATE_SUB`, `TIMESTAMP_ADD`
The exception to that is `DATE_DIFF` which parses into `date_diff('unit', startdate, enddate, [timezone])`; Note that support for `timezone` was not added in this PR.
=> feat(clickhouse): Fix roundtrips of DATE/TIMESTAMP functions

sqlglot/dialects/spark.py, sqlglot/tokens.py, sqlglotrs/src/settings.rs, sqlglotrs/src/tokenizer.rs, tests/dialects/test_databricks.py
Fixes #3686
From Databricks' [docs](https://docs.databricks.com/en/sql/language-manual/data-types/string-type.html) (same for Spark v3):
> If the string is prefixed with r there is no escape character.
=> Fix(tokenizer): don't treat escapes in raw strings as such for some dialects

sqlglot/dialects/bigquery.py, sqlglot/dialects/clickhouse.py, sqlglot/dialects/drill.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/sqlite.py, sqlglot/dialects/teradata.py, sqlglot/dialects/tsql.py, tests/dialects/test_postgres.py
Fixes #3692
Tried to do this at the `_Dialect` metaclass but the code wasn't that better. There was also an issue with `KEYWORD_TRIE`, I think because the tokenizer metaclass is executed first and we [create it](https://github.com/tobymao/sqlglot/blob/main/sqlglot/tokens.py#L495-L504) while `/*+` is still in `KEYWORDS`. So I just decided to do this the simple way.
=> Fix: don't treat /*+ as a HINT token in dialects that don't support hints

sqlglot/dialects/bigquery.py, sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/optimizer/qualify_columns.py, tests/test_optimizer.py
Fixes #3687
Take the following query:
```SQL
WITH data AS (
SELECT
1 AS id,
2 AS my_id
)
SELECT
id AS my_id
FROM
data
WHERE
my_id = 1
GROUP BY
my_id,
HAVING
my_id = 1
```
In most dialects this is an incorrect query as `GROUP BY my_id` is resolved to `GROUP BY data.my_id` which is not aggregated (the overlapping alias in the projection list is resolved later in the order of operations). 
However, the exceptions to this rule which _can_ process this query are the following:
- BigQuery, which only forwards the alias only to `GROUP BY` & `HAVING` i.e resolves to:
```SQL
WITH data AS (...)
WHERE data.my_id = 1 GROUP BY data.id HAVING data.id = 1
```
- Clickhouse, which forwards the alias across the query i.e resolves to:
```SQL
WITH data AS (...)
WHERE data.id = 1 GROUP BY data.id HAVING …
```
=> fix(optimizer): Force early alias expansion in BQ & CH

sqlglot/dialects/databricks.py, sqlglot/dialects/spark.py, tests/dialects/test_databricks.py
Fixes #3700
For a followup PR: see if we can refactor the date deltas for spark/databricks. Perhaps we can use a single implementation for both.
=> Fix: proper parsing of unit in spark/databricks date_diff

sqlglot/parser.py, tests/dialects/test_bigquery.py
Fixes https://github.com/TobikoData/sqlmesh/issues/2827
=> Fix(parser): preserve Cast expression when it's 'safe' and has a format

sqlglot/dialects/hive.py, sqlglot/dialects/mysql.py, sqlglot/dialects/presto.py, sqlglot/dialects/redshift.py, sqlglot/dialects/tsql.py, sqlglot/generator.py, tests/dialects/test_snowflake.py
Motivation behind this was that `TRY_PARSE_JSON` sets `safe` to `True` when parsed with Snowflake, which leads to a crash when we target dialects other than duckdb/snowflake (booleans aren't generated in `Generator.sql`).
Also reduced some code duplication while at it.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1719419364440449
=> Refactor: control ParseJSON generation logic with a flag

sqlglot/dialects/bigquery.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py, tests/dialects/test_duckdb.py
Add generation for `exp.Length` in DuckDB. 
Dialects like Snowflake and BigQuery also use `LENGTH() / LEN()` for binary values, so this PR will generate `LENGTH(<expr>)` if the type can be inferred or a case/when with `LENGTH` for `VARCHAR` and `OCTET_LENGTH` for the binary (`BLOB`) value.
=> feat(duckdb): Transpile exp.Length from other dialects

sqlglot/dialects/oracle.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_oracle.py, tests/dialects/test_snowflake.py
Fixes #3716
Transpiling `CONNECT_BY_ROOT` will probably require more effort based on https://stackoverflow.com/questions/22296248/connect-by-root-equivalent-in-postgres.
=> Feat(snowflake): add support for CONNECT_BY_ROOT expression

sqlglot/optimizer/qualify_columns.py, tests/fixtures/optimizer/qualify_columns.sql
Prior to this change, we'd expand a `USING(col1, col2)` clause into an `ON` clause that compared the corresponding columns as is, eg. `ON t1.col1 = t2.col1 AND t1.col2 = t2.col2`.
That is fine when there are only two tables joined, but when more tables are involved it turns out that we need to coalesce all columns from the already-joined tables that appear in the left-hand side of these equalities. If we don't, the semantics are not preserved.
For example, this:
```sql
with t1 as (select 'x' as id, date '2024-01-01' as foo, 000 as value),
t2 as (select 'x' as id, date '2024-02-02' as foo, 123 as value),
t3 as (select 'x' as id, date '2024-02-02' as foo, 456 as value)
select *
from t1
full outer join t2 using(id, foo, value)
full outer join t3 using(id, foo, value)
```
Should be …
=> Fix(optimizer)!: coalesce left-hand side of join conditions produced by expanding USING

sqlglot/dialects/teradata.py, tests/dialects/test_teradata.py
fixes [3722](https://github.com/tobymao/sqlglot/issues/3722)
after making the change, `current_timestamp` in my example sql no longer retained it's precision. I'm not sure why this happened but modifying the current timestamp transform seemed to fix it.
regarding this change: current_timestamp can have a precision of 0-6, but `current_timestamp()` (with no arguments) is not valid sql.
documentation reference: https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Functions-Expressions-and-Predicates/Built-In-Functions/CURRENT_TIMESTAMP/CURRENT_TIMESTAMP-Function-Syntax so I tried to represent this in the transform
=> fix(teradata): use timestamp with time zone over timestamptz

sqlglot/dialects/databricks.py, sqlglot/dialects/dialect.py, sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, sqlglot/executor/python.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_dialect.py, tests/dialects/test_presto.py
Fixes #3713
Both Snowflake and Databricks have a `VARIANT` type with similar extract notation e.g. `col:x.y` which can be used to store any data (most notably, semi-structured). Up until now, SQLGlot treated this notation as a JSON extraction which is not always correct; As the issue showcased, since Snowflake does not have a `STRUCT` data type, Iceberg represents it's `STRUCT` as a `VARIANT` column which should map to a `ROW` column in Presto/Trino instead of `JSON`.
This PR focuses on Snowflake -> Presto/Trino and attempts to lift off this restriction by introducing a new dialect setting which can make the `exp.JSONExtract` generation configurable such that it can either: 
1. Generate `JSON_EXTRACT(col, '$.x.y')` for JSON data (as was before) or 
2. Transform the JSONPath to the …
=> feat(presto, trino): Configurable transpilation of Snowflake VARIANT

sqlglot/dialects/oracle.py, tests/dialects/test_oracle.py
Fixes #3733
In Oracle, these two functions have [different behaviors](https://stackoverflow.com/a/34830327), with the main one being that NVL implicitly converts the args to the same type; This means that SQLGlot cannot canonicalize`NVL()` to `COALESCE()` without type annotation & schema.
This PR aims to decouple them by removing the alias from `exp.Coalesce` and treating `NVL()` as an anonymous function. This should not be the case for Redshift, which does treat `NVL()` & `COALESCE()` as exactly the same function.
Docs
---------
[Oracle NVL](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/NVL.html) | [Oracle COALESCE](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/COALESCE.html) | [Redshift …
=> fix(oracle)!: Decouple NVL() from COALESCE()

sqlglot/dialects/presto.py, tests/dialects/test_presto.py
Fixes https://github.com/TobikoData/sqlmesh/issues/2855
In SQLMesh's case this should suffice, because we can always infer the type of MD5's argument, due to [explicit casts](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/macros.py#L887-L893).
References:
- https://trino.io/docs/current/functions/string.html#to_utf8
- https://trino.io/docs/current/functions/binary.html#md5
=> Feat(presto): wrap md5 string arguments in to_utf8

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_spark.py
Fixes #3738
Add support for the `schema_binding` clause with syntax:
```SQL
WITH SCHEMA { BINDING | COMPENSATION | [ TYPE ] EVOLUTION }
```
Docs
---------
[Databricks CREATE VIEW](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-view.html)
=> feat(spark, databricks): Support view schema binding options

sqlglot/optimizer/qualify_columns.py, sqlglot/optimizer/scope.py, tests/fixtures/optimizer/qualify_columns.sql
Context from [public slack](https://app.slack.com/client/T041MTMK2JC/C044BRE5W4S)
In dialects like Snowflake the `SELECT` syntax allows the following statements (may be different per dialect):
```SQL
SELECT *
...
[ EXCLUDE {<col_name> [, ... ] }]
[ REPLACE {( <expr> AS <col_name> [, ... ] )}]
[ RENAME {<col_name> AS <col_alias>, ... )}]
```
Currently the optimizer incorrectly treats `SELECT * REPLACE`  as `SELECT * RENAME` semantically, with `RENAME` not being accounted for at all. 
This PR aims to fix this by:
- Adding support for `RENAME` which should substitute the column aliases 
- Fixing how `REPLACE` works i.e it now appends the replaced expressions directly to the selection list
```SQL
SELECT * REPLACE(1 as col) => SELECT 1 as col
```  
- The `EXCEPT`/`EXCLUDE` columns [are still …
=> fix(optimizer): Fix expansion of SELECT * REPLACE, RENAME

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_bigquery.py
Current behavior:
```python
>>> sqlglot.transpile("/* some comment */ DECLARE foo DATE DEFAULT DATE_SUB(current_date, INTERVAL 2 day)", "bigquery")
'DECLARE foo DATE DEFAULT DATE_SUB(current_date, INTERVAL 2 day)' contains unsupported syntax. Falling back to parsing as a 'Command'.
['DECLARE foo DATE DEFAULT DATE_SUB(current_date, INTERVAL 2 day)']
```
On this PR the comment is preserved and prepended to the `Command`'s SQL.
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1720648294228409
=> Fix: attach comments to Commands

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/spark.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Fixes #3755
For the dialects that support `ORDER BY ALL` such as DuckDB, Databricks, Spark3 (tested on 3.4+) parse `ALL` as an `exp.Var` and not as a column.
Docs
--------
[DuckDB ORDER BY](https://duckdb.org/docs/sql/query_syntax/orderby.html) | [Databricks ORDER BY](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select-orderby.html)
=> feat(duckdb, spark, databricks): Support for ORDER BY ALL

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
[Public slack context](https://app.slack.com/client/T041MTMK2JC/C044BRE5W4S)
This PR adds support for the `ROWS FROM` clause which is stored in `exp.Table`:
```
FROM ROWS FROM ( function_name ( [ argument [, ...] ] ) [ AS ( column_definition [, ...] ) ] [, ...] )
[ WITH ORDINALITY ] [ [ AS ] alias [ ( column_alias [, ...] ) ]
```
Note that the parser (`_parse_table()`) already supports Postgres's `from_item` set functions, which are also parsed as `exp.Table`:
```
FROM function_name ( [ argument [, ...] ] )
[ WITH ORDINALITY ] [ [ AS ] alias [ ( column_alias [, ...] ) ] ]
```
Thus, a straightforward solution was to recursively parse & generate `ROWS FROM`'s params as comma-separated set functions (i.e other `exp.Table`s).
Docs
----------
- [Postgres SELECT …
=> feat(postgres): Support FROM ROWS FROM (...)

sqlglot/dialects/presto.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py
Fixes #3762 
Transpile `exp.TimestampAdd` to Presto/Trino's `DATE_ADD()` which can accept any datetime expr; The result returned is of the same type. 
For the same reason, I also went ahead and factored out the generation of `exp.DateAdd | exp.TimestampAdd | exp.DateSub`
Docs
--------
[Presto DATE_ADD](https://prestodb.io/docs/current/functions/datetime.html#date_add-unit-value-timestamp-same-as-input) | [Trino DATE_ADD](https://trino.io/docs/current/functions/datetime.html#date_add)
=> feat(presto, trino): Add support for exp.TimestampAdd

sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/mysql.py, sqlglot/dialects/presto.py, sqlglot/dialects/spark.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Introduce `exp.Pad` which supports the string padding functions `LPAD()`, `RPAD()`; The joint node is used because these 2 functions share the same signature but differ on the result (left/right application of padding)
Most dialects default to whitespace for the padding (3rd parameter) while DuckDB, MySQL, Presto/Trino, and Hive/Spark2  require it explicitly, so the flag `PAD_FILL_PATTERN_IS_REQUIRED` was introduced to facilitate transpilation during generation.
Docs
--------
[Databricks / Spark3](https://docs.databricks.com/en/sql/language-manual/functions/lpad.html) | [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#lpad) | [DuckDB](https://duckdb.org/docs/sql/functions/char.html#lpadstring-count-character) | …
=> feat: Support for RPAD & LPAD functions

sqlglot/dialects/duckdb.py, sqlglot/generator.py, tests/dialects/test_databricks.py
Fixes #3764
A UDF in Databricks can be defined as:
```SQL
CREATE FUNCTION 
<func_name>(<schema def>) 
RETURNS 
[type | TABLE(<schema def>)] 
RETURN 
<return_expr>
```
The `RETURNS` clause is parsed into an `exp.ReturnsProperty` node while the `RETURN` expression is parsed into `exp.Return`. The distinction between scalar and table UDF is determined by the `RETURNS` expression i.e returning a single type or a schema definition.
In DuckDB, a UDF (`MACRO` or `FUNCTION` are synonyms) can be defined as:
```SQL
CREATE [MACRO | FUNCTION] 
<func_name>(col_value[, ...]) 
AS [TABLE] 
<return_expr>
```
The distinction between scalar and UDF is determined by the `AS [TABLE]` clause
To fix the Databricks -> DuckDB transpilation, this PR:
- Overrides `exp.Return` transformation to avoid generating the …
=> fix(duckdb): Transpile UDFs from Databricks

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Fixes #3763
Docs
-------
[Clickhouse Tuple](https://clickhouse.com/docs/en/sql-reference/data-types/tuple)
=> fix(clickhouse): Allow TokenType.SELECT as a Tuple field identifier

sqlglot/dialects/postgres.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #3774
Currently `_parse_unique()` attempts to parse MySQL's `UNIQUE` constraint  (https://github.com/tobymao/sqlglot/pull/1708), which is parsed as:
```SQL
UNIQUE KEY [<key>] (<col> [,...])
```
However, Postgres's `UNIQUE` (syntax below) does not seem to define `<key>` so it must not preemptively consume an id_var for it:
```SQL
UNIQUE [NULLS NOT DISTINCT] [(<col> [, ...])]
```
For this reason, this PR:
- Turns off the `[<key>]` parsing in Postgres
- Adds support for `NOT NULLS DISTINCT` as a low-lift addition to increase DDL coverage
Docs
----------
[Postgres UNIQUE](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS) | [Postgres DEFAULT](https://www.postgresql.org/docs/current/ddl-default.html) | [MySQL …
=> fix(postgres): Fix UNIQUE consuming tokens

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes #3782
Preserve precedence of `JSON_EXTRACT` / `JSON_EXTRACT_STRING` if it's followed by a subscript (legal DuckDB if the result is a `LIST`).
This PR builds on top of https://github.com/tobymao/sqlglot/pull/3478 which solved a similar issue.
Docs
-------
[DuckDB JSON Extract functions](https://duckdb.org/docs/extensions/json.html#json-extraction-functions)
=> fix(duckdb): Wrap JSON_EXTRACT if it's subscripted

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py
Transpile BQ's `DATETIME_SUB()` & `DATETIME_ADD()` to `<datetime_expr> +/- <interval_expr>` in DuckDB as is the case currently with other date/time functions.
Also, this PR merges `_ts_or_ds_add_sql()` in `_date_delta_sql()` as they have very similar control flow.
Docs
---------
[BQ DATETIME_SUB](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime_sub) | [BQ DATETIME_ADD](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime_add)
=> feat(duckdb): Transpile BQ's exp.DatetimeAdd, exp.DatetimeSub

sqlglot/dialects/dialect.py, sqlglot/dialects/presto.py, sqlglot/optimizer/annotate_types.py, tests/dialects/test_presto.py
Fixes #3778
The issue arises from the following chain reaction:
1. Transpiled divisions from Spark to Presto/Trino will be casted to `DOUBLE` due to typed division semantics
2. Certain math functions in Presto/Trino such as `FLOOR()` will return the same type as their input (`DOUBLE` in this case), so that type will bubble up
3. `DATE_ADD` requires an `INT` on the 2nd argument; While this was accounted for in #2648, what changes here is that `annotate_types` will always (incorrectly) annotate these math functions to `INT`, rendering the `_to_int()` a no-op essentially (`exp.cast()` will be optimized away)
4. Thus, the expression / 2nd parameter remains a `DOUBLE` which causes the execution error
This PR attempts to solve this long term by making the `TypeAnnotator` dialect-aware; By …
=> feat: Move ANNOTATORS to Dialect for dialect-aware annotation

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py
Fixes #3797
This PR adds parsing support for Postgres's `TO_DATE(text, text) -> date`; Generation support was added in https://github.com/tobymao/sqlglot/pull/3124.
Docs
--------
[Postgres formatting functions](https://www.postgresql.org/docs/current/functions-formatting.html)
=> feat(postgres): Parse TO_DATE as exp.StrToDate

sqlglot/dialects/dialect.py, sqlglot/dialects/hive.py, sqlglot/dialects/presto.py, tests/dialects/test_postgres.py
Fixes #3793
This PR adds support for the `SEQUENCE()` function across the Hive hierarchy. The generation is similar to the existing Presto/Trino, thus the code reuse. 
Docs
--------
[Spark 2](https://spark.apache.org/docs/2.4.0/api/sql/index.html#sequence) | [Spark 3](https://spark.apache.org/docs/latest/api/sql/#sequence) | [Databricks](https://docs.databricks.com/en/sql/language-manual/functions/sequence.html)
=> feat(hive, spark, db): Support for exp.GenerateSeries

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes #3808
The recent PR https://github.com/tobymao/sqlglot/pull/3751 enabled transpilation of BQ's `STRUCT<type>(values)` to DuckDB `CAST(ROW(<values>) AS STRUCT(<struct>))`, and the core DDB generation logic was based on the `is_struct_cast` condition. However, a struct can be casted to other types such as `JSON` which will trip this condition.
This PR fixes this regression by making sure the `is_struct_cast` more explicit, i.e it now searches the `exp.Cast` for a `STRUCT` definition under it before transforming to the casted `ROW` representation
=> fix(duckdb): Fix STRUCT_PACK -> ROW due to is_struct_cast

sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py
Fixes #3802
Currently, `OBJECT_CONSTRUCT` will transpile to `STRUCT` construction in DuckDB (context https://github.com/tobymao/sqlglot/issues/1699). 
Following this convention, this PR adds support for Snowflake's `OBJECT_INSERT(object, key, value, [update_flag])` which will get transpiled to DuckDB's `STRUCT_INSERT(object, key := value)`. 
Docs
-----------
[Snowflake OBJECT_INSERT](https://docs.snowflake.com/en/sql-reference/functions/object_insert) | [Snowflake OBJECT_CONSTRUCT](https://docs.snowflake.com/en/sql-reference/functions/object_construct) | [DuckDB STRUCT](https://duckdb.org/docs/sql/data_types/struct.html)
=> feat(snowflake): Support for OBJECT_INSERT, transpile to DDB

sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #3814
The issue is fixed as the `REFERENCES` parsing does not match all the options e.g. `MATCH [SIMPLE | PARTIAL]` . Also, the missing constraint `INITIALLY IMMEDIATE` is added to increase coverage.
Docs
--------
[Postgres CREATE TABLE](https://www.postgresql.org/docs/16/sql-createtable.html)
=> feat(postgres): Add missing constraint options

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
[Public slack context](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1721842284939239)
Docs
----------
[Snowflake querying staged files](https://docs.snowflake.com/en/user-guide/querying-stage)
=> fix(snowflake): Don't consume LPAREN when parsing staged file path

sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #3817
Before this PR a collation column constraint was parsed as `_parse_var(any_token=True)`. Because of that:
- We're unable to parse `pg_catalog."default"`,
- The existing Postgres test showcased that `COLLATE "de_DE" -> COLLATE de_DE` which doesn't seem correct, the roundtripped query is not valid according to the docs and my local testing.
For this reason, this PR changes the parsing to either `exp.Identifier` to cover existing cases or `exp.Column` to cover the `pg_catalog."default"` case.
Docs
----------
[Postgres Collation](https://www.postgresql.org/docs/16/collation.html) | [Postgres CREATE TABLE](https://www.postgresql.org/docs/16/sql-createtable.html)
=> fix(postgres): Fix COLLATE column constraint

sqlglot/parser.py, tests/fixtures/identity.sql
Fixes #3819, #3821
In Spark/Databricks (and also other dialects such as Presto/Trino from a quick test) the `ALL` keyword can be both a `SELECT` modifier and an identifier.  
This PR attempts to fix the preemptive consumption of `ALL` in `_parse_select()` if it's connected, i.e it deduplicates `SELECT ALL FROM <x>` from `SELECT all.col FROM all`.
Note: This is also is true `DISTINCT` in Spark/Databricks e.g. the following works but didn't want to increase this PR's scope yet:
```SQL
WITH distinct AS (SELECT 1 AS col) SELECT distinct.col FROM distinct"
```
Docs
--------
[Databricks SELECT](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-qry-select.html)
=> fix: Do not preemptively consume SELECT [ALL] if ALL is connected

sqlglot/dialects/presto.py, tests/dialects/test_dialect.py, tests/dialects/test_hive.py, tests/test_transpile.py
Fixes #3796
This PR is an attempt to make the transformation introduced in https://github.com/tobymao/sqlglot/pull/3225 more robust, as it seems that we're currently unable to parse timestamps with fractions of second and/or timezone.
To achieve this, the value is now passed through `DATE_PARSE` in an attempt to canonicalize it (e.g. strip milliseconds, timezone etc) before it is inputted to `PARSE_DATETIME`.
This is a before vs after demo:
- Spark:
```SQL
SELECT FROM_UNIXTIME(CURRENT_TIMESTAMP)
```
- Presto before (unable to execute locally on v451): 
```SQL
SELECT TO_UNIXTIME(COALESCE(TRY(DATE_PARSE(CAST(CURRENT_TIMESTAMP AS VARCHAR), '%Y-%m-%d %T')), PARSE_DATETIME(CAST(CURRENT_TIMESTAMP AS VARCHAR), 'yyyy-MM-dd HH:mm:ss')))
```
- Presto after:
```SQL
SELECT …
```
=> fix(presto, trino): Fix StrToUnix transpilation

sqlglot/dialects/clickhouse.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/dialects/presto.py, sqlglot/dialects/sqlite.py, sqlglot/generator.py, sqlglot/helper.py, tests/dialects/test_duckdb.py, tests/dialects/test_postgres.py, tests/test_transpile.py
Couple of quality-of-life improvements:
- Exclude boolean values in `Generator.format_args`. The motivation here was that each time we added a flag arg in an function, we needed to also exclude it from being included in the `Generator.sql` method, otherwise an error would be triggered since there's no logic to generate booleans. This PR removes the need to do this.
- Change the logging level to `INFO` for the index offset application helper. This was changed because a Slack user [reported](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1722016618281349) seeing noisy warnings in their SQLMesh project.
=> Refactor: exclude boolean args in Generator.format_args

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Accidentally introduced a regression in https://github.com/tobymao/sqlglot/pull/3848, wasn't aware that `CREATE VIEW` requires CTEs to [come after](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql?view=sql-server-ver16#syntax) the `CREATE VIEW` keywords.
=> Fix(tsql): regression related to CTEs in CREATE VIEW AS statements

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py
BigQuery can implicitly cast/coerce string literal arguments into the appropriate date/time type, which is not the case for DuckDB.
This PR aims to fix the transpilation of `exp.DateDiff` by inserting the casts to replicate this behavior.
Docs
------------
[BigQuery DATE_DIFF](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_diff) | [DuckDB DATE_DIFF](https://duckdb.org/docs/sql/functions/date.html#date_diffpart-startdate-enddate)
=> fix(duckdb): Add implicit casts to DATE_DIFF

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py
Generate BQ's `exp.TimeDiff` into DuckDB's `DATE_DIFF()`. Although both functions have similar signatures and should be calculating the partitions between `end_time - start_time`, BQ seems to inverse the operands which is more accurately documented on 3rd party pages.
Docs
-------------
[BigQuery TIME_DIFF official docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time_diff) | [BigQuery TIME_DIFF unofficial docs](https://count.co/sql-resources/bigquery-standard-sql/time_diff) | [DuckDB DATE_DIFF](https://duckdb.org/docs/sql/functions/timestamp.html#date_diffpart-startdate-enddate)
=> feat(duckdb): Support for exp.TimeDiff generation

sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_teradata.py, tests/fixtures/identity.sql
Fixes #3861
Docs
---------
[Teradata RENAME TABLE](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Definition-Language-Syntax-and-Examples/Table-Statements/RENAME-TABLE/RENAME-TABLE-Syntax-Elements/new_table_name)
=> feat(teradata): Parse RENAME TABLE as Command

sqlglot/parser.py, tests/dialects/test_snowflake.py
This was motivated by a bug I discovered in SQLMesh: `@STAR(..., exclude := [...])` doesn't work for snowflake and duckdb because they map `"EXCLUDE"` to `TokenType.EXCEPT` and that's not in `ID_VAR_TOKENS`, resulting in a `ParseError`, since `_parse_conjunction()` can't consume it.
=> Fix(parser): make assignment parsing more lenient by allowing keyword in LHS

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_bigquery.py, tests/dialects/test_redshift.py
While `exp.ArrayConcat` is a varlen function in many dialects, this isn't the case for all; This PR fixes this by refactoring the generation to _reduce_ the varlen version to a series of 2-arg based `ARRAY_CONCAT(x, y)` calls for those dialects.
This PR also fixes Redshift's `ARRAY(expr1, ..., exprN)` construction which differs from Postgres's `ARRAY[expr1, ..., exprN]`. 
Docs
---------
[Trino - Presto ARRAY Functions](https://trino.io/docs/current/functions/array.html)
[Postgres ARRAY Functions](https://www.postgresql.org/docs/9.1/functions-array.html)
[Spark CONCAT](https://spark.apache.org/docs/latest/api/sql/#concat) | [Databricks CONCAT](https://docs.databricks.com/en/sql/language-manual/functions/concat.html) 
[Redshift ARRAY](https://docs.aws.amazon.com/redshift/latest/dg/r_array.ht …
=> fix!: Generation of exp.ArrayConcat for 2-arg based dialects

sqlglot/dialects/duckdb.py, sqlglot/parser.py, tests/dialects/test_bigquery.py
Generate BigQuery's `GENERATE_DATE_ARRAY(start, stop, interval)` to DuckDB's `GENERATE_SERIES(start, stop, interval)`
Docs
--------
[BigQuery GENERATE_DATE_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#generate_date_array) | [DuckDB GENERATE_SERIES](https://duckdb.org/docs/sql/functions/nested.html#generate_series)
=> feat(duckdb)!: Support for BQ's exp.GenerateDateArray generation

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
Reference: https://docs.snowflake.com/en/sql-reference/constructs/pivot#syntax
=> Feat(snowflake): add support for a a couple of missing clauses in PIVOT clause

sqlglot/parser.py, tests/dialects/test_duckdb.py
Fixes #3869
Docs
---------
[DuckDB Describe](https://duckdb.org/docs/guides/meta/describe.html)
=> fix(duckdb): Allow DESCRIBE as a _parse_select() path

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/parser.py, tests/dialects/test_duckdb.py, tests/dialects/test_snowflake.py
Fixes #3868
The recent commit https://github.com/tobymao/sqlglot/commit/2ffb07070952cde7ac9a1883cbf9b4c477c55abb introduced support for fixed-size array parsing in DuckDB; However, not all dialects [1] support fixed-size arrays so a regression was introduced in which the subscript/bracket operator was now interpreted as the array size.
Also, this commit was not working properly for higher dimension arrays so valid queries were broken after roundtripping:
```
sqlglot.parse_one("SELECT [[1], [2], [3]]::INT[1][3]", dialect="duckdb").sql("duckdb")
SELECT CAST([[1], [2], [3]] AS INT[1])[1][3]
```
This PR fixes both issues by introducing a dialect flag that enables the recent addition only for DuckDB. From a quick search, the other dialects which come close to supporting/parsing fixed-size …
=> fix: Fixed size array parsing

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
Currently in main:
```python
import sqlglot
sqlglot.transpile("select * from read_csv('foo.csv')", "bigquery")[0]
```
This happens because `read_csv` is parsed in to `ReadCSV(this=Literal(this='foo.csv'))` and so `"." in part.name` is true for `this` in BigQuery's `_parse_table_parts` logic, resulting in us breaking the function. Granted, `READ_CSV` is not supported (?) in BigQuery, but this bug can happen for other function expressions too.
This branch fixes it:
```python
import sqlglot
sqlglot.transpile("select * from read_csv('foo.csv')", "bigquery")[0]
```
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1722937694107889
=> Fix(bigquery): ensure Funcs are preserved when used as Tables

sqlglot/executor/__init__.py, sqlglot/optimizer/qualify.py, sqlglot/optimizer/qualify_tables.py, tests/fixtures/optimizer/qualify_columns.sql, tests/test_optimizer.py
Whenever the optimizer sees a `READ_CSV` call, it 1) scans the corresponding CSV file and 2) infers the table's schema based on the CSV's header. There were two problems with these:
1. The first argument in `READ_CSV` may not exist in the local file system, e.g. it can be a hive partitioning path or a gcs bucket. In this case, the `open` call would produce a `FileNotFoundError` and the optimizer would crash. A SQLMesh user actually [had](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1722937694107889) this issue.
2. There are additional options supported by the `READ_CSV` call that affect the resulting schema, e.g.:
```
normalize_names - Boolean value that specifies whether or not column names should be normalized, removing any non-alphanumeric characters from them.
filename - …
```
=> Refactor(optimizer)!: switch off CSV file schema inference by default

sqlglot/dialects/duckdb.py, sqlglot/dialects/mysql.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/spark.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_redshift.py, tests/dialects/test_snowflake.py
Fixes #3875
This PR attempts to transpile Snowflake's `CONVERT_TIMEZONE(source_tz, target_tz, timestamp_ntz)` 3-arg version to DuckDB.
Although there isn't a 1:1 mapping, the same result can be acquired by generating nested `TIMEZONE()` calls in DuckDB:
```SQL
TIMEZONE(target_tz, TIMEZONE(source_tz, timestamp_ntz::TIMESTAMP))
```
For instance:
```
Snowflake
--------------
SELECT CONVERT_TIMEZONE('AMERICA/LOS_ANGELES', 'AMERICA/NEW_YORK', '2024-08-06 09:10:00.000')
2024-08-06 12:10:00.000
DuckDB
------------
SELECT TIMEZONE('America/New_York', TIMEZONE('America/Los_Angeles', CAST('2024-08-06 09:10:00.000' AS TIMESTAMP)))
2024-08-06 12:10:00
```
Docs
--------
[Snowflake CONVERT_TIMEZONE](https://docs.snowflake.com/en/sql-reference/functions/convert_timezone) | [DuckDB …
=> feat(duckdb): Transpile Snowflake's CONVERT_TIMEZONE 3-arg version

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/test_optimizer.py
This PR adds support for BQ's `GENERATE_TIMESTAMP_ARRAY()`, following the implementation of `GENERATE_DATE_ARRAY()`
Docs
----------
[BQ GENERATE_TIMESTAMP_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#generate_timestamp_array) | [DuckDB GENERATE_SERIES](https://duckdb.org/docs/sql/functions/timestamp#timestamp-table-functions)
=> feat(bigquery): Support for GENERATE_TIMESTAMP_ARRAY, DDB transpilation

sqlglot/parser.py, tests/test_parser.py
Fixes #3880
`COLLATE` should have a higher precedence than constructs such as `LIKE` but it's not possible to override it's parsing. For this reason, this PR unrolls `_parse_term` and transforms `COLLATE`'s RHS into an `exp.Var` (instead of `exp.Column`) if it's an unquoted identifier.
=> fix: Fix COLLATE's RHS parsing

sqlglot/dialects/snowflake.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #3890
Reference: https://docs.snowflake.com/en/sql-reference/functions/in
> In subquery form, IN is equivalent to = ANY and NOT IN is equivalent to <> ALL.
=> Fix(snowflake)!: parse v NOT IN (subquery) as v <> ALL (subquery)

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Clickhouse implements `TRY_CAST` as type-specific functions with names of form `toXXXOrNull()`. 
The function names must match the case-sensitive type names, so this PR adds the case-specific type names for substitution into the function name.
Case-specific function names in Clickhouse repo [here](https://github.com/ClickHouse/ClickHouse/blob/275de04b8f6bb8c9334bf8070001afe2dab0b17d/src/Functions/FunctionsConversion.cpp#L2939-L2989).
=> Fix(clickhouse): make try_cast toXXXOrNull() functions case-specific

sqlglot/expressions.py, sqlglot/optimizer/annotate_types.py, tests/fixtures/optimizer/annotate_types.sql, tests/test_expressions.py, tests/test_optimizer.py
Fixes #3916
I decided to make `NULL + 1` produce `INT` instead of `NULL`. This also matches duckdb's type inference:
```
D select null + 1;
┌────────────┐
│ (NULL + 1) │
│   int32    │
├────────────┤
│            │
└────────────┘
```
Same for postgres:
```
georgesittas=# select pg_typeof(1 + null);
pg_typeof
-----------
integer
(1 row)
```
=> Fix(optimizer)!: infer set op types more accurately

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Clickhouse does not distinguish between TZ and non-TZ types. The `TIMESTAMP` type accepts an optional timezone argument.
=> Fix(clickhouse): add timestamptz type mapping

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py, tests/dialects/test_clickhouse.py, tests/dialects/test_dialect.py, tests/dialects/test_duckdb.py, tests/dialects/test_tsql.py
The transpilation of data types from other dialects to ClickHouse is currently incomplete, because we don't take nullability into account. Additionally, transpiling `Nullable(T)` from ClickHouse into other dialects is incorrect, because they don't support the `Nullable` type constructor.
Simple example that demonstrates the former issue:
```
D with t as (select 1 as c union all select null as c) select cast(c as int) from t;
┌────────────────────┐
│ CAST(c AS INTEGER) │
│       int32        │
├────────────────────┤
│                  1 │
│                    │
└────────────────────┘
```
Transpiling this query (DuckDB) to ClickHouse yields:
```sql
WITH t AS (SELECT 1 AS c UNION ALL SELECT NULL AS c) SELECT CAST(c AS Int32) FROM t
```
... which fails to be executed in ClickHouse's engine, …
=> Refactor(clickhouse)!: improve transpilation of nullable/non-nullable data types

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py
The `INTERPOLATE` list can only appear after a `WITH FILL` clause, so this PR modifies the AST accordingly. This will enable us to parse the whole `WITH FILL` syntax using a simple `maybe_parse(..., into=exp.Ordered)`, which may come in handy in SQLMesh (context: `ORDER BY` physical table [property](https://github.com/TobikoData/sqlmesh/pull/3019/files#diff-3a65217abd7bfdec09572b0392317d88128cda9d14ea6aa0009699eea6f2b5f0R268)).
Tested the following queries against a local ClickHouse server:
```sql
georges-mbp.home :) SELECT n, source, inter FROM (
SELECT toFloat32(number % 10) AS n, 'original' AS source, number as inter
FROM numbers(10) WHERE number % 3 = 1
) ORDER BY n INTERPOLATE (inter AS inter + 1);
Syntax error: failed at position 163 ('INTERPOLATE') (line 4, col 14): [...]
Expected …
```
=> Refactor(clickhouse)!: attach INTERPOLATE expressions to WithFill

sqlglot/dialects/redshift.py, tests/dialects/test_dialect.py, tests/dialects/test_redshift.py
The Redshift dialect has a subtle bug in its timestamp formatting.
When mapping strftime strings like `%Y-%m-%d %H:%M:%S`,  the Redshift equivalent is being generated as:
```
SELECT TO_CHAR(timestamp '2023-01-01 15:13:14', 'YYYY-MM-DD HH:MI:SS.US')
> '2023-01-01 03:13:14.000000'
```
which wraps around the hours because `%H` (24-hour) is being mapped to `HH` (12-hour) [instead of](https://docs.aws.amazon.com/redshift/latest/dg/r_FORMAT_strings.html) `HH24`.
The correct format string is:
```
SELECT TO_CHAR(timestamp '2023-01-01 15:13:14', 'YYYY-MM-DD HH24:MI:SS.US')
> '2023-01-01 15:13:14.000000'
```
=> Fix!: Redshift date format

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py, tests/dialects/test_duckdb.py
BigQuery uses `%d` for zero-padded days (`05`) and `%e` otherwise (`5`), in contrast to DuckDB / Python which have `%d` and `%-d` respectively.
Docs
--------
[DuckDB Format](https://duckdb.org/docs/sql/functions/dateformat.html#format-specifiers) | [BigQuery Format](https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements#format_elements_date_time) | [Python strftime](https://strftime.org/)
=> fix(bigquery): Map strftime %-d to BQ %e

sqlglot/optimizer/canonicalize.py, tests/fixtures/optimizer/canonicalize.sql
Some dialects (presto/trino) are strict about casting to date.
=> fix(optimizer): convert TsOrDsToDate to Cast more conservatively

sqlglot/dialects/oracle.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_oracle.py
Fixes #3952
https://github.com/tobymao/sqlglot/pull/3734 fixed Oracle's `NVL()` roundtripping to `COALESCE()` which was incorrect due to differences in semantics between the two; The solution at the time was to parse `NVL()` as an `exp.Anonymous` function in order to preserve the RTT.
However, this also broke transpilation. To maintain the Oracle RTT _and_ to re-enable transpilation, a new arg is introduced in `exp.Coalesce` which signals if `exp.Coalesce` was built by parsing `NVL()` in Oracle.  
Docs
---------
[Clickhouse Coalesce/ifNull](https://clickhouse.com/docs/en/sql-reference/functions/functions-for-nulls#coalesce) | [Oracle NVL](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/NVL.html) | [Oracle COALESCE](https://docs.oracle.com/en/database/oracle/oracle-datab …
=> fix(oracle): Revert NVL() being parsed into exp.Anonymous

sqlglot/dialects/bigquery.py, sqlglot/dialects/duckdb.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py
In BigQuery `UNNEST`ing a nested array (i.e array of structs) explodes the struct fields, e.g.:
```SQL
BQ> SELECT name, age FROM UNNEST([STRUCT('Foo' AS name, 25 AS age), STRUCT('Bar' AS name, 34 AS age)]);
name	age
----------------
Foo	 25
Bar	 34
```
On main branch the `UNNEST()` is transpiled as-is, leading to invalid DuckDB:
```SQL
D> SELECT name, age FROM UNNEST([{'name': 'Foo', 'age': 25}, {'name': 'Bar', 'age': 34}]);
Error: Binder Error: Referenced column "name" not found in FROM clause!
```
This is because DuckDB's `UNNEST()` will always unnest one level by default, so the result is the underlying struct(s):
```SQL
D> SELECT * FROM UNNEST([{'name': 'Foo', 'age': 25}, {'name': 'Bar', 'age': 34}]);
{'name': Foo, 'age': 25}    
{'name': Bar, 'age': 34}
```
This PR fixes this issue …
=> fix(duckdb): Fix exp.Unnest generation for BQ's nested arrays

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/dialects/mysql.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py, tests/dialects/test_oracle.py, tests/dialects/test_postgres.py
Fixes #3957
Docs
------
[Oracle RTRIM](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/RTRIM.html) | [Clickhouse TRIM](https://clickhouse.com/docs/en/sql-reference/functions/string-functions#trim)
=> fix: Parse LTRIM/RTRIM functions as positional exp.Trim

sqlglot/dialects/starrocks.py, sqlglot/transforms.py, tests/dialects/test_starrocks.py
Fixes #3962
This PR adds support for the following:
- Generation of arrays as `[1, 2, 3]`
- Default initialize `exp.UNNEST` to include `"unnest"` as the default column alias if not specified
- `LATERAL UNNEST` in `transforms. unnest_to_explode()`
Docs
--------
[Starrocks LATERAL Join](https://docs.starrocks.io/docs/using_starrocks/Lateral_join/)
=> fix(starrocks): exp.Array generation, exp.Unnest transpilation

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #3965
Docs
--------
[Postgres JSON testing functions](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-MISC)
=> feat(postgres): Support for IS JSON predicate

sqlglot/dialects/tsql.py, sqlglot/generator.py, tests/dialects/test_oracle.py, tests/dialects/test_tsql.py
=> Fix!: stop normalizing qualified anonymous functions

sqlglot/dialects/dialect.py, sqlglot/dialects/mysql.py, sqlglot/dialects/trino.py, sqlglot/dialects/tsql.py, sqlglot/time.py, tests/dialects/test_dialect.py, tests/dialects/test_mysql.py, tests/dialects/test_tsql.py, tests/test_time.py
1. Fix DATETIME subsecond precision on `exp.TimeStrToTime` when generating casts for literals
```
>>> parse_one("TIME_STR_TO_TIME('2020-01-01 12:13:14.123456+00:00')").dialect("mysql")
-- BEFORE
select CAST(TIMESTAMP('2020-01-01 12:13:14.123456') AS DATETIME)
> 2020-01-01 12:13:14
-- AFTER
select CAST(TIMESTAMP('2020-01-01 12:13:14.123456') AS DATETIME(6))
> 2020-01-01 12:13:14.123456
```
2. Raise a warning in the MySQL generator if it encounters an `exp.AtTimeZone` node.
```
>>> parse_one("select foo at time zone 'UTC' from tbl").sql(dialect="mysql")
-- BEFORE
'SELECT foo AT TIME ZONE 'UTC' FROM tbl'
! You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TIME ZONE 'UTC'
-- AFTER
AT TIME ZONE is not …
```
=> Fix!: mysql/tsql datetime precision, formatting, exp.AtTimeZone

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py, tests/dialects/test_duckdb.py, tests/dialects/test_spark.py
Fixes #3972
This PR addresses all 3 issues (SHA256, LIST_TRANSFORM, IGNORE NULLS) as the first 2 are trivial to fix.
Docs
----------
[DuckDB Window Functions](https://duckdb.org/docs/sql/functions/window_functions.html) | [DuckDB LIST_TRANSFORM](https://duckdb.org/docs/sql/functions/list.html#list_transformlist-lambda) | [DuckDB SHA256](https://duckdb.org/docs/sql/functions/utility.html#sha256value)
=> fix(duckdb)!: Generation of exp.SHA2, exp.Transform, exp.IgnoreNulls

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
In Clickhouse, the second-level object name is `DATABASE` instead of `SCHEMA`.
When generating the `ON CLUSTER` property, we condition on the creatable kind. For Clickhouse this is `DATABASE`, but for other dialects it is `SCHEMA`.
This PR adds `SCHEMA` to the set of creatable kinds with the `ON CLUSTER` property so it will be generated for transpiled statements.
=> Fix(clickhouse): generate ON CLUSTER for transpiled CREATE SCHEMA

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_duckdb.py
Fixes #3992
When parsing subqueries the tralining `TABLESAMPLE` is not attached to it but to the top-level `exp.Select` statement, leading to erratic behavior such as `"sample"` arg being overwritten:
```
>>> sql = "SELECT * FROM (SELECT * FROM t) AS t1 TABLESAMPLE (1 ROWS), (SELECT * FROM t) AS t2 tablesample (2 rows)"
>>> sqlglot.parse_one(sql, read='duckdb').sql('duckdb')
SELECT * FROM (SELECT * FROM t) AS t1, (SELECT * FROM t) AS t2 USING SAMPLE RESERVOIR (2 ROWS)
```
This PR addresses this by parsing TABLESAMPLE inside `_parse_subquery()`, which binds it to the respective `exp.Subquery`.
Also, the order of subquery alias vs TABLESAMPLE generation is fixed (as is done in `table_sql()`) in order to address the issue.
=> fix!: Bind TABLESAMPLE to exp.Subquery

sqlglot/dialects/hive.py, sqlglot/parser.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py
Fixes #3988
In Spark, STRUCT values/fields that are not explicitly named by the user are default initialized to:
- The column name itself, if the expression is a column
- The name `col_i` for other literals/nested structs, where `i` is the 1-based index position of the field in the struct:
```
spark-sql (default)> WITH t AS (SELECT 1 AS x, 2 AS y) SELECT STRUCT(x, 1, y AS col3, struct(5)) FROM t;
{"x":1,"col2":1,"col3":2,"col4":{"col1":5}}
```
This PR extends `kv_to_prop_eq` by also standardizing non-aliased expressions (`exp.Column`, `exp.Literal` etc) to key-value `exp.PropertyEQ` pairs with their respective name.
=> feat(spark): Default naming of STRUCT fields

sqlglot/dialects/spark2.py, tests/test_optimizer.py
Fixes #4002
Could not test HiveQL but the docs mention only `STRING` as the return type, so this PR is limited to Spark2+:
- Spark 2:
```
scala> spark.sql("select substring(cast('thing' as binary), 1, 2), substring('thing', 1, 2)")
res4: org.apache.spark.sql.DataFrame = [substring(CAST(thing AS BINARY), 1, 2): binary, substring(thing, 1, 2): string]
```
- Spark 3:
```
spark-sql (default)> select typeof(substring('thing', 1, 2)), typeof(substring(cast('thing' as binary), 1, 2));
string  binary
```
- Databricks
```
select typeof(substring(cast('thing' as binary), 1, 2)) as bin, typeof(substring('thing', 1, 2)) as str; 
bin	str
binary	string
```
Docs
--------
[Databricks SUBSTRING](https://docs.databricks.com/en/sql/language-manual/functions/substr.html) | [HiveQL Builtin …
=> fix(spark): Custom annotation for SUBSTRING()

sqlglot/generator.py, tests/dialects/test_dialect.py
=> fix(clickhouse): ensure that ALL and DISTINCT are rendered for except and intersect

sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, sqlglot/dialects/starrocks.py, sqlglot/expressions.py, sqlglot/transforms.py, tests/dialects/test_dialect.py, tests/dialects/test_starrocks.py
Fixes #3962 
Link the before PR: 
- https://github.com/tobymao/sqlglot/pull/3964
- https://github.com/tobymao/sqlglot/pull/3966
This PR adds support for the following:
Default initialize exp.UNNEST to include "unnest" as the default table alias if not specified
Added expression type of exp.Inline
use arrays_zip to merge multiple Lateral views
Added some ut to validate unnest transpile
=> fix(starrocks): exp.Unnest transpilation

sqlglot/dialects/bigquery.py, sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/dialects/presto.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/sqlite.py, sqlglot/dialects/starrocks.py, sqlglot/dialects/tsql.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Main motivation was to address https://github.com/tobymao/sqlglot/pull/4007#issuecomment-2317930198, but later down the line I realized the way we parse & generate the `DISTINCT` and `ALL` specifiers (e.g. default values) was a bit brittle. So I took a stab at refactoring this, e.g. improved "unsupported" warnings.
<details>
<summary>Click this to see references (docs etc)</summary>
BigQuery:
- Needs specifier for all set operations
- EXCEPT, DISTINCT don’t work with ALL
- https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators
ClickHouse:
- Needs specifier for UNION, unless union_default_mode is set
- INTERSECT, EXCEPT are ALL by default
- https://clickhouse.com/docs/en/sql-reference/statements/select/union
- …
=> Fix!: refactor SET OPERATION handling to set correct defaults

sqlglot/dialects/oracle.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_oracle.py
Adds support for parsing multitable insert statements in Oracle SQL. Test cases are converted from the official example SQL queries.
Ref: https://oracle-base.com/articles/9i/multitable-inserts
=> feat(oracle): Parse multitable inserts

sqlglot/dialects/mysql.py, sqlglot/dialects/presto.py, tests/dialects/test_mysql.py
Fixes #4011 
For reference:
```
Python's strftime:
- Uses %a for abbreviated weekday (Mon, Sun)
- Uses %A for full weekday (Monday, Sunday)
MySQL's format:
- Uses %a for abbreviated weekday (Mon, Sun)
- Uses %W for full weekday (Monday, Sunday)
Snowflake's format for conversion functions:
- Uses DY for abbreviated weekday (Mon, Sun)
- Does not have a full weekday element
```
This PR fixes the following issues:
1. SQLGlot would change the `%a` to `%W` during MySQL's RTT:
```
sqlglot.parse_one("SELECT DATE_FORMAT('2024-08-22 14:53:12', '%a')", read="mysql").write("mysql")
SELECT DATE_FORMAT('2024-08-22 14:53:12', '%W')
```
2. SQLGlot would transpile MySQL's `%W` (full weekday) to Snowflake's `DY` (abbreviated weekday); The correct transpilation is `%a -> DY`, whereas `%W` does not have a …
=> fix(mysql)!: Preserve roundtrip of %a, %W time formats

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
This PR aims to fix this issue:
```
-- works
SELECT TO_GEOGRAPHY(TO_GEOMETRY(TO_GEOGRAPHY('POINT(-122.306100 37.554162)')))
-- fails
SELECT CAST(TO_GEOMETRY(TO_GEOGRAPHY('POINT(-122.306100 37.554162)')) AS GEOGRAPHY)
```
This becomes problematic when casts are added programmatically (e.g. in SQLMesh).
=> Fix(snowflake)!: use TO_GEOGRAPHY, TO_GEOMETRY instead of casts

sqlglot/dialects/duckdb.py, sqlglot/dialects/presto.py, sqlglot/dialects/spark2.py, sqlglot/expressions.py, tests/dialects/test_duckdb.py, tests/dialects/test_presto.py
Presto's day_of_week is ISO standard, which is inconsistent with other engines. Concepts:
- ISO standard: Returns the ISO day of the week from x. The value ranges from 1 (Monday) to 7 (Sunday).
- Non-ISO standard: Returns the day of the week for date/timestamp (1 = Sunday, 2 = Monday, ..., 7 = Saturday).
For reference:
|  type  |   ISO function   |    Non-ISO function     |
| :----: | :--------------: | :---------------------: |
| Spark  |        -         |        dayofweek        |
| Presto | day_of_week\|dow |            -            |
| DuckDB |      isodow      | dayofweek\|weekday\|dow |
> DuckDB's dayofweek starts from 0, which is inconsistent with others. `Day of the week (Sunday = 0, Saturday = 6)`
This PR adds support for the following:
- Spark lacks ISO standard day_of_week, …
=> fix(presto): exp.DayOfWeek

sqlglot/parser.py, tests/test_parser.py
Datetime columns can be specified in ODBC format: https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/date-time-and-timestamp-literals
Our use case only requires us to be able to parse it, for us it is fine if the output sql is `DATE('yyyy-mm-dd')` instead of `{d'yyyy-mm-dd'}`.
=> fea(tsql): Parse ODBC datetime columns

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py
BigQuery's `ARRAY_TO_STRING(array_expression, delimiter[, null_text])` allows for a 3rd argument which replaces `NULL`  values with the equivalent text.
This is not available on other dialects such as DuckDB, but a custom transformation can mimic that behavior as an intermediate step:
```
[BQ] ARRAY_TO_STRING(arr, delimiter, null_text) -> [DDB] ARRAY_TO_STRING(LIST_TRANSFORM(arr, x -> COALESCE(x, null_text), delimiter) 
```
Docs
-------
[BQ ARRAY_TO_STRING](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array_to_string) | [DuckDB LIST_TRANSFORM](https://duckdb.org/docs/sql/functions/list.html#list_transformlist-lambda) | [DuckDB ARRAY_TO_STRING](https://duckdb.org/docs/sql/functions/list.html#array_to_string)
=> feat(duckdb): Transpile BQ's exp.ArrayToString

Makefile, sqlglot/expressions.py, tests/test_build.py
Add `materialized` argument when building a CTE with `with_`. It's supported in both Postgres and DuckDB:
- [Postgres](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-CTE-MATERIALIZATION)
- [DuckDB](https://duckdb.org/docs/sql/query_syntax/with.html#materialized-ctes)
See Slack thread [here](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1725243448537369).
=> Add `materialized` argument to `with_`

sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Fixes #4037
Parse `NORMALIZE(text[, form])` into the new `exp.Normalize` node. This function signature exists in BigQuery, Trino and Presto from my research; Other dialects also support normalization functions but with different signatures. 
Docs
---------
[Presto](https://prestodb.io/docs/current/functions/string.html#unicode-functions) | [Trino](https://trino.io/docs/current/functions/string.html#unicode-functions) | [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#normalize)
=> feat: Support NORMALIZE() function

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, tests/dialects/test_hive.py, tests/dialects/test_presto.py, tests/dialects/test_snowflake.py
Fixes #4039
This PR standardizes the `group` argument of `exp.RegexpExtract` across Hive hierarchy, DuckDB, Presto/Trino and Snowflake to improve it's transpilation. For quick reference:
- Presto/Trino, DuckDB and Snowflake have a default value of `0` i.e the result is the whole expression:
```
presto> select regexp_extract('abc', '(a)(b)(c)');
_col0
-------
abc
(1 row)
trino> select regexp_extract('abc', '(a)(b)(c)');
_col0
-------
abc
(1 row)
D select regexp_extract('abc', '(a)(b)(c)');
┌────────────────────────────────────┐
│ regexp_extract('abc', '(a)(b)(c)') │
│              varchar               │
├────────────────────────────────────┤
│ abc                                │
└────────────────────────────────────┘
snowflake>  select REGEXP_SUBSTR('abc', '(a)(b)(c)'); …
```
=> fix!: Canonicalize exp.RegexpExtract group default value

sqlglot/dialects/starrocks.py, sqlglot/parser.py
link: #3997 
Fixed an issue that could cause the `_parse_distributed_property` and `_parse_duplicate` functions in lambda to not be found
=> fix(starrocks): Move the parse distribute and duplicate to Parser

sqlglot/dialects/dialect.py, tests/dialects/test_bigquery.py, tests/dialects/test_duckdb.py, tests/dialects/test_mysql.py, tests/fixtures/optimizer/optimizer.sql
The builder`dialect.py::build_date_delta_with_interval()` (used in BQ & MySQL) would construct intervals with literal numbers, when in general all other major dialects tend to support only strings;  This can limit transpilation as the following (valid) query in BigQuery would be transpiled to an incorrect DuckDB counterpart:
- BigQuery
```SQL
SELECT DATE_ADD(CURRENT_DATE, INTERVAL -1 DAY)
2024-09-04
```
- BigQuery -> DuckDB on main branch:
```SQL
D SELECT CURRENT_DATE + INTERVAL -1 DAY;
Error: Parser Error: syntax error at or near "DAY"
LINE 1: SELECT CURRENT_DATE + INTERVAL -1 DAY;
```
- BigQuery -> DuckDB on this PR:
```SQL
D select CURRENT_DATE + INTERVAL '-1' DAY;
┌────────────────────────────────────────────────────────────────────────┐
│ (CURRENT_DATE + to_days(CAST(trunc(CAST('-1' …
```
=> fix!: Do not canonicalize INTERVAL values to number literals

sqlglot/dialects/bigquery.py, sqlglot/dialects/snowflake.py, tests/dialects/test_dialect.py, tests/dialects/test_oracle.py
Fixes https://github.com/TobikoData/sqlmesh/issues/3095
Docs
-------
[BigQuery TRIM](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#trim) | [BQ LTRIM](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#ltrim) | [BQ RTRIM](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#rtrim) | [Snowflake TRIM / LTRIM / RTRIM](https://docs.snowflake.com/en/sql-reference/functions/trim)
=> fix(snowflake, bigquery): Remove exp.Trim generation

sqlglot/dialects/athena.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_athena.py, tests/dialects/test_dialect.py
Athena [quotes identifiers differently depending on query type](https://docs.aws.amazon.com/athena/latest/ug/reserved-words.html), presumably because it uses different execution engines for DDL vs DML.
DDL queries (except `CREATE VIEW`) use backticks `` ` `` to quote identifiers and everything else uses double quotes `"` to quote identifiers. 
Here some examples
```
create schema if not exists "foo"; #fails
create schema if not exists `foo`; #works
create external table "foo" ("id" int) location 's3://foo/'; #fails
create external table `foo` (`id` int) location 's3://foo/'; #works
drop table if exists "foo"; #fails
drop table if exists `foo`; #works
create or replace view `foo` as select 1 as `col`; #fails
create or replace view "foo" as select 1 as "col"; #works
select 1 as `foo`; …
```
=> Fix(athena): Apply correct quoting to queries depending on type (DML or DDL)

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
=> fix(clickhouse): Remove CURRENT_TIMESTAMP from NO_PAREN_FUNCTIONS

sqlglot/__init__.py
This PR starts to export `insert` in top-level `__init__` for `sqlglot`, to make it easier to build insertion statements without having to reach into the expressions submodule.
=> Add `insert` as top-level statement

sqlglot/__init__.py, sqlglot/expressions.py, tests/test_build.py
I have a use-case around building merge statements similar to variety of other types of expressions that sqlglot can programmatically build. This PR adds a simple `merge` function allowing for dynamic construction of merge statements.
=> Feat: add merge expression builder

sqlglot/dialects/bigquery.py, tests/dialects/test_duckdb.py
=> Feat(bigquery): transpile UUID type to STRING

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/test_expressions.py
Motivation behind this PR is that nullable types are awkward to deal with: to access the wrapped type, one has to always do `data_type.this` instead of just `data_type`, meaning that the concept of nullability "leaks" into third-party code that may not care at all about it.
This refactor encodes nullability as an arg in `DataType`, so that it's less intrusive. Now, it will be taken into account when e.g. comparing data types (which can be optionally turned off by using `is_type`), and when roundtripping CH code.
=> Refactor!: treat Nullable as an arg instead of a DataType.TYPE

sqlglot/parser.py, tests/dialects/test_bigquery.py
=> Feat(bigquery): add support for the MERGE ... THEN INSERT ROW syntax

tests/dialects/test_prql.py
This PR rewrites the PRQL tests to use `validate_all()`, instead of `validate_identity()`, which will allow separation between the parser and the generator tests.
=> fix(prql): Rewrote tests to use `validate_all()` to separate the parser and generator tests.

sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #4090
Snowflake allows JSON extraction through the colon operator such as `col:ab`, and double quotes (`col:"ab"`) can optionally be used to include special characters in the key.
This will be roundtripped/transpiled to a string literal in the respective function such as `GET_PATH(..., 'ab')`  which can break queries if single quotes are in the json key.
For this reason, this PR escapes those paths at parse time in `_parse_colon_as_variant_extract()`. Note that Databricks uses backticks for special characters so it won't be affected.
=> fix(snowflake): Manually escape single quotes in colon operator

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #4108
In Snowflake, the PIVOT clause requires `FOR <value_column>` which is currently not stored in `exp.PivotAny`.
Docs
-----------
[Snowflake PIVOT](https://docs.snowflake.com/en/sql-reference/constructs/pivot)
=> feat(snowflake): Fix exp.Pivot FOR IN clause

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/snowflake.py, sqlglot/generator.py, tests/dialects/test_duckdb.py
Had this one in my backlog for some time now, figured I'd take a quick stab at it. Not super important, just a nice QOL I guess.
=> Refactor: implement decorator to easily mark args as unsupported

sqlglot/dialects/athena.py, tests/dialects/test_athena.py
Athena is really a split between two different engines. One handles _most_ DDL (Hive) and the other handles the remaining DDL and all of the DML (Trino).
Since the Athena dialect already extends the Trino dialect, this PR:
- Adds Hive tokens to the tokenizer
- Tries to figure out (at generate time) if an Expression should be handled by Hive
- If it should, the Hive Generator is used
- Otherwise, the Athena Generator is used
Note that I was unable to find an example of a query that the Athena _parser_ couldnt handle (as long as the Hive tokens were available at the tokenization stage) so only the Generator step contains the branching logic.
This approach maximizes code re-use since we already know how to deal with 99% of this syntax, just not within the same dialect
=> Feat(athena): Improve DDL query support

sqlglot/optimizer/qualify_columns.py, tests/test_optimizer.py
This PR is an optimization follow-up on https://github.com/tobymao/sqlglot/pull/4113
When processing multiple joins such as `A JOIN B JOIN C USING(col)`, we gather the columns from the previous sources (`A`, `B` etc) to expand `USING (col)` to `ON c.col = <source>.col`. Previously, this operation would happen from scratch on each iteration, which can be avoided. A few key observations:
1. The `ordered` list is constructed as a subset of `scope.selected_sources`; It can have `[0, N]` elements before the join loop
2. At each iteration, we'll add the current `join_table` to `ordered`; It is implied that `join_table` is a member of `scope.selected_sources` as it participates in the scope's `JOIN` clause(s) so (1) continues to hold
The combination of (1) and (2) means that we can avoid …
=> Refactor(optimizer): Optimize USING expansion

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py
This PR adds the `ON CLUSTER` clause to the `DELETE` statement
https://clickhouse.com/docs/en/guides/developer/lightweight-delete
=> Feat(clickhouse): support ON CLUSTER clause in DELETE

sqlglot/parser.py, tests/dialects/test_duckdb.py
@VaggelisD I think empty structs aren't allowed ([context](https://github.com/tobymao/sqlglot/commit/a2a6efb45dc0f380747aa4afdaa19122389f3c28#diff-63eb8dd82d3561bc414e3e13cf59516bd6584c5766a10072157a8a5aee4ad85fR4496-R4499)), for example `STRUCT<...>[]` is invalid BigQuery. The logic I linked was problematic because we'd consume `[]` and `values` would also be an empty list so we'd generate a `CAST(STRUCT() AS STRUCT<...>)` in DucKDB when trying to parse a type that is an array of structs.
This is needed to fix https://github.com/TobikoData/sqlmesh/pull/3129.
=> Fix: parse struct(...)[] type properly

sqlglot/__init__.py
I think it additionally makes sense to have `delete` as a top-level expression.
=> Feat: expose `sqlglot.expressions.delete` as a sqlglot module function

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_duckdb.py
=> Fix!(parser): parse lhs of := into an Identifier if it's not qualified

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/test_build.py
Now that returning is supported, add `returning` argument to the merge expression builder. This PR also makes some fixes to make the AST representation of RETURNING in merge expressions more consistent with other SQL expressions.
=> Feat!: add `returning` to merge expression builder

sqlglot/dialects/athena.py, sqlglot/expressions.py, tests/dialects/test_athena.py
- `DESCRIBE` should be routed to Hive
- `DROP VIEW` should be routed to Trino and not Hive (but every other `DROP` appears to be Hive)
- Athena expects the table location to be in the `external_location` property if the `table_type` property is `hive`, otherwise the table location should be in `location`. So i've added this logic for generating `exp.TableLocation`
- `ALTER TABLE ADD COLUMN` is invalid SQL in Athena. It needs to be `ALTER TABLE ADD COLUMS (..)`. To generate the correct version is a slightly different AST, so I subclassed `Hive.Generator` and overrode `alter_sql()`
=> Fix(athena): DDL fixes

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #4133
When parsing a `FROM` clause, we'll attempt to `_parse_table()` which in turn will call `_parse_subquery(table=True)` if the clause is wrapped. 
The nested `exp.Values` will be parsed into `this` at `_parse_select()` but the following query modifiers (e.g. joins) will not be consumed since `this` is not `exp.Query` / `exp.Table`.
This PR transforms/wraps `this` to a table to bypass this.
=> fix(parser)!: Parse VALUES & query modifiers in wrapped FROM clause

sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py
Fixes #4139
Clickhouse supports the `APPLY` query modifier:
```SQL
SELECT <expr> APPLY( <func> ) FROM [db.]table_name
```
Although `apply` is still a valid alias, we shouldn't parse it as such if it's accompanied by an `L_PAREN` as is the case here, thus the overriden `_parse_alias()` in Clickhouse:
```SQL
clickhouse> select 1 apply;
┌─apply─┐
1. │     1 │
└───────┘
clickhouse> with t as (Select 1 as col) select COLUMNS('col') apply(sum) from t;
┌─sum(col)─┐
1. │        1 │
└──────────┘
```
Note that `APPLY` can be chained, as is shown in the docs & relevant test case
Docs
---------
[Clickhouse APPLY modifier](https://clickhouse.com/docs/en/sql-reference/statements/select#apply)
=> feat(clickhouse): Add support for APPLY query modifier

sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_bigquery.py
Fixes #4146
Docs
--------
[RANGE Data Type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#range_type) | [RANGE Functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#function_list)
=> feat(bigquery): Support RANGE<T> type

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Fixes #4150
A couple existing CH tests were syntactically invalid, so I changed them. For example:
```
georges-mbp-2.home :) CREATE MATERIALIZED VIEW test_view ON CLUSTER cl1 (id UInt8) TO table1 AS SELECT * FROM test_data;
Exception on client:
Code: 62. DB::Exception: When creating a materialized view you can't declare both 'ENGINE' and 'TO [db].[table]'. (SYNTAX_ERROR)
georges-mbp-2.home :) CREATE MATERIALIZED VIEW test_view (id UInt8) TO db.table1 AS SELECT * FROM test_data;
Exception on client:
Code: 62. DB::Exception: When creating a materialized view you can't declare both 'ENGINE' and 'TO [db].[table]'. (SYNTAX_ERROR)
```
If I move the "schema" part of the 2nd one after the "TO" property, it seems to be working fine:
```
georges-mbp-2.home :) CREATE MATERIALIZED VIEW test_view TO …
```
=> Fix(clickhouse): make ToTableProperty appear right after the DDL name

sqlglot/expressions.py, tests/dialects/test_dialect.py, tests/dialects/test_presto.py, tests/fixtures/identity.sql, tests/fixtures/optimizer/tpc-ds/tpc-ds.sql, tests/test_expressions.py
SUBSTR was not getting parsed. To add parse support via `_sql_names` I replaced SUBSTR with SUBSTRING in the transpile tests and added a distinct test in the test_functions method to ensure that they both get parsed as Substring.
=> feat: Add SUBSTR Support

.github/workflows/python-publish.yml
Been seeing this weird situation for some time now, where the `should_deploy_sqlglotrs` script incorrectly shows that `Cargo.toml` changed in the same commit as the one being tagged. E.g., this corresponds to the latest version bump:
One possible cause is documented in the `actions/checkout@v3` repo:
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags. Refer [here](https://docs.github.com/actions/using-workflows/events-that-trigger-workflows) to learn which commit $GITHUB_SHA points to for different events.
If we don't have full history, then the script can't really look into past commits to determine whether the `Cargo.toml` file was modified since the last deployment. This PR updates …
=> Chore: fetch all history to allow workflow script to skip sqlglotrs deployments

sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py, tests/dialects/test_duckdb.py
Fixes #4157
As `COLUMNS(...)` is a function that can be used in different contexts besides the projection list, this PR adds `exp.Columns` which parses the function call _and_ the following `APPLY(...)` functions. 
The `APPLY` parsing in `clickhouse.py::_parse_expression()` is left as is to accommodate `exp.Star` and potentially any other expression that can utilize `APPLY` in the selections.
=> fix(clickhouse)!: Generalize COLUMNS(...) APPLY

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes #4159 
This PR adds support for the Postgres `OVERLAY` function:
```
OVERLAY(string PLACING string FROM int [FOR int])
```
Docs
----------
[Postgres OVERLAY](https://www.postgresql.org/docs/9.1/functions-string.html)
=> feat(postgres): Support OVERLAY function

sqlglot/dialects/spark2.py, tests/test_optimizer.py
This is a follow up on https://github.com/tobymao/sqlglot/pull/4004, as during my investigation for `SUBSTRING` I came across other Spark string functions (`CONCAT`, `LPAD`, `RPAD`) which are input type dependent.
Although it's not documented clearly, these functions will return a `BINARY` only if all their "string" operands are `BINARY`, otherwise they return a `STRING`:
```
spark-sql (default)> with tbl as (select cast('test' as binary) as bin_col, 'str' as str_col) 
select 
typeof(concat(bin_col, bin_col)), 
typeof(concat(str_col, bin_col)), 
typeof(concat(bin_col, str_col)), 
typeof(concat(str_col, str_col)) 
from tbl;
binary  string  string  string
```
```
spark-sql (default)> with tbl as (select cast('test' as binary) as bin_col, 'str' as str_col) 
select 
typeof(lpad(bin_col, 1, …
```
=> feat(spark): Custom annotation for more string functions

sqlglot/dialects/sqlite.py
I'm currently seeing `DATEDIFF unsupported for '{unit}'` in my logs which is unhelpful.
=> Fix unsupported message in datediff_sql

sqlglot/dialects/athena.py, tests/dialects/test_athena.py
It turns out Athena table properties are case sensitive on the Trino engine and need to be lowercase.
```
CREATE TABLE "test_table" WITH (PARTITIONED_BY=ARRAY['ds'], ...) AS SELECT ...
```
Fails with `Table properties [PARTITIONED_BY] are not supported.`
```
CREATE TABLE "test_table" WITH (partitioned_by=ARRAY['ds'], ...) AS SELECT ...
```
Succeeds
=> Fix(athena): Case sensitivity in CTAS property names

sqlglot/generator.py, tests/dialects/test_bigquery.py
Fixes #4170
BigQuery does not allow `ASC NULLS LAST` and `DESC NULLS FIRST` ordering in aggregate functions:
```
with colors as (SELECT 1 AS id, 'red' AS color) SELECT color, array_agg(id ORDER BY id ASC NULLS LAST) AS ids FROM colors GROUP BY 1
NULLS LAST not supported with ascending sort order in aggregate functions.
```
```
with colors as (SELECT 1 AS id, 'red' AS color) SELECT color, array_agg(id ORDER BY id DESC NULLS FIRST) AS ids FROM colors GROUP BY 1
NULLS FIRST not supported with descending sort order in aggregate functions.
```
Note that BigQuery is the only dialect with `NULL_ORDERING_SUPPORTED = False` so this PR uses this as a proxy to handle this case.
=> fix(bigquery): Do not generate null ordering on agg funcs

sqlglot/dialects/redshift.py, tests/dialects/test_duckdb.py
Fixes #4169
Redshift supports [implicit unnest of an array](https://stackoverflow.com/a/72870096) but not an `UNNEST` function as other dialects. This PR adds unsupported warnings for the following cases:
- If an `exp.Unnest` is used with a _known_ non-array type
- If an `exp.Unnest` is not used under a `FROM` or `JOIN` clause
- If we attempt to transpile an `exp.Explode` node coming from Spark/DuckDB etc.
=> fix(redshift): Add unsupported warnings for UNNEST

tests/fixtures/optimizer/annotate_functions.sql, tests/test_optimizer.py
This PR introduces the `annotate_functions.sql` fixture file which abstracts away the type inference & check of functions, further supporting dialect-aware annotation & it's testing.
=> feat(optimizer): Fixture file for function annotations

sqlglot/dialects/spark.py, sqlglot/generator.py, tests/dialects/test_spark.py
[Public Slack context](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1727776434049859)
In Spark `TRY_ELEMENT_AT` is 1-based while the bracket notation is 0-based:
```
spark-sql (default)> SELECT ARRAY(1, 2, 3)[0], TRY_ELEMENT_AT(ARRAY(1, 2, 3), 1);
1       1
```
This PR fixes this discrepancy by manually adding a 1-offset during parse & generation time.
=> fix(spark): Offset TRY_ELEMENT_AT index by one

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
=> fix: rename SHA function to SHA1 for DuckDB

sqlglot/tokens.py, tests/dialects/test_duckdb.py
Fixes #4187
The `a GLOB b` operator is an alias of `a ~~~ b`:
```SQL
D SELECT 'best.txt' GLOB '*.txt';
┌──────────────────────────┐
│ ('best.txt' ~~~ '*.txt') │
├──────────────────────────┤
│ true                     │
└──────────────────────────┘
```
Docs
--------
[DuckDB GLOB](https://duckdb.org/docs/sql/functions/pattern_matching.html#globbing)
=> feat(duckdb): Parse ~~~ as GLOB

sqlglot/generator.py, tests/dialects/test_tsql.py
Only related SO thread I found is [this](https://stackoverflow.com/questions/439495/how-can-i-escape-square-brackets-in-a-like-clause) one, but I played using T-SQL and concluded that `[` after the opening bracket doesn't need to be escaped, but `]` does because it needs to be disambiguated from the closing delimiter:
```
1> SELECT 1 AS [[x]]], 1 AS "[y]"
2> GO
[x]         [y]        
----------- -----------
1           1
```
=> Fix: properly escape closing identifier delimiters

sqlglot/dialects/presto.py, sqlglot/dialects/trino.py, sqlglot/expressions.py, tests/dialects/test_trino.py
Fixes #4200
This PR adds parsing support for Trino's `JSON_QUERY(...)` which is a more powerful version of `JSON_EXTRACT(...)`.
For this matter, `exp.JSONExtract` node is reused, but to differentiate between the two a new arg is introduced; This is also required because Presto's `jsonextract_sql` has the `variant_access` logic which must be preserved for Trino.
Docs
---------
[JSON_QUERY](https://trino.io/docs/current/functions/json.html#json-query) | [JSON_EXTRACT](https://trino.io/docs/current/functions/json.html#json_extract)
=> feat(trino): Support JSON_QUERY

sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/generator.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_duckdb.py, tests/dialects/test_postgres.py
Fixes #4189
The `^@` operator is an alias of the `STARTS_WITH(a, b)` function:
```SQL
──────────────┬────────────────────┬─────────┬──────────────────┬──────────────────┬──────────┬──────────────┬────────────────────────┬────────────┐
│ database_name │ database_oid │ schema_name │ function_name │ function_type │                   description                    │ comment │ tags │ return_type │       parameters        │  parameter_types   │ varargs │ macro_definition │ has_side_effects │ internal │ function_oid │        example         │ stability  │
├───────────────┼──────────────┼─────────────┼───────────────┼───────────────┼──────────────────────────────────────────────────┼─────────┼──────┼─────────────┼─────────────────────────┼────────────────────┼─────────┼──────────────────┼───────── …
```
=> feat(duckdb): Add more Postgres operators

sqlglot/transforms.py, tests/dialects/test_mysql.py
The union syntax cause deduplication of rows from source tables, to achieve the intended result but avoid unintended deduplication I changed the logic to a left join + an anti join(right join + not exists) with union all.
This should be more in line with the behaviour of FULL OUTER JOINs since it keeps duplicate rows that would be present if there are duplicate rows in the two joined tables.
https://en.wikipedia.org/wiki/Join_%28SQL%29#Full_outer_join
Other possible ways to achieve this are:
- filtering for NULLS on joining condition columns in the right side of the union
- use a pure anti-join without the right join syntax (this would require table identifiers on columns selected) 
- use inner joins + more anti-joins (same requirements as the previous one)
=> Fix: Unexpected row deduplication using eliminate_full_outer_join

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql, tests/test_optimizer.py
This is a follow up to https://github.com/tobymao/sqlglot/pull/4201
Several BigQuery functions such as `CEIL(x)`, `FLOOR(x)` etc will borrow the input type _unless_ that is an `INT`, in which case a `FLOAT64` (i.e `DataType.DOUBLE`) is returned. 
To mimic this behavior, this PR adds a new type annotation helper.
Note: The function `TRUNC(X)` is not currently supported by SQLGlot so once that's added, it must also be annotated accordingly.
Docs
-------
[BQ Mathematical Functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions)
=> feat(bigquery): Native annotations for more math functions

sqlglot/expressions.py, tests/test_build.py
Improve ergonomics of UPDATEs:
- Add builder methods to Update class so it can be constructed incrementally in the same way a Select
- `exp.update` changes:
- Add a `with_` arg so updates with CTEs can be created in one-shot without subsequent need  to `.set(...)` the With clause
- Make the `properties` arg optional, so `set_` builder method can be used with an AST (`exp.update("tbl").set_(set_expr)` ) instead of forcing specification as a `dict`
=> Feat: add builder methods to exp.Update and add with_ arg to exp.update

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/test_transpile.py
Fixes #4216
This PR addresses 2 points:
1. On main, comments on SELECT & it's CTEs bubble up:
```SQL
sql = """
-- comment at the top
with tbl as (select 1)
-- comment for final select
select * from tbl1
"""
sqlglot.parse_one(sql).sql(pretty=True)
/* comment for final select */
/* comment at the top */
WITH tbl AS (
SELECT
1
)
SELECT
*
FROM tbl1
```
After this PR, the `SELECT` generator will differentiate the two by attaching it's comments earlier:
```SQL
/* comment at the top */
WITH tbl AS (
SELECT
1
)
/* comment for final select */
SELECT
*
FROM tbl1
```
2. Comments before the CTE commas are now preserved and attached to the next node, as is shown in the test case
=> Fix: Attach CTE comments before commas

sqlglot/dialects/tsql.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py
Fixes #4222
PS: I believe we could also consolidate `exp.RenameColumns` into `exp.AlterRename`, is this worth looking in this PR / soon?
=> Refactor!: Rename exp.RenameTable to exp.AlterRename

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
Follow up on https://github.com/tobymao/sqlglot/pull/4212 to increase native BQ annotation.
According to the docs, these `STRING` / `BYTES` (i.e `BINARY`) functions are input type dependent:
1. CONCAT 
2. LEFT / RIGHT
3. LOWER / UPPER
4. LPAD / RPAD
5. LTRIM / RTRIM / TRIM 
6. REGEXP_EXTRACT, REGEXP_REPLACE, REGEXP_SUBSTR, REPEAT, REPLACE, REVERSE, SUBSTR, TRANSLATE
7. REGEXP_EXTRACT_ALL, SPLIT (these return `ARRAY<STRING>` / `ARRAY<BYTES>` instead of scalar values)
To limit the scope, this PR addresses (1) - (5) and the next one will cover the rest.
Note: Unlike Spark, BQ functions with multiple inputs such as `CONCAT` do not allow mixed types so it's sufficient to annotate according to one of them e.g. `this`  
Docs
--------
[BQ String …
=> feat(bigquery): Native annotations for string functions (1)

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This is a follow up to https://github.com/tobymao/sqlglot/pull/4231
This PR addresses the remaining string functions with the exception of `REGEXP_EXTRACT_ALL`, `REVERSE`, `REPLACE`  and `TRANSLATE` as they're not supported by SQLGlot yet.
Docs
-------
[BQ String Functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions)
=> feat(bigquery)!: Native annotations for string functions (2)

sqlglot/dialects/mysql.py, sqlglot/parser.py, tests/dialects/test_mysql.py
Currently EXPLAIN is not supported in sqlglot.dialects.mysql. 
Because 'The [DESCRIBE](https://dev.mysql.com/doc/refman/8.4/en/describe.html) and [EXPLAIN](https://dev.mysql.com/doc/refman/8.4/en/explain.html) statements are synonyms.', this pr supports EXPLAIN by treat it as DESCRIBE
=> feat: support EXPLAIN in mysql

sqlglot/optimizer/simplify.py, tests/fixtures/optimizer/simplify.sql
We're not simplifying negations of `SubqueryPredicate`s correctly today:
```python
>>> from sqlglot.optimizer.simplify import simplify
>>>
>>> sql = "select not (2 not in (select 2 union all select 3))"  # gets converted into NEQ(2, ALL(...))
>>> 
>>> expr = parse_one(sql, "snowflake")
>>> expr.sql("snowflake")
'SELECT NOT (2 <> ALL (SELECT 2 UNION ALL SELECT 3))'
>>> simplify(expr.copy()).sql("snowflake")
'SELECT 2 = ALL (SELECT 2 UNION ALL SELECT 3)'
```
Simply flipping the `<>` into `=` is not enough.
=> Fix(optimizer): handle subquery predicate substitution correctly in de morgan's rule

sqlglot/parser.py, tests/dialects/test_duckdb.py
I realized that the fix in #4239 was actually incomplete, e.g. we currently fail to parse `val IN tbl.col`, because the column is qualified. This is valid DuckDB, for instance:
```
D create table foo (flags varchar[]);
D insert into foo values (['red', 'green']);
D select * from foo where 'red' in flags;
┌──────────────┐
│    flags     │
│  varchar[]   │
├──────────────┤
│ [red, green] │
└──────────────┘
D select * from foo where 'red' in foo.flags;
┌──────────────┐
│    flags     │
│  varchar[]   │
├──────────────┤
│ [red, green] │
└──────────────┘
```
=> Fix(parser): parse a column reference for the RHS of the IN clause

sqlglot/expressions.py, tests/dialects/test_duckdb.py
Not treating `Explode` as a `UDTF` seems like a weird decision, provided that it _is_ a table function (e.g. it's used to represent `EXPLODE` in Spark and `UNNEST` in DuckDB). It also leads to more complex code that needs to deal with `UDTF`s ([example](https://github.com/TobikoData/sqlmesh/blob/main/sqlmesh/core/model/definition.py#L2371-L2373)).
I searched a bit, and I found that the `Explode` expression was introduced in [this](https://github.com/tobymao/sqlglot/commit/5e6939c14e860c661c90944215fe2aafb52736ae) commit. [There was no `UDTF` node at the time](https://github.com/tobymao/sqlglot/blob/5e6939c14e860c661c90944215fe2aafb52736ae/sqlglot/expressions.py), so my hunch is that this was simply overlooked until now.
=> Refactor!: make Explode a UDTF subclass

sqlglot/optimizer/qualify_columns.py, tests/test_optimizer.py
[Public Slack context](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1728475163266849)
This is a follow up fix on https://github.com/tobymao/sqlglot/pull/3699, which introduced early alias expansion for BQ and Clickhouse.
As a recap, BigQuery allows `GROUP BY` to refer to `SELECT` aliases. From the [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#group_by_values): 
_GROUP BY clauses may also refer to aliases. If a query contains aliases in the SELECT clause, those aliases override names in the corresponding FROM clause._
So the early expansion was necessary to replace the references with the aliased expressions instead of qualifying them, as is explained in the PR. However, it seems that BQ allows this only for grouped _names_ and not _expressions_: …
=> fix(bigquery): Early expand only aliased names in GROUP BY

sqlglot/optimizer/qualify.py, sqlglot/optimizer/qualify_columns.py, tests/fixtures/optimizer/qualify_columns.sql
Wasn't sure whether to reuse the existing `validate_qualify_columns` flag name, or to create a new one. My thinking is validate_qualify_columns False = best effort qualification, and True = required qualification. This matches that behavior - let me know what you think.
=> Feat: support non-strict qualify_columns

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/presto.py, tests/dialects/test_hive.py
Fixes #4247
This PR reuses the existing Presto/Trino `LATERAL VIEW EXPLODE -> CROSS JOIN UNNEST` transformation in DuckDB too, e.g:
```Python
>>> sql = "WITH tmp_table(arr1, arr2) AS (SELECT * FROM VALUES (ARRAY(1,2), ARRAY('a','b'))) SELECT elem1, elem2 FROM tmp_table LATERAL VIEW EXPLODE(arr1) a1 AS elem1 LATERAL VIEW EXPLODE(arr2) a2 AS elem2"
>>> sqlglot.parse_one(sql, dialect="spark").sql("duckdb")
WITH tmp_table(arr1, arr2) AS (SELECT * FROM (VALUES ([1, 2], ['a', 'b']))) SELECT elem1, elem2 FROM tmp_table CROSS JOIN UNNEST(arr1) AS a1(elem1) CROSS JOIN UNNEST(arr2) AS a2(elem2)
```
- Spark:
```SQL
spark-sql (default)> WITH tmp_table(arr1, arr2) AS (
>   SELECT * FROM VALUES (ARRAY(1,2), ARRAY('a','b'))
> )
> SELECT elem1, elem2
> FROM
>   tmp_table
>   LATERAL VIEW EXPLODE(arr1) a1 …
```
=> feat(duckdb): Transpile Spark's LATERAL VIEW EXPLODE

sqlglot/dialects/presto.py, sqlglot/dialects/trino.py, tests/dialects/test_trino.py
Fixes #4250
Before this PR, Trino would transpile `exp.GroupConcat` into `ARRAY_JOIN(ARRAY_AGG(...))`, which was added in https://github.com/tobymao/sqlglot/issues/2331. For Presto, this [was the recommended way](https://stackoverflow.com/questions/44142356/presto-equivalent-of-mysql-group-concat).
However, at some point `LISTAGG` [was supported](https://github.com/trinodb/trino/issues/4835) :
```
LISTAGG( expression [, separator] [ON OVERFLOW overflow_behaviour])
WITHIN GROUP (ORDER BY sort_item, [...]) [FILTER (WHERE condition)]
```
An example:
```SQL
trino> WITH t AS (SELECT 'a' AS id UNION ALL SELECT 'b' AS id) SELECT LISTAGG(DISTINCT id, ',') WITHIN GROUP (ORDER BY id ASC) FROM t;
_col0
-------
a,b
(1 row)
```
This PR adds support for `LISTAGG` by:
- Reusing …
=> feat(trino): Support for LISTAGG function

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
This PR adds support for Snowflake's `TRY_TO_TIMESTAMP(...)` function for the following variants:
| Variant  | Behavior |
| ------------- | ------------- |
| TRY_TO_TIMESTAMP(string_expr) | ✅  Canonicalized into a`TRY_CAST(<string_expr> AS TIMESTAMP)` expression  |
| TRY_TO_TIMESTAMP(string_expr, format)  | ✅  Parsed into an `exp.StrToTime` node |
| TRY_TO_TIMESTAMP(col) | ❌  Parsed into exp.Anonymous  |
| TRY_TO_TIMESTAMP('integer')  | ❌  Parsed into exp.Anonymous |
The behavior of the last 2 variants is because it's not trivial to transpile them accordingly:
-  For the `<integer>` version, dialects like DuckDB don't offer functions with `TRY` semantics for string -> unix time conversion
-  For the `<col>` case we'd have to dissect the data to decide which is the matching variant
Docs …
=> feat(snowflake)!: Support TRY_TO_TIMESTAMP function

sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, tests/dialects/test_clickhouse.py, tests/fixtures/optimizer/qualify_columns.sql
Fixes #4254
Reference: https://clickhouse.com/docs/en/sql-reference/statements/select/array-join
=> Fix(clickhouse)!: dont parse right-hand side operands of ARRAY JOIN as Tables

sqlglot/dialects/bigquery.py, tests/dialects/test_dialect.py
Fixes #4275 .
This PR adds support for Bigquery's `EDIT_DISTANCE(...)` (Levinshtein) function for the following variants:
It implements the `EDIT_DISTANCE(col1, col2)` but not the `EDIT_DISTANCE(col1, col2, max_distance => max_distance_value)` variant.
[Bigque EDIT_DISTANCE](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#edit_distance) | [DuckDB TEXT SIMILARITIES Functions](https://duckdb.org/docs/sql/functions/char.html#text-similarity-functions)
=> feat(bigquery): support EDIT_DISTANCE (Levinshtein) function

sqlglot/optimizer/eliminate_subqueries.py, sqlglot/optimizer/merge_subqueries.py
Follow up on https://github.com/tobymao/sqlglot/pull/4266
=> fix(optimizer)!: Add type hints for optimizer rules eliminate & merge subqueries

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Prior to this change, something like:
```
CREATE TABLE IF NOT EXISTS foo AS (WITH cte1 AS (...), cte2 AS (...) SELECT ... FROM cte1... etc)
```
Would be turned into:
```
WITH cte1 AS (...), cte2 AS (...) IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_name = 'foo') EXEC('SELECT * INTO foo FROM (SELECT ... FROM cte1...etc) AS temp')
```
Instead of:
```
IF NOT EXISTS (SELECT * FROM information_schema.tables WHERE table_name = 'foo') 
EXEC('WITH cte1 AS (...), cte2 AS (...) SELECT * INTO foo FROM (SELECT ... FROM cte1...etc) AS temp')
```
The problem is that the CTE's were being removed from the sql literal in `EXEC` and being prepended to the `IF NOT EXISTS` check.
This caused the following error to be thrown: `SQL Error [156] [S0001]: Incorrect syntax near the keyword …
=> Fix(tsql): Keep CTE's attached to the query when emulating IF NOT EXISTS

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py
This PR adds support for the 6-arg version of `TIMESTAMP_NTZ_FROM_PARTS(...)` by adding it as an alias for the already supported `TIMESTAMP_FROM_PARTS(...)`; This is because by default `TIMESTAMP_*` functions map to `TIMESTAMP_NTZ_*` unless changed by the user through `TIMESTAMP_TYPE_MAPPING`.
Three outstanding questions:
1. This family of functions also expose the 2-arg version `TIMESTAMP_FROM_PARTS( <date_expr>, <time_expr>)`. Should we add them in this PR too?
2. For future reference, to support the other variations as well such as `TIMESTAMP_LTZ_FROM_PARTS`, should we create separate nodes or add an `arg` that stores the variant type?
3. As an extension of (2) and a thought for the future, although it simplifies things now, we probably shouldn't tie `TIMESTAMP_NTZ` to `TIMESTAMP` …
=> feat(snowflake)!: Add support for TIMESTAMP_NTZ_FROM_PARTS

sqlglot/optimizer/annotate_types.py, tests/test_optimizer.py
Fixes #4261
Consider this repro:
```Python
>>> sql = """
WITH t AS (
SELECT NULL AS col
UNION ALL
SELECT 'a' AS col
UNION ALL
SELECT NULL AS col
)
SELECT * FROM t;
"""
>>> optimized = sqlglot.optimize(sql)
>>> optimized.selects[0].type
DataType(this=Type.NULL)
```
To annotate this query, `annotate_scope` will be called for each scope:
```
1. Scope<SELECT NULL AS "col">
2. Scope<SELECT 'a' AS "col">
3. Scope<SELECT NULL AS "col" UNION ALL SELECT 'a' AS "col">
4. Scope<SELECT NULL AS "col">
5. Scope<SELECT NULL AS "col" UNION ALL SELECT 'a' AS "col" UNION ALL SELECT NULL AS "col">
6. Scope<WITH "t" AS (SELECT NULL AS "col" UNION ALL SELECT 'a' AS "col" UNION ALL SELECT NULL AS "col") SELECT "t"."col" AS "col" FROM "t" AS "t">
```
The annotation fails because:
1. Set operations are processed …
=> fix(optimizer)!: Fix chained exp.SetOperation type annotation

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py, tests/dialects/test_spark.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for BQ's `STRING(...)` function, which turns input expressions into `STRING`s. There are two supported versions:
1. JSON based: `STRING(json_expr)`
2. TIMESTAMP based: `STRING(timestamp_expression[, time_zone])`
Both variants are transpiled to `CAST(... AS VARCHAR)` for all other dialects; For the (2) variant with `time_zone` supplied, the timestamp is passed through `exp.ConvertTimezone` for the timezone conversion:
```SQL
bigquery> SELECT STRING("2008-12-25 15:30:00", "America/New_York") AS string;
2008-12-25 10:30:00-05
snowflake> SELECT CAST(CONVERT_TIMEZONE('UTC', 'America/New_York', '2008-12-25 15:30:00') AS VARCHAR);
2008-12-25 10:30:00.000
duckdb> SELECT CAST(CAST('2008-12-25 15:30:00' AS TIMESTAMP) AT TIME ZONE 'UTC' AT TIME ZONE 'America/New_York' AS TEXT) …
```
=> feat(bigquery)!: Add support for STRING function

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Fixes #4285
Consider the query:
```SQL
WITH data AS (SELECT 'a' AS name) 
SELECT name FROM data 
WHERE (SELECT DISTINCT name FROM data) IS NOT NULL;
```
This will be roundtripped across all dialects as:
```SQL
WITH data AS (SELECT 'a' AS name) 
SELECT name FROM data 
WHERE NOT (SELECT DISTINCT name FROM data) IS NULL;
```
Which invalid for Clickhouse in particular. Wrapping the `IS` expression restores the functionality:
```SQL
ch> with data as (select 'a' as name) SELECT name FROM data WHERE NOT (SELECT DISTINCT name FROM data) IS NULL;
Expected one of: token, Dot, Comma, ClosingRoundBracket, OR, AND, IS NOT DISTINCT FROM, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS
ch> with data as …
```
=> fix(clickhouse): Wrap subquery if it's LHS of IS NOT NULL

sqlglot/dialects/sqlite.py, tests/dialects/test_sqlite.py
Fixes #4291
The following issues appear throughout these cases are the following:
1. `UNIQUE` can be used as a standalone column constraint:
```SQL
CREATE TABLE foo (bar TEXT UNIQUE REFERENCES "baz")
```
However, `parser.py::_parse_unique()` can end up consuming the following constraints, so this PR overrides it to add the appropriate lookahead.
2. ~Implicit aliases can be used in column definitions, e.g:~
```SQL
CREATE TABLE foo (bar baz TEXT) -> fine
CREATE TABLE foo (bar AS baz TEXT) -> error
```
~Which is solved by overriding `parser.py::_parse_field_def()` to also parse the alias & generating it back without the `AS` prefix.~
=> fix(sqlite): Fix UNIQUE parsing

sqlglot/dialects/clickhouse.py, sqlglot/tokens.py, sqlglotrs/src/tokenizer.rs, tests/dialects/test_dialect.py
Our current assumptions around identifier delimiter escaping were wrong -- most importantly, we used `"` as an escape for all dialects, which isn't correct. I investigated what different dialects do and this is what I came up with:
```
ClickHouse, Databricks, Hive, MySQL, Spark, SQLite: `c```
DuckDB, Postgres, Presto, Trino, Redshift, Snowflake, SQLite, T-SQL: "x"""
ClickHouse also allows:  "c\", `c\``
T-SQL also allows: [[x]]]
BigQuery, Oracle don't support escaping identifier delimiters
```
As you can see, the most common rule is that the escape character is identical to the closing identifier delimiter. ClickHouse is an exception, because it also allows `\` to be used as an escape regardless of the surrounding context.
=> Fix: improve support for identifier delimiter escaping

sqlglot/diff.py, tests/test_diff.py
This PR was motivated by the following case:
```python
>>> from sqlglot import diff, parse_one
>>>
>>> e1 = parse_one("select a as a, b as b from t where concat('a', 'b') = 'ab'")
>>> e2 = parse_one("select a as a from t where concat('a', 'b', b) = 'ab'")
>>>
>>> for edit in diff(e1, e2, matchings=[(e1, e2)], delta_only=True):
...     print(edit)
...
Remove(expression=Alias(
this=Column(
this=Identifier(this=b, quoted=False)),
alias=Identifier(this=b, quoted=False)))
```
Notice how there's no information in the edit script about `b` being moved within the `concat` call. It looks like there were a few tests in `test_diff.py` that missed similar `Move` edits, so I updated them accordingly.
=> Fix: handle a Move edge case in the semantic differ

sqlglot/generator.py, tests/dialects/test_spark.py
Fixes #4300
https://github.com/tobymao/sqlglot/pull/4033 was introduced to solve the transpilation of `ARRAY_AGG` from dialects that exclude `NULL` values (e.g. Spark) to those that don't (e.g. DuckDB) by adding a `FILTER` on it.
However, this (1) doesn't have to be added if the input is not a column and (2) even if it was kept as a no-op, DuckDB seems to hit on internal errors as is reported on the issue.
=> fix(generator): Add NULL FILTER on ARRAY_AGG only for columns

sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/expressions.py, tests/dialects/test_postgres.py
Fixes #4299
Postgres's `JSONB_EXISTS` is not properly documented but it can be queried & used as following:
```SQL
vaggelisd=# select proname,prosrc from pg_proc where proname= 'jsonb_exists';
proname    |    prosrc
--------------+--------------
jsonb_exists | jsonb_exists
(1 row)
vaggelisd=# \sf jsonb_exists
CREATE OR REPLACE FUNCTION pg_catalog.jsonb_exists(jsonb, text)
RETURNS boolean
LANGUAGE internal
IMMUTABLE PARALLEL SAFE STRICT
AS $function$jsonb_exists$function$
vaggelisd=# SELECT JSONB_EXISTS('{"a": [1,2,3]}', 'a');
jsonb_exists
--------------
t
(1 row)
vaggelisd=# SELECT JSONB_EXISTS('{"a": [1,2,3]}', 'b');
jsonb_exists
--------------
f
(1 row)
```
Docs
-----------
[Postgres JSONB_EXISTS](https://stackoverflow.com/questions/43862936/postgresql-where-in-jsonb) | [Postgres JSON …
=> feat(postgres): Support JSONB_EXISTS

sqlglot/dialects/databricks.py, sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, sqlglot/expressions.py, sqlglot/transforms.py, tests/dialects/test_databricks.py, tests/dialects/test_hive.py, tests/dialects/test_postgres.py, tests/fixtures/identity.sql
Fixes #4298
In Hive hierarchy `ANY` is an aggregate function for `BOOLEAN` expressions and not an array/subquery operator as is in other dialects, meaning that the following transpiled queries do not work:
```Python
>>> sqlglot.parse_one("WITH t AS (SELECT ARRAY[1, 2, 3] AS col) SELECT * FROM t WHERE 1 <= ANY(col)", dialect="postgres").sql("spark")
'WITH t AS (SELECT ARRAY(1, 2, 3) AS col) SELECT * FROM t WHERE 1 <= ANY(col)'
spark-sql (default)> WITH t AS (SELECT ARRAY(1, 2, 3) AS col) SELECT * FROM t WHERE 1 <= ANY(col);
[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "any(col)" due to data type mismatch: Parameter 1 requires the "BOOLEAN" type, however "col" has the type "ARRAY<INT>".; line 1 pos 68;
...
```
However, Spark2+ supports the `EXISTS()` function which can process …
=> feat(spark)!: Transpile ANY to EXISTS

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py
=> Fix(clickhouse): improve parsing of WITH FILL ... INTERPOLATE

sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py, tests/dialects/test_presto.py
BigQuery supports `TIMESTAMP(<expr>[, zone])` function for `TIMESTAMP` construction. Today, this is parsed in BQ and transpiled to other dialects (DuckDB, Presto/Trino) through the `no_timestamp_sql` helper which generates either a cast (1-arg version) or an `AT TIME ZONE` expression if a `zone` is present (2-arg version).
However, the 2-arg version transpilation does not seem correct; BigQuery's `TIMESTAMP`s are always stored at UTC which is not the case for other dialects. In main branch, these are the transpilations & their results today:
```SQL
bigquery> SELECT TIMESTAMP('2008-12-25 15:30:00', 'America/Los_Angeles')
2008-12-25 23:30:00 UTC
presto> SELECT AT_TIMEZONE(CAST('2008-12-25 15:30:00' AS TIMESTAMP), 'America/Los_Angeles');
2008-12-25 07:30:00.000 America/Los_Angeles
duckdb> …
```
=> feat(snowflake)!: Transpile BQ's TIMESTAMP() function

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
- BigQuery:
```SQL
SELECT TIMESTAMP_ADD(TIMESTAMP "2008-12-25 15:30:00+00", INTERVAL 10 MINUTE)
2008-12-25 15:40:00 UTC
```
- Snowflake:
```SQL
SELECT TIMESTAMPADD(MINUTE, '10', CAST('2008-12-25 15:30:00+00' AS TIMESTAMPTZ))
2008-12-25 15:40:00.000 +0000
```
Docs
--------
[BigQuery TIMESTAMP_ADD](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_add) | [Snowflake TIMESTAMPADD](https://docs.snowflake.com/en/sql-reference/functions/timestampadd)
=> feat(snowflake): Transpile exp.TimestampAdd

sqlglot/dialects/clickhouse.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/mysql.py, sqlglot/dialects/oracle.py, sqlglot/dialects/postgres.py, sqlglot/dialects/presto.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/spark.py, sqlglot/dialects/sqlite.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_clickhouse.py, tests/dialects/test_dialect.py, tests/dialects/test_duckdb.py, tests/dialects/test_snowflake.py
Fixes #4315
This PR adds support for `MEDIAN(<expr>)` across major dialects (DuckDB, Spark3, Databricks, Snowflake, Redshift, Clickhouse, Oracle). For the dialects that don't support it, the transpilation remains as `PERCENTILE_CONT(<expr>, 0.5)` which is a best-effort attempt.
Note: BigQuery supports `PERCENTILE_CONT(...)` only as a window function
Docs
---------
- [Oracle MEDIAN](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/MEDIAN.html) | [DuckDB](https://duckdb.org/docs/sql/functions/aggregates.html#medianx) | [Clickhouse MEDIAN/QUANTILE](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantile#quantile) | [Redshift MEDIAN](https://docs.aws.amazon.com/redshift/latest/dg/r_MEDIAN.html) | [Spark/Databricks …
=> feat!: Support MEDIAN() function

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
Snowflake does not have a `TIMESTAMP_SUB` function, but it's `TIMESTAMP_ADD` can be reused by negating the value. After this PR, the transpilation is the following:
- BigQuery:
```SQL
WITH t AS (SELECT 20 AS col)
SELECT
TIMESTAMP_SUB(TIMESTAMP "2008-12-25 15:30:00+00", INTERVAL 10 MINUTE),
TIMESTAMP_SUB(TIMESTAMP "2008-12-25 15:30:00+00", INTERVAL col MINUTE)
FROM t;
2008-12-25 15:20:00 UTC | 2008-12-25 15:10:00 UTC
```
- Snowflake:
```SQL
WITH t AS (SELECT 20 AS col) 
SELECT 
TIMESTAMPADD(MINUTE, -10, CAST('2008-12-25 15:30:00+00' AS TIMESTAMPTZ)), 
TIMESTAMPADD(MINUTE, -col, CAST('2008-12-25 15:30:00+00' AS TIMESTAMPTZ)) 
from t;
2008-12-25 15:20:00.000 +0000 | 2008-12-25 15:10:00.000 +0000
```
Docs
---------
[BQ TIMESTAMP_SUB](https://cloud.google.com/bigquery/docs/reference/standard-sq …
=> feat(snowflake): Transpile exp.TimestampSub

sqlglot/dialects/oracle.py, sqlglot/expressions.py, tests/dialects/test_oracle.py
Fixes #4321
Time unit normalizations such as unabbreviation (e.g. `Q` -> `QUARTER`) take place in expression constructors so decoupling them from specific nodes & dialects is not trivial. 
To minimize damage I went with the following arg-based approach, but if similar bugs appear for other expressions and/or dialects we probably look into establishing finer granularity (per expr and per dialect).
Docs
-------
[Oracle TRUNC units](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/ROUND-and-TRUNC-Date-Functions.html#GUID-8E10AB76-21DA-490F-A389-023B648DDEF8)
=> fix(oracle): Do not normalize time units for exp.DateTrunc

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
Currently SQLGlot supports BigQuery's `JSON_EXTRACT_SCALAR`. From the docs, this now seems deprecated, with the suggested replacement being `JSON_VALUE`:
```SQL
bigquery> WITH t AS (SELECT JSON_VALUE('{"name": "Jakob", "age": "6"}', '$.age') as col) SELECT col, typeof(col) from t;
6 | STRING
snowflake> WITH t AS (SELECT JSON_EXTRACT_PATH_TEXT('{"name": "Jakob", "age": "6"}', 'age') AS col) SELECT col, typeof(col::variant) FROM t;
6 | VARCHAR
duckdb> WITH t AS (SELECT '{"name": "Jakob", "age": "6"}' ->> '$.age' AS col) SELECT col, TYPEOF(col) FROM t;
┌─────────┬─────────────┐
│   col   │ typeof(col) │
│ varchar │   varchar   │
├─────────┼─────────────┤
│ 6       │ VARCHAR     │
└─────────┴─────────────┘
```
This PR now parses `JSON_VALUE(...)` as `exp.JsonExtractScalar`.
Docs
--------
[BQ …
=> feat(BigQuery): Support JSON_VALUE()

sqlglot/dialects/databricks.py, sqlglot/dialects/dialect.py, sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
Transpile BQ's `DATETIME_DIFF` into Snowflake's `TIMESTAMPDIFF`. Both functions can process different date/time types, so the solution here should be a catch-all, e.g:
- `DATETIME` -> `TIMESTAMP` diff
```SQL
bigquery> SELECT DATETIME_DIFF(DATETIME "2010-07-07 10:20:00", DATETIME "2008-12-25 15:30:00", DAY);
559
snowflake> SELECT TIMESTAMPDIFF(DAY, CAST('2008-12-25 15:30:00' AS TIMESTAMP), CAST('2010-07-07 10:20:00' AS TIMESTAMP));
559
```
- `DATE` -> `DATE` diff
```SQL
bigquery> SELECT DATETIME_DIFF(DATE "2010-07-07", DATE "2008-12-25", MONTH);
19
snowflake> SELECT TIMESTAMPDIFF(MONTH, CAST('2008-12-25' AS DATE), CAST('2010-07-07' AS DATE));
19
```
Docs
---------
[BQ DATETIME_DIFF](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime_diff) | [SF …
=> feat(snowflake): Transpile exp.DatetimeDiff

sqlglot/dialects/bigquery.py, sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
Currently SQLGlot supports `JSON_EXTRACT` which is deprecated in favor of `JSON_QUERY`:
```SQL
bigquery> SELECT JSON_QUERY('{"class": {"students": []}}', '$.class')
{"students":[]}
snowflake> SELECT GET_PATH(PARSE_JSON('{"class": {"students": []}}'), 'class');
{"students": []}
duckdb> SELECT '{"class": {"students": []}}' -> '$.class';
┌──────────────────────────────────────────────┐
│ ('{"class": {"students": []}}' -> '$.class') │
│                     json                     │
├──────────────────────────────────────────────┤
│ {"students":[]}                              │
└──────────────────────────────────────────────┘
```
This PR also improves Snowflake's `GET_PATH` as it's unable to process JSON strings (unlike BQ and DuckDB), so as an extra step the string will be parsed first. …
=> feat(bigquery): Support JSON_QUERY

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/expressions.py, tests/dialects/test_duckdb.py
Now this works:
```python
import sqlglot as sg
import sqlglot.expressions as sge
e = sg.func(
"regexp_extract",
sge.convert("2023-04-15"),
sge.convert(r"(\d+)-(\d+)-(\d+)"),
sge.convert(["y", "m", "d"]),
"i",
dialect="duckdb",
)
e.sql("duckdb")
```
I was mostly stumbling around as I made the tests pass, but I don't really understand if the tests in their current state are adequately exercising all the variations of reading and writing. If you give me some pointers I can add more as needed.
=> feat(duckdb): support flags for RegexpExtract

sqlglot/dialects/bigquery.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, tests/dialects/test_duckdb.py, tests/dialects/test_snowflake.py
Follow up of https://github.com/tobymao/sqlglot/pull/4326
- Reverted BigQuery's generator and it's unsupported args; We add default values to `group` on other dialects so we'd need to silence these warnings on each test
- Simplified DuckDB's generator
- Removed duplicated tests
- Removed decorator prefix by importing it
=> fix!: Refactor exp.RegexpExtract (follow up 4326)

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Followup to https://github.com/tobymao/sqlglot/pull/4341
Before, roundtripping `SELECT REGEXP_EXTRACT(a, 'pattern', 0, 'i')` would result in `SELECT REGEXP_EXTRACT(a, 'pattern', 'i')`, which is incorrect (the group=0 arg is needed to fill space). So, we need to adjust our logic of when we can drop the group arg: it can only happen when there are no following args.
=> fix(duckdb): we ALWAYS need to render group if params is present for RegexpExtract

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
Fixes #4346
Docs
----------
[BQ DATE_TRUNC](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_trunc)
=> fix(bigquery): Parse timezone for DATE_TRUNC

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
BigQuery:
```SQL
SELECT DATETIME_ADD(DATETIME "2008-12-25 15:30:00", INTERVAL 10 MINUTE);
2008-12-25T15:40:00
```
Snowflake:
```SQL
SELECT TIMESTAMPADD(MINUTE, '10', CAST('2008-12-25 15:30:00' AS TIMESTAMP));
2008-12-25 15:40:00.000
```
Docs
-------
[BQ DATETIME_ADD](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime_add) | [BQ DATETIME vs TIMESTAMP](https://stackoverflow.com/questions/47713945/bigquery-datetime-vs-timestamp) | [SF TIMESTAMP_ADD](https://docs.snowflake.com/en/sql-reference/functions/timestampadd)
=> feat(snowflake): Transpile exp.DatetimeAdd

sqlglot/dialects/bigquery.py, sqlglot/dialects/spark.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
BigQuery and Spark3/Databricks support `UNIX_SECONDS(expr)` which returns the number of seconds since 1970-01-01 00:00:00 UTC:
```SQL
bigquery> SELECT UNIX_SECONDS(TIMESTAMP "2008-12-25 15:30:00+00") AS seconds;
seconds
1230219000
spark-sql (default)> SELECT UNIX_SECONDS(TIMESTAMP "2008-12-25 15:30:00+00") AS seconds;
seconds
1230219000
```
This PR adds `exp.UnixSeconds` to enable seamless parsing as well as transpiles the newly added node to DuckDB & Snowflake by utilizing `exp.TimestampDiff` at a `SECOND` granularity:
```SQL
duckdb> SELECT DATE_DIFF('SECONDS', CAST('1970-01-01 00:00:00+00' AS TIMESTAMPTZ), '2008-12-25 15:30:00+00') AS seconds;
┌────────────┐
│  seconds   │
│   int64    │
├────────────┤
│ 1230219000 │
└────────────┘
snowflake> SELECT TIMESTAMPDIFF(SECONDS, …
```
=> feat(spark, bigquery): Add support for UNIX_SECONDS(...)

sqlglot/dialects/clickhouse.py, tests/dialects/test_dialect.py
Fixes #4354
```SQL
:) select MEDIAN(5);
Received exception:
Code: 63. DB::Exception: Unknown aggregate function MEDIAN. Maybe you meant: ['median','medianDD']. (UNKNOWN_AGGREGATE_FUNCTION)
:) select median(5);
┌─median(5)─┐
1. │         5 │
└───────────┘
```
=> fix(clickhouse): Generate exp.Median as lowercase

sqlglot/dialects/bigquery.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py
This PR adds support for `JSON_VALUE_ARRAY(expr [, json_path])` which extracts a JSON array of scalar values and converts it to `ARRAY<STRING>`:
```SQL
bigquery> WITH t AS (
SELECT
JSON_VALUE_ARRAY(JSON '{"arr": [1, "a"]}', '$.arr') AS arr
)
SELECT
arr,
typeof(arr),
typeof(arr[0])
FROM t;
arr	f0_	f1_
"[1,a]"	ARRAY<STRING>	STRING
```
Transpilation support towards DuckDB & Snowflake is also added through the following transformations:
- DuckDB: Extracts the array and casts it to `TEXT[]`
```SQL
D WITH t AS (
SELECT
CAST(JSON('{"arr": [1, "a"]}') -> '$.arr' AS TEXT[]) AS arr
)
SELECT
arr,
TYPEOF(arr),
TYPEOF(arr[1])
FROM t;
┌───────────┬─────────────┬────────────────┐
│    arr    │ typeof(arr) │ typeof(arr[1]) │
│ varchar[] │   varchar   │    varchar     │ …
```
=> feat(bigquery): Support JSON_VALUE_ARRAY(...)

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py, tests/dialects/test_snowflake.py
This PR parses `REGEXP_SUBSTR` into `exp.RegexpExtract`, as acccording to the docs it's a synonym for `REGEXP_EXTRACT`. For the tests:
- The cases in `bigquery.py` are organized into a single function
- The case in `snowflake.py` is wrong, probably copy-pasted from the `"snowflake"` line. It's only failing now as `REGEXP_SUBSTR` is no longer Anonymous for BQ
Docs
------
[BQ REGEXP_SUBSTR](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_substr)
=> feat(bigquery): Parse REGEXP_SUBSTR as exp.RegexpExtract

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes #4365
BigQuery supports inline `STRUCT` constructors such as the following:
```SQL
bq> SELECT STRUCT<a STRING, b INTEGER>('str', 1) AS strct;
strct.a   strct.b
'str'        1
```
https://github.com/tobymao/sqlglot/pull/3751 introduced support in SQLGlot by canonicalizing those expressions to a CAST:
```Python
>> sqlglot.parse_one("SELECT STRUCT<a STRING, b INTEGER>('str', 1)", read="bigquery").sql("bigquery")
`CAST(STRUCT('str', 1) AS STRUCT<a STRING, b INTEGER>)`
```
Note thought that transpilation towards DuckDB was still not complete as it requires explicit key-value pairs to construct STRUCTs:
```SQL
D SELECT CAST(STRUCT_PACK('str', 1) AS STRUCT("a" TEXT, "b" INT));
Binder Error: Need named argument for struct pack, e.g. STRUCT_PACK(a := b)
``` 
To solve this issue efficiently, …
=> fix(duckdb)!: Fix STRUCT cast generation

sqlglot/expressions.py
Closes #4367
Closes #4362
Now this works:
```python
>>> import sqlglot.expressions as expressions
>>> from sqlglot.expressions import column
>>>
>>> is_equal_list = ['a'] * 500
>>> is_equal = expressions.false()
>>>
>>>
>>> for value in is_equal_list:
...     is_equal = is_equal.or_(column("a_column").eq(value), wrap=False)
...
>>> is_equal.sql()[:100]
"FALSE OR a_column = 'a' OR a_column = 'a' OR a_column = 'a' OR a_column = 'a' OR a_column = 'a' OR a"
```
I didn't add a timing test because they're flaky. I think we should refactor the existing ones at some point too.
=> Feat: optionally wrap connectors when using builders

sqlglot/dialects/bigquery.py, sqlglot/dialects/clickhouse.py, sqlglot/dialects/drill.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/hive.py, sqlglot/dialects/postgres.py, sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/teradata.py, sqlglot/generator.py, tests/dialects/test_postgres.py
Fixes #4368
This PR aims to standardize the generation of `exp.ArraySize` across the major dialects:
- Postgres and DuckDB (for backwards compatibility with PG) support `ARRAY_LENGTH(array, dimension)` 
- Other major dialects support only `ARRAY_LENGTH(array)`
Docs
-------
[BQ](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array_length) | [Spark / Databricks](https://docs.databricks.com/en/sql/language-manual/functions/array_size.html) | [Presto / Trino](https://prestodb.io/docs/current/functions/array.html#cardinality-x-bigint) | [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/array_size) | [DuckDB](https://duckdb.org/docs/sql/functions/list.html#lenlist) | [Postgres](https://www.postgresql.org/docs/8.4/functions-array.html) | …
=> fix: Transpilation of exp.ArraySize from Postgres (read)

tests/test_parser.py
These asserts keep messing with github's CI/CD tests; Removed them for now, open to discussion on whether these tests are needed at all, if they can be reincorporated on a different suite etc
=> fix: Remove flaky timing test

sqlglot/dialects/databricks.py, sqlglot/dialects/spark.py, tests/dialects/test_spark.py
Fixes #4372
I couldn't find `TIMESTAMP_DIFF` on Spark 3 docs, but it works locally from at least 3.4+:
```SQL
spark-sql (default)> SELECT timestampdiff(MONTH, TIMESTAMP'2021-02-28 12:00:00', TIMESTAMP'2021-03-28 12:00:00');
timestampdiff(MONTH, TIMESTAMP '2021-02-28 12:00:00', TIMESTAMP '2021-03-28 12:00:00')
1
```
Docs
--------
[Spark 4](https://spark.apache.org/docs/preview/api/python/reference/pyspark.sql/api/pyspark.sql.functions.timestamp_diff.html) | [Databricks](https://docs.databricks.com/en/sql/language-manual/functions/timestampdiff.html)
=> fix(spark): Support DB's TIMESTAMP_DIFF

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py, tests/dialects/test_dialect.py
This PR adds parsing support for `exp.StrPosition` in BigQuery, enabling it's transpilation:
```SQL
bigquery> SELECT STRPOS('foo@example.com', '@');
4
snowflake> SELECT POSITION('@', 'foo@example.com');
4
duckdb> SELECT STRPOS('foo@example.com', '@');
┌────────────────────────────────┐
│ strpos('foo@example.com', '@') │
│             int64              │
├────────────────────────────────┤
│                              4 │
└────────────────────────────────┘
```
Docs
--------
[BQ](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#strpos) | [DuckDB](https://duckdb.org/docs/sql/functions/char.html#strposstring-search_string) | [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/position)
=> feat(bigquery): Add parsing support for STRPOS(...)

sqlglot/dialects/bigquery.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py, tests/dialects/test_clickhouse.py
This PR adds support for BQ's `FORMAT_TIMESTAMP` through `exp.TimeToStr`:
```SQL
bigquery> SELECT FORMAT_TIMESTAMP("%b-%d-%Y", TIMESTAMP "2050-12-25 15:30:55+00");
Dec-25-2050
snowflake> SELECT TO_CHAR(CAST(CAST('2050-12-25 15:30:55+00' AS TIMESTAMPTZ) AS TIMESTAMP), 'mon-DD-yyyy');
Dec-25-2050
duckdb> SELECT STRFTIME(CAST('2050-12-25 15:30:55+00' AS TIMESTAMP), '%b-%d-%Y');
┌───────────────────────────────────────────────────────────────────┐
│ strftime(CAST('2050-12-25 15:30:55+00' AS TIMESTAMP), '%b-%d-%Y') │
│                              varchar                              │
├───────────────────────────────────────────────────────────────────┤
│ Dec-25-2050                                                       │
└───────────────────────────────────────────────────────────────────┘ …
```
=> fix(bigquery)!: Support FORMAT_TIMESTAMP

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py
This PR adds support for BQ's `MAKE_INTERVAL` and enables transpilation towards DuckDB & Snowflake by serializing the units into `INTERVAL '<units>'` expressions:
```SQL
bigquery> SELECT CAST('2024-01-01 10:00:00' AS DATETIME) + MAKE_INTERVAL(1, 2, minute => 5, day => 3);
2025-03-04T10:05:00
snowflake> SELECT CAST('2024-01-01 10:00:00' AS TIMESTAMP) + INTERVAL '1 year, 2 month, 5 minute, 3 day';
2025-03-04 10:05:00.000
duckdb> SELECT CAST('2024-01-01 10:00:00' AS TIMESTAMP) + INTERVAL '1 year 2 month 5 minute 3 day';
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (CAST('2024-01-01 10:00:00' AS TIMESTAMP) + CAST('1 year 2 month 5 minute 3 day' AS INTERVAL)) │
│                                           timestamp …
```
=> feat(bigquery): Support MAKE_INTERVAL

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
This PR adds support for BQ's `INT64(...)` which converts a JSON number to an INT64 value:
```SQL
bigquery> WITH t AS (SELECT INT64(JSON_QUERY(JSON '{"gate": "A4", "flight_number": 2005}', "$.flight_number")) AS col) SELECT col, typeof(col) from t;
col	f0_
2005	INT64
snowflake>  WITH t AS (SELECT CAST(GET_PATH(PARSE_JSON('{"gate": "A4", "flight_number": 2005}'), 'flight_number') AS BIGINT) AS col) SELECT col, TYPEOF(col) FROM t;
COL | TYPEOF(COL)
-- | --
2005 | INTEGER
duckdb> WITH t AS (SELECT CAST(JSON('{"gate": "A4", "flight_number": 2005}') -> '$.flight_number' AS BIGINT) AS col) SELECT col, TYPEOF(col) FROM t;
┌───────┬─────────────┐
│  col  │ typeof(col) │
│ int64 │   varchar   │
├───────┼─────────────┤
│  2005 │ BIGINT      │
└───────┴─────────────┘
```
Docs
-------
[BQ …
=> feat(bigquery): Support INT64(...)

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py
Fixes #4392
Conditionally wrap the `DIV0` operands as going from a function based -> binop representation can alter the precedence.
Docs
-------
[SF DIV0](https://docs.snowflake.com/en/sql-reference/functions/div0)
=> fix(snowflake): Wrap DIV0 operands if they're binary expressions

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py
This PR adds support for BQ's `CONTAINS_SUBSTR(...)` along with `CONTAINS(...)` which is the popular variant across other dialects.
Other design choices:
- BQ also supports a 3rd arg regarding JSON search which is currently parsed as `exp.Anonymous` since it differs from other dialects
- Because BQ performs the substring check in a case-insensitive manner, it wraps the operands with `exp.Lower` to aid the transpilation (or unwraps them during roundtrip)
```SQL
bigquery> SELECT CONTAINS_SUBSTR('blue', 'Blue') AS result;
true
spark-sql (default)> SELECT CONTAINS('blue', 'Blue') AS case_sensitive, CONTAINS(LOWER('blue'), LOWER('Blue')) AS case_insensitive;
case_sensitive  case_insensitive
false   true
snowflake> SELECT CONTAINS('blue', 'Blue') AS case_sensitive, CONTAINS(LOWER('blue'), …
```
=> feat: Add support for CONTAINS(...)

benchmarks/bench.py, benchmarks/optimize.py
Right now if one tries to run `bench.py`, python yells that the `benchmarks` module does not exist.
=> Chore: fix relative benchmark import, comment out sqltree

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Ref: https://duckdb.org/docs/sql/statements/attach#detach-syntax
Allow `DETACH` in DuckDB to be parsed as a command.
=> Add DETACH as command to DuckDB dialect

sqlglot/expressions.py, tests/dialects/test_clickhouse.py
Added support for specifying target column in `row_number` function
Some dialects such as ClickHouse allow this syntax: https://clickhouse.com/docs/en/sql-reference/window-functions/row_number
=> feat: add support for specifying column in row_number function

sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, tests/dialects/test_clickhouse.py
Current implementation of the `transform` function allows only to specify 2 arguments. But there are dialects other than Spark, for example, ClickHouse:
https://clickhouse.com/docs/en/sql-reference/functions/other-functions#transform
It accepts 3 or 4 arguments, and with current implementation, the parsing of such queries raises `ParseError`:
```
sqlglot.errors.ParseError: The number of provided arguments (3) is greater than the maximum number of supported arguments (2).
```
IMO, it would be better to accept a variable amount of arguments to support dialects other than Spark.
This is a breaking change since the `expression` is replaced with `expressions`.
=> feat(clickhouse): transform function support

sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #4410
- Before this PR, this would be the AST of the following query: 
```python3
>>> ast = sqlglot.parse_one("select * from table(a.b.func2(a) over ())", read="snowflake")
>>> print(repr(ast))
Select(
expressions=[
Star()],
from=From(
this=Table(
this=Anonymous(
this=table,
expressions=[
Column(
this=Window(
this=Anonymous(
this=func2,
expressions=[
Column(
this=Identifier(this=a, quoted=False))]),
over=OVER),
table=Identifier(this=b, quoted=False),
db=Identifier(this=a, quoted=False))]))))
```
- After this PR, the AST for the same query is:
```python3
>>> print(repr(ast))
Select(
expressions=[
Star()],
from=From(
this=Table(
this=Anonymous(
this=table,
expressions=[
Window(
this=Dot(
this=Dot(
this=Identifier(this=a, quoted=False),
expression=Identifier(this=b, quoted=False)), …
```
=> fix(parser): Do not parse window function arg as exp.Column

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_mysql.py
Fixes #4414
This PR adds parsing support for:
- The pre-statement `FORMAT` property
- Non-table and non-select statements e.g `UPDATE`
Docs
--------
[MySQL EXPLAIN](https://dev.mysql.com/doc/refman/8.4/en/explain.html)
=> fix(parser): Extend DESCRIBE parser for MySQL FORMAT & statements

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
Fixes #4428
Add support for the following ML function:
```
ML.FEATURES_AT_TIME(
{ TABLE feature_table | (query_statement) }
[, time => TIMESTAMP]
[, num_rows => INT64]
[, ignore_feature_nulls => BOOL]
)
```
Docs
--------
[BQ FEATURES_AT_TIME()](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-feature-time)
=> feat(bigquery): Support FEATURES_AT_TIME()

sqlglot/dialects/mysql.py, sqlglot/dialects/oracle.py, sqlglot/parser.py, sqlglot/tokens.py, sqlglotrs/src/settings.rs, sqlglotrs/src/tokenizer.rs, tests/dialects/test_oracle.py, tests/dialects/test_postgres.py
Fixes #4425
Currently, hints are not tokenized as a single entity like we do for the comments (i.e through `_scan_comments()`), but instead the following token stream is produced:
```
>>> tokens = tokenize("SELECT /*+ hint */ * FROM t")
>>> for token in tokens:
... print(token)
<Token token_type: TokenType.SELECT, text: SELECT, line: 1, col: 6, start: 0, end: 5, comments: []>
<Token token_type: TokenType.HINT, text: /*+, line: 1, col: 10, start: 7, end: 9, comments: []>
<Token token_type: TokenType.VAR, text: hint, line: 1, col: 15, start: 11, end: 14, comments: []>
<Token token_type: TokenType.STAR, text: *, line: 1, col: 17, start: 16, end: 16, comments: []>
<Token token_type: TokenType.SLASH, text: /, line: 1, col: 18, start: 17, end: 17, comments: []>
<Token token_type: …
```
=> fix!: Tokenize hints as comments

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py, tests/dialects/test_snowflake.py
Fixes #4427 
This co-opts the `DictProperty` and `DictSubProperty` properties, originally created for [clickhouse](https://clickhouse.com/docs/en/sql-reference/statements/create/dictionary). Clickhouse and snowflake specify these key-value pairs with different syntax, so I tried to make the parsing / generation generic for various key-value syntaxes. This got a little awkward for generation because the separator and delimiter values have to be specified, and I didn't see any TokenType -> string method. I'm happy to instead create a less generic `SnowflakeTagListProperty` if that's preferred.
=> feat(snowflake): Support Snowflake syntax CREATE ... WITH TAG

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes #4435
- The Python specifier `%W` is for week number in year (1 - 52), while `%w` is for day of week (0-6)
```Python3
>>> from datetime import datetime
>>> now = datetime.now()
>>> now.strftime("%W")
47
>>> now.strftime("%w")
4
```
- The corresponding `%W` T-SQL formats:
```SQL
1> SELECT DATEPART(WEEK, CAST('2024-11-21' AS DATETIME2)), DATEPART(WK, CAST('2024-11-21' AS DATETIME2)), DATEPART(WW, CAST('2024-11-21' AS DATETIME2))
2> go
----------- ----------- -----------
47         47          47
```
And `%w` (they're shifted by +1 i.e 1-7):
```SQL
1> SELECT DATEPART(WEEKDAY, CAST('2024-11-21' AS DATETIME2)), DATEPART(DW, CAST('2024-11-21' AS DATETIME2))
2> go
----------- -----------
5           5
```
Docs
-----
[T-SQL DATE_PART](https://learn.microsoft.com/en-us/sql/t-sql/functions/dat …
=> fix(tsql): Map weekday to %w

sqlglot/dialects/snowflake.py, tests/dialects/test_dialect.py
Currently, transpilation of BQ's `GENERATE_DATE_ARRAY` to Snowflake is supported only if it's `UNNEST`ed (introduced by https://github.com/tobymao/sqlglot/pull/3899), e.g:
1. Supported:
```Python3
>>> sqlglot.parse_one("SELECT * FROM UNNEST(GENERATE_DATE_ARRAY(DATE '2020-01-01', DATE '2020-02-01', INTERVAL 1 WEEK))", read="bigquery").sql("snowflake")
"SELECT * FROM (SELECT DATEADD(WEEK, CAST(value AS INT), CAST('2020-01-01' AS DATE)) AS value FROM TABLE(FLATTEN(INPUT => ARRAY_GENERATE_RANGE(0, (DATEDIFF(WEEK, CAST('2020-01-01' AS DATE), CAST('2020-02-01' AS DATE)) + 1 - 1) + 1))) AS _u(seq, key, path, index, value, this))"
bigquery> SELECT * FROM UNNEST(GENERATE_DATE_ARRAY(DATE '2020-01-01', DATE '2020-02-01', INTERVAL 1 WEEK)); 
f0_
2020-01-01
2020-01-08
2020-01-15 …
```
=> feat(snowflake): Transpile non-UNNEST exp.GenerateDateArray refs

sqlglot/expressions.py, sqlglot/optimizer/qualify_columns.py
The `copy` method on `Expression`s does not have a return type specified. This PR adds one (and makes one additional change that was necessitated by the addition of the return type).
=> fix: add return type

sqlglot/dialects/dialect.py, sqlglot/dialects/presto.py, sqlglot/parser.py, tests/dialects/test_mysql.py
=> Fix: parse DEFAULT in VALUES clause into a Var

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
Fixes #4456
The name `CONTAINS_SUBSTRING` was a typo from my end:
```
bq> SELECT CONTAINS_SUBSTRING('the blue house', 'Blue house') AS result;
Function not found: CONTAINS_SUBSTRING; Did you mean contains_substr? at [1:8]
bq> SELECT CONTAINS_SUBSTR('the blue house', 'Blue house') AS result;
true
```
Docs
--------
[BQ CONTAINS_SUBSTR](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#contains_substr)
=> fix(bigquery): Rename CONTAINS_SUBSTRING to CONTAINS_SUBSTR

sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, tests/dialects/test_databricks.py, tests/dialects/test_hive.py, tests/dialects/test_mysql.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py
Fixes #4442
Spark defines it's `TIMESTAMP` to be a configurable session variable, with it's default value being timestamp with local time zone (`TIMESTAMP_LTZ`):
```SQL
spark-sql (default)> SELECT CAST('2024-11-27 15:03:20.603467+03' AS TIMESTAMP);
2024-11-27 14:03:20.603467
duckdb> SELECT CAST('2024-11-27 15:03:20.603467+03' AS TIMESTAMP);
┌────────────────────────────────────────────────────┐
│ CAST('2024-11-27 15:03:20.603467+03' AS TIMESTAMP) │
│                     timestamp                      │
├────────────────────────────────────────────────────┤
│ 2024-11-27 12:03:20.603467                         │
└────────────────────────────────────────────────────┘
duckdb> SELECT CAST('2024-11-27 15:03:20.603467+03' AS TIMESTAMPTZ); …
```
=> fix(spark)!: Make TIMESTAMP map to Type.TIMESTAMPTZ

sqlglot/dialects/oracle.py, sqlglot/dialects/tsql.py, sqlglot/parser.py, tests/dialects/test_presto.py, tests/dialects/test_tsql.py, tests/fixtures/identity.sql
=> Fix(parser)!: treat NEXT as a func keyword, parse NEXT VALUE FOR in tsql, oracle

sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/helper.py, tests/test_expressions.py
This will allow SQLMesh users to control which table references will be resolved to the db objects in the physical layer.
=> Feat: allow tables to be preserved in replace_table

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py
Fixes #4463
Postgres supports the following column constraints for `CREATE TABLE` DDLs:
```
where column_constraint is:
[ CONSTRAINT constraint_name ]
{ 
...
GENERATED ALWAYS AS ( generation_expr ) STORED |
GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ] |
...
}
```
The former defines a _generated_ column while the latter an _identity_ one. 
This PR overrides `parser.py::_parse_generated_as_identity()` which will transform the produced `exp.GeneratedAsIdentityColumnConstraint` into an `exp.ComputedColumnConstraint()`, as is already happening on `spark.py`.
> [!WARNING]  
> Something that stands out as bad naming/design is the fact that `exp.GeneratedAsIdentityColumnConstraint` should concern only **IDENTITY** columns, but overtime it has grown to parse different …
=> feat(postgres): Support generated columns

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
I realized that Snowflake requires a constant for the 2nd argument of `TO_TIMESTAMP*` when it detects that the used variant is `timestampFunction ( <numeric_expr> [ , <scale> ] )` ([docs](https://docs.snowflake.com/en/sql-reference/functions/to_timestamp)), so we can leverage this constraint to improve the transpilation.
=> Feat!(snowflake): improve transpilation of TO_TIMESTAMP* variants

sqlglot/dialects/duckdb.py, sqlglot/dialects/mysql.py, tests/dialects/test_mysql.py
Fixes #4445
References:
- https://dev.mysql.com/doc/refman/8.4/en/string-functions.html#function_format
- https://duckdb.org/docs/sql/functions/char#fmt-syntax
cc @ddh-5230
=> Feat!: transpile MySQL FORMAT to DuckDB

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_snowflake.py
Fixes #4489
Snowflake supports 2 definitions for `FOREIGN KEY`:
- Inline:
```
inlineFK :=
[ CONSTRAINT <constraint_name> ]
[ FOREIGN KEY ]
REFERENCES <ref_table_name> [ ( <ref_col_name> ) ]
...
```
- Out of line:
```
outoflineFK :=
[ CONSTRAINT <constraint_name> ]
FOREIGN KEY ( <col_name> [ , <col_name> , ... ] )
REFERENCES <ref_table_name> [ ( <ref_col_name> [ , <ref_col_name> , ... ] ) ]
...
```
This PR adds support for the inline version which now produces an empty `exp.ForeignKey` node.
Docs
---------
[Snowflake CREATE TABLE](https://docs.snowflake.com/en/sql-reference/sql/create-table-constraint)
=> feat(snowflake): Support for inline FOREIGN KEY

sqlglot/dialects/clickhouse.py, sqlglot/dialects/mysql.py, sqlglot/dialects/tsql.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_tsql.py
[Public Slack context](https://tobiko-data.slack.com/archives/C044BRE5W4S/p1733610657252759)
This PR introduces `Type.DATETIME2` with the intention of preserving T-SQL's roundtrips of `DATETIME` and `DATETIME2` respectively.
According to the docs, `DATETIME2` is an extension to `DATETIME` supporting higher precision, date range etc. However, it's not 100% backwards compatible so transforming `"DATETIME" -> Type.DATETIME2` is not always safe.
Docs
--------
[T-SQL DATETIME](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16) | [T-SQL DATETIME2](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16) | [S/O DATETIME VS DATETIME2](https://stackoverflow.com/questions/1334143/datetime2-vs-datetime-in-sql …
=> fix(tsql)!: Preserve roundtrips of DATETIME/DATETIME2

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes #4496
This PR adds support for DuckDB's escape strings `E'...'` / `e'...'`, which is a Postgres-borrowed concept.
Docs
------
[DuckDB](https://duckdb.org/docs/sql/data_types/literal_types.html#escape-string-literals) | [Postgres](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE)
=> fix(duckdb): Allow escape strings similar to Postgres

sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/test_parser.py
The motivation behind this PR is to make parsing multiple `WHEN [NOT] MATCHED` clauses easier. This is related to a SQLMesh refactor I'm currently working on.
=> Refactor!!: bundle multiple WHEN [NOT] MATCHED into a exp.WhenSequence

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_postgres.py
I made a few additional changes in `_parse_function_call` to allow `xmlattributes('xyz' as bar)` to be parsed. Right now it's not because we only expect an alias in certain functions. My fix was to extend this behavior so that we also consume them in anonymous ones.
Fixes #4512
=> Feat(postgres): add support for XMLELEMENT

sqlglot/dialects/postgres.py, tests/dialects/test_redshift.py
Postgres doesn't support specifying a precision for the `REAL` and `DOUBLE PRECISION` types:
```
georgesittas=# select 1::real(4);
ERROR:  syntax error at or near "("
LINE 1: select 1::real(4);
^
georgesittas=# select 1::double precision(4);
ERROR:  syntax error at or near "("
LINE 1: select 1::double precision(4);
^
georgesittas=# select 1::real;
float4
--------
1
(1 row)
georgesittas=# select 1::double precision;
float8
--------
1
(1 row)
```
OTOH, according to its [docs](https://www.postgresql.org/docs/current/datatype-numeric.html), it does support a `FLOAT(p)` type, so we use that instead to (1) roundtrip and (2) facilitate transpilation from other dialects to Postgres:
> PostgreSQL also supports the SQL-standard notations float and float(p) for specifying inexact numeric types. …
=> Fix(postgres): generate float if the type has precision

sqlglot/parser.py, tests/dialects/test_postgres.py
=> Fix: another interval parsing edge case

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes #4520
```SQL
1> SELECT DATEADD(DAY, DATEDIFF(DAY, -3, GETDATE()), '08:00:00')
2> go
-----------------------
2024-12-19 08:00:00.000
1> SELECT DATEADD(DAY, DATEDIFF(DAY, CAST('1899-12-29' AS DATETIME2), CAST(GETDATE() AS DATETIME2)), '08:00:00')
2> go
-----------------------
2024-12-19 08:00:00.000
```
=> fix(tsql): Convert DATE_DIFF literals through to_py()

sqlglot/planner.py
Fixes #4525
Planner looks to be working correctly with this change, without any optimizations needed:
```python
>>> import sqlglot.planner
>>>
>>> r = 'select suma from (select sum(a) as suma from table1) order by suma'
>>> parsed = sqlglot.parse_one(r, dialect='snowflake')
>>> p = sqlglot.planner.Plan(parsed)
>>> p
Plan
----
- Sort: (4385150576)
Context:
Key:
- suma NULLS LAST
Projections:
- suma
Dependencies:
- Aggregate: (4382705472)
Context:
Aggregations:
- SUM(a) AS suma
Projections:
- "table1"."suma"
Dependencies:
- Scan: table1 (4364384592)
Context:
Source: table1
Projections:
```
=> Fix(planner): ensure aggregate variable is bound

sqlglot/dialects/mysql.py, tests/dialects/test_mysql.py
Fixes #4529
According to MySQL docs `SERIAL` is an alias for `BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE`.
Docs
--------
[MySQL Numeric types](https://dev.mysql.com/doc/refman/8.4/en/numeric-type-syntax.html)
=> feat(mysql): Support SERIAL data type

sqlglot/expressions.py, sqlglot/parser.py, tests/test_parser.py
Fixes #4522
This PR introduces support for the meta comment `/* sqlglot.meta anonymous */` which forces the parser to ignore the known functions during `_parse_function_call`:
- Without meta comment
```Python3
>>> print(repr(parse_one("YEAR(a)")))
Year(
this=Column(
this=Identifier(this=a, quoted=False)))
```
- With meta comment
```Python3
>>> print(repr(parse_one("YEAR(a) /* sqlglot.meta anonymous */")))
Anonymous(
this=YEAR,
expressions=[
Column(
this=Identifier(this=a, quoted=False))],
_comments=[
sqlglot.meta anonymous ])
``` 
- With incorrect / incomplete meta comment
```Python3
>>> print(repr(parse_one("YEAR(a) /* sqlglot.meta anon */")))
Year(
this=Column(
this=Identifier(this=a, quoted=False)),
_comments=[
sqlglot.meta anon ])
```
=> feat: Introduce meta comment to parse known functions as exp.Anonymous

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_duckdb.py
Fixes #4542
This PR adds support for the simplified `UNPIVOT` as an extension to our supported simplified `PIVOT` statement parsing.
Docs
--------
[DuckDB UNPIVOT](https://duckdb.org/docs/sql/statements/unpivot#simplified-unpivot-syntax)
=> feat(duckdb): Support simplified UNPIVOT statement

sqlglot/dialects/clickhouse.py, sqlglot/dialects/spark.py, sqlglot/parser.py, tests/dialects/test_clickhouse.py
=> Fix(parser)!: require AS token in CTEs for all dialects except spark, databricks

.github/workflows/python-package.yml
The regression in the CI seems to be due to `ubuntu-latest` i.e Ubuntu 24.04 no longer supporting Python 3.7
https://github.com/actions/setup-python/issues/962
=> fix: Pin ubuntu to 22.04 for Python 3.7

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes #4558
```
>>> sqlglot.exp.DateFromParts(year="2012", month="4", day="21").sql(dialect="tsql")`
'DATEFROMPARTS(2012, 4, 21)'
```
**Docs**
[T-SQL DATEFROMPARTS](https://learn.microsoft.com/en-us/sql/t-sql/functions/datefromparts-transact-sql?view=sql-server-ver16)
=> fix(tsql): generate correct DateFromParts naming #4558

sqlglot/parser.py, tests/dialects/test_duckdb.py
Fixes #4561
In the previous implementation, an error was thrown every time the `FROM-First` syntax was used with parentheses.
For example: 
```
CREATE TABLE table1 AS (FROM table2 SELECT foo1, foo2)
```
In the above example, an error `sqlglot.errors.ParseError: Expecting )` was thrown because the parsing of the `SELECT`  was missing. 
After the fix: 
```
>>> sqlglot.transpile("FROM (FROM table1 SELECT foo1, foo2)", read="duckdb", write="duckdb")
['SELECT * FROM (SELECT foo1, foo2 FROM table1)']
```
**Docs**
[DuckDB From-First](https://duckdb.org/docs/sql/query_syntax/from#from-first-syntax)
=> fix(duckdb): support parentheses with FROM-First syntax #4561

sqlglot/dialects/mysql.py, tests/dialects/test_snowflake.py
Added support for `LOGICAL_AND` and `LOGICAL_OR` in MySQL. The latest MySQL version supports `BIT_AND` and `BIT_OR`, but `MIN` and `MAX` also work and have wider support. The `MIN` and `MAX` trick is already used by SQLite.
For `BIT_OR`/`BIT_AND` see [this](https://dev.mysql.com/doc/refman/8.4/en/aggregate-functions.html#function_bit-and).
=> LOGICAL_AND and LOGICAL_OR for MySQL

sqlglot/dialects/oracle.py, tests/dialects/test_oracle.py
Oracle does not support `STR_POSITION`, the correct function is `INSTR`.
See the [docs](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/INSTR.html).
=> StrPosition fixed for Oracle

sqlglot/tokens.py
Add flag to allow setting Rust tokenizer per Tokenizer instance.
Currently, it is only possible to enable/disable the Rust tokenizer globally via an environment variable (`USE_RS_TOKENIZER`). It would be great if we had a way to enable/disable the Rust backend per `Tokenizer` instance, i.e., to selectively choose which tokenizer should be used for parsing a particular query.
Why would we want to do this? The Rust tokenizer is faster in most cases, and is compatible with 99.99% of queries, but we've come across a few queries that are not (yet) supported - so it would be great to selectively enable/disable it (to use Rust for the majority of parsing, but use the Python fallback for the 0.01% of queries).
This PR proposes a minimally invasive change that adds a new flag …
=> Add flag to allow setting Rust tokenizer per Tokenizer instance

sqlglotrs/src/tokenizer.rs, tests/dialects/test_snowflake.py
Fixes #4560
The issue here was that u64 can represent up to 18446744073709551615, whereas the given hex literal is greater than this value: 378935326159973281336632520865622722.
=> Fix(rust-tokenizer): increase integer width when converting hex literals

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes [here](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1736263004411849)
This PR fixes the transpilation of the `TIMESTAMP_NTZ` to `DATETIME2`. 
Based on the snowflake's docs: `TIMESTAMP_NTZ is the default for TIMESTAMP`.
**Note** : the precision of `snowflake's TIMESTAMP_NTZ` is `0 to 9`, and the precision of `tsql's DATETIME2` is `0 to 7`. 
**Docs**
[Snowflake TIMESTAMP_NTZ](https://docs.snowflake.com/en/sql-reference/data-types-datetime#label-datatypes-timestamp-variations) | [T-SQL datetime2](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16)
=> fix(tsql): transpile snowflake TIMESTAMP_NTZ to DATETIME2

sqlglot/dialects/postgres.py, tests/dialects/test_dialect.py
`STRPOS` works well for Postgres and the [documentation](https://www.postgresql.org/docs/9.1/functions-string.html) states that "[it is the] same as position(substring in string), but note the reversed argument order", but in reality, `POSITION(substring in string)` is more robust as it works with binary strings as well.
```sql
select strpos(decode('DEADBEEF', 'hex'), decode('BE', 'hex'));
select position(decode('BE', 'hex') in decode('DEADBEEF', 'hex'));
```
=> STRPOS to POSITION for Postgres

.github/workflows/rust-bench.yml, sqlglotrs/Cargo.toml
The CI is currently broken for PRs, I'm temporarily disabling the job so we can take our time to debug this without producing noise.
=> Chore: temporarily disable sqlglotrs benchmarking

sqlglot/dialects/mysql.py, sqlglot/dialects/sqlite.py, sqlglot/dialects/tsql.py, tests/dialects/test_mysql.py
I renamed `exp.Chr` for SQLite, TSQL, and added default encoding for MySQL.
```
SELECT CHAR(10) # sqlite
SELECT CHR(10) # postgres
SELECT CHAR(10 USING utf8mb4) # mysql
```
See [SQLite docs](https://www.sqlite.org/lang_corefunc.html#char) and [TSQL docs](https://learn.microsoft.com/en-us/sql/t-sql/functions/char-transact-sql?view=sql-server-ver16).
The encoding is necessary since MySQL 8.0.19 (see [this](https://stackoverflow.com/questions/65614116/in-mysql-char-function-works-weird)).
=> Feat: add support for Chr in tsql and sqlite

.github/workflows/python-publish.yml
The Python 3.13 Windows release does [not work](https://github.com/tobymao/sqlglot/actions/runs/12673518778/job/35320129684) due to a known pyo3 [linker error](https://github.com/PyO3/maturin-action/issues/292).
Pinning the python version was the recommendation [here](https://github.com/PyO3/maturin-action/issues/292#issuecomment-2504729250). If `win32` issues arise, we can also consolidate the `architecture` line.
=> fix: Pin python 3.13 for sqlglotrs build

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes snowflake problem #4575 
This PR allows the generation of snowflake queries when the `OFFSET` is present in the input dialect without a `LIMIT`.
Based on the snowflake's doc, an `OFFSET` must always match with a `LIMIT`. Based on the discussion [here](https://snowflake.discourse.group/t/how-do-i-use-offset-without-limit/5342), a `LIMIT NULL` can be inserted into the query in order to be parsed correctly. 
Example:
```
>>> sqlglot.transpile("SELECT 1 ORDER BY 1 OFFSET 0", read="trino", write="snowflake")
['SELECT 1 ORDER BY 1 LIMIT NULL OFFSET 0']
```
**Docs**
[Snowflake LIMIT](https://docs.snowflake.com/en/sql-reference/constructs/limit#postgresql-syntax)
=> fix(snowflake): generate LIMIT when OFFSET exists #4575

sqlglot/dialects/dialect.py, sqlglot/dialects/postgres.py, tests/dialects/test_dialect.py, tests/dialects/test_hive.py
This PR reverts https://github.com/tobymao/sqlglot/pull/4577 as Postgres's `exp.StrPos` generation does not take into account the `position` arg anymore (regression).
Also, the position offset logic is fixed; If a match is not found the return value should be 0, so `position_offset` should be added conditionally e.g:
```SQL
-- Example query on a dialect that supports 'pos' when match is not found
spark-sql (default)> SELECT LOCATE('a', 'abc', 2);
locate(a, abc, 2)
0
-- Incorrect transpilation (before this PR): Match hasn't been found but position offset is applied
postgres> SELECT STRPOS(SUBSTR('abc', 2), 'a') + 2 - 1;
?column?
----------
1
(1 row)
-- Correct transpilation (after this PR): Match is not found, position offset is not applied
postgres> SELECT CASE WHEN STRPOS(SUBSTR('abc', …
```
=> fix(postgres): Revert exp.StrPos generation, fix str_position_sql edge case

sqlglot/expressions.py, tests/test_build.py
Example:
```python
select("x")
.with_("v", as_=select("foo").from_("bar"), scalar=True)
.from_("t")
.where("id = v")
```
```sql
WITH (SELECT foo FROM bar) AS v
SELECT x FROM t WHERE id = v
```
=> feat(clickhouse): support scalar CTE in query builder

sqlglotrs/Cargo.lock, sqlglotrs/Cargo.toml, sqlglotrs/src/settings.rs, sqlglotrs/src/tokenizer.rs, sqlglotrs/src/trie.rs
mostly just to test the benchmark job but this improves parsing performance by 17% on long.
=> feat: move to rustc fx hashmap

sqlglot/dialects/tsql.py, tests/dialects/test_dialect.py
I found a cleaner way to implement `IS_ASCII` for TSQL. It is basically the same as the SQLite trick. See #4557
=> Feat!: Cleaner IS_ASCII for TSQL

sqlglot/dialects/oracle.py
Just like SQLite, Oracle does not support `LOGICAL_AND/OR`, but `MIN` and `MAX` work well. I covered the compilation path.
=> Feat: LOGICAL_AND and LOGICAL_OR for Oracle

sqlglot/optimizer/scope.py, tests/fixtures/optimizer/qualify_columns.sql
The optimizer currently errors when there are nested subqueries in a set operation, e.g.
```sql
((select a from x where a < 1)) UNION ((select a from x where a > 2))
```
Here's a little fix.
=> fix(optimizer): set operations on nested subqueries

sqlglot/dialects/dialect.py, tests/dialects/test_dialect.py
Fixes #4595
Further building upon https://github.com/tobymao/sqlglot/pull/3940 there was a gap whereby the UPDATE part of a MERGE query needed to be fully qualified if it's used within a function.
The specific example we had was when we were concatenating arrays but I've substituted for a coalesce in the unit test.
=> Fix!: exp.Merge condition for Trino/Postgres

sqlglot/dialects/oracle.py, tests/dialects/test_dialect.py, tests/dialects/test_tsql.py
Currently, SQLGlot transpiles all integer types to `NUMBER`. This is not the correct way, as `NUMBER` (with no parameters) is a float. This messed up type castings such as `cast(1.23 as int)` that would be transpiled to `cast(1.23 as number)`.
I changed this to `SMALLINT` and `INT` and updated the tests. You can also consider using `NUMBER(3, 0)` for say `TINYINT`, though I think there will be some performance penalty.
See the [docs](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#GUID-0BC16006-32F1-42B1-B45E-F27A494963FF).
=> Feat: Fix Oracle Integer Type Mapping

sqlglot/parser.py, tests/dialects/test_tsql.py
Fixes #4610
This PR adds support for using `DESC or ASC` in the `PRIMARY KEY` constraint definition.
Example:
`
CREATE TABLE db.t1 (a INTEGER, b VARCHAR(50), CONSTRAINT c PRIMARY KEY (a DESC))
`
**DOCS**
[T-SQL Constraints](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16#constraint)
=> fix(tsql): support PRIMARY KEY constraint with DESC, ASC #4610

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
These `FF[0-9]` [formats](https://docs.snowflake.com/en/sql-reference/data-types-datetime#date-and-time-formats) were introduced [a long time ago](https://github.com/tobymao/sqlglot/commit/8532f465beadcd0a49961bf601ffff4ea34bc7f9), but I don't think they were all correct. The `FF` one ends up roundtripping to `FF6` because the latter came after it in the mapping.
=> Fix(snowflake): get rid of incorrect time mappings

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_snowflake.py
Fixes https://github.com/tobymao/sqlglot/issues/4625
This PR adds support for Snowflake's `TO_TIME` & `TRY_TO_TIME` by mimicking the implementation of `TO_DATE`:
- The expression `exp.TsOrDsToTime` is chosen & enhanced with `format` and `safe` args
- Snowflake's `_build_datetime` can now handle `Type.TIME` kind (proxy for `TO_TIME`)
- The base generator of `exp.TsOrDsToTime` is extended to also account for `format` on other dialects, allowing transpilation of `TO_TIME( <string_expr> [, <format> ])`
After this PR, the following transpilations are enabled:
- Single argument:
```Python3
snowflake> SELECT TO_TIME(CONVERT_TIMEZONE('UTC', 'US/Pacific', '2024-08-06 09:10:00.000')) AS pst_time
PST_TIME
02:10:00
duckdb> SELECT CAST(CAST('2024-08-06 09:10:00.000' AS TIMESTAMP) AT TIME ZONE 'UTC' AT …
```
=> fix(snowflake)!: Allow parsing of TO_TIME & TRY_TO_TIME

sqlglot/dialects/trino.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_trino.py
Fixes #4623
This PR adds support for the QUOTES option of the JSON_QUERY.
Example:
```
parse_one("JSON_QUERY(description, 'strict $.comment' OMIT QUOTES ON SCALAR STRING)", dialect="trino")
JSONExtract(
this=Column(
this=Identifier(this=description, quoted=False)),
expression=Literal(this=strict $.comment, is_string=True),
json_query=True,
quote=JSONExtractQuote(option=OMIT, scalar=True))
```
**DOCS**
[Trino QUOTES option](https://trino.io/docs/current/functions/json.html#json-query)
=> fix(trino): support QUOTES option for JSON_QUERY #4623

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes https://github.com/tobymao/sqlglot/issues/4639
DuckDB does not implement Postgres's `~*` operator:
```SQL
postgres> SELECT 'ThOmAs' ~* 'thomas';
?column?
----------
t
(1 row)
duckdb> SELECT 'ThOmAs' ~* 'thomas';
Catalog Error: Scalar Function with name ~* does not exist!
Did you mean "~"?
LINE 1: SELECT 'ThOmAs' ~* 'thomas';
```
The next best solution as described in the issue is `REGEXP_MATCHES` with the `'i'` flag to account for the case-insensitive matching:
```SQL
duckdb>  SELECT REGEXP_MATCHES('ThOmAs', 'thomas', 'i');
┌─────────────────────────────────────────┐
│ regexp_matches('ThOmAs', 'thomas', 'i') │
│                 boolean                 │
├─────────────────────────────────────────┤
│ true                                    │
└─────────────────────────────────────────┘ …
```
=> fix(duckdb): Transpile exp.RegexpILike

sqlglot/optimizer/simplify.py, tests/fixtures/optimizer/simplify.sql
Fixes https://github.com/TobikoData/sqlmesh/issues/3672
Afaict it's only Postgres that cannot parse inline bracketed expressions such as the following:
- Before this PR
```Python3
>>> simplify(parse_one("SELECT (ARRAY_AGG(name))[1]")).sql()
'SELECT ARRAY_AGG(name)[1]'
```
```SQL
postgres> WITH sample_data AS (SELECT 'foo' AS name) SELECT ARRAY_AGG(name)[1] FROM sample_data;
ERROR:  syntax error at or near "["
LINE 1: ...a AS (SELECT 'foo' AS name) SELECT ARRAY_AGG(name)[1] FROM s...
```
- After
```Python3
>>> simplify(parse_one("SELECT (ARRAY_AGG(name))[1]")).sql()
'SELECT (ARRAY_AGG(name))[1]'
```
```SQL
postgres> WITH sample_data AS (SELECT 'foo' AS name) SELECT (ARRAY_AGG(name))[1] FROM sample_data;
array_agg
-----------
foo
(1 row)
```
=> fix(optimizer)!: Do not remove parens on bracketed expressions

.github/workflows/python-publish.yml
Took another shot at this... The difference was copied from the template printed using the latest `maturin` version using` maturin generate-ci github`.
=> Chore: fix sqlglotrs deployment job

sqlglot/dialects/trino.py, tests/dialects/test_trino.py
Prior to this change, `exp.LocationProperty` was parsed correctly but stripped entirely when generating SQL.
The reason for this is that the Trino dialect extends the Presto dialect and it was marked as `exp.Properties.Location.UNSUPPORTED` in the Presto dialect.
However, it is supported in Trino, in both [schemas](https://trino.io/docs/current/sql/create-schema.html#examples) and tables.
I've updated it to be `exp.Properties.Location.POST_WITH` and also treat it as a normal property instead of a naked property because it needs to be generated as `key=value` and not `key value`.
Before:
```
>>> parse_one("CREATE SCHEMA foo WITH (location = 's3://bucket')", dialect="trino").sql(dialect="trino")
Unsupported property locationproperty
'CREATE SCHEMA foo'
```
After:
```
>>> parse_one("CREATE …
```
=> Fix(trino): Correctly handle exp.LocationProperty

sqlglot/dialects/presto.py, tests/dialects/test_presto.py
=> Fix(Trino): Prevent first_value and last_value from being converted

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, tests/dialects/test_clickhouse.py
Fixes https://github.com/tobymao/sqlglot/issues/4662
As shown in the issue, the function-based representation doesn't work under `SETTINGS`:
```SQL
:) WITH table AS (SELECT 1) SELECT COUNT(1) FROM table SETTINGS additional_table_filters = map('table', 'tenant_id = 123');
Syntax error: failed at position 120 (end of query):
Expected one of: token, OpeningRoundBracket, FILTER, RESPECT NULLS, IGNORE NULLS, OVER, literal or map, literal, NULL, NULL, number, Bool, TRUE, FALSE, string literal, OpeningCurlyBrace
```
But the bracket notation does:
```
:) WITH table AS (SELECT 1) SELECT COUNT(1) FROM table SETTINGS additional_table_filters = {'table': 'tenant_id = 123'};
┌─COUNT(1)─┐
1. │        1 │
└──────────┘
```
<br/>
<br/>
This PR applies a bandaid solution for this issue in which `MAP(...)` …
=> fix(clickhouse): Generate bracket notation for exp.VarMap

sqlglot/dialects/trino.py, tests/dialects/test_trino.py
Fixes https://github.com/tobymao/sqlglot/issues/4672
The `CONDITIONAL` / `UNCONDITIONAL` keywords are optional, so this PR adds the missing `[ARRAY] WRAPPER` options for `WITH` / `WITHOUT`:
```
JSON_QUERY(
json_input [ FORMAT JSON [ ENCODING { UTF8 | UTF16 | UTF32 } ] ],
json_path
[ PASSING json_argument [, ...] ]
[ RETURNING type [ FORMAT JSON [ ENCODING { UTF8 | UTF16 | UTF32 } ] ] ]
[ WITHOUT [ ARRAY ] WRAPPER |
WITH [ { CONDITIONAL | UNCONDITIONAL } ] [ ARRAY ] WRAPPER ]
[ { KEEP | OMIT } QUOTES [ ON SCALAR STRING ] ]
[ { ERROR | NULL | EMPTY ARRAY | EMPTY OBJECT } ON EMPTY ]
[ { ERROR | NULL | EMPTY ARRAY | EMPTY OBJECT } ON ERROR ]
)
```
Docs
-------
[Trino JSON_QUERY](https://trino.io/docs/current/functions/json.html#json-query)
=> fix(trino): Add more JSON_QUERY options

sqlglot/parser.py, tests/dialects/test_postgres.py
Fixes https://github.com/tobymao/sqlglot/issues/4674
- AST before:
```Python3
>>> ast = sqlglot.parse_one("SELECT ARRAY[]::INT[]", dialect="postgres")
>>> ast
Select(
expressions=[
Cast(
this=DataType(
this=Type.ARRAY,
expressions=[
DataType(this=Type.ARRAY, nested=True)],
nested=True),
to=DataType(
this=Type.ARRAY,
expressions=[
DataType(this=Type.INT, nested=False)],
nested=True))])
```
<br/>
- AST after
```Python3
>>> ast = sqlglot.parse_one("SELECT ARRAY[]::INT[]", dialect="postgres")
>>> ast
Select(
expressions=[
Cast(
this=Array(
),
to=DataType(
this=Type.ARRAY,
expressions=[
DataType(this=Type.INT, nested=False)],
nested=True))])
```
<br/>
Note how before, the `ARRAY[]` would be confused into nesting itself even though on Postgres it's a 1-D array:
```SQL
psql> SELECT …
```
=> fix(postgres)!: Parse empty bracketed ARRAY with cast

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py, tests/dialects/test_presto.py
Fixes https://github.com/tobymao/sqlglot/issues/4670
https://github.com/tobymao/sqlglot/pull/3751 canonicalized BigQuery's inlined constructors into casts which may not be correct for certain roundtrips, as shown in the issue:
- Safe
```SQL
bq> SELECT ARRAY<INT64>[1, 2, 3], CAST([1, 2, 3] AS ARRAY<INT64>);
f0_	f1_
"[1,2,3]"	"[1,2,3]"
```
<br/>
- Not safe (type mismatch)
```SQL
bq> SELECT CAST([1, 2, 3] AS ARRAY<FLOAT64>);
Casting between arrays with incompatible element types is not supported: Invalid cast from ARRAY<INT64> to ARRAY<FLOAT64> at [1:13]
```
<br/>
<br/>
This PR fixes this particular scenario by preserving the inlined `ARRAY` type annotation & literal value for BQ's roundtrip.
Docs
-------
[BQ ARRAY Literals](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-t …
=> fix(bigquery)!: Inline type-annotated ARRAY literals

sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/expressions.py, tests/dialects/test_duckdb.py, tests/dialects/test_postgres.py
Fixes #4667
`duckdb` only supports the `JSON_GROUP_OBJECT` aggregate function (`JSONB` isn't supported), thus for both 
`JSON/JSONB_OBJECT_AGG` cases the mapping is the `JSON_GROUP_OBJECT` function.
Moreover, the roundtrip for the postgres `JSON/JSONB_OBJECT_AGG` is preserved.
**DOCS**
[DuckDB JSON_GROUP_OBJECT](https://duckdb.org/docs/data/json/json_functions#json-aggregate-functions) | [Postgres  JSON/JSONB_OBJECT_AGG ](https://www.postgresql.org/docs/9.5/functions-aggregate.html)
=> fix(duckdb): support postgres JSON/JSONB_OBJECT_AGG to duckdb JSON_GROUP_OBJECT

sqlglot/dialects/tsql.py, tests/dialects/test_oracle.py
Fixes https://github.com/tobymao/sqlglot/issues/4665
Dialects like Oracle can `FETCH` directly from a result set:
```SQL
oracle>  WITH t AS (SELECT 1 AS col UNION SELECT 2 AS col UNION SELECT 3 as col) 
SELECT * FROM t FETCH FIRST 2 ROWS ONLY;
col
1
2
```
<br/>
T-SQL has the concept of OFFSET-FETCH which are defined under an ORDER BY clause. Thus, a possible transpilation is the following:
```SQL
tsql> WITH t AS (SELECT 1 AS col UNION SELECT 2 AS col UNION SELECT 3 AS col) 
SELECT * FROM t AS ROWS ORDER BY (SELECT NULL) OFFSET 0 ROWS FETCH FIRST 2 ROWS ONLY
col
1
2
```
Docs
--------
[T-SQL OFFSET-FETCH](https://www.sqlservertutorial.net/sql-server-basics/sql-server-offset-fetch/) | [Oracle FETCH](https://www.oracletutorial.com/oracle-basics/oracle-fetch/)
=> fix(tsql): Transpile standalone exp.Fetch LIMIT

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_oracle.py
Fixes #4682
This only covers the `CAST` example, left the second one out for now, @jaredschwartz-ofs feel free to tackle it in a follow up if you need it.
=> Feat(oracle): add support for CAST(... DEFAULT <value> ON CONVERSION FAILURE)

sqlglot/dialects/hive.py, tests/dialects/test_hive.py, tests/dialects/test_spark.py
To facilitate Hive -> Presto [transpilation](https://github.com/tobymao/sqlglot/issues/831#issuecomment-1363629299) of `DATE_FORMAT`, https://github.com/tobymao/sqlglot/commit/0f9216647179aa28292984a9c25b53e9677cce1c casted the 1st arg into a `TIMESTAMP` by wrapping it in `exp.TimeStrToTime`. 
However, this is not required for Hive's roundtrip since it can process all date/time types, e.g:
- Spark 2:
```SQL
spark2> spark.sql("SELECT DATE_FORMAT(CAST('2020-01-01' AS TIMESTAMP), 'yyyy-MM-dd HH:mm:ss') AS cast, 
DATE_FORMAT('2020-01-01', 'yyyy-MM-dd HH:mm:ss') AS no_cast").show();
+-------------------+-------------------+
|               cast|            no_cast|
+-------------------+-------------------+
|2020-01-01 00:00:00|2020-01-01 00:00:00|
+-------------------+-------------------+
``` …
=> fix(hive): Simplify DATE_FORMAT roundtrip

sqlglot/dialects/__init__.py, sqlglot/dialects/dialect.py, tests/dialects/test_dialect.py
When sqlglot is imported for the first time, all dialects are eagerly imported. The time needed for this is small, but not necessarily insignificant. This PR makes the dialect loading & registering lazy.
<details>
<summary> Benchmark results for <b>make check</b> & import time (BEFORE) </summary>
```
(.venv) ➜  sqlglot git:(main) make check
pre-commit run --all-files
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed
SQLGLOTRS_TOKENIZER=0 python -m unittest
..................................................................................................................................................... …
```
=> Fix!: load dialects lazily

sqlglot/dialects/tsql.py, sqlglot/parser.py, tests/dialects/test_tsql.py
`BEGIN` is a reserved keyword in TSQL, thus it can't be used as an identifier of any purpose.
This PR removes the usage of `BEGIN` for this occasion. 
Moreover, this PR removes the `INTERVAL_VARS` from the base `Parser` class because it isn't needed any more.  
**DOCS**
[T-SQL BEGIN](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?view=sql-server-ver16#syntax)
=> fix(tsql): remove BEGIN from identifiers

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes #4694 
This PR adds support for the AUTO INCREMENT transpilation for `Snowflake`. 
It's similar to the `SQLite`. 
**DOCS**
[Snowflake AUTOINCREMENT](transpilation)
=> fix(snowflake): support correct AUTO INCREMENT transpilation

sqlglot/dialects/redshift.py, sqlglot/generator.py, tests/dialects/test_redshift.py
Reference: https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
=> Fix(redshift): generate proper syntax for column type alteration

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py, tests/test_transpile.py
DuckDB [supports user-defined types](https://duckdb.org/docs/sql/statements/create_type.html):
```
D create type foo as integer;
D select x::foo from (select 1 x) t;
┌────────────────┐
│ CAST(x AS foo) │
│     int32      │
├────────────────┤
│              1 │
└────────────────┘
```
This was probably added after we added support for them in SQLGlot.
=> Fix(duckdb): enable support for user-defined types

sqlglot/dialects/dialect.py, sqlglot/expressions.py, sqlglot/parser.py
Vaggelis mentioned that as he was iterating locally, he saw an error like `dialect 'postgres' not found. Did you mean 'postgres'?`. This can happen when making changes to dialects themselves that result in an exception at module load time, because the exception is nullified => we fail to register the dialect => sqlglot crashes at runtime.
I refactored the try-except block in order to avoid hiding exceptions. This is consistent with what we do in `dialects/__init__.py` ([source](https://github.com/tobymao/sqlglot/blob/5f9030786f8489e70aee70acabee440ecf23699c/sqlglot/dialects/__init__.py#L111-L112)).
=> Fix: avoid concealing dialect module exception in _try_load

sqlglot/dialects/postgres.py, tests/dialects/test_dialect.py
This PR transpiles the `COUNT_IF` function found in BQ, Snowflake etc into Postgres:
- Used as aggregate
```SQL
bigquery> SELECT COUNTIF(x<0) AS num_negative, COUNTIF(x>0) AS num_positive
FROM UNNEST([5, -2, 3, 6, -10, -7, 4, 0]) AS x;
num_negative	num_positive
3	        4
postgres> SELECT SUM(CASE WHEN x < 0 THEN 1 ELSE 0 END) AS num_negative, SUM(CASE WHEN x > 0 THEN 1 ELSE 0 END) AS num_positive 
FROM UNNEST(ARRAY[5, -2, 3, 6, -10, -7, 4, 0]) AS _t0(x);
num_negative | num_positive
--------------+--------------
3 |            4
```
<br />
- Used as window
```SQL
bigquery> SELECT
x,
COUNTIF(x<0) OVER (ORDER BY ABS(x) ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS num_negative FROM UNNEST([5, -2, 3, 6, -10, NULL, -7, 4, 0]) AS x;
x	num_negative
0
0	1
-2	1
3	1
4	0
5	0
6	1
-7	2
-10	2 …
```
=> feat(postgres): Support generation of exp.CountIf

sqlglot/dialects/tsql.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_tsql.py
This PR adds support:
1. For default initialization of both input parameters and declared variables (e.g. `CREATE PROCEDURE test(@input INT = 1`, `DECLARE @var AS INTEGER = 1`) 
2. The `OUTPUT/OUT/READONLY`  keywords, which primarily serve to return scalar values or enforce immutability (e.g. `CREATE PROCEDURE test(@out_var INT OUTPUT)`)
**DOCS**
[T-SQL Stored Procedures Paramaters](https://learn.microsoft.com/en-us/sql/relational-databases/stored-procedures/specify-parameters?view=sql-server-ver16)
=> fix(tsql): support default values on definitons and the OUTPUT/OUT/READ_ONLY syntax

sqlglot/dialects/spark.py, sqlglot/dialects/tsql.py, sqlglot/expressions.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_dialect.py, tests/dialects/test_postgres.py, tests/dialects/test_tsql.py
This PR addresses some UUID support issues with T-SQL and Postgres. A small example of what I wanted to get working:
Input: sqlglot.transpile('create table x (i uniqueidentifier not null default(newid()))', read='tsql', write='postgres')
Output: ['CREATE TABLE x (i UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()))']
Expected: ['CREATE TABLE x (i uuid NOT NULL DEFAULT (gen_random_uuid()))']
- Removed unnecessary UNIQUEIDENTIFER token (standardized on UUID)
- Added NEWID() support to T-SQL
- Cleaned up Spark UUID support, which I noticed was also broken. (I think Hive might be, too, but I don't know for a fact so I didn't touch that one.)
=> fix(tsql, postgres)!: Improve UUID support

sqlglot/parser.py, tests/dialects/test_clickhouse.py
Fixes https://github.com/tobymao/sqlglot/issues/4723 by adding an additional allowed token when parsing column definitions with an aggregate function type. Note that while the specific issue manifests itself for the `clickhouse` dialect, the issue could potentially apply to any dialect supporting aggregate functions which support using a keyword function like `any` in the column type.
=> fix: Add additional allowed tokens for parsing aggregate functions in DDL

sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/expressions.py, tests/dialects/test_dialect.py, tests/dialects/test_duckdb.py, tests/dialects/test_spark.py, tests/dialects/test_tsql.py
Fixes https://github.com/tobymao/sqlglot/issues/4710
This PR solves two legacy issues:
1. `MAP`s do not return `LIST`s anymore but values (1.2 change):
```SQL
spark3> SELECT MAP('key', 'value')['key'] AS col;
col
value
duckdb> SELECT (MAP(['key'], ['value'])['key'])[1] AS col;
┌─────────┐
│   col   │
│ varchar │
├─────────┤
│ v       │
└─────────┘
duckdb> SELECT MAP(['key'], ['value'])['key'] AS col;
┌─────────┐
│   col   │
│ varchar │
├─────────┤
│ value   │
└─────────┘
```
<br />
2. Inline indexed `LIST`s do not need to be wrapped anymore (this was fixed earlier in the year iirc):
```SQL
spark-sql (default)> SELECT TRY_ELEMENT_AT(ARRAY(1, 2, 3), 2) AS col;
col
2
duckdb> SELECT ([1, 2, 3])[2] AS col;
┌───────┐
│  col  │
│ int32 │
├───────┤
│   2   │
└───────┘
duckdb> SELECT [1, 2, 3][2] …
```
=> fix(duckdb)!: Remove extra MAP bracket and ARRAY wrap

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Fixes https://github.com/tobymao/sqlglot/issues/4728
DuckDB's `_date_delta_sql` would preemptively construct an `INTERVAL` for the RHS, but that is not needed for roundtrips where the `expression.expression` is already one.
After this PR:
```SQL
D SELECT DATE_ADD(CAST('2020-01-01' AS DATE), INTERVAL 1 DAY);
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ date_add(CAST('2020-01-01' AS DATE), to_days(CAST(trunc(CAST(1 AS DOUBLE)) AS INTEGER))) │
│                                        timestamp                                         │
├──────────────────────────────────────────────────────────────────────────────────────────┤
│ 2020-01-02 00:00:00                                                                      │ …
```
=> fix(duckdb): Fix INTERVAL roundtrip of DATE_ADD

sqlglot/dialects/mysql.py, sqlglot/expressions.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_mysql.py
This PR adds a `UDOUBLE` type. 
Accordingly [mysql documentation](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html) this feature is deprecated but still has support due past versions, turning the column as regular double type.
```sql
CREATE TABLE `bar` (`abacate` DOUBLE(10, 2) UNSIGNED NOT NULL);
```
```sql
SELECT COLUMN_NAME, DATA_TYPE FROM information_schema.columns WHERE table_name = 'bar' AND column_name = 'abacate';
```
RESULT:
=> feat(mysql): add unsigned double type

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py, tests/fixtures/optimizer/qualify_columns.sql
Fixes #4740
cc @cpcloud ClickHouse now supports table aliases with column names, relevant past ticket [here](https://github.com/tobymao/sqlglot/issues/3726).
=> Fix(clickhouse)!: add generate_series table column alias

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
When transpiling from e.g. oracle `select to_date(substr(nullable_column, 1,10), 'YYYY-MM-DD')` to clickhouse the following 
`SELECT CAST(STR_TO_DATE(SUBSTRING(nullable_column, 1, 10), '%Y-%m-%d') AS DATE)` which fails `Cannot convert NULL value to non-Nullable type: while executing`.
By this PR we ask sqlglot to use already existing cast method which respects data types nullity while transpiling.
=> Fix(clickhouse)!: respect type nullability when casting in strtodate_sql

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Fixes https://github.com/tobymao/sqlglot/issues/4751
Docs
-------
[CH arrayConcat](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arrayconcat)
=> fix(clickhouse): Generation of exp.ArrayConcat

sqlglotrs/src/tokenizer.rs, tests/test_transpile.py
=> Fix(tokenizer-rs): use is_whitespace in token scan loop

sqlglot/dialects/sqlite.py, tests/dialects/test_sqlite.py
Fixes #4770 
Replacing the separator of `JSON_OBJECT` from `":"` to `","`
**DOCS**
[SQLite JSON_OBJECT](https://www.sqlite.org/json1.html#jobj)
=> fix(sqlite): correct json key value pair separator

sqlglot/optimizer/qualify_tables.py, tests/test_optimizer.py
Addresses the issue reported in https://github.com/tobymao/sqlglot/pull/4767, cc @zeta9044.
The problem here is that pivoted tables show up as scope "sources", where the source itself is a `Table`, [regardless](https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/scope.py#L722) of the pivoted table being a CTE (unpivoted CTE references are stored as `Scope` sources). This leads `qualify_tables` to qualify CTE references as well.
Simple script to reproduce:
```python
sql = """
INSERT INTO sales_summary
WITH sales_by_quarter AS (
SELECT * FROM t
)
SELECT *
FROM sales_by_quarter
PIVOT(
SUM(total_amount)
FOR quarter IN ('Q1', 'Q2', 'Q3', 'Q4')
)
ORDER BY product_name;
"""
from sqlglot import parse_one
from sqlglot.optimizer.qualify import qualify
from sqlglot.optimizer.scope import …
```
=> Fix(optimizer): do not qualify ctes that are pivoted

sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, sqlglot/generator.py
cc @pkit, check out https://github.com/TobikoData/sqlmesh/pull/3877 for context. We should be more careful and make sure `Expression` subclasses can always be generated in the base dialect.
=> Chore: remove redundant "parts" arg from CH ast, move gen methods to base

sqlglot/optimizer/scope.py
example test code
```
query = """
SELECT group_name, GROUP_CONCAT(name, ', ') WITHIN GROUP (ORDER BY sub_group_name NULLS LAST) AS sub_group_name
FROM department 
GROUP BY group_name
"""
parsed_query = parse_one(query)
qualified_query = qualify(parsed_query, schema={"department": {"group_name": "string", "sub_group_name": "string", "name": "string"}})
print(qualified_query.sql(pretty=True))
```
current output
```
SELECT
"department"."group_name" AS "group_name",
GROUP_CONCAT("department"."name", ', ') WITHIN GROUP (ORDER BY
"sub_group_name" NULLS LAST) AS "sub_group_name"
FROM "department" AS "department"
GROUP BY
"department"."group_name"
```
after fix 
```
SELECT
"department"."group_name" AS "group_name",
GROUP_CONCAT("department"."name", ', ') WITHIN GROUP (ORDER BY …
```
=> Fix(optimizer): column qualify not applying in an order by inside within group when it also the alias

sqlglot/parser.py, tests/fixtures/optimizer/qualify_columns.sql
Fixes #4791
This is the example I used to conclude that aliases take precedence over table columns:
```
D WITH t AS (SELECT 1 AS x, 'a' AS y UNION ALL SELECT 1 AS x, 'b' AS y) SELECT DISTINCT ON (x) x::varchar || y AS x, y AS y FROM t;
┌─────────┬─────────┐
│    x    │    y    │
│ varchar │ varchar │
├─────────┼─────────┤
│ 1b      │ b       │
│ 1a      │ a       │
└─────────┴─────────┘
```
The behavior is consistent across Postgres, DuckDB and ClickHouse. I tested many of the remaining dialects (*) but they don't seem to support `DISTINCT ON (...)`, so this shouldn't affect them.
(*) BigQuery, Databricks, MySQL, Oracle, Redshift, Snowflake, Spark, Trino, T-SQL
=> Fix(optimizer)!: parse unqualified names in DISTINCT ON (...) as identifiers

sqlglot/optimizer/annotate_types.py, tests/fixtures/optimizer/annotate_functions.sql
Fixes #4792
Decided to avoid any coercions when type parameters are present, to avoid dealing with:
- Are we dealing with something like `VARCHAR(MAX)`, where the parameter is a `Var`?
- Are there two parameters in the source type? if so, do we require that the target type (a) also has two parameters and (b) all of them are numbers and both parameters in source are smaller than their counterparts in target? E.g., do we only coerce in cases like `DECIMAL(18, 2) -> DECIMAL(20, 3)`? Is this coercion correct across different dialects? Etc.
=> Fix(optimizer)!: do not coerce parameterized types

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Parse as expression, rather than command. These are issued by the Snowflake JDBC driver.
Refs:
https://docs.snowflake.com/en/sql-reference/sql/show-databases
https://docs.snowflake.com/en/sql-reference/sql/show-functions
https://docs.snowflake.com/en/sql-reference/sql/show-procedures
https://docs.snowflake.com/en/sql-reference/sql/show-warehouses
NB: `show databases in account` is valid syntax, although its not mentioned above. See the Snowflake JDBC driver's usage [here](https://github.com/snowflakedb/snowflake-jdbc/blob/dcb60b2905ca512c417a90ab08a87305e31e486c/src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java#L1648).
=> feat(snowflake)!: show databases, functions, procedures and warehouses 

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_tsql.py
Fixes #4793
This PR adds support for using `PERCENT` and `WITH TIES` alongside the `TOP` command in T-SQL. 
Moreover, the base parsing method `limit` and the base generator method `fetch` have been refactored.
**DOCS**
[T-SQL TOP PERCENT/WITH TIES](https://learn.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql?view=sql-server-ver16#syntax)
=> fix(tsql)!: support TOP with PERCENT and WITH TIES

sqlglotrs/src/tokenizer.rs, tests/dialects/test_dune.py
This is the current behavior:
```python
>>>
>>> for hex_literal in (
...     "0xdeadbeef",
...     "0xdeadbeefdead",
...     "0xdeadbeefdeadbeef",
...     "0xdeadbeefdeadbeefde",
...     "0xdeadbeefdeadbeefdead",
...     "0xdeadbeefdeadbeefdeadbeef",
...     "0xdeadbeefdeadbeefdeadbeefdeadbeef",
... ):
...     print(type(sqlglot.parse_one(hex_literal, read="dune")))
...
<class 'sqlglot.expressions.HexString'>
<class 'sqlglot.expressions.HexString'>
<class 'sqlglot.expressions.HexString'>
<class 'sqlglot.expressions.Column'>
<class 'sqlglot.expressions.Column'>
<class 'sqlglot.expressions.Column'>
<class 'sqlglot.expressions.Column'>
```
The reason we get `Column`s starting at `0xdeadbeefdeadbeefde` is because we …
=> Fix(tokenizer-rs)!: make hex literal tokenization more robust

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
Clickhouse has `GLOBAL NOT IN` variant https://clickhouse.com/docs/sql-reference/operators/in. Superset 4.1 is conservatively refusing a `GLOBAL NOT IN` query as not-read-only.
I parsed the keyword into a new `exp.In` flag `is_negated`, but I'm not sure if a richer datatype for `is_global` make sense.
Hope this helps.
=> feat(clickhouse): support `GLOBAL NOT IN`

sqlglot/dialects/presto.py, sqlglot/dialects/trino.py, sqlglot/expressions.py, tests/dialects/test_trino.py
Fixes https://github.com/TobikoData/sqlmesh/issues/3905
This doesn't cover the full syntax spec yet, just the `... ON {EMPTY|ERROR}` clause.
Reference: https://trino.io/docs/current/functions/json.html#json-query
=> Feat(trino): add support for ON ... ERROR/NULL syntax for JSON_QUERY

sqlglot/transforms.py, tests/test_transforms.py
Currently there is a problem if a join with join marks has multiple conditions because a new join is created every time, there is a column with a join mark. This reset the parent of the joined table and the link is lost which breaks the tree consistency down
Example:
```
s = "select a.id from a, b where a.id = b.id (+) and b.d (+) = const"
tree = parse_one(s, dialect="oracle")
print("before", [type(t.parent_select) for t in tree.find_all(exp.Table)])
eliminate_join_marks(tree)
print("after", [type(t.parent_select) for t in tree.find_all(exp.Table)])
```
outputs
```
before [<class 'sqlglot.expressions.Select'>, <class 'sqlglot.expressions.Select'>]
after [<class 'sqlglot.expressions.Select'>, <class 'NoneType'>]
```
against expected 
```
before [<class 'sqlglot.expressions.Select'>, <class …
```
=> fix: orphan node(s) in eliminate_join_marks

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_mysql.py
MySQL 8.0 introduced the [ability to hide and unhide columns]. Columns can be hidden in a `CREATE TABLE` statement (currently unimplemented in `sqlglot`) and can be subsequently changed with an `ALTER TABLE` syntax: `ALTER COLUMN x SET {VISIBLE|INVISIBLE}`.
This commit adds support for column hiding through the `ALTER TABLE` syntax. However, it does so in a MySQL-specific way. Other RDBMSs have similar support for column hiding, but implement it slightly differently:
* Oracle uses `MODIFY x INVISIBLE`
* DB2 uses `ALTER x t IMPLICITLY HIDDEN`
* SQLServer uses `ALTER x ADD HIDDEN`
As there is no other dialect in `sqlglot` that implements invisibility, and because the parser currently maintains other dialect-specific implementations, I wasn't sure if the amount of effort to refactor the …
=> Support setting visibility on `ALTER COLUMN`.

sqlglot/parser.py, tests/dialects/test_clickhouse.py
count is the only agg function that may not have argument at all
=> clickhouse: fix unparseable `AggregateFunction(count)`

sqlglot/dialects/duckdb.py, tests/dialects/test_bigquery.py
Fixes https://github.com/tobymao/sqlglot/issues/4815
The diffs besides `SHA256` are to ab-sort the dict. After this PR:
```python3
>>> sqlglot.parse_one("SHA256(x)", dialect="duckdb").sql("snowflake")
'SHA2(x, 256)'
```
Docs
----------
[DuckDB](https://duckdb.org/docs/stable/sql/functions/utility.html#sha256value) |  [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/sha2#syntax)
=> fix(duckdb): Parse SHA256

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/trino.py, sqlglot/parser.py, tests/dialects/test_bigquery.py, tests/dialects/test_redshift.py, tests/dialects/test_snowflake.py
Fixes https://github.com/tobymao/sqlglot/issues/4821
This PR generalizes Trino's `groupconcat_sql` to enable transpilation between other dialects and to simplify the various overlapping generators.
Some dialect support `LISTAGG(...) WITHIN GROUP (ORDER BY ...)` while others `LISTAGG(... ORDER BY ...).
Docs
--------
[DuckDB](https://duckdb.org/docs/stable/sql/functions/aggregates.html#string_aggarg-sep) | [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/listagg) | [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#string_agg) | [Trino](https://trino.io/docs/current/functions/aggregate.html#listagg)
=> fix(duckdb, snowflake)!: Refactor exp.GroupConcat generation

sqlglot/dialects/oracle.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_oracle.py
Fixes #4826
Add support for the `FORCE` property, when creating a view in Oracle. 
**DOCS**
[Oracle FORCE](https://docs.oracle.com/cd/B13789_01/server.101/b10759/statements_8004.htm)
=> feat(oracle): add FORCE property

sqlglot/parser.py
This PR refactors `_parse_user_defined_function` by using the `_parse_table_parts` instead of manually parsing all the dots.
=> refactor!: use _parse_table_parts for udf parsing

sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
The [HEX_DECODE_BINARY](https://docs.snowflake.com/en/sql-reference/functions/hex_decode_binary) function is equivalent to the `Unhex` function that is already supported by sqlglot. To support it, we just had to add the map in snowflake and add the transform in duckdb.
Partially solves #4852, we still need to add support for `HEX_DECODE_STRING`.
Testing:
Duckdb ([playground](https://codapi.org/embed/?sandbox=duckdb&code=data%3A%3Bbase64%2CK07NSU0uUeBKK8rPjc9IrdBQNzNV19RRKKksSM1P00AV1tThSklNzk9JxRCHqccuranDVZqHaTiSGMJkZEEA))
Bigquery
(Note that Bigquery outputs binary data (bytes) in base64)
Snowflake
(Note that Snowflake outputs binary data in hex format)
=> fix(snowflake): add support for HEX_DECODE_BINARY

sqlglot/dialects/dialect.py, sqlglot/dialects/oracle.py, sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes #4857
Add support for the transpilation of `TO_CHAR` of snowflake to duckdb's `STRFTIME`.
**DOCS**
[Snowflake TO_CHAR](https://docs.snowflake.com/en/sql-reference/functions/to_char) | [DuckDB STRFTIME](https://duckdb.org/docs/stable/sql/functions/dateformat.html)
=> fix(snowflake)!: support TO_CHAR to duckdb STRFTIME

.github/workflows/python-package.yml, .github/workflows/python-publish.yml, .gitignore, pyproject.toml, setup.py, sqlglot/expressions.py, sqlglotrs/pyproject.toml
This moves the bulk of the `setup.py` declarations to `pyproject.toml` and builds packages using `python -m build` instead of invoking setuptools directly.
Note that this just affects Python sqlglot, sqlglot-rs already uses `pyproject.toml` and has a build process based on maturin.
I checked that the wheel and sdist files produced by `python -m build` contained the same files as before, in particular the `py.typed` marker and a correct `extras` declaration for `[rs]` with the version parsed from Cargo.toml
=> Chore!: Introduce pyproject.toml and switch to packaging via build

sqlglot/expressions.py, tests/test_expressions.py
This PR introduces lazy query resolution to the exp.expand function, significantly enhancing its efficiency and flexibility. Previously, expanding a query required a complete dictionary of all possible source queries upfront, which could be inefficient for large datasets with thousands of views. This approach necessitated either prior knowledge of all referenced tables or a costly recursive traversal to gather them, leading to unnecessary parsing overhead when only a subset of queries needed expansion.
---
Queries can now be resolved on demand, eliminating the need for pre-parsing all queries and improving performance.
A new abstract class, QueryProvider, has been added to define a standardized interface for retrieving queries by name.
A default implementation ensures backward …
=> Add a query provider to the expand function, enabling lazy loading of queries during AST transformations.

sqlglot/expressions.py, tests/test_expressions.py
This is a fix to the nice new feature added in [#4872 ](https://github.com/tobymao/sqlglot/pull/4872).
The issue is that in the way it is implemented, there was an inconsistency if passing sources a `Callable` or a string.
For strings, normalization happens by the `expand` function. For callables, it doesn't. So for example the following calls would have different results.
It's expected for the same name to be resolved to the same query, so normalization should be consistent regardless of lazy parsing.
I changed the implementation a bit so that it is back to only accepting a dict, but values are allowed to be callables with no arguments. This makes the handling of lazy and non-lazy `Query` objects almost identical.
running this:
```Python
expand(parse_one("""select * from "a-b"."C" AS …
```
=> fix: expand util - align normalization behaviour with lazy and non-lazy source providers.

sqlglot/dialects/hive.py, tests/dialects/test_hive.py
Fixes #4871
This PR adds support for `STRUCT(*)` and `MAP(*)` for hive, spark, spark2, databricks dialects.
=> fix(hive)!: support STRUCT(*) and MAP(*)

sqlglot/optimizer/simplify.py, tests/fixtures/optimizer/simplify.sql
Motivated by the following behavior in Redshift. Turning `COALESCE(x, 1) = 2` into `NOT x IS NULL AND x = 2` can lead to different results.
=> Fix(redshift)!: turn off multi-arg coalesce simplification

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes support for creating temporary tables as select statements in T-SQL. The syntax is the same as selecting into a physical table, except that T-SQL uses a `#` symbol to denote a temp table, and a `##` to denote a global temp table.
This commit will slightly change the AST representation of the query, such that the `Table` expression is marked as `temporary` rather than its `Identifier` expression. This seems to be consistent with other dialects that support `select...into` syntax, e.g. postgres.
Here's a basic example:
```python
>>> sqlglot.parse_one("SELECT 1 INTO #foo", dialect="tsql")
Select(
expressions=[
Literal(this=1, is_string=False)],
into=Into(
this=Table(
this=Identifier(this=FOO, quoted=False, temporary=True))))
Select(
expressions=[
Literal(this=1, is_string=False)], …
```
=> fix!(tsql): support select...into #temp_table syntax

sqlglot/optimizer/pushdown_projections.py
If a set operation has a column number mismatch, then we raise an OptimizeError instead of IndexError in line 68 which might make things confusing regarding the source of the exception
=> feat: Add a check and error message for set operations in pushdown_projections

sqlglot/expressions.py, tests/test_expressions.py
=> Fix: preserve whitespace in quoted identifiers and strings

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
SQLGlot currently infers a `TIMESTAMP` type for functions like `CURRENT_TIMESTAMP` in BigQuery, which is problematic because this type is mapped to `DATETIME` to facilitate transpilation.
```python
>>> from sqlglot.optimizer.annotate_types import annotate_types
>>>
>>> annotate_types(parse_one("SELECT CURRENT_TIMESTAMP()", "bigquery"), dialect="bigquery").selects[0].type
DataType(this=Type.TIMESTAMP)
>>> annotate_types(parse_one("SELECT CURRENT_TIMESTAMP()", "bigquery"), dialect="bigquery").selects[0].type.sql("bigquery")
'DATETIME'
```
This PR changes the type inference logic so that we annotate the functions with `TIMESTAMPTZ` instead.
=> Fix(optimizer)!: infer timestamp function types as TIMESTAMPTZ for bigquery

sqlglot/optimizer/merge_subqueries.py, tests/fixtures/optimizer/merge_subqueries.sql
The current check is broken (selected_sources returns the inner Select instance, not the Subquery instance), but this code doesn't usually get exercised because `eliminate_subqueries` runs first.
But I don't know yet know how I'll install this change... without 3.7 support, we might need to fork 😓
=> fix(optimizer): Merge subqueries when inner has subquery name conflict with outer

sqlglot/dialects/sqlite.py, sqlglot/expressions.py, tests/dialects/test_sqlite.py
Fixes #4938
**DOCS**
[SQLite double quotes identifier](https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted)
=> fix(sqlite): transpile double quoted PRIMARY KEY

sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_duckdb.py
Addresses the first item in #4944
=> Feat(duckdb): add support for GROUP clause in standard PIVOT syntax

sqlglot/dialects/athena.py, tests/dialects/test_athena.py
Prior to this, if a CTAS query contained a Union, eg:
```
CREATE TABLE foo AS
SELECT * FROM a
UNION
SELECT * FROM b
```
Then it would be incorrectly quoted as Hive / backticks and not Trino / quotes
This PR loosens the "should this be Trino?" check to use the `exp.Query` base class instead of just `exp.Select`, so `exp.Union` is now detected correctly.
This addresses https://github.com/TobikoData/sqlmesh/issues/4091
=> Fix(athena): Correctly handle CTAS queries that contain Unions

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/optimizer/pushdown_projections.py, sqlglot/optimizer/qualify_columns.py, sqlglot/parser.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/qualify_columns.sql
Fixes https://github.com/tobymao/sqlglot/issues/4942
This PR introduces support for the `BY NAME` & `CORRESPONDING` modifiers as are laid out in the docs; The latter is canonicalized into the former based on the facts that:
- `{SET_OP} STRICT CORRESPONDING [BY (col1, ...)]` == `{SET_OP} BY NAME [ON (col1, ...)]`
- `{SET_OP} CORRESPONDING` == `INNER {SET_OP} BY NAME`
- `{LEFT | FULL} [OUTER] {SET_OP} CORRESPONDING` == `{LEFT | FULL} [OUTER] {SET_OP} BY NAME` 
Docs
--------
[BQ Set Operators](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators) | [BQ BY NAME / CORRESPONDING modifiers](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#by_name_or_corresponding)
=> feat(bigquery): Add support for side & kind on set operators

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
=> fix: support SHOW (ALL) TABLES for duckdb

sqlglot/parser.py, tests/dialects/test_spark.py
Small lift to support things like `@IF(cond, <expression> as column)` in SQLMesh. SQLGlot does not parse this today and SQLMesh fails to parse things like `SELECT @IF(cond, a AS b) FROM t`, because it falls back to its [statement parser logic](https://github.com/TobikoData/sqlmesh/blob/8db57008b53cdde59c12fa3298c910cff2440c4d/sqlmesh/core/dialect.py#L520-L543) and expects an `)` after the `true` arg:
```sqlglot.errors.ParseError: Expecting ). Line 1, Col: 18.
select @IF(cond, a as b) from t
~
```
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1744207056323959
=> Feat: allow explicit aliasing in if(...) expressions

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, sqlglot/dialects/duckdb.py, sqlglot/dialects/postgres.py, sqlglot/dialects/presto.py, sqlglot/dialects/snowflake.py, sqlglot/executor/__init__.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/helper.py, sqlglot/optimizer/canonicalize.py, sqlglot/parser.py, tests/dialects/test_bigquery.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py, tests/test_optimizer.py
Fixes #4967
Cleaned up a few `annotate_types` calls. Let's remember including the `dialect` argument to ensure things don't silently break in the future when type inference changes for a dialect.
=> Feat!: ensure JSON_FORMAT type is JSON when targeting Presto

sqlglot/dialects/clickhouse.py, tests/dialects/test_clickhouse.py
First of all, thank you for an amazing library! 🙏 
In ClickHouse, our team uses the `ON CLUSTER` clause with a string macro that is evaluated by the server, like so: `ON CLUSTER '{cluster}'`.
The problem is that queries using the macro string literal:
```
CREATE TABLE foo ON CLUSTER '{cluster}' ...
```
will be parsed and re-generated with a double-quoted identifier
```
CREATE TABLE foo ON CLUSTER "{cluster}" ...
```
This is incorrect because the double-quoted identifier `{cluster}` is not a valid cluster name. The parser should accept the string literal `'{cluster}'`.
In the ClickHouse source, parsing the ON CLUSTER clause uses a function called `parseIdentifierOrStringLiteral`
ON CLUSTER: https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTQueryWithOnCluster.cpp#L24 …
=> fix(clickhouse): allow string literal for clickhouse ON CLUSTER clause

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
With the recent changes in #4947 , we are now able to parse `CREATE STAGE` statements into `exp.Create` (which is awesome! 🎉 ).
We've discovered one small discrepancy related to specifying a `FILE_FORMAT` via a file format name. While this is the canonical syntax [mentioned in the docs](https://docs.snowflake.com/en/sql-reference/sql/create-stage):
```
CREATE STAGE mystage FILE_FORMAT = ( FORMAT_NAME = 'myformat' )
```
... Snowflake also accepts these shorthand syntaxes, specifying the file format name/identifier directly (I've verified that against my Snowflake account):
```
CREATE STAGE mystage FILE_FORMAT = 'myformat'
CREATE STAGE mystage FILE_FORMAT = mystage.myformat
```
---
Note that if you try to parse the expressions above against latest `sqlglot`, we end up in an infinite loop: …
=> fix(Snowflake): Enhance parity for FILE_FORMAT & CREDENTIALS in CREATE STAGE

sqlglot/generator.py, tests/dialects/test_tsql.py
Added a warning for the `QueryOption` expression, which is mainly used for the T-SQL transpilation.
**DOCS**
[T-SQL Option Sytnaxt](https://learn.microsoft.com/en-us/sql/t-sql/queries/option-clause-transact-sql?view=sql-server-ver16)
=> feat(generator): unsupported warning for T-SQL query option

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Reference: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver16
=> Fix(tsql)!: treat GO as command

sqlglot/dialects/hive.py, sqlglot/dialects/presto.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_athena.py, tests/dialects/test_spark.py, tests/dialects/test_trino.py
Follow up on https://github.com/tobymao/sqlglot/pull/4962
This PR introduces the expressions `exp.PartitionedByBucket` and `exp.PartitionedByTruncate` which control the generation of Iceberg transforms:
- Athena's "Hive" engine (used for `CREATE TABLE`) demands `BUCKET(n, col)` / `TRUNCATE(n, col)` 
- Athena's "Trino" engine (used for CTAS) demands `BUCKET(col, n)` / `TRUNCATE(col, n)` 
Note: The `PARTITIONED BY` property attempts to parse a schema, so the new expressions are parsed as "constraints" since `_parse_schema()` ends up parsing `_parse_constraint() or _parse_column_def()`.
=> fix!: Add support for Athena's Iceberg partitioning transforms

sqlglot/optimizer/canonicalize.py, tests/fixtures/optimizer/canonicalize.sql
Fixes #4977
- Compare the inferred expression's type with that of the `CAST` _structurally_
- Do not simplify `exp.Date` or `exp.TsOrDsToDate` if the inferred expression's type is "complex"
=> Fix(optimizer): compare the whole type to determine if a cast can be removed

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
Fixes #4983 
This PR adds parsing support for the `RELY` option in the base parser.
In the future, `KEY_CONSTRAINT_OPTIONS` can have more options to be automatically supported.
**DOCS**
[Snowflake RELY](https://docs.snowflake.com/en/user-guide/join-elimination)
=> feat(parser)!: support RELY option for PRIMARY KEY, FOREIGN KEY, and UNIQUE constraints

sqlglot/optimizer/merge_subqueries.py, sqlglot/optimizer/pushdown_projections.py, sqlglot/optimizer/qualify_columns.py, tests/fixtures/optimizer/optimizer.sql
Fixes #4991
Reference: https://spark.apache.org/docs/3.5.1/sql-ref-syntax-qry-select-transform.html
=> Feat(optimizer): add support for Spark's TRANSFORM clause

sqlglot/optimizer/qualify_tables.py, tests/test_optimizer.py
There's currently a bug in main where some AST refs are reused in various nodes, leading to corrupted ASTs. I'm not sure what's the severity of this, maybe it's not super important, e.g. if we copy the AST down the line somewhere.
I added a couple of new assertions in `test_optimizer.py::check_file` for some important invariants that need to hold post-optimization. This should catch similar AST mutations in the future. For reference, before fixing the mutations in `qualify_tables.py`, there were about 23 optimizer tests failing (related to that rule).
=> Fix(optimizer): ensure there are no shared refs after qualify_tables

sqlglot/executor/python.py, sqlglot/helper.py, sqlglot/optimizer/simplify.py, tests/test_executor.py, tests/test_optimizer.py
Saw https://github.com/tobymao/sqlglot/compare/main...toby/simplify yesterday and figured I'd try to take it to the finish line. Please take a look.
=> Refactor(optimizer)!: remove recursion from `simplify`

sqlglot/dialects/presto.py, tests/dialects/test_athena.py, tests/dialects/test_trino.py
Prior to this PR, `CREATE TABLE` expressions containing  for Athena/Trino were generated like so when `identify=True` was set (or an `exp.Identifier` node had `quoted=True` set):
```
create table "test_table" (id integer, ds varchar) with (partitioning=array['"ds"'])
```
This is valid for Athena and Trino/Iceberg, but not Trino/Hive. Trino/Hive would throw the following error:
```
Query failed: Partition columns ["ds"] not present in schema
```
This PR ensures that identifiers in partitioning expression string literals are never quoted
=> Fix(trino): Dont quote identifiers in string literals for the partitioned_by property

sqlglot/parser.py, tests/dialects/test_clickhouse.py
This PR adds support for ClickHouse's special variant of `CREATE TABLE AS` which allows you to specify another table to create your table from as opposed to using a `SELECT` statement. 
I don't know of any other dialects which support this, but I still added the implementation in `sqlglot.parser` since I did not see an easy way to customize just this part of the parser in the `sqlglot.dialects.clickhouse`.
https://clickhouse.com/docs/sql-reference/statements/create/table#with-a-schema-similar-to-other-table
=> feat(clickhouse): Support parsing CTAS with alias

sqlglot/dialects/clickhouse.py, sqlglot/dialects/dialect.py, sqlglot/expressions.py, tests/dialects/test_clickhouse.py
Unlike many other dialects, ClickHouse's dateDiff function supports an optional fourth argument for specifying a timezone.  This PR updates the DateDiff AST node to support this optional argument and updates the logic in the ClickHouse dialect to populate it.
The existing helper for constructing a DateDiff was a bit hard to extend, so I've included a new ClickHouse-specific implementation which can handle the optional fourth argument.
https://clickhouse.com/docs/sql-reference/functions/date-time-functions#date_diff
=> fix(clickhouse): Support optional timezone argument in date_diff()

sqlglot/parser.py, tests/dialects/test_athena.py
Currently, SQLGLot throws an exception if you try something like:
```
>>> parse_one('(a, b)', into=exp.PartitionedByProperty)
TypeError: No parser registered for <class 'sqlglot.expressions.PartitionedByProperty'>
```
This PR allows it to work:
```
>>> parse_one('(a, b)', into=exp.PartitionedByProperty)
PartitionedByProperty(
this=Schema(
expressions=[
Identifier(this=a, quoted=False),
Identifier(this=b, quoted=False)]))
```
The use-case is to be able to correctly roundtrip partition expressions like `exp.PartitionedByBucket` from JSON where `exp.PartitionedByProperty` may be stored as a Python list of string representations of the AST nodes (eg in SQLMesh state)
=> Feat: Support exp.PartitionedByProperty for parse_into()

sqlglot/dialects/databricks.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_databricks.py
Reference: https://docs.databricks.com/aws/en/sql/language-manual/data-types/null-type
This also works, FYI:
```sql
-- returns a single row with a column void
with t as (select 1 as void) select void from t
```
=> Feat(databricks): add support for the VOID type

sqlglot/parser.py, tests/dialects/test_snowflake.py, tests/fixtures/identity.sql
Fixes https://github.com/tobymao/sqlglot/issues/5020
Currently, the query of the issue yields a parse error because `DISTINCT` defaults to parsing all of the arguments as it's own CSV list in `parser.py::_parse_lambda`. 
Note: From my testing, the dialects that support `DISTINCT` such as Snowflake or CH only allow it for the first argument:
```SQL
snowflake> WITH t AS (SELECT 1 AS col, 2 AS bar) SELECT MAX_BY(DISTINCT col, bar, 2) FROM t;
[1]
snowflake> WITH t AS (SELECT 1 AS col, 2 AS bar) SELECT MAX_BY(col, DISTINCT bar, 2) FROM t;
Syntax error: unexpected 'DISTINCT'. (line 1)
```
=> fix: Add MAX_BY & MIN_BY to FUNCTION_PARSER

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_snowflake.py
Hi folks, following up on https://github.com/tobymao/sqlglot/issues/4813 in order to add support for `GET` statements in snowflake dialect similarly to the way `PUT` statements are being handled.
- Add a `GET` expression and TokenType
- Extend Snowflake Parser with `_parse_get` which parses `GET` statements to `exp.Get`, except for the case of unquoted file path (treated as `exp.Command`)
- Tests to cover the functionality of get parsing
Thank you for the support 🙌
=> feat(snowflake): add support for GET statements

sqlglot/dialects/spark2.py, tests/dialects/test_databricks.py
Fixes https://github.com/tobymao/sqlglot/issues/5027
The colon operator returns a `VARIANT` type:
```SQL
databricks> WITH tbl as (SELECT parse_json('{"owner":"amy"}') as col) 
SELECT typeof(col:['owner']) FROM tbl;
VARIANT
```
But `FROM_JSON(json_str, schema)` accepts only JSON strings:
```SQL
databricks> WITH tbl as (SELECT parse_json('{"owner":"amy"}') as col) 
SELECT FROM_JSON(col:owner, 'VARIANT') FROM tbl;
[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "from_json(variant_get(col, $.owner))" due to data type mismatch: 
The first parameter requires the "STRING" type, however "variant_get(col, $.owner)" has the type "VARIANT"
```
=> fix(databricks): Preserve colon operators in TRY_CAST

sqlglot/parser.py, tests/dialects/test_duckdb.py, tests/dialects/test_snowflake.py
https://github.com/tobymao/sqlglot/pull/4959 introduced a silent regression in which `parse_set_operations` wouldn't check if `this` exists prior to attempting to parse a set op.
=> fix(parser): Do not parse set ops if input expr is None

sqlglot/dialects/teradata.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_teradata.py
Finsihes [PR 5049](https://github.com/tobymao/sqlglot/pull/5049)
In general, the `TRANSLATE` is expressed as a `CAST`.
In the case of the `WITH ERROR` a new expression is added in order to represent this special case on the AST.
**DOCS**
[Teradata Translate](https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Functions-Expressions-and-Predicates/String-Operators-and-Functions/TRANSLATE/TRANSLATE-Function-Syntax)
=> feat(teradata)!: support translate with error

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
This is to avoid bracketing the `COLLATE` argument when transpiling to tsql in SQLMesh.
Note: This fixes the `COLLATE` transpiling for `ALTER TABLE` commands, but if `COLLATE` is used in table queries, this obviously doesn't address those cases!
=> Fix(tsql): Change `COLLATE` expression to `Var` for `ALTER TABLE`

sqlglot/dialects/druid.py, tests/dialects/test_druid.py
fixes https://github.com/tobymao/sqlglot/issues/5059
=> fix: support current_timestamp

sqlglot/dialects/duckdb.py, sqlglot/dialects/oracle.py, sqlglot/dialects/postgres.py, sqlglot/dialects/sqlite.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_dialect.py
This PR adds support for `EXCLUDE` in window definition:
`SELECT SUM(x) OVER (... ROWS BETWEEN ... EXCLUDE CURRENT ROW)`
`EXCLUDE` options are common across dialects supporting the clause:
- `CURRENT ROW`
- `GROUP`
- `TIES`
- `NO OTHER`
**Supported dialects:**:
- [Postgres](https://www.postgresql.org/docs/current/sql-select.html#:~:text=and%20frame_exclusion%20can%20be%20one%20of)
- [SQLite](https://sqlite.org/syntax/frame-spec.html)
- [DuckDB](https://duckdb.org/docs/stable/sql/functions/window_functions.html#syntax)
- [Oracle 21c](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Analytic-Functions.html)
=> fix: Support EXCLUDE in window definition

sqlglot/parser.py, tests/dialects/test_databricks.py
Fixes #5057
**DOCS**
[Databricks FK](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-ddl-create-table-constraint#syntax)
=> feat(parser): FK REFERENCES without specifying column

sqlglot/transforms.py, tests/dialects/test_bigquery.py
Fixes #5062
In the previous implementation, `unqualify_unnest` stripped qualifying prefixes from every aliased `UNNEST` expression when the column path matched the `table` or `db` name. This behavior was intended to support dialects like BigQuery and Redshift because the optimizer adds via the `qualify` aliases to the `UNNEST`. 
However, this approach led to incorrect behavior in certain cases. For example:
```
SELECT * FROM t1, UNNEST("t1"."t2"."t3") "t2" ("col")
```
In this query, `unqualify_unnest` would incorrectly remove `"t2"` from the path, resulting in an incorrect SQL output after transpilation (duckb -> bigquery).
=> fix!: unqualify UNNEST only the left most part of a column

sqlglot/dialects/oracle.py, tests/dialects/test_oracle.py
Fixes #5068 
**DOCS**
[Oracle TO_TIMESTAMP](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/TO_TIMESTAMP.html)
=> fix(oracle)!: to_timestamp without format

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
=> Fix(bigquery): always infer concat type as either bytes or string

README.md
Update dialect count from 24 to 27, as there are now 27 dialects listed in [sqlglot/dialects/__init__.py](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/__init__.py#L67-L95).
=> docs: update dialect count

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
This is a best-effort transpilation as BigQuery's `BIGDECIMAL` has P=77, S=38 while Snowflake's `NUMBER` can't exceed P=38, S=37.
Docs
--------
[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types) | [Snowflake](https://docs.snowflake.com/en/sql-reference/data-types-numeric)
=> feat(snowflake): Transpile DataType.BIGDECIMAL to DOUBLE

sqlglot/tokens.py, sqlglotrs/src/tokenizer.rs, tests/test_tokens.py
Addresses #5091, by initializing the self._col value to `i` instead of `1` after a newline, which will correctly account for any leading whitespace which is accumulated in the _scan method.
=> Fix token col attribute when there is leading whitespace after newline

sqlglot/dialects/presto.py, sqlglot/dialects/redshift.py, sqlglot/dialects/snowflake.py, sqlglot/dialects/trino.py, sqlglot/transforms.py, tests/dialects/test_bigquery.py, tests/test_transforms.py
Dialects that support the `WINDOW` clause: BigQuery, ClickHouse, DuckDB, Oracle, PostgreSQL, MySQL, SQLite, T-SQL, Databricks, Spark SQL, Trino.
- https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#window_clause
- https://www.postgresql.org/docs/current/sql-select.html
- https://dev.mysql.com/doc/refman/8.4/en/select.html
- https://www.sqlite.org/lang_select.html
- https://learn.microsoft.com/en-us/sql/t-sql/queries/select-window-transact-sql?view=sql-server-ver16
- https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-qry-select-named-window
- https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select.html
- https://clickhouse.com/docs/sql-reference/statements/select
- https://duckdb.org/docs/stable/sql/statements/select.html#window-clause
- …
=> Feat: transpile WINDOW clause

sqlglot/parser.py, tests/dialects/test_starrocks.py
StarRocks security option for CREATE VIEW can contain "NONE" as a value
[Create View Documentation](https://docs.starrocks.io/docs/sql-reference/sql-statements/View/CREATE_VIEW/#parameters)
=> feat(starrocks): Support parsing "NONE" as security option

sqlglot/dialects/databricks.py, sqlglot/dialects/dialect.py, sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, sqlglot/optimizer/annotate_types.py, tests/fixtures/optimizer/annotate_functions.sql, tests/test_optimizer.py
Fixes #5067 
This PR fixes type coercion issues in the IF and COALESCE functions for Hive, Spark2, Spark, and Databricks.
For Hive, Spark 2 and Spark, we maintain the default non-ANSI behavior.
For Databricks, we follow the default ANSI-compliant behavior.
**DOCS**
[Hive Type precedence](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27838462#LanguageManualTypes-AllowedImplicitConversions)
[Databricks Type precedence graph](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-datatype-rules#type-precedence-graph)
=> fix!: hive, spark2, spark, databricks type coercion for IF and COALESCE functions

sqlglot/dialects/tsql.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_tsql.py
This PR fixes the issue of treating `ISNULL` as `COALESCE` in T-SQL.
This assumption is wrong because these two functions have different semantics.
**DOCS**
[T-SQL COALESCE vs ISNULL](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/coalesce-transact-sql?view=sql-server-ver16#compare-coalesce-and-isnull)
=> fix(tsql)!: separate ISNULL from COALESCE

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Addresses SQLMesh issue: https://github.com/TobikoData/sqlmesh/issues/4181
Currently, if `exp.CopyGrantsProperty` is present in a `CREATE VIEW` then it is output after the columns list. This is in line with the [Snowflake docs](https://docs.snowflake.com/en/sql-reference/sql/create-view#syntax).
However, for `CREATE MATERIALIZED VIEW`, it [needs to go](https://docs.snowflake.com/en/sql-reference/sql/create-materialized-view#syntax) *before* the columns list or the following error will be thrown:
```
>>> CREATE MATERIALIZED VIEW ERIN_TEST_MV ("ITEM_ID", "NUM_ORDERS") COPY GRANTS AS SELECT ITEM_ID, NUM_ORDERS FROM UPSTREAM_TABLE
SQL compilation error: syntax error line 1 at position 50 unexpected '"ITEM_ID"'.
```
=> Fix(snowflake): Put COPY GRANTS in the right place for materialized views

sqlglot/generator.py, tests/dialects/test_bigquery.py
Fixes the following bug:
```python
>>> print(sqlglot.transpile("--c\narray_agg(v ignore nulls)", "bigquery")[0])
array_agg(v) /* c * IGNORE NULLS)
```
=> Fix: ignore/respect nulls generation edge case

sqlglot/dialects/snowflake.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
Notes for Snowflake's `ARRAY_AGG`:
- It does not support an inline `ORDER BY`, it must be moved to `WITHIN GROUP (<orderby_clause>)`
- It does not support  `IGNORE NULLS` / `RESPECT NULLS`, the nulls are always excluded. This looks like an exception for some other window functions like `LEAD` or `LAG` which do allow them 
Docs
---------
[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg) | [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/array_agg)
=> fix(snowflake): Properly transpile ARRAY_AGG, IGNORE/RESPECT NULLS

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
- Before:
```Python3
>>> parse_one("SELECT EXTRACT(ISOWEEK FROM DATE '2013-12-25') AS the_day", "bigquery").sql("snowflake")
"SELECT DATE_PART(ISOWEEK, CAST('2013-12-25' AS DATE)) AS the_day
bigquery> SELECT EXTRACT(ISOWEEK FROM DATE '2013-12-25') AS the_day
52
snowflake> SELECT DATE_PART(ISOWEEK, CAST('2013-12-25' AS DATE)) AS the_day;
Error: invalid value [ISOWEEK] for parameter 'DATE_PART date/time part'
```
<br />
- After 
```Python3
>>> parse_one("SELECT EXTRACT(ISOWEEK FROM DATE '2013-12-25') AS the_day", "bigquery").sql("snowflake")
"SELECT DATE_PART(WEEKISO, CAST('2013-12-25' AS DATE)) AS the_day"
snowflake> SELECT DATE_PART(WEEKISO, CAST('2013-12-25' AS DATE)) AS the_day;
52
```
Docs
------
[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#ext …
=> fix(snowflake): Transpile ISOWEEK to WEEKISO

sqlglot/dialects/tsql.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_tsql.py
Closes https://github.com/tobymao/sqlglot/issues/5135
This only addresses the error reported in the linked issue:
```
Trying: ALTER TABLE dbo.SimpleTable SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.SimpleTable_History))
Error
```
Fixing the `Command` warning is low priority for the time being.
Reference: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver17
=> Fix(tsql): properly parse and generate ALTER SET

sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, tests/dialects/test_bigquery.py, tests/dialects/test_hive.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py
According to the [Hive Language Manual](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27838462#LanguageManualTypes-ComplexTypes) srtuct column names and data types should be separate by ':' in DDLs. Since the spark2 dialect inherits from hive and spark2 had the correct implementations I moved the implementation into the HiveGenerator and adjusted the test cases accordingly.
=> Fix(hive): STRUCT column names and data type should be separated by ':'

sqlglot/dialects/bigquery.py, sqlglot/dialects/mysql.py, sqlglot/dialects/presto.py, sqlglot/dialects/sqlite.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
=> Fix: avoid generating nested comments when not supported

sqlglot/parser.py, tests/dialects/test_dialect.py
BigQuery only allows `OFFSET` with prefix a `LIMIT`. 
Databricks supports `OFFSET` without `LIMIT`.
**DOCS**
[BigQuery LIMIT pipe syntax](https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax#limit_pipe_operator)
[Databricks LIMIT/OFFSET pipe syntax](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-qry-select-pipeop#syntax)
| `WHERE (replacing HAVING)`           |         |
| `WHERE (replacing QUALIFY)`           |          |
| `EXTEND`           |          |
| `SET`              |          |
| `RENAME`           |          |
| `DROP`             |         |
| `AS` …
=> feat(parser): LIMIT/OFFSET pipe syntax

.github/workflows/benchmark-sqlglot.yml, sqlglot/tokens.py, sqlglotrs/src/tokenizer.rs, tests/test_tokens.py
=> Fix(rust-tokenizer)!: return token vector in `tokenize` even on failure

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py, tests/dialects/test_presto.py
Fixes https://github.com/TobikoData/sqlmesh/issues/4674
Postgres 16 (released 24 Sep 2023) added support for `ANY_VALUE`. As this may be too recent for some Postgres workloads, I thought it'd make for another use case of `Version`, but if we want to simplify we can instead always preserve the roundtrip.
Docs
---------
[PSQL ANY_VALUE](https://www.postgresql.org/docs/16/functions-aggregate.html) | [PSQL Feature Matrix](https://www.postgresql.org/about/featurematrix/)
=> feat(postgres)!: Add support for ANY_VALUE for versions 16+

sqlglot/dialects/bigquery.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Add support for the `AGGREGATE` pipe syntax.
In the case of BigQuery the `ASC` and `DESC` have been removed from the `ID_VAR_TOKENS` because they can't be used as identifiers. Moreover, in BigQuery pipe syntax when we find `ASC` or `DESC` it means that the query needs an `ORDE BY`.
**DOCS**
[BigQuery AGGREGATE Syntax](https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax#aggregate_pipe_operator)
[Databricks AGGREGATE Syntax](en/sql/language-manual/sql-ref-syntax-qry-select-pipeop)
| `WHERE (replacing HAVING)`           |         |
| `WHERE (replacing QUALIFY)`           |          |
| …
=> feat(parser): AGGREGATE with GROUP AND ORDER BY pipe syntax

sqlglot/expressions.py, tests/test_expressions.py
This PR allows `exp.to_table` to construct `Table` instances even if the identifiers in the SQL path are unsafe, i.e., they are unquoted when they should be.
https://github.com/TobikoData/sqlmesh/issues/4426
=> Feat: make to_table more lenient

sqlglot/dialects/sqlite.py, tests/dialects/test_sqlite.py
If handed the duckdb/postgres/etc SQL of `SELECT FIRST_VALUE(val RESPECT NULLS) OVER ....` then we should just strip out the `RESPECT NULLS` part. If handed `IGNORE NULLS`, we should error, because sqlite doesn't support this, it always considers nulls.
This isn't a working PR I'm sure. Consider it more of a bug that I'm filing, and giving a slight head start in fixing it. I'll be curious to see what changes need to happen to actualy make this work.
=> feat(sqlite): implement RESPECT/IGNORE NULLS in first_value()

sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_dialect.py
Add support for the SET OPERATORS = `{UNION, INTERSECT, EXCEPT}` pipe syntax.
**DOCS**
[BigQuery pipe syntax UNION](https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax#union_pipe_operator)
[BigQuery pipe syntax INTERSECT](https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax#intersect_pipe_operator)
[BigQuery pipe syntax EXCEPT](https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax#except_pipe_operator)
| `WHERE (replacing HAVING)`           |         |
| `WHERE (replacing QUALIFY)`           |          |
| `EXTEND`           |          |
| `SET` …
=> feat(parser): SET OPERATORS with pipe syntax

sqlglot/parser.py, tests/dialects/test_dialect.py
This PR refactors the whole implementation of the pipe syntax and substitutes the subquery logic to CTEs. 
This makes the generated SQL more readable and also solves issues with the scoping of the query columns.
A problem with the previous implementation can be spotted in the following example:
```
Input:
FROM c.x |> SELECT x.col1, x.col2
Output:
SELECT x.col1, x.col2 FROM (SELECT * FROM c.x)
```
The subquery "shadows" the scope.
=> fix(parser)!: CTEs instead of subqueries for pipe syntax

sqlglot/parser.py, tests/dialects/test_pipe_syntax.py
This PR adds support for the `PIVOT/UNPIVOT` pipe syntax. 
| `WHERE (replacing HAVING)`           |    ✅      |
| `WHERE (replacing QUALIFY)`           |   ✅        |
| `EXTEND`           |          |
| `SET`              |          |
| `RENAME`           |          |
| `DROP`             |         |
| `AS`               |           |
| `LIMIT`        |    ✅       |
| `AGGREGATE WITH GROUP/ORDER BY`       |   ✅        |
| `ORDER BY` | ✅  |
| `UNION`               |      ✅      |
| `INTERSECT`               |   ✅         |
| `EXCEPT`               |       ✅     |
| `JOIN`           |      ✅       |
| `CALL` …
=> feat(parser): PIVOT/UNPIVOT pipe syntax

sqlglot/parser.py, tests/dialects/test_pipe_syntax.py
This PR adds support for the `EXTEND` pipe syntax. 
| `WHERE (replacing HAVING)`           |    ✅      |
| `WHERE (replacing QUALIFY)`           |   ✅        |
| `EXTEND`           |      ✅      |
| `SET`              |          |
| `RENAME`           |          |
| `DROP`             |         |
| `AS`               |    ✅       |
| `LIMIT`        |    ✅       |
| `AGGREGATE WITH GROUP/ORDER BY`       |   ✅        |
| `ORDER BY` | ✅  |
| `UNION`               |      ✅      |
| `INTERSECT`               |   ✅         |
| `EXCEPT`               |       ✅     |
| `JOIN`           |      ✅       |
| `CALL` …
=> feat(parser): EXTEND pipe syntax

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes issue: https://github.com/TobikoData/sqlmesh/issues/4649 
Subqueries are parsed twice (at least for tsql) by `select_sql`, which causes subqueries using `LIMIT` or `TOP` to drop these on the second run, when converting CTAS statement to `SELECT .. INTO ..`. 
The subquery expression object suffers a side-effect in `Generator.select_sql` method where any `limit` expression is popped from the expression and propagated within the method as a string component. 
This simple fix reinjects the original `limit` expression to any query that HAD a `limit` expression prior to `select_sql`, but lacks it afterward.
=> fix(tsql): Retain limit clause in subquery expression.

sqlglot/parser.py, tests/dialects/test_pipe_syntax.py
This PR adds support for the `TABLESAMPLE` pipe syntax. 
| `WHERE (replacing HAVING)`           |    ✅      |
| `WHERE (replacing QUALIFY)`           |   ✅        |
| `EXTEND`           |      ✅      |
| `SET`              |          |
| `RENAME`           |          |
| `DROP`             |           |
| `AS`               |    ✅       |
| `LIMIT`        |    ✅       |
| `AGGREGATE WITH GROUP/ORDER BY`       |   ✅        |
| `ORDER BY` | ✅  |
| `UNION`               |      ✅      |
| `INTERSECT`               |   ✅         |
| `EXCEPT`               |       ✅     |
| `JOIN`           |      ✅       |
| `CALL` …
=> feat(parser): TABLESAMPLE pipe syntax

sqlglot/dialects/duckdb.py, tests/dialects/test_duckdb.py
Prior to this PR:
```
>>> parse_one("DETACH DATABASE IF EXISTS foo", dialect="duckdb").sql(dialect="duckdb")
'DETACH IF EXISTS foo'
```
This is invalid syntax, at least as of DuckDB 1.3.0. Unlike `ATTACH`, when `IF EXISTS` is used for `DETACH`, it has to be `DETACH DATABASE` or the following error gets thrown:
```
Parser Error: syntax error at or near "exists" (Line Number: 1)
```
This is in line with the [DuckDB documentation
](https://duckdb.org/docs/stable/sql/statements/attach.html#detach-syntax)
Note that `DETACH foo` works as expected, the error is only thrown if `IF EXISTS` is added
=> Fix(duckdb): Generate correct DETACH syntax if IF EXISTS is set

sqlglot/dialects/snowflake.py, sqlglot/optimizer/scope.py, tests/dialects/test_snowflake.py
This PR:
- Introduces a new transformation for Snowflake, in order to transpile BigQuery queries with unnests to it
- Modifies the `walk_in_scope` logic to stop considering plain `UDTF`s without `Query` children as scope boundaries
We incorrectly transpile BigQuery queries like the following to Snowflake today:
```python
import sqlglot
print(sqlglot.transpile("select _u.foo from unnest([struct('x' as foo, 'y' AS bar)]) as _u", "bigquery", "snowflake")[0])
```
The resulting query fails with `Error: invalid identifier '_U.FOO' (line 1)`, because the value `_u` is a `VARIANT`, and so accessing its contents using the dot notation is not allowed. Instead, Snowflake requires that we use either the colon (`x:y`) or the bracket syntax `x['y']` for this reason.
To address this, the new …
=> Feat(snowflake): improve transpilation of unnested object lookup

sqlglot/dialects/fabric.py, tests/dialects/test_fabric.py
This pull request introduces support for the Fabric SQL dialect by adding a new `Generator` class with Fabric-specific type mappings and corresponding tests to ensure the mappings are correctly applied. The most important changes include defining type mappings for unsupported or differently named types in Fabric and adding comprehensive tests for these mappings.
* **Type Mapping for Unsupported/Differently Named Types**:
- Added a `Generator` class within the `Fabric` dialect to override T-SQL types that are unsupported or have different names in Fabric. Examples include mapping `MONEY` and `SMALLMONEY` to `DECIMAL`, `DATETIME` and `SMALLDATETIME` to `DATETIME2`, and `TINYINT` to `SMALLINT`.
* **Validation of Type Mappings**:
- Added a new test class `TestFabric` to validate that …
=> feat(fabric): implement type mappings for unsupported Fabric types

sqlglot/dialects/presto.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_presto.py, tests/dialects/test_trino.py
=> Fix(presto)!: cast constructed timestamp literal to zone-aware type if needed

sqlglot/dialects/fabric.py, tests/dialects/test_fabric.py
This pull request introduces Fabric-specific enhancements to the SQLGlot library, focusing on precision handling. The changes ensure compatibility with Microsoft Fabric's data warehouse by adding precision constraints for temporal data types.
* Implemented a custom `datatype_sql` method to cap precision for temporal types (`TIME`, `DATETIME2`, `DATETIMEOFFSET`) at 6 digits, defaulting to 6 when unspecified.
>**NOTE:** Depends on #5249
=> feat(fabric): Add precision cap to temporal data types

sqlglot/dialects/dialect.py, tests/dialects/test_snowflake.py
Fixes https://github.com/tobymao/sqlglot/issues/5255
- Snowflake
```sql
SELECT TO_CHAR(CURRENT_TIMESTAMP(), 'DY'), TO_CHAR(CURRENT_TIMESTAMP(), 'MMMM');
--  | --
Fri | June
```
- DuckDB
```SQL
D SELECT STRFTIME(CURRENT_TIMESTAMP, '%a'), STRFTIME(CURRENT_TIMESTAMP, '%B');
┌───────────────────────────────────┬───────────────────────────────────┐
│ strftime(CURRENT_TIMESTAMP, '%a') │ strftime(CURRENT_TIMESTAMP, '%B') │
│              varchar              │              varchar              │
├───────────────────────────────────┼───────────────────────────────────┤
│ Fri                               │ June                              │
└───────────────────────────────────┴───────────────────────────────────┘
```
Docs
---------
[Snowflake](https://docs.snowflake.com/en/sql-reference/functions …
=> feat(duckdb): Transpile Snowflake's TO_CHAR if format is in Snowflake

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
This pull request updates the `create_sql` method in the `sqlglot/dialects/tsql.py` file to ensure consistent capitalization for SQL keywords and identifiers. The changes improve readability and adhere to standard SQL conventions.
* Updated the capitalization of `information_schema` and its sub-elements (`schemata`, `tables`) to `INFORMATION_SCHEMA`, `SCHEMATA`, and `TABLES` for consistency and adherence to SQL standards.
* Adjusted column names (`table_name`, `table_schema`, `table_catalog`) to uppercase (`TABLE_NAME`, `TABLE_SCHEMA`, `TABLE_CATALOG`) for uniformity.
=> fix(tsql)!: update SQL keywords to uppercase for consistency

sqlglot/parser.py, tests/dialects/test_tsql.py
Fixes https://github.com/TobikoData/sqlmesh/issues/4813
The roundtrip is preserved in both cases but the AST was incorrect ([Internal discussion](https://tobikodata.slack.com/archives/C040V7ZP9NH/p1750877167847629))
- Before:
```Python
>>> sqlglot.parse_one("ALTER TABLE tbl ADD CONSTRAINT cnstr PRIMARY KEY CLUSTERED (ID)", "tsql")
Alter(
this=Table(
this=Identifier(this=tbl, quoted=False)),
kind=TABLE,
actions=[
ColumnDef(
this=Identifier(this=CONSTRAINT, quoted=False),
kind=DataType(this=Type.USERDEFINED, kind=cnstr),
constraints=[
ColumnConstraint(
kind=PrimaryKeyColumnConstraint(
)),
ColumnConstraint(
kind=ClusteredColumnConstraint(
this=[
Ordered(
this=Column(
this=Identifier(this=ID, quoted=False)),
nulls_first=True)]))])])
```
<br />
- After
```Python3
>>> sqlglot.parse_one("ALTER …
```
=> fix(tsql)!: Fix parsing of ADD CONSTRAINT

sqlglot/optimizer/scope.py, tests/test_optimizer.py
This addresses the issue reported in this Slack thread: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1750862162339109. This should only impact users that have queries with `UNNEST` sources and who build scopes without first calling `qualify_tables` or `qualify` on the ASTs.
This example reproduces the error:
```python
from sqlglot import parse_one
from sqlglot.optimizer.scope import build_scope
query = """
SELECT
ID
, release
FROM table
LEFT JOIN UNNEST(environments) AS env
LEFT JOIN UNNEST(env.deploySteps) AS release
"""
parsed = parse_one(query, dialect="bigquery")
scope = build_scope(parsed)
print(scope.selected_sources)
```
=> Fix(scope)!: include bigquery unnest aliases in selected sources

sqlglot/dialects/bigquery.py, sqlglot/optimizer/annotate_types.py, tests/fixtures/optimizer/annotate_functions.sql
This PR fixes the type annotation of `ARRAY_CONCAT`
Following examples (`qualify` -> `annotate_types`)
Before the fix:
```
SELECT ARRAY_CONCAT(['a'], ['b'])
Select(
expressions=[
Alias(
this=ArrayConcat(
this=Array(
expressions=[
Literal(this='a', is_string=True, _type=DataType(this=Type.VARCHAR))],
_type=DataType(
this=Type.ARRAY,
expressions=[
DataType(this=Type.VARCHAR)],
nested=True)),
expressions=[
Array(
expressions=[
Literal(this='b', is_string=True, _type=DataType(this=Type.VARCHAR))],
_type=DataType(
this=Type.ARRAY,
expressions=[
DataType(this=Type.VARCHAR)],
nested=True))],
_type=DataType(this=Type.VARCHAR)),
alias=Identifier(this='_col_0', quoted=True, _type=DataType(this=Type.UNKNOWN)),
_type=DataType(this=Type.VARCHAR))],
_type=DataType(
this=Type.STRUCT,
expressions=[ …
```
=> fix(bigquery)!: ARRAY_CONCAT type annotation

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [BIT_OR](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/bit_or.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add bitwiseOr function to exasol dialect

sqlglot/dialects/clickhouse.py, sqlglot/dialects/hive.py, sqlglot/dialects/mysql.py
* **New AST node `SubstringIndex`**  
*inherits from `Func`; doc-string & `arg_types` included.*
* **Parser support** in ClickHouse, Hive, Spark, Spark2, Databricks, MySQL (and alias `SUBSTRINGINDEX` in ClickHouse).  
Previously the token was parsed as `Anonymous`, so users could not
transpile `substringIndex` ↔ `SUBSTRING_INDEX` without a manual replace.
* **ClickHouse generator transform**  
Normalises output to the canonical **`substringIndex`** spelling
(camel-case, no underscore) instead of the default `SUBSTRINGINDEX`.
* **Tests**  
* `test_substring_index.py` – parse & round-trip for  
ClickHouse ↔ Hive, Databricks → MySQL, positive / negative / zero count.
I wanted to transpile `substringIndex` of clickhouse to `SUBSTRING_INDEX` of databricks.
**The change lets me (and everyone) …
=> feat!: add support for `SUBSTRING_INDEX`

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [BIT_XOR](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/bit_xor.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): added bit_xor built in exasol function

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `ARRAY_TO_STRING` function.
This annotation expands to the dialects that use `ARRAY_JOIN`. 
**DOCS**
[BigQuery ARRAY_TO_STRING](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array_to_string)
=> feat(parser)!: annotate type of ARRAY_TO_STRING

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [BIT_RSHIFT](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/bit_rshift.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): added the bit_rshift built in exasol function

sqlglot/dialects/duckdb.py, tests/dialects/test_spark.py
Fixes https://github.com/tobymao/sqlglot/issues/5309
- Spark:
```SQL
spark-sql (default)> SELECT POSEXPLODE(ARRAY('a','b','c'));
pos     col
0       a
1       b
2       c
spark-sql (default)> SELECT POSEXPLODE(ARRAY('a','b','c')) AS (mypos, myval);
mypos   myval
0       a
1       b
2       c
spark-sql (default)> SELECT * FROM POSEXPLODE(ARRAY('a','b','c'));
pos     col
0       a
1       b
2       c
spark-sql (default)> SELECT * FROM POSEXPLODE(ARRAY('a','b','c')) AS (mypos, myval);
mypos   myval
0       a
1       b
2       c
```
<br />
- DuckDB
```SQL
D SELECT GENERATE_SUBSCRIPTS(['a', 'b', 'c'], 1) - 1 AS pos, UNNEST(['a', 'b', 'c']) AS col;
┌───────┬─────────┐
│  pos  │   col   │
│ int64 │ varchar │
├───────┼─────────┤
│     0 │ a       │
│     1 │ b       │
│     2 │ c       │ …
```
=> feat(duckdb): Transpile Spark's `exp.PosExplode`

sqlglot/dialects/athena.py, sqlglot/dialects/dialect.py, sqlglot/jsonpath.py, sqlglot/optimizer/pushdown_predicates.py, sqlglot/parser.py, sqlglot/tokens.py, tests/dialects/test_athena.py
Fixes #5267
This PR is a refactor of the Athena implementation. It was motivated by the linked issue, but its value extends beyond that– in other words, the ticket is not the only issue that I expect to be fixed by this PR.
TL;DR: Athena will now act as a proper router to either Hive or Trino, depending on the statement type (1, 2). Until now, it only routed the AST to the correct generator, but this was not enough, because the _lexical_ syntaxes of Hive and Trino contain incompatibilities, such as different string escapes, making them tricky to handle with a single tokenizer.
The way is implemented is that Athena now tokenizes the input string once, using a superset tokenizer that consumes both HiveQL and Trino SQL, and then re-tokenizes depending on what it finds in the token stream. …
=> Refactor(athena)!: route statements to hive/trino depending on their type

sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_hive.py, tests/dialects/test_presto.py, tests/dialects/test_spark.py
Fixes #5317
This PR distinguishes `STORED AS` from `USING`. 
Spark and Databricks supports hive format when creating a table. This means that if we only use the previous approach, generating `STORED AS` with `USING` the generated SQL can be wrong. 
Example: 
```CREATE TABLE student (id INT, name STRING, age INT) STORED AS TEXTFILE```
**DOCS**
[Hive Format (STORED AS)](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-syntax-ddl-create-table-hiveformat)
=> fix(spark)!: distinguish STORED AS from USING

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [VAR_POP](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/var_pop.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add var_pop built in function to exasol dialect

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `FROM_BASE64` function.
**DOCS**
[BigQuery FROM_BASE64](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#from_base64)
=> feat(optimizer)!: annotate type for FROM_BASE64

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [APPROXIMATE_COUNT_DISTINCT](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/approximate_count_distinct.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add add_approximate_count_distinct function

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for the type annotation of `LOGICAL_AND` and `LOGICAL_OR`.
**DOCS**
[BigQuery LOGICAL_AND](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#logical_and)
[BigQuery LOGICAL_OR](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#logical_or)
=> feat(optimizer)!: annotate type for LOGICAL_AND and LOGICAL_OR

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for the type annotation of `MAKE_INTERVAL`
**DOCS**
[BigQuery MAKE_INTERVAL](https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions#make_interval)
=> feat(optimizer)!: annotate type for MAKE_INTERVAL

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for the annotate type of `LAST_VALUE`
[BigQuery LAST_VALUE](https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions#last_value)
=> feat(optimizer)!: annotate type for LAST_VALUE

sqlglot/generator.py, sqlglot/parser.py, tests/fixtures/pretty.sql
Fix the lost single-line comments before GROUP, JOIN and HAVING.
```SQL
SELECT
count(*)
FROM
table_a
/* join comment */
JOIN
table_b
ON
table_a.id = table_b.id
/* group by comment */
GROUP BY
table_a.id
/* having comment */
HAVING
table_a.id = 1
```
The AST of the aboving SQL was like this with all the comments lost:
```
Select(
expressions=[
Count(
this=Star(),
big_int=True)],
from=From(
this=Table(
this=Identifier(this=table_a, quoted=False))),
joins=[
Join(
this=Table(
this=Identifier(this=table_b, quoted=False)),
on=EQ(
this=Column(
this=Identifier(this=id, quoted=False),
table=Identifier(this=table_a, quoted=False)),
expression=Column(
this=Identifier(this=id, quoted=False),
table=Identifier(this=table_b, quoted=False))))],
group=Group(
expressions=[
Column(
this=Identifier(this=id, …
```
=> fix: fix comment lost before GROUP, JOIN and HAVING

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for the type annotation of `STARTS_WITH`.
**DOCS**
[BigQuery STARTS_WITH](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#starts_with)
=> feat(optimizer)!: annotate type for STARTS_WITH

sqlglot/dialects/bigquery.py, sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR makes annotation of `SHA` functions only related to BigQuery dialect.
Other dialects aren't return the same type. 
**DOCS**
[BigQuery SHA functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions#sha1)
=> chore(optimizer)!: annotate type SHA1, SHA256, SHA512 for BigQuery

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [TO_CHAR](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/to_char%20(datetime).htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): Add TO_CHAR function support in exasol dialect

sqlglot/dialects/duckdb.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_duckdb.py
=> Feat(duckdb): support new lambda syntax

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for `CORR`.
**DOCS**
[BigQuery CORR](https://cloud.google.com/bigquery/docs/reference/standard-sql/statistical_aggregate_functions#corr)
=> feat(optimizer)!: annotate type for CORR

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds annotation support for `COVAR_POP`
**DOCS**
[BigQuery COVAR_POP](https://cloud.google.com/bigquery/docs/reference/standard-sql/statistical_aggregate_functions#covar_pop)
=> feat(optimizer)!: annotate type for COVAR_POP

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for the type annotation of `DATETIME`
**DOCS**
[BigQuery DATETIME](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#datetime)
=> feat(optimizer)!: annotate type for DATETIME

sqlglot/dialects/fabric.py, tests/dialects/test_fabric.py
This pull request updates the handling of `TIMESTAMPTZ` and `DATETIMEOFFSET` types in the Fabric SQL dialect to ensure compliance with Microsoft Fabric's requirements. It introduces logic to differentiate how `TIMESTAMPTZ` is treated based on whether it is used in an `AT TIME ZONE` expression and adjusts test cases accordingly.
* **Logic for `TIMESTAMPTZ` in `datatype_sql`:**
- Added a check to wrap `TIMESTAMPTZ` in `AT TIME ZONE 'UTC'` when `AT TIME ZONE` is missing.
* **Modified precision handling for `DATETIMEOFFSET`:**
- Adjusted tests to ensure `DATETIMEOFFSET` is only valid when paired with `AT TIME ZONE`, preserving precision limits.
* **Added new test for `TIMESTAMPTZ` behavior:**
- Introduced a dedicated test to verify that `TIMESTAMPTZ` is used with `AT TIME ZONE`.
=> feat(fabric): Ensure TIMESTAMPTZ is used with AT TIME ZONE

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py
Fixing https://github.com/tobymao/sqlglot/issues/5366
=> Fix round double for postgres

.github/workflows/package-publish.yml, .github/workflows/package-test.yml, pyproject.toml, sqlglotrs/pyproject.toml
Not much context here, I simply observed that Python 3.8 CI checks were taking longer and thought it's a good opportunity to deprecate it, since it's [EOL](devguide.python.org/versions/) since October 2024.
=> Chore: bump min. supported version to python 3.9

sqlglot/dialects/dremio.py, tests/dialects/test_dremio.py
Adding `TIME_MAPPING` for Dremio dialect based on https://docs.dremio.com/current/reference/sql/sql-functions/DATE_TIME/
Also added support for `TO_CHAR` function which is needed for tests
=> feat(dremio): Add TIME_MAPPING for Dremio dialect

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py, tests/dialects/test_snowflake.py
This PR adds transpilation support for `CURRENT_DATE` with timezone of BigQuery to Snowflake.
Snowflake doesn't support `CURRENT_DATE('timezone')`, so we implement this by using the `CURRENT_TIMESTAMP` combined with `CONVERT_TIMEZONE` and `CAST`.
**DOCS**
[BigQuery CURRENT_DATE](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#current_date)
[Snowflake CURRENT_TIMESTAMP](https://docs.snowflake.com/en/sql-reference/functions/current_timestamp)
[Snowflake CONVERT_TIMEZONE](https://docs.snowflake.com/en/sql-reference/functions/convert_timezone)
[Snowflake TO_DATE](https://docs.snowflake.com/en/sql-reference/functions/to_date)
=> fix(snowflake): transpile bigquery CURRENT_DATE with timezone

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [TO_DATE](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/to_date.htm) built -in function to exasol dialect in sqlglot and implementing time mappings
=> feat(exasol): add to_date and refactored to_char functions with respect to time mapping

sqlglot/dialects/fabric.py, tests/dialects/test_fabric.py
This pull request refines how the Fabric dialect handles temporal data types and refactors precision capping for these types. It also updates the handling of `TIMESTAMPTZ` casts to transform it into `TIMESTAMP`.
* **Precision capping logic**: Added `_cap_data_type_precision` helper function to cap the precision of temporal types to a maximum of 6 digits and default to 6 if no precision is specified. (`sqlglot/dialects/fabric.py`, [sqlglot/dialects/fabric.pyL3-R30](diffhunk://#diff-ec3f7bdb2c80d6a8318d44a7f5fcb07a5aa1a3f4f3641156eb9f14b1a0931f6aL3-R30))
* **Updated SQL generation for temporal types**: Modified `datatype_sql` and `cast_sql` methods to use `_cap_data_type_precision` for temporal types, ensuring capped precision and consistent handling of `TIMESTAMPTZ` casts. …
=> Fix(fabric): cast datetimeoffset to datetime2

sqlglot/dialects/exasol.py, sqlglot/expressions.py, tests/dialects/test_exasol.py
This involves adding the parsing of [CONVERT_TZ](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/convert_tz.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add support for CONVERT_TZ function

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves mapping STR_TO _TIME function in sqlglot to [TO_DATE](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/to_date.htm) exasol built -in function to exasol dialect in sqlglot
=> feat(exasol): map STR_TO_TIME to TO_DATE and

sqlglot/expressions.py, tests/test_expressions.py
I've been playing with the Python executor (building a backend for [shillelagh](https://github.com/betodealmeida/shillelagh)) and I found that there's no handling of `datetime.time` objects, so I added it in this PR.
=> feat: add `DateStrToTime`

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
In PR #4704, support was added for OUT, OUTPUT, and READ_ONLY parameter modifiers.
However, READ_ONLY is not correct -- it should be READONLY.
See the documentation for procedures and functions:
https://learn.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-ver16#readonly 
https://learn.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver17#readonly
=> fix(tsql): change READ_ONLY to READONLY

sqlglot/dialects/snowflake.py, tests/dialects/test_dialect.py, tests/dialects/test_snowflake.py
Transpiling BigQuery queries to Snowflake is not always correct today. One example is:
```sql
-- BigQuery input
SELECT x FROM UNNEST([STRUCT('x' AS x)])
-- Snowflake output, produced by SQLGlot's transpiler
SELECT x FROM TABLE(FLATTEN(INPUT => [OBJECT_CONSTRUCT('x', 'x')])) AS _u(seq, key, path, index, value, this)
```
The transpiler's output is not valid Snowflake, because the identifier `x` referenced in the projection list does not exist. Instead, only the identifiers mentioned in the table alias are visible, and accessing `x` requires extracting it from `value`.
To address this issue, I implemented a rule that conditionally qualifies `UNNEST` sources and the columns they produce, if we can statically determine them.
After this rule is applied, a followup rule, already in effect today, …
=> Feat(snowflake): improve transpilation of queries with UNNEST sources

sqlglot/dialects/risingwave.py, tests/dialects/test_risingwave.py
Before this PR the SQL generated for a MAP datatype declaration expression in the RisingWave dialect was `MAP<x, y>`, where `x` and `y` are other datatypes e.g. `MAP<VARCHAR, INT>`. 
The correct way according to the official docs here https://docs.risingwave.com/sql/data-types/map-type is instead `MAP(x, y)` e.g. `MAP(VARCHAR, INT)`
=> fix(risingwave): Fix RisingWave dialect SQL for MAP datatype declaration

sqlglot/dialects/postgres.py, tests/dialects/test_postgres.py
Fixes #5412
Support the following non-native placeholders for parameter sub:
```
SELECT * FROM foo WHERE id = %s
SELECT * FROM foo WHERE id = %(id_param)s")
```
**DOCS**
[Postgres placeholders](https://www.psycopg.org/psycopg3/docs/basic/params.html)
=> feat(postgres): query placeholders

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
This PR adds support for the transpilation of `GENERATE_DATE_ARRAY` from BigQuery to Snowflake, when a column is an argument. 
In the previous implementation the following BigQuery query:
```
SELECT id, mnth FROM t CROSS JOIN UNNEST(GENERATE_DATE_ARRAY(start_month, DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 MONTH)) AS mnth
```
Would be transpiled into Snowflake: 
```
SELECT
id,
mnth
FROM t
CROSS JOIN (
SELECT
DATEADD(MONTH, CAST(mnth AS INT), CAST(start_month AS DATE)) AS mnth
FROM TABLE(FLATTEN(INPUT => ARRAY_GENERATE_RANGE(
0,
(
DATEDIFF(MONTH, start_month, DATE_TRUNC('MONTH', CURRENT_DATE)) + 1 - 1
) + 1
))) AS _t1(seq, key, path, index, mnth, this)
) AS _t0(mnth)
```
Which is wrong. First, the `CROSS JOIN` doesn't allow access to the column `start_month` of table `t`. 
Moreover, …
=> fix(snowflake): transpile bigquery GENERATE_DATE_ARRAY with column access

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for BigQuery `JSON_ARRAY`.
**DOCS**
[BigQuery JSON_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_array)
=> feat(optimizer)!: parse and annotate type support for bigquery JSON_ARRAY

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for BigQuery `JSON_VALUE` function.
**DOCS**
[BigQuery JSON_VALUE](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_value)
=> feat(optimizer)!: annotate type for bigquery JSON_VALUE

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for `JSON_VALUE_ARRAY` of BigQuery
**DOCS**
[BigQuery JSON_VALUE_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_value_array)
=> feat(optimizer)!: annotate type for bigquery JSON_VALUE_ARRAY

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
This pull request introduces a new feature to the T-SQL dialect in `sqlglot` to automatically add a default precision (`MAX`) to `VARCHAR` data types without an explicit precision. It also includes corresponding updates to preprocessing and test cases.
* **New Functionality**: Added a helper function `add_default_precision_to_varchar` in `sqlglot/dialects/tsql.py` to add a default precision (`MAX`) to `VARCHAR` expressions that lack an explicit precision. This is implemented by checking for `VARCHAR` data types and appending a `DataTypeParam` with the value `MAX` if none exists.
* **Integration with T-SQL Dialect**: Updated the T-SQL `Generator` class to include the new `add_default_precision_to_varchar` function in the preprocessing step for `CREATE` expressions. This ensures the …
=> feat(tsql)!: add default precision to VARCHAR create expressions

sqlglot/dialects/dialect.py, sqlglot/dialects/snowflake.py, sqlglot/expressions.py, sqlglot/parser.py, tests/dialects/test_bigquery.py, tests/dialects/test_snowflake.py
https://github.com/tobymao/sqlglot/pull/2560 made it so that Snowflake's `TRY_CAST` is generated only if the value is of type `{TEXT, UNKNOWN}`; The latter was added to preserve roundtrips but can hurt transpilation attempts coming from other dialects.
To fix this, this PR adds a new boolean arg to `exp.Cast` and removes `UNKNOWN` types from that branch as a "best effort" transpilation attempt.
=> fix(snowflake)!: Remove `UNKNOWN` type from `TRY_CAST`

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [HASH_SHA1](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/hash_sha%5B1%5D.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): Add support for HASH_SHA1 function

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [HASH_MD5](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/hash_md5.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add HASH_MD5 functionality to exasol dialect

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
Snowflake requires that the top-level access is done through the colon operator, while the subsequent accesses can use the dot notation.
-  Before this PR, cannot execute on Snowflake:
```Python3
>>> sql = "WITH tbl AS (SELECT STRUCT(STRUCT(1 as fld2) as fld1) AS col) select CAST(col AS STRUCT<fld1 STRUCT<fld2 INT>>).fld1.fld2 from tbl;"
>>> sqlglot.parse_one(sql, "bigquery").sql("snowflake")
'WITH tbl AS (SELECT OBJECT_CONSTRUCT('fld1', OBJECT_CONSTRUCT('fld2', 1)) AS col) SELECT CAST(col AS OBJECT(fld1 OBJECT(fld2 INT))).fld1.fld2 FROM tbl'
```
- After this PR (note the colon following the cast):
```Python3
>>> sqlglot.parse_one(sql, "bigquery").sql("snowflake")
'WITH tbl AS (SELECT OBJECT_CONSTRUCT('fld1', OBJECT_CONSTRUCT('fld2', 1)) AS col) SELECT CAST(col AS OBJECT(fld1 OBJECT(fld2 …
```
=> feat(snowflake): Transpile BQ's `STRUCT` dot access

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [HASHTYPE_MD5](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/hashtype_md5.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): Add HASHTYPE_MD5 functions to Exasol dialect

sqlglot/dialects/bigquery.py, sqlglot/optimizer/annotate_types.py, tests/test_optimizer.py
This PR aims to address the following bug, introduced [here](https://github.com/tobymao/sqlglot/pull/5230):
```python
>>> from sqlglot.optimizer.annotate_types import annotate_types
>>> from sqlglot.optimizer.qualify import qualify
>>>
>>> ast = parse_one("SELECT ARRAY(SELECT 'foo')", "bigquery")
>>> qualified = qualify(ast, dialect="bigquery")
>>> annotated = annotate_types(qualified, dialect="bigquery")
>>>
>>> annotated.selects[0].type
DataType(
this=Type.ARRAY,
expressions=[
DataType(
this=Type.STRUCT,
expressions=[
ColumnDef(
this=Identifier(this=foo, quoted=False),
kind=DataType(this=Type.VARCHAR))],
nested=True)],
nested=True)
>>> annotated.selects[0].type.sql("bigquery")
'ARRAY<STRUCT<foo STRING>>'
```
Note that BigQuery behaves differently: …
=> Fix(bigquery)!: store Query schemas in meta dict instead of type attr

sqlglot/parser.py, tests/dialects/test_mysql.py
Fixes https://github.com/tobymao/sqlglot/issues/5479
MySQL `UNIQUE` syntax:
```
create_definition: {
col_name column_definition
| ...
| [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
[index_name] [index_type] (key_part,...)
[index_option] ...
| ...
}
```
Docs
---------
[MySQL CREATE](https://dev.mysql.com/doc/refman/8.4/en/create-table.html)
=> feat(mysql): Parse `UNIQUE INDEX` constraint similar to `UNIQUE KEY`

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [REGEXP_SUBSTR](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/regexp_substr.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add support for REGEXP_SUBSTR  in exasol dialect

sqlglot/dialects/oracle.py, sqlglot/dialects/postgres.py, tests/dialects/test_oracle.py, tests/dialects/test_postgres.py
See https://github.com/tobymao/sqlglot/pull/5476#discussion_r2231075745 for reference.
=> Fix!: remove AM/PM entries from postgres, oracle `TIME_MAPPING`

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
SingleStore uses different time formatting formats in different functions.
One of the formats is compatible with MySQL
Related documentation:
* [TO_DATE](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/to-date/)
* [TO_TIMESTAMP](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/to-timestamp/)
* [TO_CHAR](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/to-char/)
* [STR_TO_DATE](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/str-to-date/)
* [DATE_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-format/)
* [TIME_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/time-for …
=> feat(singlestore): Fixed time formatting

pyproject.toml
[AUR](https://aur.archlinux.org/packages/python-sqlglot) package maintainer here.
When building the package we get this warning
```
--- SNIP ---
/usr/lib/python3.13/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated                                  
!!                                                                                                                                                                                             
********************************************************************************                                                                                                       
Please use a simple string containing a SPDX expression for `project.license`. You can …
```
=> Fix deprecated warning when building the package

sqlglot/optimizer/eliminate_joins.py, sqlglot/optimizer/scope.py, tests/fixtures/optimizer/eliminate_ctes.sql, tests/fixtures/optimizer/eliminate_joins.sql, tests/test_optimizer.py
Fixes https://github.com/tobymao/sqlglot/issues/5481
Consider the following query:
```SQL
WITH 
t1 AS (SELECT 1 AS col),
t2 AS (SELECT 1 AS col) 
SELECT * FROM t1 LEFT ANTI JOIN t2 ON t1.col = t2.col
```
There are 2 different issues at play:
1. In `eliminate_joins.py`, this is incorrectly thought to be a simple `LEFT JOIN` which is trivially optimized away:
```Python3
>>> from sqlglot.optimizer.eliminate_joins import eliminate_joins
>>> sql = "WITH t1 AS (SELECT 1 AS col), t2 AS (SELECT 1 AS col) SELECT * FROM t1 LEFT ANTI JOIN t2 ON t1.col = t2.col"
'WITH t1 AS (SELECT 1 AS col), t2 AS (SELECT 1 AS col) SELECT * FROM t1'
```
<br/>
2. In `eliminate_ctes.py`, `t2` is removed as unused. [Previous work](https://github.com/tobymao/sqlglot/pull/4622) excluded SEMI/ANTI join …
=> fix(optimizer): Fix SEMI/ANTI join handling in optimizer rules

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves adding [ADD_DAYS](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/add_days.htm) built -in function to exasol dialect in sqlglot.
=> feat(exasol): add support for ADD_DAYS function in exasol dialect

sqlglot/dialects/doris.py, tests/dialects/test_doris.py
This PR implements an override of the table_sql method for the Doris dialect to resolve the issue #5512 where the AS keyword should not be used in UPDATE and DELETE statements.
- File : sqlglot/dialects/doris.py
- Feature : Override table_sql method to use space separator instead of "AS" keyword in UPDATE and DELETE statements
- Implementation : Check parent nodes of the expression to determine if it's within an UPDATE or DELETE statement, and use space separator accordingly
=> feat(doris): Override table_sql to avoid AS keyword in UPDATE and DELETE statements

sqlglot/dialects/exasol.py, tests/dialects/test_exasol.py
This involves mapping DATE_DIFF function in exasol by adding [DAY_BETWEEN](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/days_between.htm), [YEARS_BETWEEN](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/years_between.htm), [HOURS_BETWEEN](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/hours_between.htm) , [MINUTES_BETWEEN](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/minutes_between.htm) , [SECONDS_BETWEEN](https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/seconds_between.htm) , built -in functions to exasol dialect in sqlglot.
=> feat(exasol): Add support for date difference functions in Exasol dialect

sqlglot/dialects/dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `LAST_DAY`.
**DOCS**
[BigQuery LAST_DAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#last_day)
[Databricks LAST_DAY](http://docs.databricks.com/aws/en/sql/language-manual/functions/last_day)
[Doris LAST_DAY](https://doris.apache.org/docs/2.0/sql-manual/sql-functions/date-time-functions/last-day)
[MySQL LAST_DAY](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html#function_last-day)
[Snowflake LAST_DAY](https://docs.snowflake.com/en/sql-reference/functions/last_day)
[Redshift LAST_DAY](https://docs.aws.amazon.com/redshift/latest/dg/r_LAST_DAY.html)
[DuckDB LAST_DAY](https://duckdb.org/docs/stable/sql/functions/date.html#last_daydate)
=> feat(optimizer)!: annotate type for LAST_DAY

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annoation for `TIME_TRUNC`
**DOCS**
[BigQuery TIME_TRUNC](https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time_trunc)
=> feat(optimizer)!: annotate type for bigquery TIME_TRUNC

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for `TIME`
**DOCS**
[BigQuery TIME](https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time)
=> feat(optimizer)!: annotate type for bigquery TIME

sqlglot/dialects/bigquery.py, sqlglot/dialects/spark.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `DATE_FROM_UNIX_DATE`
**DOCS**
[BigQuery DATE_FROM_UNIX_DATE](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_from_unix_date)
=> feat(optimizer)!: parse and annotate type for bigquery DATE_FROM_UNIX_DATE

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `TIMESTAMP_TRUNC` 
**DOCS**
[BigQuery TIMESTAMP_TRUNC](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_trunc)
=> feat(optimizer)!: annotate type for bigquery TIMESTAMP_TRUNC

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation for BigQuery `CODE_POINTS_TO_STRING`
**DOCS**
[BigQuery CODE_POINTS_TO_STRING](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#code_points_to_string)
=> feat(optimizer)!: parse and annotate type for bigquery CODE_POINTS_TO_STRING

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for BigQuery `REGEXP_EXTRACT_ALL`
**DOCS**
[BigQuery REGEXP_EXTRACT_ALL](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_extract_all)
=> feat(optimizer)!: annotate type for bigquery REGEXP_EXTRACT_ALL

sqlglot/dialects/bigquery.py, sqlglot/generator.py, sqlglot/jsonpath.py, tests/dialects/test_bigquery.py
This is a valid BigQuery query:
```sql
-- "z"
WITH t AS (SELECT '{"x-y": "z"}' AS c) SELECT JSON_EXTRACT(c, '$.x-y') FROM t;
```
Parsing it today produces a waring due to the unrecognized `-` character in the key:
```
Invalid JSON path syntax. Unexpected TokenType.DASH at index 3: $.x-y
```
This PR fixes this by treating it as a "var" token, so it's consumed when parsing keys as a sequence of "vars".
=> Fix(bigquery)!: allow dashes in JSONPath keys

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation for `GROUPING`
**DOCS**
[BigQuery GROUPING](https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#grouping)
[T-SQL GROUPING](https://learn.microsoft.com/en-us/sql/t-sql/functions/grouping-transact-sql?view=sql-server-ver17)
[Oracle GROUPING](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/GROUPING.html)
[Spark GROUPING](https://spark.apache.org/docs/latest/api/sql/index.html#grouping)
[Snowflake GROUPING](https://docs.snowflake.com/en/sql-reference/functions/grouping)
[Redshift GROUPING](https://docs.aws.amazon.com/redshift/latest/dg/r_GROUP_BY_aggregation-extensions.html)
[Clickhouse GROUPING](https://clickhouse.com/docs/sql-reference/aggregate-functions/grouping_function)
[MySQL …
=> feat(optimizer)!: parse and annotate type for bigquery GROUPING

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
See https://github.com/tobymao/sqlglot/issues/5605#issuecomment-3205279961 for context.
We cannot attach `TOP` to the set operation, if any. It clearly binds to the query operand. Only `LIMIT`, `ORDER BY` etc are ambiguous.
=> Fix(tsql): do not attach limit modifier to set operation

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
Documentation:
[MICROSECOND](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/microsecond/)
[DATE_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-format/)
=> feat(singlestore): Added parsing of MICROSECOND function

sqlglot/dialects/doris.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_doris.py
update `exp.UniqueKeyProperty` SQL generation logic to support the `KEY` in materialized views
https://doris.apache.org/docs/sql-manual/sql-statements/table-and-view/async-materialized-view/CREATE-ASYNC-MATERIALIZED-VIEW
=> feat(doris): update exp.UniqueKeyProperty SQL generation logic

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
Documentation:
* [MONTHNAME](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/monthname/)
* [DATE_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-format/)
=> feat(singlestore): Added parsing of MONTHNAME function

sqlglot/dialects/singlestore.py
Following JSON path parts should be removed [here](https://github.com/tobymao/sqlglot/blob/deebf0c3cc379e28c4ab66b6bb7a9c84c14e88c6/sqlglot/generator.py#L69)
=> feat(singelstore): Removed redundant deletions from TRANSFORMS

sqlglot/dialects/tsql.py, tests/dialects/test_tsql.py
Fixes https://github.com/tobymao/sqlglot/issues/5618
I left `offset` in the modifiers due to the following scenario coming from base dialect:
```Python3
sql = "SELECT * FROM a UNION SELECT * FROM b ORDER BY x LIMIT 1"
```
<br/>
- ❌ Without any `SET_OP_MODIFIERS`, T-SQL query can't execute due to error `Invalid usage of the option FIRST in the FETCH statement`:
```Python3
>>> sqlglot.parse_one(sql, dialect="").sql("tsql")
"WITH t1 AS (SELECT 1 AS col), t2 AS (SELECT 2 AS col) 
SELECT * FROM t1 UNION SELECT * FROM t2 ORDER BY col FETCH FIRST 1 ROWS ONLY"
```
<br/>
- ✅ With `SET_OP_MODIFIERS = {"offset"}`, T-SQL query executes fine because `LIMIT` is lifted as a `TOP`
```Python3
>>> sqlglot.parse_one(sql, dialect="").sql("tsql")
"WITH t1 AS (SELECT 1 AS col), t2 AS (SELECT 2 AS col) 
SELECT …
```
=> fix(tsql): Remove ORDER from set op modifiers too

sqlglot/dialects/singlestore.py
SingleStore supports only [EXISTS](https://docs.singlestore.com/cloud/reference/sql-reference/data-manipulation-language-dml/exists-and-not-exists/) subquery predicate.
=> feat(singlestore): Marked exp.All as unsupported

sqlglot/expressions.py, sqlglot/optimizer/qualify_columns.py, tests/fixtures/optimizer/qualify_columns.sql
Fixes https://github.com/tobymao/sqlglot/issues/5638
Properly handle `exp.Aliases` by:
- Including it in the `exp.Select::named_selects`, so that it's available to the `Resolver::get_source_columns()`  
- Excluding it from the nodes that will get aliased otherwise, so that we don't generate `STACK (...) AS (a1, a2, ...) AS _q_0`
=> feat(optimizer)!: Qualify columns generated by exp.Aliases

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, sqlglot/generator.py, tests/dialects/test_bigquery.py
Add support for the BigQuery ML `GENERATE_EMBEDDING` [function,](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-generate-embedding) 
Move and expanded tests for ML functions, including both `FEATURES_AT_TIME` and `GENERATE_EMBEDDING`, into a dedicated test method in `tests/dialects/test_bigquery.py`.
Note that ML.GENERATE_EMBEDDING function syntax is identical to ML.PREDICT function. This is because BigQuery has at least three types of ML. functions: 
- Table-Valued functions like the mentioned above, that are used used in FROM clauses and return tables
- Column-Valued functions that are used in SELECT clauses and return strings/int/scalar/array etc. values ([example](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-bucketize# …
=> feat(bigquery): Add support for ml.generate_embedding function

sqlglot/dialects/dremio.py, tests/dialects/test_dremio.py
Support dremio array_generate_range, parsing to series and back.
https://docs.dremio.com/24.3.x/reference/sql/sql-functions/functions/ARRAY_GENERATE_RANGE/
=> feat(dremio): support array_generate_range

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
SingleStore doesn't support the `XOR` binary operator.
Changed to expand `XOR` into `AND`/`OR`
=> feat(singlestore): Fixed exp.Xor generation

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_bigquery.py
Add support for [BigQuery's `VECTOR_SEARCH`](https://cloud.google.com/bigquery/docs/reference/standard-sql/search_functions#vector_search)
Move `PREDICT` parser to `bigquery.py` to align with the rest of ML functions. Move its tests to test_ml_functions (from test_models) for consistency.
Rearrange order of `FEATURES_AT_TIME`, move the code closer to the other similar functions.
=> feat(bigquery): Add support for vector_search function. Move predict to BigQuery dialect.

sqlglot/dialects/bigquery.py, sqlglot/optimizer/annotate_types.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `APPROX_TOP_COUNT`
**DOCS**
[BigQuery APPROX_TOP_COUNT](https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions#approx_top_count)
=> feat(optimizer)!: parse and annotate type for bigquery APPROX_TOP_COUNT

sqlglot/dialects/bigquery.py, sqlglot/dialects/clickhouse.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/dialects/test_clickhouse.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `APPROX_TOP_SUM`
[BigQuery APPROX_TOP_SUM](https://cloud.google.com/bigquery/docs/reference/standard-sql/approximate_aggregate_functions#approx_top_sum)
[Clickhouse approx_top_sum](https://clickhouse.com/docs/sql-reference/aggregate-functions/reference/approxtopsum)
=> feat(optimizer)!: parse and annotate type for bigquery APPROX_TOP_SUM

sqlglot/dialects/dialect.py, sqlglot/expressions.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `FROM_BASE32` and `TO_BASE32`
**DOCS**
[BigQuery FROM_BASE32](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#from_base32)
[BigQuery TO_BASE32](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#to_base32)
[Presto FROM_BASE32](https://prestodb.io/docs/current/functions/binary.html#from_base32-string-varbinary)
[Presto TO_BASE32](https://prestodb.io/docs/current/functions/binary.html#to_base32-binary-varchar)
[Trino FROM_BASE32](https://trino.io/docs/current/functions/binary.html#from_base32)
[Trino TO_BASE32](https://trino.io/docs/current/functions/binary.html#to_base32)
=> feat(optimizer)!: parse and annotate type for bigquery FROM/TO_BASE32

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for `TO_HEX`
**DOCS**
[BigQuery TO_HEX](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#to_hex)
=> feat(optimizer)!: annotate type for bigquery TO_HEX

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
[REGEXP_MATCH](https://docs.singlestore.com/cloud/reference/sql-reference/regular-expression-functions/regexp-match/)
=> feat(singlestore): Fixed parsing/generation of exp.RegexpExtractAll

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation for `CODE_POINTS_TO_BYTES`
**DOCS**
[BigQuery CODE_POINTS_TO_BYTES](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#code_points_to_bytes)
=> feat(optimizer)!: parse and annotate type for bq CODE_POINTS_TO_BYTES

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `TO_CODE_POINTS`
**DOCS**
[BigQuery TO_CODE_POINTS](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#to_code_points)
=> feat(optimizer)!: parse and annotate type for bq TO_CODE_POINTS

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
[REGEXP_SUBSTR](https://docs.singlestore.com/cloud/reference/sql-reference/regular-expression-functions/regexp-substr/)
=> feat(singlestore): Fixed generation/parsing of exp.RegexpExtract

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
[REGEXP_INSTR](https://docs.singlestore.com/cloud/reference/sql-reference/regular-expression-functions/regexp-instr/)
[CONCAT](https://docs.singlestore.com/cloud/reference/sql-reference/string-functions/concat/)
=> feat(singlestore): Fixed generation of exp.StartsWith

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `BOOL`
**DOCS**
[BigQuery BOOL](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#bool_for_json)
=> feat(optimizer)!: parse and annotate type for bq BOOL

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `REGEXP_INSTR`
**DOCS**
[BigQuery REGEXP_INSTR](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_instr)
[Oracle REGEXP_INSTR](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/REGEXP_INSTR.html)
[Snowflake REGEXP_INSTR](https://docs.snowflake.com/en/sql-reference/functions/regexp_instr)
[T-SQL REGEXP_INSTR](https://learn.microsoft.com/en-us/sql/t-sql/functions/regexp-instr-transact-sql?view=sql-server-ver17)
[Spark REGEXP_INSTR](https://spark.apache.org/docs/latest/api/sql/index.html#regexp_instr)
[Databricks REGEXP_INSTR](https://docs.databricks.com/gcp/en/sql/language-manual/functions/regexp_instr)
[Redshift REGEXP_INSTR](https://docs.aws.amazon.com/redshift/latest/dg/REGEXP_INSTR. …
=> feat(optimizer)!: parse and annotate type for bq REGEXP_INSTR

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `ROW_NUMBER`
**DOCS**
[BigQuery ROW_NUMBER](https://cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions#row_number)
=> feat(optimizer)!: annotate type for bq ROW_NUMBER

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `FIRST_VALUE`
**DOCS**
[BigQuery FIRST_VALUE](https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions#first_value)
=> feat(optimizer)!: annotate type for bq FIRST_VALUE

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `PERCENTILE_DISC`
**DOCS**
[BigQuery PERCENTILE_DISC](https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions#percentile_disc)
=> feat(optimizer)!: annotate type for bq PERCENTILE_DISC

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
Support nested commands inside for loops, such as `BEGIN`:
```
FOR record IN (SELECT word FROM shakespeare) DO
BEGIN
EXECUTE IMMEDIATE "SELECT 1";
END;
END FOR;
```
=> Feat(bigquery): support commands inside for loops

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_duckdb.py, tests/dialects/test_oracle.py, tests/fixtures/identity.sql, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `CUME_DIST`
[BigQuery CUME_DIST](https://cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions#cume_dist)
[T-SQL CUME_DIST](https://learn.microsoft.com/en-us/sql/t-sql/functions/cume-dist-transact-sql?view=sql-server-ver17)
[Snowflake CUME_DIST](https://learn.microsoft.com/en-us/sql/t-sql/functions/cume-dist-transact-sql?view=sql-server-ver17)
[Databricks CUME_DIST](https://docs.databricks.com/aws/en/sql/language-manual/functions/cume_dist)
[Oracle CUME_DIST](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CUME_DIST.html)
[Redshift CUME_DIST](https://docs.aws.amazon.com/redshift/latest/dg/r_WF_CUME_DIST.html)
[Postgres CUME_DIST](https://www.postgresql.org/docs/current/functions-window.html) …
=> feat(optimizer)!: parse and annotate type for bq CUME_DIST

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_oracle.py, tests/fixtures/identity.sql, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `DENSE_RANK`
**DOCS**
[BigQuery DENSE_RANK](https://cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions#dense_rank)
[T-SQL DENSE_RANK](https://learn.microsoft.com/en-us/sql/t-sql/functions/dense-rank-transact-sql?view=sql-server-ver17)
[Snowflake DENSE_RANK](https://docs.snowflake.com/en/sql-reference/functions/dense_rank)
[Oracle DENSE_RANK](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DENSE_RANK.html)
[Clickhouse dense_rank - denseRank](https://clickhouse.com/docs/sql-reference/window-functions/dense_rank)
[Redshift DENSE_RANK](https://docs.aws.amazon.com/redshift/latest/dg/r_WF_DENSE_RANK.html)
[Spark DENSE_RANK](https://docs.databricks.com/gcp/en/sql/language-manual/functions/dense_rank) …
=> feat(optimizer)!: parse and annotate type for bq DENSE_RANK

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `JSON_OBJECT`
**DOCS**
[BigQuery JSON_OBJECT](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_object)
=> feat(optimizer)!: annotate type for bq JSON_OBJECT

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation for `JSON_ARRAY_APPEND`
**DOCS**
[BigQuery JSON_ARRAY_APPEND](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_array_append)
[MySQL JSON_ARRAY_APPEND](https://dev.mysql.com/doc/refman/8.4/en/json-modification-functions.html#function_json-array-append)
=> feat(optimizer)!: parse and annotate type for bq JSON_ARRAY_APPEND

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
[DATE_TRUNC](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-trunc/)
=> feat(singlestore): Fixed generation of exp.DatetimeTrunc and exp.DateTrunc

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation for BigQuery `JSON_KEYS`
**DOCS**
[BigQuery JSON_KEYS](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_keys)
=> feat(optimizer)!: parse and annotate type for bq JSON_KEYS

sqlglot/dialects/singlestore.py, sqlglot/generator.py, tests/dialects/test_singlestore.py
* Improved handling of unsupported datatypes by throwing a corresponding error message and returning the closest available data type
* Updated type mapping for SingleStore-specific data types
* Replaced `VARBINARY` without size by `BLOB`
[Data types](https://docs.singlestore.com/cloud/reference/sql-reference/data-types/)
=> feat(singlestore): Improved geneation of exp.DataType

sqlglot/dialects/bigquery.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/dialects/test_dialect.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds parsing and type annotation support for `JSON_STRIP_NULLS`
**DOCS**
[BigQuery JSON_STRIP_NULLS](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_strip_nulls)
[Postgres JSON_STRIP_NULLS](https://www.postgresql.org/docs/9.5/functions-json.html)
=> feat(optimizer)!: parse and annotate type for bq JSON_STRIP_NULLS

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
Without this column operator, dialect fails to parse expressions like ``` `t0`.`name` ```
=> feat(singlestore): Fixed parsing of columns with table name

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `TO_JSON_STRING`
**DOCS**
[BigQuery TO_JSON_STRING](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#to_json_string)
=> feat(optimizer)!: annotate type for bq TO_JSON_STRING

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation support for `CBRT`
**DOCS**
[BigQuery CBRT](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#cbrt)
=> feat(optimizer)!: annotate type for bq CBRT

sqlglot/dialects/bigquery.py, tests/fixtures/optimizer/annotate_functions.sql
This PR adds type annotation for `RAND`
**DOCS**
[BigQuery RAND](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#rand)
=> feat(optimizer)!: annotate type for bq RAND

sqlglot/dialects/duckdb.py, sqlglot/dialects/snowflake.py
`EXCEPT` is an ANSI standard set operator that removes one rowset from another rowset (e.g., `SELECT id FROM tbl1 EXCEPT SELECT id FROM tbl2`). Sqlglot parses it in `parse_set_operation` based on token type.
Some dialects also use except as a star operator for selecting columns (e.g., `SELECT * EXCEPT(id) FROM tbl`). Sqlglot parses those in `_parse_star_operator` based on text match.
DuckDB and Snowflake use the word `EXCLUDE` for the latter operation. Currently, sqlglot incorrectly maps "EXCLUDE" to `TokenType.EXCEPT` for them, which incorrectly mixes the two usages above.
=> Chore!: remove EXCLUDE keyword mapping to TokenType.EXCEPT

sqlglot/dialects/databricks.py, tests/dialects/test_databricks.py
Databricks has a regexp_like function.  This is preferred over the inherited rlike from spark which is missing that function.
https://docs.databricks.com/aws/en/sql/language-manual/functions/regexp_like
=> feat(databricks): use regexp_like as it exists

sqlglot/optimizer/qualify_columns.py, tests/test_optimizer.py
Consider a query with an aliased integer literal projection that is used in group by: `SELECT 99 as x GROUP BY x`
The optimizer replaces the group by column reference `x` with a positional reference `1`:
```
>>>
>>> optimize(parse_one("SELECT 99 as x GROUP BY x")).sql()
'SELECT 99 AS "x" GROUP BY 1'
```
However, it errors when the integer literal is negative:
```
>>> optimize(parse_one("SELECT -99 as x GROUP BY x")).sql()
Traceback (most recent call last):
return scope.expression.selects[int(node.this) - 1].assert_is(exp.Alias)
^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Literal'
```
This PR fixes the optimizer such that negative integers are optimized …
=> fix(optimizer): allow aliased negative integer literal as group by column

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes #5837 
In sf `TO_CHAR` and `TO_VARCHAR` are synonyms, so this pr adds a common representation that enables also transpilation for `TO_VARCHAR`
**DOCS**
[Snowflake TO_CHAR - TO_VARCHAR](https://docs.snowflake.com/en/sql-reference/functions/to_char)
=> fix(snowflake)!: correct parsing of TO_VARCHAR

sqlglot/dialects/singlestore.py, tests/dialects/test_singlestore.py
[TRUNCATE](https://docs.singlestore.com/cloud/reference/sql-reference/data-definition-language-ddl/truncate/)
=> feat(singlestore): Splitted truncation of multiple tables into several queries

sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_snowflake.py
This PR adds support for `COPY INTO` statements without file list. This is a special syntax supported in Snowflake to load data into a table from a [table stage](https://docs.snowflake.com/en/user-guide/data-load-local-file-system-create-stage#table-stages). (see [docs here](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#loading-using-pattern-matching))
For example, the following statement is valid syntax in Snowflake: 
```
COPY INTO mytable FILE_FORMAT = (TYPE='csv')
```
With the current version of sqlglot, parsing this expression fails with:
```
../../sqlglot/__init__.py:139: in parse_one
result = dialect.parse(sql, **opts)
^^^^^^^^^^^^^^^^^^^^^^^^^^
../../sqlglot/dialects/dialect.py:1083: in parse
return self.parser(**opts).parse(self.tokenize(sql), sql) …
```
=> fix(snowflake): Enable parsing of COPY INTO without files list

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
🐛 fix(snowflake): transpile TO_HEX of bq using TO_VARCHAR
❌ Problem:
When transpiling a BigQuery query containing `TO_HEX(SHA1(...))`, the output for Snowflake is `LOWER(HEX(SHA1(...)))`. This causes an error during execution because Snowflake does not have a built-in HEX function.
Example of failing query:
BigQuery Input: `SELECT TO_HEX(SHA1('abc'))`
Incorrect Snowflake Output: SELECT` LOWER(HEX(SHA1('abc')))`
✅ Solution:
This pull request corrects the transpilation logic by mapping BigQuery's TO_HEX function to Snowflake's TO_VARCHAR function. When applied to the output of a hashing function like SHA1, TO_VARCHAR correctly returns the hexadecimal string representation, achieving the same result as the original BigQuery function.
Note: Snowflake's HEX_ENCODE function was considered, but …
=> fix(snowflake): transpile to_hex of bq using to_varchar

sqlglot/parser.py, tests/dialects/test_pipe_syntax.py
This PR fixes the following:
```
Input:
SELECT * FROM (FROM t2 |> SELECT id)
Output:
SELECT * FROM (WITH __tmp1 AS (SELECT id FROM t2) SELECT * FROM __tmp1)
```
=> fix(parser): JOIN with nested rhs pipe syntax

sqlglot/dialects/redshift.py, tests/dialects/test_redshift.py
- Fixed Redshift dialect to properly convert FETCH FIRST clauses to LIMIT clauses
- Added `LIMIT_FETCH = "LIMIT"` to Redshift Generator class
- Resolves issue where transpiling SQL with FETCH clauses resulted in invalid Redshift syntax
- **sqlglot/dialects/redshift.py**: Added `LIMIT_FETCH = "LIMIT"` property to automatically convert FETCH to LIMIT
=> fix(redshift): convert FETCH clauses to LIMIT for Redshift dialect

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py
Continuation of  #5852 
🐛 Correct BigQuery to Snowflake MD5 transpilation
This PR fixes an issue where BigQuery's MD5 function was incorrectly transpiled to MD5_DIGEST for Snowflake, which is not a valid function. This error caused the transpiled queries to fail. 🚨
The fix correctly maps BigQuery's MD5 to Snowflake's native MD5_BINARY function, ensuring the resulting query is syntactically valid and can execute. A new test case has been added to verify this behavior. 🧪
⚠️ Important Notes on Dialect Discrepancies
While this change produces executable SQL, it's important to be aware of key differences in the function's output between the two dialects:
Output Format: In BigQuery, the result is a base64 encoded string. In Snowflake, the output isn't encoded.
Semantic Equivalence: As a result, …
=> feat(snowflake): MD5Digest transpiling to MD5_BINARY

sqlglot/dialects/snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate and add tests for snowflake LENGTH and LOWER functions.
Documentation: 
https://docs.snowflake.com/en/sql-reference/functions/length
https://docs.snowflake.com/en/sql-reference/functions/lower
=> feat(optimizer)!: annotate and add tests for snowflake LENGTH and LOWER functions

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Adds parsing of OCTET_LENGTH
**DOCS**
[Snowflake OCTET_LEGNTH](https://docs.snowflake.com/en/sql-reference/functions/octet_length)
=> fix(snowflake): parse OCTET_LENGTH

sqlglot/optimizer/annotate_types.py, tests/fixtures/optimizer/annotate_functions.sql, tests/test_optimizer.py
Prior to this fix, the assertion in `test_struct_annotation_bigquery` would fail because the type showed up as `UNKNOWN`, which is incorrect.
=> Fix(optimizer)!: use column name in struct type annotation

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py
Fixes #5895
```
BigQuery:
WITH foo AS (SELECT [1] AS arr_1) SELECT (SELECT unnested_arr FROM UNNEST(arr_1) AS unnested_arr) AS f FROM foo
Snowflake (old output + wrong):
WITH foo AS (SELECT [1] AS arr_1) SELECT (SELECT unnested_arr FROM TABLE(FLATTEN(INPUT => unnested_arr['arr_1'])) AS _t0(seq, key, path, index, unnested_arr, this)) AS f FROM foo
Snowflake (PR's output):
WITH foo AS (SELECT [1] AS arr_1) SELECT (SELECT unnested_arr FROM TABLE(FLATTEN(INPUT => arr_1)) AS _t0(seq, key, path, index, unnested_arr, this)) AS f FROM foo
```
=> fix(snowflake): transpile BQ UNNEST with alias

sqlglot/dialects/duckdb.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/tokens.py, tests/dialects/test_duckdb.py
This PR adds support for the `INSTALL` of duckdb
Finishes #5882 
**DOCS**
[DuckDB INSTALL](https://duckdb.org/docs/stable/extensions/installing_extensions.html)
=> feat(duckdb): support INSTALL

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Links: https://fivetran.atlassian.net/browse/RD-1036143
Documentation: https://docs.snowflake.com/en/sql-reference/functions/chr
=> feat(optimizer)!: annotate type for Snowflake CHR function

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Closes https://fivetran.atlassian.net/browse/RD-1035998 
Add expression class, Annotate types for snowflake BASE64_DECODE_STRING and BASE64_ENCODE functions.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/base64_decode_string
https://docs.snowflake.com/en/sql-reference/functions/base64_encode
=> feat(optimizer)!: Add expression class, annotate types for snowflake BASE64_DECODE_STRING and BASE64_ENCODE functions

README.md, sqlglot/dialects/__init__.py, sqlglot/dialects/dialect.py, sqlglot/dialects/solr.py, tests/dialects/test_solr.py
This is an initial Solr dialect. It captures:
* Literal and identifier quotation rules
* Normalization strategy
* Disabling double pipe string concatenation
Solr Query Language: https://solr.apache.org/guide/solr/latest/query-guide/sql-query.html
=> feat(solr): initial Solr dialect

sqlglot/dialects/bigquery.py, tests/dialects/test_bigquery.py
https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved_keywords
=> fix(bigquery): Allow GRANT as an id var

Makefile
Allows users to set `UV=1` and use uv instead of pip for managing packages.
Matches what is done in SQLMesh: https://github.com/TobikoData/sqlmesh/blob/bf40bbeafc07723d76d64da44c635387cda57b62/Makefile#L3-L7
=> chore: add uv support to Makefile

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake TRY_BASE64_DECODE_STRING function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/try_base64_decode_string
=> feat(optimizer)!: Annotate type for snowflake TRY_BASE64_DECODE_STRING function

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake TRY_HEX_DECODE_BINARY function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/try_hex_decode_binary
=> feat(optimizer)!: Annotate type for snowflake TRY_HEX_DECODE_BINARY function

sqlglot/optimizer/merge_subqueries.py, tests/fixtures/optimizer/merge_subqueries.sql
=> fix(optimizer): convert INNER JOINs to LEFT JOINs when merging LEFT JOIN subqueries

sqlglot/dialects/hive.py, sqlglot/dialects/oracle.py, sqlglot/dialects/presto.py, sqlglot/dialects/spark.py, sqlglot/transforms.py, tests/dialects/test_dialect.py, tests/test_transforms.py
Fixes #5995
This transformation was [introduced ~3 years ago](github.com/tobymao/sqlglot/pull/305) as a response to [this issue](https://github.com/tobymao/sqlglot/issues/304), but I think it's unsafe to use without a schema & additional logic. I've added a couple of tests in `test_dialect.py` that demonstrate the issue (both convert valid Hive SQL into invalid SQL).
Since we have `_expand_positional_references` in `qualify_columns.py`, I think there's already a path to resolving these aliases referenced in `GROUP BY` clauses, so this is not needed anymore.
=> Fix!: remove `unalias_group_by` transformation since it is unsafe

sqlglot/optimizer/merge_subqueries.py, tests/fixtures/optimizer/merge_subqueries.sql, tests/fixtures/optimizer/optimizer.sql, tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
We were incorrectly merging subqueries that contained `JOINs` when the outer query also used a `JOIN` clause. This changed join precedence and produced incorrect results.
```
WITH
t0 AS (SELECT 5 as id),
t1 AS (SELECT 1 AS id, 'US' AS cid),
t2 AS (SELECT 1 AS id, 'US' AS cid)
SELECT t0.id, t3.cid AS cid
FROM t0
INNER JOIN (
SELECT t1.id, t2.cid
FROM t1
RIGHT JOIN t2 ON t1.cid = t2.cid
) AS t3 ON t0.id = t3.id;
┌───────┬─────────┐
│  id   │   cid   │
│ int32 │ varchar │
├───────┴─────────┤
│     0 rows      │
└─────────────────┘
======= Optimized (previous version) =======
WITH
t0 AS (SELECT 5 as id),
t1 AS (SELECT 1 AS id, 'US' AS cid),
t2 AS (SELECT 1 AS id, 'US' AS cid)
SELECT t0.id, t2.cid AS cid
FROM t0
INNER JOIN t1 ON t0.id = t1.id
RIGHT JOIN t2 ON t1.cid = t2.cid; …
```
=> fix(optimizer): avoid merging subquery with JOIN when outer query uses JOIN

sqlglot/dialects/dialect.py, sqlglot/expressions.py, tests/dialects/test_snowflake.py
This valid Snowflake query:
```sql
SELECT DATEADD(DAY, -7, DATEADD(t.m, 1, CAST('2023-01-03' AS DATE))) FROM (SELECT 'month' AS m) AS t
```
Gets clobbered up today:
```python
>>> sqlglot.transpile("SELECT DATEADD(DAY, -7, DATEADD(t.m, 1, CAST('2023-01-03' AS DATE))) FROM (SELECT 'month' AS m) AS t", "snowflake")
["SELECT DATEADD(DAY, -7, DATEADD(MINUTE, 1, CAST('2023-01-03' AS DATE))) FROM (SELECT 'month' AS m) AS t"]
```
I guess we've been assuming that columns aren't valid in this context.
Reported here: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1759511628261859
=> Fix: respect multi-part Column units instead of converting to Var

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake DIV0 and DIVNULL functions.
DIV0 is already handled, so only added the tests.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/div0
https://docs.snowflake.com/en/sql-reference/functions/div0null
=> feat(optimizer): Annotate type for snowflake DIV0 and DIVNULL functions

sqlglot/dialects/snowflake.py, tests/dialects/test_bigquery.py, tests/dialects/test_databricks.py, tests/dialects/test_duckdb.py, tests/dialects/test_postgres.py, tests/dialects/test_redshift.py, tests/dialects/test_snowflake.py, tests/dialects/test_tsql.py, tests/fixtures/optimizer/annotate_functions.sql
Documentation: https://docs.snowflake.com/en/sql-reference/functions/exp
Platform Support:
Platform | Supported | Arguments | Return Type | Notes
Snowflake | Yes | Numeric | Numeric (float) | Native EXP function
BigQuery | Yes | Numeric convertible | FLOAT64 | Native EXP function
Redshift | Yes | Integer, Decimal, Double | DOUBLE PRECISION | Native EXP function
PostgreSQL | Yes | Numeric | DOUBLE PRECISION | Native EXP function
Databricks | Yes | Numeric | DOUBLE | Native EXP function
DuckDB | Yes | Numeric | Numeric (double) | Native EXP function
TSQL | Yes | Float expression | Float | Native EXP function
=> feat(optimizer)!: annotate type for Snowflake EXP function

sqlglot/dialects/snowflake.py, sqlglot/expressions.py, tests/dialects/test_bigquery.py, tests/dialects/test_databricks.py, tests/dialects/test_duckdb.py, tests/dialects/test_postgres.py, tests/dialects/test_redshift.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Documentation: https://docs.snowflake.com/en/sql-reference/functions/cosh
Platform Support:
Platform | Supported | Arguments | Return Type | Notes
Snowflake | Yes | Numeric or convertible | Numeric | Snowflake native COSH function
BigQuery | Yes | Numeric coercible to FLOAT64 | FLOAT64 | Native COSH function
Redshift | Yes | Numeric | Numeric | Based on PostgreSQL compatibility
PostgreSQL | Yes | Numeric | Numeric | Standard function
Databricks | Yes | Numeric | DOUBLE | Native COSH function
DuckDB | Yes | Numeric | Numeric | Native COSH function
TSQL | No | N/A | N/A | No native COSH, compute via formula
=> feat(optimizer)!: annotate type for Snowflake COSH function

sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake ROUND function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/round 
Platform | Supported | Argument Type | Return Type
-- | -- | -- | --
Snowflake | ✅ Yes | NUMERIC, INT (scale), STRING (mode) | Preserves input type
BigQuery | ✅ Yes | NUMERIC, INT (scale) | Preserves input type
Redshift | ✅ Yes | NUMERIC, INT (scale) | Preserves input type
PostgreSQL | ✅ Yes | NUMERIC, INT (scale) | Preserves input type
Databricks | ✅ Yes | NUMERIC, INT (scale) | Preserves input type
DuckDB | ✅ Yes | NUMERIC, INT (scale) | Preserves input type
T-SQL | ✅ Yes | NUMERIC, INT (scale), INT (function) | Preserves input type
</body>
</html>
=> feat(optimizer): Annotate type for snowflake ROUND function

sqlglot/dialects/dialect.py, sqlglot/dialects/hive.py, sqlglot/dialects/spark2.py, sqlglot/expressions.py, sqlglot/generator.py, sqlglot/parser.py, tests/dialects/test_hive.py, tests/dialects/test_spark.py
Documentation:
- [Hive](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-AlterColumn)
- [Spark](https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-alter-table.html#alter-or-change-column)
I validated that the test case output were considered syntactically valid by their respective engines.
=> feat(hive,spark)!: Support CHANGE COLUMN statements in Hive and CHANGE/ALTER COLUMN statements in Spark

sqlglot/dialects/dialect.py, sqlglot/dialects/snowflake.py, tests/dialects/test_snowflake.py, tests/fixtures/optimizer/annotate_functions.sql
Annotate type for FLOOR function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/floor
=> feat(optimizer): Annotate type for snowflake FLOOR function
