tobymao/sqlglot

- README.md
- benchmarks/bench.py
> add sqloxide to benchmarks

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_transpile.py
> extract and timestamps / refactor

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_expressions.py
- tests/test_tokens.py
- tests/test_transpile.py
so i first tried implementing AST comparison. and that worked, but it was far more lines of code 
i figure it's possible for the AST to differ but the resulting SQL be the same due to optimizations, this actually happens when we parse IF vs CASE, the AST is different, but the resulting SQL is the same due to optimization in the Generator.
so anyways, I choose to have the identified non-pretty sql be the source of truth
> add equality and hashing abilities + convenience functions to columns

- sqlglot/expressions.py
I must've messed this up during the previous refactoring.
> Fix the parent class for the Identifier tree node (previously was Func)

- README.md
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_parser.py
Adding pound `#` and then an identifier you can now annotate a selected field
> Added support to recognize annotations

- sqlglot/expressions.py
- sqlglot/parser.py
I didn't notice any change in performance in the benchmarks. I think ultimately it's the same amount of work, just not all at once.
But there's enough variance between runs that it's hard to tell.
@tobymao
> Set parents on the fly

- sqlglot/dialects.py
- tests/test_dialects.py
This PR added a tableau dialect class to do if sql transform
Tableau IF function syntax:
IF test THEN value ELSE else END
Revewers:
@tobymao @robert8138 @kelsin
> Add tableau dialect class

- sqlglot/dialects.py
- tests/test_dialects.py
Support `array_length` function
See https://duckdb.org/docs/sql/functions/nested
> [Duckdb] Support array_length

- sqlglot/expressions.py
- tests/test_expressions.py
Used [deque](https://docs.python.org/3/tutorial/datastructures.html#using-lists-as-queues)
> Use a proper queue for bfs instead of a stack

- sqlglot/expressions.py
- tests/test_expressions.py
This allows expressions within an AST to be surgically replaced.
Kind of an ugly operation.
@tobymao
> feat: Expression.replace

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/helper.py
- sqlglot/optimizer.py
- tests/test_expressions.py
- tests/test_optimizer.py
initial optimizer rule, to rewrite sql into canonical form
useful for parsing arbitrary queries and physical plans
> first pass of optimizer

- sqlglot/optimizer/helper.py
- sqlglot/optimizer/optimize.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- sqlglot/optimizer/quote_identities.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/qualify_tables.sql
- tests/fixtures/optimizer/quote_identities.sql
- tests/test_optimizer.py
This adds aliases to all tables.
This also quotes everything.
@tobymao
> feat(optimizer): qualify_tables to add aliases

- sqlglot/__init__.py
- sqlglot/generator.py
- tests/test_parser.py
This allows users to set pretty to True for an entire project if they prefer the default behavior to be pretty.
> Make pretty a module config

- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/tcp-h.sql
- tests/test_optimizer.py
This pushes ambiguous columns in subqueries up.
@tobymao
> fix: tcph 2

- sqlglot/optimizer/__init__.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/schema.py
- tests/test_docs.py
- tests/test_optimizer.py
> fix(optimizer): add catalog and db to schema

- setup.py
Whoops. Looks like we're not actually publishing the optimizer package.
> fix: publish optimizer package

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
- tests/test_optimizer.py
> add absorb and eliminate

- sqlglot/expressions.py
- sqlglot/optimizer/decorrelate_subqueries.py
- sqlglot/optimizer/pushdown_predicates.py
- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- sqlglot/optimizer/scope.py
- tests/test_optimizer.py
references... selectables... referenced_selectables... selectable_references... 
The names might be getting confusing.
> feat: Scope.selectable_references()

- sqlglot/expressions.py
- sqlglot/generator.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
- tests/fixtures/pretty.sql
> finally have pretty working well

- sqlglot/parser.py
- sqlglot/tokens.py
> Add support for 'SELECT TOP <n>' as an alternative syntax for LIMIT.

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/decorrelate_subqueries.py
- sqlglot/optimizer/simplify.py
- sqlglot/tokens.py
- tests/fixtures/identity.sql
- tests/fixtures/optimizer/simplify.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
based on
https://github.com/tobymao/sqlglot/pull/171/files
cc @marsupialtail
> simplify literals

- sqlglot/expressions.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
> fix: Some optimizer speedups

- sqlglot/expressions.py
- sqlglot/optimizer/scope.py
Incremental improvement. 
@tobymao
> fix: collect scope once

- .github/workflows/python-package.yml
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
> Upgrade GitHub Actions

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/helpers.py
- tests/test_executor.py
- tests/test_optimizer.py
- tests/test_transpile.py
Fixes https://github.com/tobymao/sqlglot/issues/241
> qualify QUALIFY clauses

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_columns.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
fixes https://github.com/tobymao/sqlglot/issues/258
> fix: allow post FROM clauses to reference unaliased, named outputs

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
fixes https://github.com/tobymao/sqlglot/issues/259
> fix: Handle nested subqueries

- sqlglot/__init__.py
- sqlglot/dialects/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/helper.py
Add DialectType enum for all dialect names
> Add DialectType for all dialect names

- sqlglot/errors.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/helpers.py
- tests/test_transpile.py
This just popped into my head, that I forgot to add this ErrorLevel to the Generator as well.
> ErrorLevel.IMMEDIATE for Generator

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_dialects.py
- tests/test_expressions.py
- tests/test_transpile.py
> spark to_date takes in a format which makes things more complicated

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/sqlite.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/test_dialects.py
Also adds support in SQLite for ` identifier enclosures
Fixes #302
> Add support for SQLite square bracket identifier enclosures

- sqlglot/dialects/oracle.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
> improve oracle support

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
Fixes https://github.com/tobymao/sqlglot/issues/375
> MySQL double quotes

- sqlglot/dialects/oracle.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/dialects/test_dialect.py
> added BLOB and CLOB

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
fix parsing of check constraints to require parens and for expression to be a condition
> fix parsing of check constraints

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
> Add support for casting to interval type

- sqlglot/executor/__init__.py
- sqlglot/expressions.py
- sqlglot/optimizer/__init__.py
- sqlglot/optimizer/merge_derived_tables.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/merge_derived_tables.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
- tests/test_executor.py
- tests/test_optimizer.py
New optimizer rule: merge derived tables
References:
https://dev.mysql.com/doc/refman/8.0/en/derived-table-optimization.html
https://mariadb.com/kb/en/derived-table-merge-optimization/
@tobymao this fights with the "isolate_table_selects" rule a bit. Happy to chat more.
cc @ginter
> Optimizer: Merge derived tables

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
> Support lateral with subqueries

- sqlglot/parser.py
- tests/test_transpile.py
> Support datetime operations in extract function

- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Support operations in substring's arguments

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
See [discussion](https://github.com/tobymao/sqlglot/pull/444#discussion_r973199672).
> Use joins instead of all query modifiers in table

- sqlglot/dialects/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_dialect.py
- tests/dialects/test_redshift.py
This is an attempt to add support for the redshift dialect. Feedback is welcome. Plan to add more features soon.
> Add redshift dialect (WIP)

- sqlglot/executor/__init__.py
- sqlglot/expressions.py
- sqlglot/helper.py
- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/merge_subqueries.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
- tests/test_expressions.py
- tests/test_optimizer.py
- tests/test_transforms.py
Optimizer step to rewrite subqueries as CTEs.
This shouldn't be part of our standard optimizer steps.
cc @jeffwong
> Rewrite derived tables as CTEs

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
> fix scope traversal

- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/qualify_columns__invalid.sql
Honing in on the name selection.
The previous version was a bit too conservative.
> less conservative CTE name

- sqlglot/optimizer/merge_subqueries.py
- tests/fixtures/optimizer/merge_subqueries.sql
Holy moly this took me a long time to debug.
I wasn't copying the expression when replace columns in the outer query.
> fix merge subqueries

- sqlglot/expressions.py
- sqlglot/optimizer/scope.py
- tests/test_optimizer.py
We already have logic for traversing within a scope. Let's expose it as a public method.
Solves this: https://github.com/tobymao/sqlglot/discussions/522#discussioncomment-3783662
> Scope.walk, Scope.find, and Scope.find_all

- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
postgres overload TO_TIMESTAMP and Oracle add time_mapping
> postgres overload TO_TIMESTAMP and Oracle add time_mapping

- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/schema.py
- tests/fixtures/optimizer/qualify_columns__with_invisible.sql
- tests/test_optimizer.py
add support for invisible columns ([ref](https://dev.mysql.com/doc/refman/8.0/en/invisible-columns.html)). This will let us have more control over the columns that get expanded for select stars in the optimizer.
cc @barakalon
> add support for invisible columns

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_dialect.py
> implement map/array/struct syntax for clickhouse

- sqlglot/__init__.py
- sqlglot/expressions.py
- tests/test_build.py
> Export union/intersect/except builders

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Allow functions after IN

- sqlglot/parser.py
- tests/dialects/test_tsql.py
Fixes: https://github.com/tobymao/sqlglot/discussions/574
> Allow OVER syntax after WITHIN GROUP (tsql)

- sqlglot/optimizer/eliminate_joins.py
- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/scope.py
- sqlglot/planner.py
- tests/fixtures/optimizer/eliminate_joins.sql
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/test_optimizer.py
Adds optimizer rule to remove unused LEFT JOINs
More context: https://github.com/tobymao/sqlglot/issues/564
> Optimizer: Eliminate joins

- sqlglot/optimizer/eliminate_ctes.py
- sqlglot/optimizer/optimizer.py
- sqlglot/optimizer/pushdown_predicates.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/eliminate_ctes.sql
- tests/test_optimizer.py
Fixes https://github.com/tobymao/sqlglot/issues/564
> Optimizer: Eliminate CTEs

- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Support right operand after json cast (postgres)

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
Opening this PR for feedback. Aims to support syntax mentioned in https://github.com/tobymao/sqlglot/pull/586. If this is on the right track, I can try implementing the `N'literal'` syntax similarly.
> Add E'\\xDEADBEEF' (postgres) and N'Some Text' (mysql)

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/fixtures/identity.sql
Sources:
- https://www.postgresql.org/docs/current/sql-delete.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_DELETE.html
Fixes #594
> Support DELETE USING syntax

- sqlglot/expressions.py
- sqlglot/helper.py
- tests/test_expressions.py
I removed the doc string tests for to_table and to_column since they didn't really work before due to a recursion issue.
> Add to_column and add helper for splitting to num words

- sqlglot/dialects/dialect.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/helper.py
- tests/dialects/test_duckdb.py
Also simplified the `rename_func`.
> Add support for array_concat

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
This is an attempt to tackle https://github.com/tobymao/sqlglot/discussions/604.
References:
- https://prestodb.io/docs/current/functions/datetime.html
- https://docs.snowflake.com/en/sql-reference/functions-date-time.html#label-supported-date-time-parts
- https://docs.snowflake.com/en/sql-reference/functions/date_part.html
> Transpile snowflake epoch_ time parts

- sqlglot/dataframe/sql/functions.py
- sqlglot/generator.py
i had some trouble with round, arraysort, power, date, and map,
the code that you have is a bit confusing and i'm not sure the correct abstraction,
for example with round, you accept both a column and a float, but you have no way for that to be passed to Round(decimals=...) because ensure_column returns a spark column, not a sqlglot expression.
> fix up some spark funcs

- sqlglot/expressions.py
https://github.com/tobymao/sqlglot/pull/559#discussion_r990416563
> Add comment for window exprs @ alias builder

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Working on making T-SQL available, more pull requests to come.
> Added TSQL CHARINDEX support in parser

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING
> Postgres - Dollar-Quoted String Constants

- sqlglot/expressions.py
- tests/test_expressions.py
> Add support for placeholder substitution

- sqlglot/parser.py
- tests/dialects/test_dialect.py
> Support alternative limit/offset syntax

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_tsql.py
Noticed the dateadd addition and I was working on this part as well.
Some extensions to the already implemented, similar problems to other date functions in tsql arise here.
> extend dateadd tsql/hive

- README.md
- dev-requirements.txt
- sqlglot/__init__.py
See what README looks like with these changes [here](https://github.com/tobymao/sqlglot/blob/eb4072dce563e2cbf9633b3d0a42b2ac251a83ad/README.md).
> README cleanup, add pdocs

- tests/dialects/test_snowflake.py
Add more complete test (didn't get chance to on original PR).
https://github.com/tobymao/sqlglot/pull/646#issuecomment-1293608718
> More complete transient test for Snowflake

- sqlglot/dialects/mysql.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
Kinda janky.
See https://github.com/tobymao/sqlglot/pull/673 for context.
> Make SET a Command by default

- sqlglot/dialects/mysql.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
This fixes various issues I found while testing.
> MySQL command fixups

- sqlglot/errors.py
- sqlglot/executor/__init__.py
- sqlglot/executor/context.py
- sqlglot/executor/env.py
- sqlglot/executor/python.py
- sqlglot/planner.py
- tests/test_executor.py
My brain is fried right now, so I should do another pass on cleaning this up tomorrow.
But I wanted to put up my progress so far.
> execute SQL on python objects

- sqlglot/executor/__init__.py
- sqlglot/executor/python.py
- sqlglot/executor/table.py
- sqlglot/helper.py
- sqlglot/schema.py
- tests/test_executor.py
No you can execute statements like `SELECT * FROM catalog.db.x`.
> Execute SQL on catalog.db.table

- sqlglot/parser.py
- tests/fixtures/identity.sql
> Fix delete using with table alias

- sqlglot/dialects/tsql.py
As we can also have just expressions within the convert function.
> TSQL parse convert expression fix

- CHANGELOG.md
- sqlglot/diff.py
- sqlglot/planner.py
- sqlglot/schema.py
Posting this for some early feedback, plan to annotate some more files for this PR.
> Add more python types

- sqlglot/parser.py
- tests/test_transpile.py
> Fix current time issue

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
> Add support for Snowflake TRIM function

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- tests/dialects/test_mysql.py
This command is documented a long with the other SET commands, so I missed it.
> MySQL SET TRANSACTION

- sqlglot/tokens.py
- tests/test_tokens.py
- tests/test_transpile.py
These changes ensure consistency in the comment attachment logic for tokens.
References: discussion in https://github.com/tobymao/sqlglot/issues/712
> Fix token comment attachment logic

- sqlglot/parser.py
- sqlglot/tokens.py
- tests/test_transpile.py
Reference: https://github.com/tobymao/sqlglot/issues/714#issuecomment-1317607713
> Fix parsing logic for hints

- sqlglot/executor/env.py
- sqlglot/executor/python.py
- tests/test_executor.py
Adding tests and fixing some issues.
> Executor fixes

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_sqlite.py
- tests/fixtures/identity.sql
> Fix sqlite primary key order constraint

- sqlglot/dialects/redshift.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_redshift.py
Do we want to parse these at a finer granularity or is this ok? @tobymao 
Fixes #763
Fixes #764
> Add support for Redshift's COPY and UNLOAD commands

- sqlglot/optimizer/annotate_types.py
- sqlglot/optimizer/eliminate_subqueries.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
fixes https://github.com/tobymao/sqlglot/issues/775
> Optimizer: Support nested CTEs

- sqlglot/executor/__init__.py
- sqlglot/executor/python.py
- sqlglot/planner.py
- tests/test_executor.py
Fixes https://github.com/tobymao/sqlglot/issues/781
> Execute SELECT DISTINCT

- sqlglot/dialects/clickhouse.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
Fixes #783 
cc: @cpcloud feel free to post any use cases so I can include them in the test suite.
> Add support for clickhouse ANY/ASOF in joins

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
> Add support for redshift DECODE

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
> Add support for bigquery ARRAY function

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
> Fix transpilation of regexp (mysql) to regexp_contains (bigquery)

- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- dev-requirements.txt
- pdoc/cli.py
- pdoc/templates/module.html.jinja2
- run_checks.sh
- setup.py
- sqlglot/__init__.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/starrocks.py
- sqlglot/dialects/tableau.py
- sqlglot/dialects/tsql.py
This is an attempt to improve the workflow in SQLGlot.
- Replaced the `run_checks.sh` script with a `Makefile`.
- Added pre-commit hooks for lint checks.
- Moved dev. dependencies in `setup.py`.
> Refactor SQLGlot workflow, CI/CD, improve pdoc template

- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/unnest_subqueries.py
- tests/fixtures/optimizer/unnest_subqueries.sql
@barakalon I think I'll pass on optimizing this for now.. If it's clear to you how it can be done, feel free to tackle it. I tried some approaches already but they weren't quite correct, so I thought I'd leave this be since it's not high priority.
> Optimizer: fix bug in correlated subquery projections

- sqlglot/parser.py
- tests/test_transpile.py
> Fix bug in presto values parsing

- sqlglot/dataframe/sql/_typing.pyi
- sqlglot/dataframe/sql/dataframe.py
Minor changes to simplify the typing used in DataFrame API implementation
> Simplify dataframe typing

- posts/python_sql_engine.md
Python SQL engine post edits for grammar/style.
> Python SQL engine post edits.

- sqlglot/dialects/clickhouse.py
- sqlglot/helper.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Phew... this was more tricky than expected.
Fixes #882
> Add support for clickhouse's parametric function syntax

- sqlglot/expressions.py
- sqlglot/helper.py
- sqlglot/optimizer/eliminate_joins.py
- sqlglot/optimizer/qualify_columns.py
- tests/dataframe/unit/test_functions.py
- tests/dialects/test_hive.py
- tests/helpers.py
- tests/test_optimizer.py
[`pyupgrade --py37-plus **/*.py`](https://pypi.org/project/pyupgrade)
> pyupgrade: Modernize syntax for Python >= 3.7

- sqlglot/dialects/hive.py
- sqlglot/dialects/spark.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_presto.py
- tests/dialects/test_tsql.py
- Added support for EOMONTH in T-SQL
- Made sure that if its a temporal type no precision is beeing specified in the datatypes at Hive and depending dialects
- Changed class of GETDATE() to CurrentTimestamp as it is also helding time
- Added support for SYSDATETIME
- Fixed the parsing of a CAST on a subquery
> Added support for multiple T-SQL features

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
> Refactor clickhouse parametric functions, add quantiles

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
> Add support for clickhouse GLOBAL IN syntax

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
> Optimizer: add datetime simplification, fix date

- sqlglot/tokens.py
- tests/dialects/test_hive.py
> Fix: allow underscore after digits in identifier names

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/fixtures/pretty.sql
> Fix: parse WITH OFFSET AS offset for bigquery

- sqlglot/tokens.py
- tests/dialects/test_hive.py
> More fixes regarding spark/hive identifiers

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix: parse TSQL table variables (e.g. @table_name)

- sqlglot/parser.py
- tests/test_transpile.py
Fixes item 21 of https://github.com/tobymao/sqlglot/issues/963
> Fix presto values parsing

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes #973 
Reference: https://clickhouse.com/docs/en/sql-reference/statements/select/with/
> Add support for alternative CTE syntax (clickhouse)

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_tsql.py
Fixes #993 
Reference: https://learn.microsoft.com/en-us/sql/relational-databases/tables/querying-data-in-a-system-versioned-temporal-table?view=sql-server-ver16
> Add support for TSQL 'FOR SYSTEM_TIME' clause

- sqlglot/parser.py
- tests/dialects/test_dialect.py
> Fix parsing for MERGE statement

- sqlglot/dataframe/sql/dataframe.py
I believe this is functionality equivalent to prior behavior but just simplifying as we start trying to figure out why we are getting flaky tests.
> Simpify CTE name replacement

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_tsql.py
Addresses some leftover issues in #970
> Fix TSQL UDF BEGIN parsing

- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
> Fix: remove mapping of 'END' token for T-SQL

- sqlglot/optimizer/expand_multi_table_selects.py
- sqlglot/optimizer/optimize_joins.py
Fixes https://github.com/tobymao/sqlglot/issues/1044
> Add docs for expand_multi_table_selects and optimize_joins

- sqlglot/parser.py
- tests/dialects/test_hive.py
> Fix Hive GROUPING SETS parsing

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_hive.py
> Fix Hive PARTITION parsing

- sqlglot/dialects/hive.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_hive.py
> Fix Hive WITH CUBE/ROLLUP syntax

- sqlglot/generator.py
- sqlglot/parser.py
Address @GeorgeSittas comments in #1033
> Clean up CREATE TABLE options generator

- sqlglot/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/expressions.py
- sqlglot/lineage.py
- sqlglot/schema.py
- tests/dialects/test_dialect.py
> Fix: handling Dialect, t.Type[Dialect] now works in get_or_raise

- sqlglot/parser.py
- tests/fixtures/identity.sql
> Fix quoted id/var parsing

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- tests/dialects/test_dialect.py
- tests/dialects/test_spark.py
> Fix transpilation of aggregate for presto

- sqlglot/dialects/oracle.py
- tests/dialects/test_dialect.py
Mapping SUBSTRING to SUBSTR for Oracle
> Oracle only supports SUBSTR

- sqlglot/generator.py
Addresses https://github.com/tobymao/sqlglot/pull/1101#discussion_r1097909167
> Replace unnecessary 'properties' check

- README.md
- sqlglot/executor/__init__.py
- sqlglot/executor/table.py
> Cleanup docs, add more type hints

- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
References:
- https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
- https://www.cockroachlabs.com/blog/select-for-update/
> Add support for locking read syntax: SELECT ... FOR UPDATE/SHARE

- sqlglot/parser.py
- tests/fixtures/identity.sql
- tests/fixtures/pretty.sql
> Fix EXCEPT parsing

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix Snowflake DAYOFWEEK generation

- sqlglot/dialects/snowflake.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
> Fix parsing for snowflake AUTOINCREMENT/IDENTITY constraints

- sqlglot/dialects/redshift.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
> Add COPY as a command

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
fixes https://github.com/tobymao/sqlglot/issues/1134
> order by in window function

- .github/workflows/python-package.yml
Reverts tobymao/sqlglot#1145
That didn't work.
> Revert "only publish docs on tags"

- tests/fixtures/optimizer/optimizer.sql
- tests/test_optimizer.py
> Revert "Disable execution of lateral column tests"

- sqlglot/dialects/teradata.py
- tests/dialects/test_teradata.py
- Abbreviate INSERT as INS
- Abbreviate comparison operators:
- LT, <
- LE, <=
- GT, >
- GE, >=
- ^=, <>
- NE, <>
- NOT=, <>
> Teradata: more abbreviations

- sqlglot/dialects/oracle.py
- sqlglot/tokens.py
- tests/dialects/test_oracle.py
Some fixups related to https://github.com/tobymao/sqlglot/pull/1159
> Improve xmltable parsing & formatting

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
fixes https://github.com/tobymao/sqlglot/issues/1167
> Expand group by after stars

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Fix UDF kwarg parsing

- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_columns.sql
fixes https://github.com/tobymao/sqlglot/issues/1168
This adds `lateral_sources`. I'm not crazy about yet another concept in scope.
> UDTF scope refactor

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_sqlite.py
Attempt to clean up https://github.com/tobymao/sqlglot/pull/1154
> Add support for INSERT OR ... sqlite syntax

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
This pull request address issue https://github.com/tobymao/sqlglot/issues/1182, according to the approach described in https://github.com/tobymao/sqlglot/issues/1182#issuecomment-1431861858.
> account for differences in regexp_extract translation

- sqlglot/dialects/bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_spark.py
> Fix transpilation of TsOrDsAdd for Bigquery

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #1237
Reference: https://docs.snowflake.com/en/sql-reference/sql/alter-table
> Refactor ALTER TABLE parser, add support for Snowflake SET/UNSET TAG

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Improve parsing of DIV0 and ZEROIFNULL for snowflake

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/test_build.py
Added a qualify builder.
Note -- `make check` made a bunch of unrelated formatting changes.
> Implement qualify builder.

- sqlglot/dialects/redshift.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_redshift.py
https://docs.aws.amazon.com/redshift/latest/dg/r_CAST_function.html
> Fix parsing for Redshift's CONVERT function

- sqlglot/dialects/mysql.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_sqlite.py
can you check this out and take this to the finish line?
> sqlite datediff

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Reopened this because for some reason the commit history got messed up in the other PR.
> Fix parsing/generation of DATEADD for redshift

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix parsing of pivot clauses after aliased subqueries

- sqlglot/dialects/hive.py
- tests/dialects/test_presto.py
> Drop ORDER BY clause when transpiling ARRAY_AGG to hive

- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/pushdown_projections.sql
This is a WIP, I'm trying to fix the optimizer so that it doesn't break when we have structs.
EDIT: I'm going to try and move this change to `qualify_columns` instead of `pushdown_projections`.
> Handle structs gracefully in qualify columns

- sqlglot/optimizer/canonicalize.py
- tests/fixtures/optimizer/canonicalize.sql
query:
```sql
SELECT
a
FROM (
SELECT 1 AS a
) AS x
WHERE a
```
Postgres:
```
error: argument of WHERE must be type boolean, not type integer
```
MySQL:
```
a
1
```
> canonicalize.ensure_bool_predicates

- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
> Fix parsing of clickhouse quantiles

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Add support for Bigquery SELECT AS [STRUCT|VALUE] expression

- sqlglot/dialects/hive.py
- tests/dialects/test_hive.py
> Improve transpilation of DATE_DIFF (sec, min etc) to Hive

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/fixtures/identity.sql
SQLITE: https://www.sqlite.org/pragma.html
DuckDB: https://duckdb.org/docs/sql/pragmas.html
PL/SQL: https://juliandontcheff.wordpress.com/2023/01/03/the-106-oracle-pl-sql-pragmas/
> added PRAGMA statement

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_presto.py
- tests/fixtures/identity.sql
Fixes #1337 
- https://trino.io/docs/current/functions/json.html#json-object
- https://learn.microsoft.com/en-us/sql/t-sql/functions/json-object-transact-sql?view=sql-server-ver16
> Add support for JSON_OBJECT (presto, tsql)

- sqlglot/tokens.py
- tests/test_tokens.py
> Fix comment tokenization for an edge case

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
> Add support for MATCH .. AGAINST .. (MySQL)

- sqlglot/parser.py
- tests/dialects/test_duckdb.py
> Fix: allow '[]' when parsing a nested type

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
> Fix parsing and generation for match(..) (Clickhouse)

- sqlglot/lineage.py
- tests/test_lineage.py
Track the source of a node in an alias attribute.
> Add alias to column lineage nodes

- sqlglot/dialects/starrocks.py
- tests/dialects/test_starrocks.py
https://docs.starrocks.io/en-us/2.4/sql-reference/sql-functions/aggregate-functions/approx_count_distinct
> Starrocks APPROX_COUNT_DISTINCT

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
References:
- https://docs.aws.amazon.com/redshift/latest/dg/r_DATE_PART_function.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_EXTRACT_function.html
- https://www.postgresql.org/docs/8.1/functions-datetime.html
> Feat(postgres, redshift): improve parsing of DATE_PART

- sqlglot/dialects/oracle.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
- tests/dialects/test_snowflake.py
Fixes #1422
References:
- https://oracle-base.com/articles/12c/pattern-matching-in-oracle-database-12cr1
- https://docs.oracle.com/cd/E29542_01/apirefs.1111/e12048/pattern_recog.htm#CQLLR2208
- https://docs.snowflake.com/en/sql-reference/constructs/match_recognize
> Fix: improve parsing of MATCH_RECOGNIZE clause

- sqlglot/generator.py
- sqlglot/parser.py
- tests/fixtures/identity.sql
- tests/test_transpile.py
> Fix: preserve comments attached to the WITH clause (CTEs)

- sqlglot/dialects/mysql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
Convert TIME_STR_TO_UNIX to UNIX_TIMESTAMP for MySQL dialects
> Feat(mysql) Convert TIME_STR_TO_UNIX to UNIX_TIMESTAMP

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
Similar to https://github.com/tobymao/sqlglot/pull/1454, and encouraged by #1455.
> Add Spark's date function to Parser.FUNCTIONS

- sqlglot/dialects/databricks.py
- tests/dialects/test_databricks.py
Reference: https://docs.databricks.com/sql/language-manual/functions/colonsign.html
> Feat(databricks): add support for the : (colon sign) operator

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
I meant to add this to #1485 yesterday, but ran into some noob git issue where I didn't manage to push to the remote before it was merged https://github.com/tobymao/sqlglot/pull/1485#issuecomment-1523444653
> Add Spark's int cast function

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
Added parsing support for `INSERT ON CONFLICT` statement. 
As this is my first contribution appreaciate any feedback on improvement needed
> Added _parse_on_conflict 

- .github/workflows/python-publish.yml
Based on: https://github.com/marketplace/actions/changelog-from-conventional-commits
> Chore: set action for automatic conventional changelog generation

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Reference: https://duckdb.org/docs/sql/functions/date.html
> Fix(duckdb): parse DATEDIFF correctly

- sqlglot/expressions.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/test_expressions.py
- tests/test_optimizer.py
We weren't propagating `selects` from subqueries
> fix: subquery selects

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): improve DDL statement parsing

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Reference: https://learn.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver16
> Feat(tsql): add support for the OPENJSON function

- sqlglot/dataframe/sql/dataframe.py
- sqlglot/expressions.py
- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/isolate_table_selects.py
- sqlglot/optimizer/merge_subqueries.py
- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- sqlglot/transforms.py
is this what you meant? can you go through the different usages and see what makes the most sense to do here? copy false or true as default?
> Fix: remove unconditional expression copy

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Feat(snowflake): translate [CHAR|NCHAR] VARYING into VARCHAR

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/redshift.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): add support for GEOGRAPHY, GEOMETRY types

- sqlglot/executor/__init__.py
- sqlglot/schema.py
- tests/test_executor.py
> Feat(executor): add support for qualified table references

- sqlglot/generator.py
- tests/dialects/test_spark.py
> Fix: add exp.Neg to UNWRAPPED_INTERVAL_VALUES

- sqlglot/lineage.py
- tests/test_lineage.py
> Fix(lineage): remove unnecessary optimization

- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): allow 2nd argument in initcap

- sqlglot/dataframe/sql/dataframe.py
- sqlglot/dataframe/sql/operations.py
- sqlglot/helper.py
- tests/dataframe/integration/test_dataframe.py
- tests/dataframe/unit/test_session.py
Just some cleanup after reviewing some code. Most notable is that CTE names prior to optimization are now deterministic which will make it easier to debug issues.
> Fix: Minor Dataframe cleanup

- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix: parse query modifiers for ddl selects

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_spark.py
xref: https://github.com/duneanalytics/harmonizer/pull/70
cc: @vegarsti
> Fix!(spark): cast to string instead of (var)char in non DDL expressions

- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- tests/dialects/test_redshift.py
Fixes #1742
References:
- https://docs.aws.amazon.com/redshift/latest/dg/r_STRTOL.html
- https://prestodb.io/docs/current/functions/math.html
> Feat(redshift,presto): transpile FROM_BASE to STRTOL and vice versa

- sqlglot/dialects/redshift.py
- tests/dialects/test_presto.py
- tests/dialects/test_redshift.py
Fixes #1745
Tested all added cases in the corresponding engines, the results indeed match for them.
> Feat(redshift,presto): transpile DATEADD, DATEDIFF to presto

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tsql.py
- sqlglot/executor/env.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/annotate_types.py
- sqlglot/optimizer/canonicalize.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dataframe/unit/test_functions.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
- tests/test_executor.py
> Fix!(presto): ensure ||, CONCAT args are strings

- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/optimizer/optimizer.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/fixtures/identity.sql
> Fix: map "RETURNING" to its token in the base Tokenizer

- sqlglot/dialects/teradata.py
- tests/dialects/test_dialect.py
> Fix(teradata): add support for the SELECT TOP N syntax

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Ref: https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#generate_array
> feat: support BigQuery GENERATE_ARRAY

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Reference: https://dev.mysql.com/doc/refman/8.0/en/delete.html
> Feat: add support for LIMIT clause in DELETE statement

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Reference: https://dev.mysql.com/doc/refman/8.0/en/update.html
> Feat: add support for LIMIT clause in UPDATE statement

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
- tests/fixtures/pretty.sql
Reference: https://docs.databricks.com/sql/language-manual/sql-ref-syntax-dml-insert-into.html
> Feat(databricks): add support for REPLACE WHERE in INSERT statement

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #1824
Reference: https://docs.snowflake.com/en/sql-reference/sql/alter-table
> Refactor!(snowflake): improve handling of ALTER TABLE .. (UN)SET syntax

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions#cast_as_string
> Feat(bigquery): add support for casting to string w/ format

- sqlglot/executor/context.py
- sqlglot/planner.py
- tests/test_executor.py
> Fix(executor): allow non-projected aggregates in ORDER BY

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Reference: https://docs.snowflake.com/en/sql-reference/constructs/group-by
> Feat(snowflake): add support for GROUP BY ALL

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
Fixes #1866
Reference: https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of
> Feat(mysql): add support for the MEMBER OF operator

- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_dialect.py
> Fix!(tsql): convert LIMIT to TOP clause

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
The content type of 'Member of' is not just a string
> Fix(mysql): add support more kind for MEMBER OF content

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
- tests/fixtures/identity.sql
Fixes #1877
Reference: https://dev.mysql.com/doc/refman/8.0/en/delete.html
> Feat!(mysql): add support for multi-table DELETE syntax

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tableau.py
- sqlglot/dialects/teradata.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_mysql.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
- tests/fixtures/identity.sql
- tests/test_optimizer.py
- tests/test_transpile.py
Reference: https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html
> Fix!(mysql): activate hint generation

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- sqlglot/optimizer/annotate_types.py
- tests/dialects/test_duckdb.py
- tests/test_optimizer.py
References:
- https://duckdb.org/docs/sql/functions/date.html
- https://duckdb.org/docs/sql/functions/dateformat.html
- https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date
> Fix(duckdb): improve transpilation of BigQuery DATE function

- sqlglot/dialects/oracle.py
- tests/dialects/test_dialect.py
do not convert NCHAR to CHAR for Oracle
> Oracle - keep NCHAR as-is

- sqlglot/optimizer/scope.py
We already have the concept of a "subquery" scope, so the name of this helper function was a bit confusing, e.g. in the context of the `_collect` method.
> Refactor(scope): rename _is_subquery_scope to _is_derived_table for clarity

- sqlglot/parser.py
- tests/dialects/test_teradata.py
> Fix(teradata): separate POST_EXPRESSION props from POST_INDEX

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
> Fix(duckdb): ensure 'day' will be generated for exp.DateDiff by default

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
References:
- https://docs.aws.amazon.com/redshift/latest/dg/r_ADD_MONTHS.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_DATEADD_function.html
> Feat(redshift): improve transpilation of ADD_MONTHS function

- sqlglot/dialects/postgres.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/dialects/test_redshift.py
- tests/dialects/test_tsql.py
References:
- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cast/
- https://docs.aws.amazon.com/redshift/latest/dg/r_CAST_function.html
> Fix!(postgres): ensure casts are strict

- sqlglot/dialects/oracle.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/test_optimizer.py
> Fix!(oracle): resolve identifiers just like in snowflake

- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Fix(oracle): improve handling of KEEP (...) OVER (...) window syntax

- sqlglot/schema.py
- tests/test_schema.py
These changes were motivated by https://github.com/TobikoData/sqlmesh/issues/1205 -- the goal is to make the schema module a bit more flexible.
> Feat(schema): improve overridability of normalization setting

- sqlglot/optimizer/qualify_tables.py
- sqlglot/schema.py
- tests/test_schema.py
Plan to add another test to ensure the constructor enforces this logic too.
> Feat!(schema): prohibit registering tables of different nesting

- sqlglot/optimizer/unnest_subqueries.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
Fixes #1987
Tested this in SQL fiddle, seems to be good.
> Fix(optimizer): wrap scalar subquery replacement in a MAX call

- sqlglot/optimizer/normalize_identifiers.py
- tests/fixtures/optimizer/normalize_identifiers.sql
xref: https://github.com/TobikoData/sqlmesh/pull/1206#discussion_r1282546326
> Feat(optimizer): allow normalize_identifiers to accept strings

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Fixes a bug I introduced in https://github.com/tobymao/sqlglot/commit/bb1f1a035c8701c881f61c65742331cf7e667260.
> Fix!(redshift): ensure TsOrDsToDate produces a cast to DATE

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/test_optimizer.py
> Fix(optimizer): wrap expanded alias expressions

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): tokenize $$ as raw string delimiters

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/hive.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_hive.py
- tests/fixtures/identity.sql
- tests/test_parser.py
> Fix!(parser): ensure _parse_function consumes an R_PAREN before returning

- README.md
- sqlglot/dialects/dialect.py
- sqlglot/dialects/doris.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/starrocks.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
cc: @liujiwen-up
References:
- https://doris.apache.org/docs/dev/sql-manual/sql-functions/date-time-functions/date-format?_highlight=format
- https://www.programiz.com/python-programming/datetime/strftime
- https://www.w3schools.com/sql/func_mysql_date_format.asp
> Refactor(doris): cleanup implementation of Doris dialect

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- tests/dialects/test_tsql.py
> Fix(tsql): add support for 'culture' argument in FORMAT

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Fixes #2048
Reference: https://learn.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver16
> Fix(tsql): improve handling of table hints in MERGE statement

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
> fix: parenthesize coalesce simplification

- sqlglot/dialects/spark2.py
- tests/dialects/test_spark.py
> Fix(spark): handle MAP(..) without arguments correctly

- sqlglot/optimizer/pushdown_predicates.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/pushdown_predicates.sql
> fix: pushdown predicate to HAVING

- sqlglot/dialects/oracle.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Feat(oracle): add support for old-style SELECT UNIQUE .. syntax

- sqlglot/expressions.py
- sqlglot/optimizer/eliminate_subqueries.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/test_expressions.py
> Fix!(optimizer): remove redundant parens during subquery elimination

- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Fix: allow placeholders to be any ID_VAR token

- sqlglot/dialects/hive.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/transforms.py
- tests/test_parser.py
> Refactor!: rename DataTypeSize -> DataTypeParam

- sqlglot/dialects/presto.py
- tests/dialects/test_dialect.py
- tests/dialects/test_presto.py
https://prestodb.io/docs/current/language/types.html#date-and-time
> fix(presto): datetime -> timestamp

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
https://prestodb.io/docs/current/functions/datetime.html#interval-functions
> fix(presto): transpile DATE_SUB

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
support order in UPDATE statement
refs: https://dev.mysql.com/doc/refman/8.0/en/update.html
> Fix(parser): support order in update statement

- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_tsql.py
> Fix(tsql): remove COLUMN keyword from ALTER TABLE

- sqlglot/dialects/teradata.py
- tests/dialects/test_teradata.py
> Feat(teradata): improve support for DATABASE statement

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
Fixes #2166
Reference: https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
cc: @Nitrino
> Feat(mysql): improve support for unsigned int types

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Feat(oracle): add support for JSON_ARRAYAGG

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Fixes #2195
Reference: https://dev.mysql.com/doc/refman/8.0/en/create-index.html
> Fix(mysql): parse column prefix in index / pk defn. correctly

- sqlglot/dialects/mysql.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
> Fix(tokenizer): treat quote as escape only if its followed by itself

- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Fix(oracle): allow CONNECT BY / START WITH to be interchanged

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/transforms.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_postgres.py
cc: @longxiaofei
References:
- https://duckdb.org/docs/sql/aggregates.html
- https://www.postgresql.org/docs/9.4/functions-aggregate.html
> Feat: improve support for percentiles in duckdb, postgres

- sqlglot/parser.py
- tests/dialects/test_oracle.py
- tests/test_expressions.py
> Feat: add support for scoped user-defined types

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
> Fix: unescape escape sequences

- sqlglot/dialects/snowflake.py
- tests/dialects/test_duckdb.py
Fixes #2228
This doesn't fully solve the issue; it's a temporary workaround that aims to fix the simple use cases.
> Fix(snowflake): transpile SELECT UNNEST(x) to TABLE(FLATTEN(..))

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/transforms.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/dialects/test_spark.py
- tests/fixtures/pretty.sql
also remove with ordinality with just offset for consistency closes #2227
> Fix!: explode to unnest with multiple explosions

- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
> Fix!: store expressions in Limit.expression when using builder

- sqlglot/dialects/presto.py
- tests/dialects/test_duckdb.py
> Fix(presto): treat struct with key-value definition as unsupported

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
> Fix(parser): check for column operators after having parsed brackets

- sqlglot/expressions.py
- tests/dialects/test_sqlite.py
Closes #2252
Reference: https://www.sqlite.org/lang_datefunc.html
> Fix!(sqlite): allow exp.Date to function as a 'var_len_arg'

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/canonicalize.py
- sqlglot/parser.py
- tests/dataframe/unit/test_column.py
- tests/dataframe/unit/test_functions.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_hive.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_spark.py
- tests/dialects/test_sqlite.py
- tests/dialects/test_tsql.py
- tests/fixtures/identity.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/test_transpile.py
> Fix!: preserve ascending order of sorting when present

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix(bigquery): reduce the scope where UNKNOWN is treated as NULL

- sqlglot/dialects/hive.py
- tests/dialects/test_tsql.py
> Fix(hive): get rid of any ASC in a ClusteredColumnConstraint

- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Fix!(postgres): parse create index method (e.g. btree) correctly

- sqlglot/dialects/databricks.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_tsql.py
Completes https://github.com/tobymao/sqlglot/pull/2116.
cc: @dmoore247
> Feat!: improve transpilation of T-SQL's SET assignment command

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
Fixes https://github.com/TobikoData/sqlmesh/issues/1457
> Fix(postgres): generate ARRAY[] correctly

- sqlglot/dialects/mysql.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
> Fix(parser): make kwarg parsing more robust

- sqlglot/dialects/snowflake.py
- tests/dialects/test_duckdb.py
References:
* https://duckdb.org/docs/sql/aggregates.html
* https://docs.snowflake.com/en/sql-reference/functions/percentile_cont
* https://docs.snowflake.com/en/sql-reference/functions/percentile_disc
> Feat: support for percentiles in duckdb, snowflake

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Fixes #2304
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_copy
> Feat(bigquery): add support for CREATE TABLE .. COPY DDL syntax

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
Fixes a little bug when casting a non-literal to a date.
Also handles nested casts.
> fix(optimizer): a couple simplify_date_trunc enhancements

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #2330
Reference: https://docs.snowflake.com/en/user-guide/querying-stage
> Feat(snowflake): add support for staged file table syntax

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
References:
- https://docs.snowflake.com/en/sql-reference/functions/collate
- https://cloud.google.com/bigquery/docs/reference/standard-sql/collation-concepts#collate_propagate
> Fix(snowflake, bigquery): parse COLLATE as a func instead of a binary operator

- sqlglot/dialects/hive.py
- tests/dialects/test_databricks.py
Fixes https://github.com/tobymao/sqlglot/discussions/2344
> Fix(databricks): don't generate WithDataProperty

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
References:
- https://docs.snowflake.com/en/user-guide/querying-stage
- https://docs.snowflake.com/en/sql-reference/constructs/from#syntax
> Feat(snowflake): add support for staged file file_format clause

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-predict#mlpredict_function
> Feat(bigquery): add support for ML.PREDICT function

- sqlglot/dialects/oracle.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
Reference: https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html
> Fix(mysql): move parsing logic for JSON_TABLE to base parser

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
- tests/dialects/test_oracle.py
Fixes #2391
Reference: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/JSON_TABLE.html
> Fix!(oracle): add support for NESTED PATH in JSON schemas

- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_teradata.py
> Fix(teradata): FOR in LOCKING ROW FOR ACCESS is optional

- sqlglot/parser.py
- tests/dialects/test_redshift.py
> Fix(redshift): add a missing retreat in the group by parser

- sqlglot/dialects/bigquery.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Context: https://github.com/tobymao/sqlglot/pull/2403#issuecomment-1760681507
> Fix!(bigquery): reduce eq and neq to null if either operand is null

- sqlglot/generator.py
- sqlglot/parser.py
- tests/fixtures/optimizer/qualify_tables.sql
@edpaget this should solve the [issue](https://github.com/tobymao/sqlglot/pull/2424#issuecomment-1769107517) you were seeing with the alias.
> Fix!(parser): move alias from lateral's child to itself

- sqlglot/generator.py
- sqlglot/parser.py
- tests/test_transpile.py
> Fix: attach comments to Union expressions

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): treat CURRENT_DATE as a function

- sqlglot/optimizer/annotate_types.py
- sqlglot/parser.py
- tests/test_optimizer.py
- tests/test_parser.py
> Fix: improve bracket parsing error, set Slice type to Unknown

- sqlglot/dialects/hive.py
- tests/dialects/test_spark.py
- tests/dialects/test_tsql.py
Resolves https://github.com/tobymao/sqlglot/issues/2426#issuecomment-1774417332
> Fix!(hive): cast months_between to int when generated from datediff

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Related Slack thread: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1697922425207749
> Feat: add support for {fn ...} function syntax

- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
Fixes #2449
Reference: https://docs.snowflake.com/en/sql-reference/functions/approx_top_k
> Feat(snowflake): register APPROX_TOP_K as AggFunc

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
References:
- https://duckdb.org/docs/sql/aggregates.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_LISTAGG.html
> Fix: facilitate transpilation of Redshift's LISTAGG

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/transforms.py
- tests/dialects/test_mysql.py
Fixes #2458
This is an incomplete fix since the generic solution is more tricky.
> Feat(mysql): convert full outer join to union with left/right outer joins

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
- tests/fixtures/optimizer/qualify_tables.sql
Fixes https://github.com/TobikoData/sqlmesh/issues/1619
Reference: https://www.postgresql.org/docs/9.5/sql-select.html
>  Feat(postgres): support WITH ORDINALITY in table functions 

- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #2469
Reference: https://www.postgresql.org/docs/current/sql-createtable.html
> Feat(postgres): add support for the PARTITION OF property in CREATE

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql): add 'dddd' to '%A' time mapping

- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Fix(postgres): allow opclass types to be namespaced

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
> Fix(tsql): improve support for SYSTEM_VERSIONING

- sqlglot/planner.py
> Revert "fix(planner): missing step of subquery"

- sqlglot/dialects/bigquery.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
Fixes #2506
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#for-in
> Feat(bigquery): add support for FOR .. IN statement

- sqlglot/parser.py
- tests/dialects/test_tsql.py
> Fix(tsql): parse DROP CONSTRAINT into Drop instead of Command

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): avoid advancing beyond array limit when parsing staged files

- sqlglot/dialects/hive.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_spark.py
> Feat(hive): add fine-grained parsing for REFRESH

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/spark2.py
- sqlglot/generator.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
> Fix: transpile Snowflake structs correctly

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
> Feat(postgres): parse CREATE CONSTRAINT TRIGGER as Command

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
> Fix(parser): take TokenType.RAW_STRING into account in _parse_string

- sqlglot/parser.py
- tests/dialects/test_oracle.py
fix https://github.com/tobymao/sqlglot/issues/2572
> fix(oracle): parse DROP CONSTRAINT into DROP instead of Command

- sqlglot/dialects/duckdb.py
- sqlglot/generator.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
> Fix: treat := as PropertyEQ in base sqlglot classes

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql): generate DATEPART when the format is quarter

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql): add dw, hour to the DATEPART-only formats

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/simplify.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_postgres.py
- tests/dialects/test_redshift.py
- tests/dialects/test_tsql.py
- tests/fixtures/optimizer/simplify.sql
- tests/test_expressions.py
Fixes https://github.com/TobikoData/sqlmesh/issues/1815
Fixes https://github.com/duneanalytics/harmonizer/issues/91
> Fix!: make generation of CONCAT less verbose

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse): add support for arrayJoin

- sqlglotrs/src/tokenizer.rs
In my initial implementation I relied on the `panic!` macro to raise errors to the Python layer. 
However, in Rust `panic!` is reserved for unrecoverable errors and results in `PanicException` on the Python side. This exception class doesn't inherit from `Exception` but from `BaseException` instead.
Because of this I had to resort to a hack which involved usage of the `catch_unwind` function to intercept all panics and transform them into Python exceptions. This isn't the cleanest approach, as explicitly stated in the [documentation](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html):
> It is not recommended to use this function for a general try/catch mechanism. The [Result](https://doc.rust-lang.org/std/thread/type.Result.html) type is more appropriate to use for functions that …
> Refactor error handling in Rust implementation using the idiomatic approach

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
> Fix(duckdb): transpile bigquery structs w/ aliases correctly

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/optimizer.sql
> Fix(optimizer): handle case where top-level query is a Subquery in scope

- sqlglot/optimizer/eliminate_subqueries.py
- sqlglot/optimizer/merge_subqueries.py
- sqlglot/planner.py
- tests/fixtures/optimizer/eliminate_subqueries.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/test_executor.py
- tests/test_optimizer.py
whew. This surfaced a few nasty bugs.
> fix(optimizer): eliminate eliminate_unions

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): time travel syntax can be used in queries as well

- sqlglot/dialects/dialect.py
- sqlglot/dialects/presto.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_presto.py
Related issue: #2702 
Reference: https://trino.io/docs/current/language/types.html#varchar
> Feat: add support for unicode strings

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): implement correct parsing semantics for TO_ARRAY

- README.md
- posts/ast_primer.md
Thought this might be helpful for a lot of folks.
Happy to move this somewhere else, too (I'm not really sure how to add arbitrary markdown to pdocs). Also happy to keep this out of this repo, if you don't think this belongs here.
> chore: new docs - AST primer

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/sqlite.py
- sqlglot/expressions.py
- sqlglot/optimizer/simplify.py
- tests/dialects/test_dialect.py
- tests/fixtures/optimizer/simplify.sql
> feat(optimizer): simplify date comparisons

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#format_date
> Fix(bigquery): add FUNCTIONS entry for FORMAT_DATE to facilitate transpilation

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_dialect.py
- tests/dialects/test_hive.py
- tests/dialects/test_mysql.py
- tests/fixtures/optimizer/simplify.sql
Fixes #2749
Reference: https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time
> Fix(bigquery): enable transpilation of single-argument TIME func

- sqlglot/expressions.py
Small helper to improve debuggability of parsed ASTs. Relevant Slack discussion [here](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1704217854505609?thread_ts=1703632977.455049&cid=C0448SFS3PF).
Demo:
```python
>>> print(sqlglot.parse_one("select x from t").to_s())
Select(
kind=None,
hint=None,
distinct=None,
expressions=[
Column(
this=Identifier(this=x, quoted=False, _type=None, _comments=None, _id=4317543360),
_type=None,
_comments=None,
_id=4317543472)],
limit=None,
from=From(
this=Table(
this=Identifier(this=t, quoted=False, _type=None, _comments=None, _id=4317543696),
db=None,
catalog=None,
_type=None,
_comments=None,
_id=4317543808),
_type=None,
_comments=None,
_id=4317543920),
_type=None,
_comments=[],
_id=4317543584)
```
> Feat: implement to_s method in Expression for verbose repr mode

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
> Fix!(tsql): ensure CROSS/OUTER APPLY can be round-tripped

- sqlglot/dialects/doris.py
- sqlglot/dialects/oracle.py
- tests/dialects/test_doris.py
- tests/dialects/test_oracle.py
Cherry-picked from https://github.com/tobymao/sqlglot/pull/2773
References:
- https://doris.apache.org/docs/sql-manual/sql-functions/date-time-functions/to-date/?_highlight=to_date
- https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions033.htm
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/SYSDATE.html#GUID-807F8FC5-D72D-4F4D-B66D-B0FE1A8FA7D2
> Feat: improve support for Doris' TO_DATE, Oracle's SYSDATE

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Reference: https://docs.snowflake.com/en/sql-reference/sql/show-columns
> Feat(snowflake): add support for SHOW COLUMNS 

- sqlglot/dialects/tsql.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_tsql.py
> Fix(tsql): gracefully handle complex formats in FORMAT

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): allow transpilation of countIf, fix 2 arg variant parsing

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): apply range parser after colon, if any

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Fix(oracle): improve parsing of JSON_OBJECT[AGG] functions

- sqlglot/optimizer/pushdown_predicates.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/fixtures/optimizer/tpc-h/tpc-h.sql
> Fix(optimizer): pushdown predicates more conservatively to avoid DAG cycles

- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/qualify_tables.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_tables.sql
> Fix(optimizer): handle table alias columns for (UN)PIVOTs

- sqlglot/dialects/oracle.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_oracle.py
> Feat(oracle): add support for ORDER SIBLINGS BY clause

- sqlglot/dialects/doris.py
- tests/dialects/test_doris.py
https://doris.apache.org/docs/dev/sql-manual/sql-functions/date-time-functions/last-day/
https://doris.apache.org/docs/dev/sql-manual/sql-functions/aggregate-functions/max-by
https://doris.apache.org/docs/dev/sql-manual/sql-functions/aggregate-functions/min-by
> Fix(doris): add transformation of aggregation function and last_day function 

- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- tests/dialects/test_postgres.py
- tests/dialects/test_tsql.py
- tests/fixtures/identity.sql
TODO: Integrate test cases to the existing framework
> Feat: transpile SELECT .. INTO to dialects that do not support it

- sqlglot/dialects/dialect.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/trino.py
See https://github.com/tobymao/sqlglot/pull/2852#discussion_r1457936060
> Refactor: simplify merge without target transformation

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #2855
Reference: https://www.postgresql.org/docs/current/sql-createindex.html
> Feat(postgres): support the INCLUDE clause in INDEX creation

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
> feat(snowflake): SHOW SCHEMAS/OBJECTS

- sqlglot/optimizer/annotate_types.py
- tests/test_optimizer.py
Handle `SELECT STRUCT_PACK(a := 1, b := 2.5)`
> Feat(optimizer): improve struct type annotation support for EQ-delimited kv pairs

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
> Fix(optimizer): compute external columns for union sopes correctly

- sqlglot/optimizer/qualify_tables.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_tables.sql
> Fix(optimizer): don't qualify CTEs for DDL/DML statements

- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/simplify.sql
Removing the parenthesis was causing subtle bugs.
> fix(optimizer): don't remove NOT parenthesis

- sqlglot/dialects/hive.py
- sqlglot/dialects/postgres.py
- sqlglot/generator.py
- sqlglot/jsonpath.py
- tests/dialects/test_dialect.py
- tests/test_jsonpath.py
I think this is the final item
> Feat: improve transpilation of JSON path wildcards

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/generator.py
- tests/dialects/test_spark.py
> Feat: transpile multi-arg DISTINCT expression

- sqlglot/expressions.py
- tests/dialects/test_bigquery.py
> fix: posexplode_outer to unnest

- sqlglot/optimizer/qualify_columns.py
Small optimization for tables with lots of columns.
> fix(optimizer): qualify_columns optimizations for wide tables

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
> Fix(redshift): don't assume Table is an unnested Column if Join has a predicate

- sqlglot/expressions.py
- tests/test_expressions.py
Related Slack thread: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1707882805970539
> Fix: pass dialect in to_table call inside replace_tables

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/duckdb.py
- sqlglot/generator.py
Cleans up https://github.com/tobymao/sqlglot/commit/7c4807918de53d18fbfe0295b2644f0ad46003a8 a bit.
cc @r1b
> Refactor: clean up duplicative placeholder_sql implementations

- sqlglot/optimizer/annotate_types.py
- tests/test_optimizer.py
Fixes https://github.com/TobikoData/sqlmesh/issues/2152
> Fix(optimizer): don't coerce nested arg types in annotate_by_args

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
https://cloud.google.com/bigquery/docs/querying-wildcard-tables
> feat: allow more leniant bigquery wildcard parsing

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
> Feat(bigquery): support ELSE and ELSEIF procedural statements

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/doris.py
- sqlglot/expressions.py
- tests/dialects/test_doris.py
- tests/test_expressions.py
> Feat: improve transpilation of Doris' MONTHS_ADD

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/qualify_tables.sql
- tests/test_expressions.py
> Fix!(bigquery): preserve quoted table paths

- sqlglot/optimizer/qualify_columns.py
- tests/test_optimizer.py
> Fix(optimizer): fix parent mutation of new_projections in column qualifier

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
> Feat(mysql): add LOCK property, allow properties after ALTER TABLE

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
- tests/fixtures/identity.sql
> Fix(duckdb): recognize ENUM as a type

- sqlglot/lineage.py
See https://github.com/tobymao/sqlglot/issues/3047#issuecomment-1969175353
> Fix: avoid raising a KeyError in the lineage module, log a warning

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/tokens.py
- sqlglotrs/Cargo.lock
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_dialect.py
- tests/dialects/test_tsql.py
Fixes #3023
Reference: https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
> Fix!(tsql): preserve CONVERT function

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
@tobymao it seems like the fix was pushed to your branch. Opening this to merge it in main as well.
> fix(snowflake): allow any identifier after :

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
- tests/dialects/test_presto.py
See https://github.com/tobymao/sqlglot/issues/3060
> Feat(postgres): improve transpilation of JSON array unnesting

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
- tests/dialects/test_sqlite.py
Fixes #3070
Reference: https://www.sqlite.org/lang_createtable.html
> Fix!(sqlite): allow ON CONFLICT constraint after UNIQUE

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
see https://docs.snowflake.com/en/sql-reference/sql/create-sequence
partially resolves #2954
> feat(snowflake): parse CREATE SEQUENCE

- sqlglot/dialects/__init__.py
- sqlglot/dialects/athena.py
- sqlglot/dialects/dialect.py
- tests/dialects/test_athena.py
> Feat: add Athena dialect

- sqlglot/lineage.py
> refactor(lineage): simplify `Node.walk()`

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/databricks.py
- sqlglot/dialects/doris.py
- sqlglot/dialects/drill.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/prql.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/dialects/sqlite.py
- sqlglot/dialects/tableau.py
- sqlglot/dialects/teradata.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_oracle.py
- tests/dialects/test_sqlite.py
- tests/dialects/test_tsql.py
fix [#3093](https://github.com/tobymao/sqlglot/issues/3093)
> Feat(doris):add support for to_number(x)

- sqlglot/lineage.py
> Fix: make the lineage sources dict type covariant

- sqlglot/dialects/postgres.py
- tests/dialects/test_oracle.py
Addresses first issue in https://github.com/tobymao/sqlglot/discussions/3117
> Feat(postgres): generate StrToDate

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_redshift.py
> feat: Adding BACKUP property

- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_postgres.py
- tests/fixtures/identity.sql
Fixes #3123 
Docs
--------
- https://www.postgresql.org/docs/current/datatype-character.html
- https://dba.stackexchange.com/questions/217533/what-is-the-data-type-name-in-postgresql
> feat: Adding NAME data type in Postgres/Redshift

- sqlglot/dialects/athena.py
- tests/dialects/test_athena.py
> fix(athena): Fix CREATE TABLE properties, STRING data type

- sqlglot/dialects/snowflake.py
- sqlglot/executor/env.py
- sqlglot/helper.py
- tests/dialects/test_snowflake.py
- tests/test_executor.py
> Fix!(snowflake): clean up TO_TIME, TO_TIMESTAMP* builder

- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/test_executor.py
Number of TPC-DS query that passed: 62/99
> Feat(test): Add standard alias to some TPC-DS query

- sqlglot/expressions.py
- tests/test_optimizer.py
> Fix: fill in missing implementation details for replace(None)

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/snowflake.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
References:
- https://duckdb.org/docs/sql/functions/time
- https://docs.snowflake.com/en/sql-reference/functions/timeadd
- https://cloud.google.com/bigquery/docs/reference/standard-sql/time_functions#time_add
- https://docs.snowflake.com/en/sql-reference/functions/timestampadd
> Feat: transpile Snowflake's ADDTIME

- sqlglot/dataframe/sql/functions.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
[Slack message genesis, while it lasts](https://tobiko-data.slack.com/archives/C0448SFS3PF/p1710794131224809)
[Snowflake Aggregate Functions](https://docs.snowflake.com/en/sql-reference/functions-aggregation)
For Snowflake dialect:
* Change MEDIAN -> PERCENTILE_CONT
* Add CORR
* Add COVAR_POP
* Add COVAR_SAMP
Not sure if I am attempting too little or too much for the transpilation.
> Add more Snowflake aggregate functions

- sqlglot/expressions.py
- tests/test_expressions.py
> Feat: add support for converting `bytes` to sqlglot AST

- sqlglot/generator.py
- tests/test_transpile.py
> Fix(generator): compute csv leading comma pad length correctly

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Fixes #3202
This is breaking because I also refactored the IsolatedLoading property to get rid of some redundant args.
> Feat!(tsql): add support for WITH <view_attribute> in view DDL

- sqlglot/optimizer/merge_subqueries.py
- tests/fixtures/optimizer/merge_subqueries.sql
- tests/test_optimizer.py
fixes https://github.com/tobymao/sqlglot/issues/3211
> fix(optimizer): don't merge ORDER BY into UNION

- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix: make property value parsing more lenient

- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Fix: amend interval unit parsing regression

- sqlglot/optimizer/canonicalize.py
- sqlglot/optimizer/simplify.py
- tests/fixtures/optimizer/canonicalize.sql
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/simplify.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
A couple tweaks to handling dates in the optimizer
> fix(optimizer): tweaks to date simplification

- sqlglot/dialects/prql.py
- sqlglot/tokens.py
- tests/dialects/test_prql.py
[PRQL take transform doc](https://prql-lang.org/book/reference/stdlib/transforms/take.html)
> Feat(prql): Add support for TAKE 

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_mysql.py
> Fix!(mysql): parse wrapped ordered for KEY/INDEX constraint

- sqlglot/optimizer/unnest_subqueries.py
- tests/fixtures/optimizer/optimizer.sql
> Fix(optimizer): unnest union subqueries

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_presto.py
Fixes #3286
Reference: https://prestodb.io/docs/current/sql/select.html
> Feat(presto): add support for DISTINCT / ALL after GROUP BY

- sqlglot/dialects/prql.py
- tests/dialects/test_prql.py
1. Add support for `FILTER`: https://prql-lang.org/book/reference/stdlib/transforms/filter.html
2. Add support for `APPEND`, `REMOVE`, `INTERSECT` (some are experimental in prql): https://prql-lang.org/book/reference/stdlib/transforms/append.html
> Feat(prql): Add FILTER 

- sqlglot/dialects/prql.py
- tests/dialects/test_prql.py
https://prql-lang.org/book/reference/stdlib/transforms/sort.html
> Feat(prql): Add support for SORT

- sqlglot/dialects/bigquery.py
- sqlglot/generator.py
- tests/dialects/test_bigquery.py
- tests/test_optimizer.py
> Fix!(bigquery): parse multiple quoted table parts in columns correctly

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #3338
For some context around this change, see https://github.com/tobymao/sqlglot/pull/3167#discussion_r1530889048 and the reply following it.
> Fix!(snowflake): improve transpilability of [TO_]DATE(x)

- sqlglot/optimizer/__init__.py
> Fix: export optimizer functions explicitly in init

- sqlglot/lineage.py
- tests/test_lineage.py
> Fix(lineage): use source names of derived table sources for laterals

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
Fixes https://github.com/tobymao/sqlglot/issues/3368#issuecomment-2082507427
> Fix(mysql): generate GROUP_CONCAT for ArrayAgg

- sqlglot/dialects/mysql.py
- tests/dialects/test_dialect.py
- tests/dialects/test_mysql.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1714405276460029?thread_ts=1714402133.524589&cid=C044BRE5W4S
> Fix(mysql): don't cast into invalid numeric/text types

- sqlglot/dialects/dialect.py
- sqlglot/dialects/spark2.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_presto.py
> Fix(spark): transpile presto TRY, fix JSON casting issue

- sqlglot/parser.py
- tests/test_build.py
> Fix: allow joins in FROM expression parser

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/test_parser.py
> Fix!: parse column instead of identifier for SET assignment LHS

- sqlglot/lineage.py
- tests/test_lineage.py
> Fix(lineage): get rid of comments in Node names

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Fixes https://github.com/tobymao/sqlglot/issues/3451
> fix(bigquery): fix SHA1 generator

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_clickhouse.py
Fixes https://github.com/tobymao/sqlglot/issues/3452
Affected hash functions: SHA, SHA2, MD5 and MD5_Digest
> fix(clickhouse): fix parsing and generating hash functions

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
Fixes #3456
References:
- https://duckdb.org/docs/sql/samples.html
- https://docs.snowflake.com/en/sql-reference/constructs/sample
- https://www.postgresql.org/docs/current/sql-select.html
> Feat!: improve transpilation of TABLESAMPLE clause

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
Fixes #3468
Reference: https://docs.snowflake.com/en/sql-reference/sql/create-tag
> Feat(snowflake): add support for CREATE TAG DDL statement

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #3475
References:
- https://docs.snowflake.com/en/sql-reference/sql/select
- https://duckdb.org/docs/sql/query_syntax/select.html
> Fix(snowflake)!: preserve star clauses (EXCLUDE, RENAME, REPLACE)

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
> Fix(mysql): generate CONCAT for DPipe

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- tests/dialects/test_duckdb.py
postgres document: https://www.postgresql.org/docs/current/functions-formatting.html
mysql docucment: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_from-unixtime
clickhouse document: https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#fromunixtimestamp
> feat: improve transpilation of UnixToTime (postgres, mysql, clickhouse)

- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql)!: parse TININT into UTINYINT to improve transpilation

- sqlglot/dialects/presto.py
- tests/dialects/test_bigquery.py
Refactors https://github.com/tobymao/sqlglot/pull/3466
cc @viplazylmht
> Refactor(presto): make DELETE transpilation more robust

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/databricks.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
References:
* https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#date_trunc
* https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/varsamp
* https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/stddevsamp
> feat(clickhouse): support generate TimestampTrunc, Variance, Stddev

- sqlglot/dialects/databricks.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark2.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
- tests/dialects/test_snowflake.py
This fixes the JSON extraction generator for Databricks. I noticed that various test cases were broken, so this must have not been tested properly.
> Fix(databricks)!: parse : operator as JSONExtract (similar to Snowflake)

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
> Fix(postgres): parse @> into ArrayContainsAll, improve transpilation

- sqlglot/dialects/hive.py
- tests/dialects/test_hive.py
fixes #3532
I expect there will be similar issues. I will submit separate PRs for each one as they are found.
> Fix(HIVE): Correcting invalid function names

- sqlglot/parser.py
- tests/dialects/test_databricks.py
> Fix(parser): make _parse_type less aggressive, only parse column as last resort

- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix(clickhouse): improve struct type parsing

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
> Feat(snowflake): add support for WITH-prefixed column constraints

- sqlglot/dialects/redshift.py
- tests/dialects/test_redshift.py
Added support for `MINUS` operator in Redshift.
> Fix(redshift): add support for MINUS operator #3553

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #3554
Reference: https://docs.snowflake.com/en/sql-reference/data-types-datetime
> Fix: use regex to split interval strings

- sqlglot/parser.py
- tests/fixtures/optimizer/qualify_columns.sql
Fixes #3570
Similar to https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L4455-L4456 and https://github.com/tobymao/sqlglot/blob/main/sqlglot/parser.py#L3265-L3266.
> Fix: bubble up Identifier comments to TableAliases

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Reference: https://duckdb.org/docs/sql/data_types/timestamp
> Feat(duckdb): transpile TIMESTAMPNTZ into TIMESTAMP

- sqlglot/dialects/materialize.py
- sqlglot/dialects/postgres.py
- sqlglot/parser.py
- tests/dialects/test_materialize.py
> Refactor(materialize): clean up initial implementation of Materialize

- sqlglot/dialects/dialect.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/redshift.py
- sqlglot/generator.py
- sqlglot/parser.py
> Refactor: clean up logic related to join marker parsing/generation

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): support fqns in masking/projection policy constraint

- sqlglot/dialects/mysql.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_mysql.py
> Feat(mysql): support ADD INDEX/KEY/UNIQUE in ALTER TABLE

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_mysql.py
- tests/fixtures/identity.sql
> Feat(mysql): support STRAIGHT_JOIN

- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_duckdb.py
> Fix(tokenizer): properly handle tags that need to be identifiers in heredocs

- sqlglot/dialects/dialect.py
- sqlglot/dialects/oracle.py
- sqlglot/generator.py
- tests/dialects/test_presto.py
> Feat(oracle): support unicode strings u'...'

- sqlglot/schema.py
> Fix: improve schema error handling

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/hive.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/lineage.py
- sqlglot/optimizer/pushdown_projections.py
- sqlglot/optimizer/scope.py
- sqlglot/optimizer/unnest_subqueries.py
- sqlglot/parser.py
- sqlglot/planner.py
- sqlglot/transforms.py
> Refactor!: create SetOperation class

- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/fixtures/identity.sql
- tests/test_transpile.py
Fixes #3668
Will add a few more tests later
> Feat(tokenizer): add support for nested comments

- sqlglot/parser.py
- tests/dialects/test_bigquery.py
> Fix(parser): handle another edge case in struct field type parser

- sqlglot/parser.py
- tests/dialects/test_mysql.py
> Fix(parser): make parse_var_or_string more lenient

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
Fixes #3690
References:
- https://docs.snowflake.com/en/sql-reference/functions/try_parse_json
- https://duckdb.org/docs/extensions/json.html
> Feat: transpile TRY_PARSE_JSON Snowflake -> DuckDB

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/optimizer/qualify_columns.py
Context: https://github.com/tobymao/sqlglot/pull/3699#discussion_r1653168484
> Refactor: add EXPAND_ALIAS_REFS_ONLY_IN_GROUP_BY dialect constant

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_tsql.py
Fixes [#SQLMesh/2817](https://github.com/TobikoData/sqlmesh/issues/2817)
Introduce support for `<data type>::<static_func>` in T-SQL.
> feat(tsql): Add support for scope qualifier operator

- sqlglot/dialects/tsql.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
Bit of a low lift to make this roundtrippable so here it is
> Refactor(tsql): make ScopeResolution round-trippable

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_bigquery.py
Fixes https://github.com/TobikoData/sqlmesh/issues/2837
> Feat: transpile BigQuery's SAFE_CAST with FORMAT to DuckDB

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql): parse rhs of x::varchar(max) into a type

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/duckdb.py
- sqlglot/generator.py
- tests/dialects/test_clickhouse.py
- tests/dialects/test_dialect.py
- tests/dialects/test_duckdb.py
> Fix(duckdb, clickhouse)!: QUALIFY comes after WINDOW clause in queries

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #3783
Docs
-------
[Postgres CREATE INDEX](https://www.postgresql.org/docs/current/sql-createindex.html)
> feat(postgres): Support for CREATE INDEX CONCURRENTLY

- sqlglot/dialects/mysql.py
- tests/dialects/test_mysql.py
> Fix(mysql): don't wrap VALUES clause

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- tests/dialects/test_tsql.py
Fixes #3804
Docs
--------
[T-SQL STDEV](https://learn.microsoft.com/en-us/sql/t-sql/functions/stdev-transact-sql?view=sql-server-ver16)
> fix(tsql): Fix roundtrip of exp.Stddev

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse): improve parsing/transpilation of StrToDate

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
Fixes #3843
Reference: https://learn.microsoft.com/en-us/sql/t-sql/functions/json-query-transact-sql?view=sql-server-ver16
> Fix(tsql): handle JSON_QUERY with a single argument

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> Fix(tsql): bubble up exp.Create CTEs to improve transpilability

- sqlglot/dialects/presto.py
- tests/dialects/test_spark.py
Fixes #3854
Reference: https://prestodb.io/docs/current/functions/datetime.html
> Fix(presto): map %W to %A in the TIME_MAPPING

- sqlglot/optimizer/scope.py
- tests/test_optimizer.py
Fixes https://github.com/tobymao/sqlglot/discussions/3851
> Fix!(optimizer): detect correlation in derived tables nested within subqueries

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): support table qualification in USING clause

- sqlglot/parser.py
- tests/test_parser.py
> Fix(parser): improve performance of OUTER/CROSS APPLY parsing

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Reference: https://clickhouse.com/docs/en/sql-reference/statements/insert-into
> Feat(clickhouse): support PARTITION BY, SETTINGS in Insert expression

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
@treysp discovered an issue with the previous approach: `toTOrNull(value)` functions require `value` to be a string. Since we parse expressions like `CAST(x AS INT)` in Spark into a `TryCast`, that condition doesn't always hold. So, I implemented an alternative approach that Trey found (see [here](https://stackoverflow.com/a/69096497)), where we generate `Nullable(type)` instead. It looks like this behaves similarly to the `TRY_CAST` function.
The only gotcha (that I found) is that sometimes `TRY_CAST` in other dialects _can_ raise an exception, which won't always happen in CH as shown in the following example. Wasn't sure whether we want to always generate a warning when generating `TryCast` to let users know this may happen.
Spark (fails):
```
spark-sql (default)> select try_cast(date …
```
> Refactor(clickhouse): transpile TRY_CAST(x AS T) to CAST(x AS Nullable(T))

- sqlglot/dialects/oracle.py
- sqlglot/dialects/redshift.py
- sqlglot/expressions.py
- tests/dialects/test_oracle.py
Fixes #3934
References:
- https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions191.htm#SQLRF06124
- https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions037.htm
> Fix(oracle)!: preserve SYSDATE

- sqlglot/dialects/spark.py
- tests/dialects/test_spark.py
> Add support for `MINUS` keyword in `Spark`

- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Fix(parser): allow complex expressions for UNPIVOT alias

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse): add support for "@"-style parameters

- sqlglot/dialects/dialect.py
- tests/dialects/test_dialect.py
[This PR](https://github.com/tobymao/sqlglot/pull/2852) introduced the stripping of the target alias in the WHEN clauses of MERGE statements for Trino / Postgres.
However, it only needs to be stripped from the `THEN` part of the clause. It's still required in the `WHEN MATCHED` condition, if there is a condition defined.
Stripping it from the `WHEN MATCHED` condition produces the following error on Trino:
> TrinoUserError(type=USER_ERROR, name=AMBIGUOUS_NAME, message="line 1:471: Column 'a' is ambiguous"
And on Postgres:
> SQL Error [42702]: ERROR: column reference "a" is ambiguous
So this PR adjusts the logic to only strip the target alias from the `THEN` clause and leave the condition alone
> Fix!: exp.Merge condition for Trino/Postgres

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_spark.py
Fix https://github.com/tobymao/sqlglot/issues/3941
> Fix(parser): Support sqls with DESCRIBE partition 

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1724248183130339
> Fix(duckdb): TIME does not support modifiers

- sqlglot/dialects/duckdb.py
- sqlglot/expressions.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
Context: https://tobiko-data.slack.com/archives/C0448SFS3PF/p1724332762978299
> Feat: transpile from_iso8601_timestamp from presto/trino to duckdb

- sqlglot/expressions.py
- tests/test_expressions.py
Fixes a regression introduced by: https://github.com/tobymao/sqlglot/pull/3938
> fix: include dialect when parsing inside cast

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): handle DIV0 case where divident is null

- sqlglot/dialects/oracle.py
- tests/dialects/test_oracle.py
> fix(oracle): Use LTRIM/RTRIM for LEADING/TRAILING positions

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_mysql.py
Fixes #3983
Docs
-------
[MySQL JSON_VALUE()](https://dev.mysql.com/doc/refman/8.4/en/json-search-functions.html#function_json-value)
> feat(mysql): Parse JSON_VALUE()

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/fixtures/pretty.sql
> Fix(parser)!: preserve each distinct CUBE/ROLLUP/GROUPING SET clause

- sqlglot/dialects/dialect.py
- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
- tests/dialects/test_tsql.py
Fixes: https://github.com/tobymao/sqlglot/issues/3995
> fix(tsql): Use count_big instead of count

- sqlglot/dialects/dialect.py
- sqlglot/dialects/duckdb.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/starrocks.py
- sqlglot/jsonpath.py
- tests/dialects/test_dialect.py
- tests/dialects/test_starrocks.py
> Fix: don't log warning in to_json_path conditionally

- sqlglot/dialects/hive.py
- sqlglot/transforms.py
- tests/dialects/test_starrocks.py
Follow up to #3999
Refactor `generator` arg out of `unnest_to_explode()`
> feat!: Add UnsupportedError to unnest_to_explode transform

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
fixes #3783 
[Postgres DROP INDEX](https://www.postgresql.org/docs/current/sql-dropindex.html)
> fix(postgres): Support for DROP INDEX CONCURRENTLY.

- sqlglotrs/Cargo.toml
- sqlglotrs/pyproject.toml
> Chore: set the license for sqlglotrs

- sqlglot/dialects/oracle.py
- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
Fixes https://github.com/TobikoData/sqlmesh/issues/3080
> fix(parser)!: Ensure exp.Coalesce expressions is a list

- sqlglot/dialects/tsql.py
- tests/dialects/test_tsql.py
> fix(tsql): use plus operator for string concat to support more systems that use tsql

- sqlglotrs/pyproject.toml
Addresses https://github.com/tobymao/sqlglot/issues/4047#issuecomment-2332393032
Reference: https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata
> Chore: fill in more details for sqlglotrs pypi page

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #4083, #4085
Docs
----------
[Postgres MERGE](https://www.postgresql.org/docs/current/sql-merge.html) | [Postgres MERGE ... RETURNING](https://neon.tech/blog/top-3-features-in-postgres-17#merge-command-with-returning-support)
> feat(postgres): Parse DO NOTHING and RETURNING in MERGE statement

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
> Fix(parser)!: refactor exp.Chr

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
Fixes #4101
Docs
--------
[DuckDB Unpacked Columns](https://duckdb.org/2024/09/09/announcing-duckdb-110.html#unpacked-columns)
> feat(duckdb): Support *COLUMNS() function

- sqlglot/dialects/databricks.py
- sqlglot/dialects/dialect.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_databricks.py
- tests/dialects/test_snowflake.py
> fix: Move JSON path escape to generation

- sqlglot/optimizer/qualify_columns.py
- tests/test_optimizer.py
fixes tobymao/sqlglot#4112
also added test for this case
> fix(optimizer): Enable USING expansion with multiple joins

- sqlglot/optimizer/qualify_columns.py
Followup for https://github.com/tobymao/sqlglot/pull/4115
> Chore(optimizer): rename helper function in expand_using

- sqlglot/expressions.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
Reference: https://duckdb.org/docs/sql/data_types/union
> Feat(duckdb): add support for the UNION type

- sqlglot/generator.py
- tests/dialects/test_snowflake.py
> fix: Do not generate DISTINCT keyword in FILTER

- sqlglot/dialects/hive.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_presto.py
- tests/dialects/test_starrocks.py
Fixes #4158
Docs
------
[SO Thread](https://stackoverflow.com/questions/30776860/regular-expression-q-e)
> fix(hive)!: Enclose exp.Split with \E

- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
> fix: add support for UHUGEINT for duckdb

- sqlglot/diff.py
- tests/test_diff.py
> Fix: expand UPDATABLE_EXPRESSION_TYPES to account for Identifier changes

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/dialects/sqlite.py
- sqlglot/parser.py
- tests/dialects/test_sqlite.py
- tests/test_expressions.py
See the [corresponding issue](https://github.com/tobymao/sqlglot/issues/4196).
> StrPosition compilation path for SQLite

- sqlglot/parser.py
- tests/fixtures/pretty.sql
> Fix: attach comments to subquery predicates properly, fix comment case

- sqlglot/diff.py
- tests/test_diff.py
> Feat: allow supplying dialect in diff, conditionally copy ASTs

- sqlglot/dialects/tsql.py
- sqlglot/expressions.py
- tests/dialects/test_tsql.py
> Refactor!: Simplify PARSENAME <-> SPLIT_PART transpilation

- sqlglot/expressions.py
- tests/test_build.py
> Feat!: refactor set operation builders so they can work with N expressions

- sqlglot/parser.py
- tests/dialects/test_duckdb.py
> Fix(parser)!: produce exp.Column for the RHS of <value> IN <name>

- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_mysql.py
fixes #4236
reference: https://dev.mysql.com/doc/refman/8.4/en/select.html
> Feat(mysql): add support for operation modifiers like HIGH_PRIORITY

- sqlglot/dialects/starrocks.py
- tests/dialects/test_starrocks.py
Similar to snowflake, see: #2420
> Feat(starrocks): support for ALTER TABLE SWAP WITH

- sqlglot/dialects/dialect.py
- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
Docs
-------
[Snowflake TO_DOUBLE](https://docs.snowflake.com/en/sql-reference/functions/to_double)
> feat(snowflake)!: Support TO_DOUBLE function

- sqlglot/optimizer/scope.py
- tests/dialects/test_clickhouse.py
> clickhouse: fix traverse_scope with FINAL modifier

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Fixes https://github.com/TobikoData/sqlmesh/issues/3276
> Fix(clickhouse): properly parse CREATE FUNCTION DDLs

- sqlglot/parser.py
- tests/dialects/test_databricks.py
> Fix(parser): optionally parse a Stream expression

- benchmarks/optimize.py
- setup.py
- sqlglot/dialects/bigquery.py
- sqlglot/dialects/trino.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_trino.py
> Feat(trino): add support for the ON OVERFLOW clause in LISTAGG

- sqlglot/dialects/snowflake.py
- tests/dialects/test_bigquery.py
- BigQuery:
```SQL
SELECT PARSE_DATE('%Y%m%d', '20081225');
2008-12-25
```
- Snowflake:
```SQL
SELECT DATE('20081225', 'yyyymmDD');
2008-12-25
```
Docs
-----------
[BQ PARSE_DATE](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#parse_date) | [SF TO_DATE/DATE](https://docs.snowflake.com/en/sql-reference/functions/to_date)
> feat(snowflake): Transpile exp.StrToDate

- sqlglot/parser.py
- tests/test_parser.py
> fix(parser)!: Parse exp.Column for DROP COLUMN

- sqlglot/dialects/risingwave.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_risingwave.py
Cleaned up https://github.com/tobymao/sqlglot/commit/fc591ae2fa80be5821cb53d78906afe8e5505654#diff-27aa4e15e396712e087e156864ce3ab14c8d41041c8b3267e1ba9e2c5d77af8aR21.
cc @lin0303-siyuan
References:
- https://docs.risingwave.com/sql/commands/sql-create-source#create-source
- https://docs.risingwave.com/sql/commands/sql-create-sink
> Refactor(risingwave): clean up SINK/SOURCE logic

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_clickhouse.py
Cleans up https://github.com/tobymao/sqlglot/commit/0acc248361f49f68f17d799cbaf6b3de06c57f7e, cc @asikowitz 
Reference: https://docs.snowflake.com/en/sql-reference/sql/create-table
> Refactor(snowflake): clean up [WITH] TAG property / constraint

- sqlglot/dialects/dialect.py
- sqlglot/dialects/mysql.py
- sqlglot/expressions.py
- sqlglot/optimizer/canonicalize.py
- tests/fixtures/optimizer/canonicalize.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
- tests/test_optimizer.py
> Fix(optimizer)!: fix datetime coercion in the canonicalize rule

- sqlglot/dialects/presto.py
- tests/dialects/test_presto.py
> fix(presto): Remove parentheses from CURRENT_USER

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
> Fix(bigquery): properly consume dashed table parts

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
Fixes https://github.com/TobikoData/sqlmesh/issues/3465
> feat(optimizer)!: Alias expanded USING STRUCT fields

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> Fix(snowflake): generate only one INPUT => clause in unnest_sql

- sqlglot/dialects/dialect.py
- sqlglot/dialects/snowflake.py
- tests/dialects/test_bigquery.py
> Feat(snowflake): transpile date subtraction

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
> Fix(optimizer): only expand stars for select scopes

- sqlglot/optimizer/qualify_columns.py
- tests/fixtures/optimizer/qualify_columns.sql
> Fix(optimizer): qualify snowflake queries with `level` pseudocolumn

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
closes #4527
Reference: https://clickhouse.com/docs/en/sql-reference/data-types/map
> Feat(clickhouse): add support for bracket map syntax

- sqlglot/lineage.py
- tests/test_lineage.py
Extends the lineage functionality to work with pivot operation.
Works with pivot aggregations with and without alias.
> feat(lineage): Extend lineage function to work with pivot operation

- sqlglot/optimizer/qualify.py
- tests/fixtures/optimizer/optimizer.sql
- tests/test_optimizer.py
> fix!: normalize before qualifying tables

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes #4549
Reference: https://www.postgresql.org/docs/current/sql-insert.html
> Fix(postgres): add support for WHERE clause in INSERT DML

- sqlglot/dialects/__init__.py
- sqlglot/dialects/dialect.py
- sqlglot/dialects/druid.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_druid.py
Another stab at https://github.com/tobymao/sqlglot/pull/4475:
- Add a Druid dialect with type mapping.
- Add support to parser and generator for `CEIL(col TO unit)` and `FLOOR(col TO unit)`.
> feat: Druid dialect

- sqlglot/parser.py
- tests/test_transpile.py
Fixes https://github.com/TobikoData/sqlmesh/issues/3556
> Fix(parser): expand single VALUES clause in CTE into a SELECT *

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
see https://clickhouse.com/docs/en/sql-reference/data-types/dynamic
> feat(clickhouse): Dynamic data type

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
- tests/dialects/test_postgres.py
> feat(parser): Support Oracle/Postgres XMLNAMESPACES in XMLTABLE

- sqlglot/dialects/athena.py
- tests/dialects/test_athena.py
Currently, `PartitionedByProperty` is hardcoded to be generated as `partitioned_by` when routed to Athena's "Trino" engine.
However, this behaviour is only correct when `table_type='hive'`. When `table_type='iceberg'`, the property should be called `partitioning` instead.
Note that this only affects `CREATE TABLE.. AS SELECT` queries. `CREATE TABLE` is routed to Athena's Hive engine and handled differently.
This change addresses an issue in SQLMesh, https://github.com/TobikoData/sqlmesh/issues/3683
> Fix(athena): Generate PartitionedByProperty correctly on CTAS for an Iceberg table

- .github/workflows/python-publish.yml
Some references:
- https://github.com/actions/upload-artifact/issues/480
- https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
> Chore: fix sqlglotrs deployment job

- sqlglot/dialects/duckdb.py
- sqlglot/dialects/postgres.py
- sqlglot/expressions.py
- tests/dialects/test_postgres.py
Closes this [issue](https://github.com/tobymao/sqlglot/issues/4668)
Will be happy for review.
Thanks!
> Feat!: transpile postgres DATE_BIN function to duckdb TIME_BUCKET

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
Relevant ticket and PR:
- https://github.com/tobymao/sqlglot/issues/4670
- https://github.com/tobymao/sqlglot/pull/4671
> Fix(bigquery): type-annotated array literal logic edge case

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/fixtures/optimizer/qualify_columns.sql
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1739398974572499
> Fix(snowflake): unqualify ANY ORDER BY columns

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1739704817608639
> Feat(duckdb): transpile JSONB into JSON

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #4760
Reference: https://docs.snowflake.com/en/sql-reference/sql/use-secondary-roles
> Feat(snowflake): add support for USE SECONDARY ROLES

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_postgres.py
Fixes https://github.com/tobymao/sqlglot/issues/4763
Docs
--------
[Postgres WITH queries](https://www.postgresql.org/docs/current/queries-with.html)
> feat(postgres): Add support for WITH RECURSIVE search options

- sqlglot/generator.py
- sqlglot/parser.py
- tests/test_parser.py
Reverts https://github.com/tobymao/sqlglot/pull/4772 due to regressions in SQLMesh.
> Fix!: Revert #4772

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse): add support for dynamic json casting

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
Takes #4787 to the finish line.
> Fix(snowflake): add missing clauses in SHOW statements

- sqlglot/dialects/clickhouse.py
- sqlglot/expressions.py
- tests/dialects/test_clickhouse.py
> Feat(clickhouse)!: add support for and/2 and or/2 functions

- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
> Chore(optimizer): refactor DISTINCT ON qualification to better match ORDER BY

- sqlglot/parser.py
- tests/dialects/test_hive.py
Follow up on https://github.com/tobymao/sqlglot/pull/4832 
cc: @tsamaras 
Docs
---------
[Hive StorageHandler](https://hive.apache.org/docs/latest/storagehandlers_27362063/)
> Chore: Simplify Hive's STORED BY property

- sqlglot/dialects/duckdb.py
- tests/dialects/test_snowflake.py
> Chore:(duckdb): treat auto-increment DDL property as unsupported

- pdoc/cli.py
> Chore: fix pdoc deployment

- sqlglot/dialects/duckdb.py
- tests/dialects/test_duckdb.py
Reference: https://duckdb.org/2025/02/25/prefix-aliases-in-sql.html
> Feat(duckdb): add support for prefix aliases

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
- tests/test_lineage.py
> Fix(snowflake)!: treat TABLE(...) as a UDTF

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes https://github.com/tobymao/sqlglot/issues/4882
> fix(snowflake)!: Fix parsing multi-part format name

- sqlglot/generator.py
- tests/dialects/test_bigquery.py
Fixes https://github.com/TobikoData/sqlmesh/issues/4003
> Fix: apply unpivot alias string conversion only for UNPIVOT

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
Fixes https://github.com/TobikoData/sqlmesh/issues/4002
> Fix(clickhouse)!: parse parameter key as Var instead of Identifier

- sqlglot/lineage.py
- sqlglot/optimizer/annotate_types.py
- tests/test_optimizer.py
Fixes https://github.com/TobikoData/sqlmesh/issues/4004
> Fix(optimizer): handle TableFromRows properly in annotate_types

- sqlglot/dialects/tsql.py
- sqlglot/parser.py
- tests/dialects/test_tsql.py
> Feat(tsql): allow MERGE to be used in place of a subquery

- sqlglot/dialects/bigquery.py
- tests/dialects/test_bigquery.py
> Fix(bigquery): preserve time zone info in FORMAT_TIMESTAMP roundtrip

- sqlglot/dialects/hive.py
- tests/dialects/test_bigquery.py
> Fix(hive)!: handle string interval values in DATE ADD/SUB

- sqlglot/dialects/bigquery.py
- sqlglot/dialects/presto.py
- sqlglot/dialects/snowflake.py
- sqlglot/transforms.py
- tests/dialects/test_spark.py
Fixes https://github.com/tobymao/sqlglot/issues/4879
> Feat(presto)!: improve LATERAL VIEW EXPLODE transpilation

- sqlglot/dialects/presto.py
Relevant Slack thread: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1742910034056779?thread_ts=1742826420.141709&cid=C044BRE5W4S
> Fix(presto)!: only use ARRAY[...] syntax for Schema if parent is partitioned by prop

- sqlglot/dialects/duckdb.py
- tests/dialects/test_bigquery.py
> fix(duckdb)!: refactor length_sql so it handles any type, not just varchar/blob

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
return `exp.Create` instead of `exp.Command`
see https://docs.snowflake.com/en/sql-reference/sql/create-stage
> feat(snowflake)!: parse CREATE STAGE

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- sqlglot/tokens.py
- tests/dialects/test_snowflake.py
return `exp.Create` instead of `exp.Command`
see https://docs.snowflake.com/en/sql-reference/sql/create-file-format
> feat(snowflake)!: parse CREATE FILE FORMAT

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
return `exp.Show` instead of `exp.Command`
see https://docs.snowflake.com/en/sql-reference/sql/show-stages
> feat(snowflake): parse SHOW STAGES

- sqlglot/dialects/clickhouse.py
- sqlglot/dialects/dialect.py
- sqlglot/optimizer/qualify_tables.py
- tests/dialects/test_clickhouse.py
- tests/fixtures/optimizer/qualify_columns.sql
Fixes https://github.com/TobikoData/sqlmesh/issues/4056
> fix(clickhouse)!: Fix generation of exp.Values

- sqlglot/generator.py
- tests/fixtures/optimizer/optimizer.sql
- tests/fixtures/optimizer/tpc-ds/tpc-ds.sql
Fixes https://github.com/TobikoData/sqlmesh/issues/4098
> fix(generator)!: Fix pretty generation of exp.Window

- sqlglot/expressions.py
- tests/dialects/test_postgres.py
Fixes https://github.com/tobymao/sqlglot/issues/4999
> fix(postgres): Capture optional minus sign in interval regex

- sqlglot/dialects/duckdb.py
- tests/dialects/test_bigquery.py
- tests/dialects/test_duckdb.py
> Fix(duckdb): warn on unsupported IGNORE/RESPECT NULLS

- sqlglot/dialects/__init__.py
> Chore: put a lock around the lazy dialect module loading call

- sqlglot/dialects/postgres.py
- tests/dialects/test_postgres.py
> Feat(postgres): transpile QUARTER interval unit

- sqlglot/parser.py
- tests/dialects/test_databricks.py
> Fix(parser): parse column ops after no-paren type casting

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
Fixes #5032 
**DOCS**
[Trino day_of_week](https://trino.io/docs/current/functions/datetime.html#day_of_week)
[Snowflake DAYOFWEEKISO](https://docs.snowflake.com/en/sql-reference/functions/year)
> fix(snowflake): transpile expression DayOfWeekIso using DAYOFWEEKISO

- sqlglot/dialects/presto.py
- tests/dialects/test_snowflake.py
Fixes #5036 
**DOCS**
[Presto DOW](https://prestodb.io/docs/current/functions/datetime.html#dow-x-bigint)
[Presto DOY](https://prestodb.io/docs/current/functions/datetime.html#dow-x-bigint)
> feat(presto)!: parse DOW and DOY

- sqlglot/generator.py
- tests/dialects/test_bigquery.py
> Fix: prevent redundant backslash escapes in rawstring generator

- sqlglot/dialects/clickhouse.py
- sqlglot/parser.py
- sqlglot/transforms.py
- tests/dialects/test_clickhouse.py
- tests/test_transforms.py
> clickhouse: fix parsing of Null engine

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_oracle.py
> Feat: allow PIVOT to follow a JOIN

- CONTRIBUTING.md
- README.md
Fix Ibis and GitHub capitalization.
> docs: fix capitalization

- sqlglot/generator.py
- tests/dialects/test_tsql.py
- tests/fixtures/pretty.sql
> Feat: improve pretty-printing of MERGE statement

- sqlglot/dialects/dialect.py
- tests/fixtures/optimizer/annotate_functions.sql
> feat(optimizer): annotate SORT_ARRAY

- sqlglot/dialects/dialect.py
- sqlglot/dialects/presto.py
- sqlglot/helper.py
- tests/dialects/test_dialect.py
Public Slack thread for context: https://tobiko-data.slack.com/archives/C044BRE5W4S/p1748246900411949?thread_ts=1748243432.697819&cid=C044BRE5W4S.
> Chore!: error on unsupported dialect settings

- tests/dialects/test_dialect.py
- tests/dialects/test_starrocks.py
- tests/test_expressions.py
Follow up of https://github.com/tobymao/sqlglot/pull/5186
> chore: Clean up exp.ArrayIntersect PR

- sqlglot/dialects/snowflake.py
- sqlglot/dialects/starrocks.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
- tests/dialects/test_starrocks.py
- tests/test_expressions.py
Continuing from https://github.com/tobymao/sqlglot/pull/5191.
> Feat: improve transpilation of st_point and st_distance

- sqlglot/dialects/athena.py
- tests/dialects/test_athena.py
> Fix(athena): include Hive string escapes in the tokenizer

- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/optimizer/annotate_types.py
- sqlglot/optimizer/qualify_columns.py
- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
- tests/test_optimizer.py
Fixes #5207
I've described the issue in this comment: https://github.com/tobymao/sqlglot/issues/5207#issuecomment-2961924796. Let me know what you think.
> Fix(optimizer)!: resolve table "columns" in bigquery that produce structs

- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- tests/dialects/test_spark.py
> feat(spark, databricks): parse brackets as placeholder

- sqlglot/dialects/exasol.py
- tests/dialects/test_exasol.py
Implemented the Mod Function in exasol - https://docs.exasol.com/db/latest/sql_references/functions/alphabeticallistfunctions/mod.htm
> feat(exasol): implemented the Mod function

- sqlglot/optimizer/qualify_tables.py
- tests/fixtures/optimizer/qualify_tables.sql
> fix(optimizer): avoid qualifying CTE

- sqlglot/dialects/dialect.py
- tests/fixtures/optimizer/annotate_functions.sql
This PR adds support for `CHR`
**DOCS**
[BigQuery CHR](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#chr)
> feat(optimizer)!: annotate type for CHR

- sqlglot/dialects/dialect.py
- sqlglot/dialects/oracle.py
- sqlglot/dialects/redshift.py
- sqlglot/dialects/snowflake.py
- sqlglot/dialects/spark.py
- sqlglot/expressions.py
- sqlglot/generator.py
- sqlglot/parser.py
- tests/dialects/test_dialect.py
- tests/dialects/test_redshift.py
- tests/dialects/test_snowflake.py
> Fix!: preserve multi-arg DECODE function instead of converting to CASE

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- sqlglot/generator.py
- tests/dialects/test_snowflake.py
Fixes https://github.com/tobymao/sqlglot/issues/5406
Docs
--------
[Syntax](https://docs.snowflake.com/en/sql-reference/constructs/semantic_view#syntax) | [Examples](https://docs.snowflake.com/en/user-guide/views-semantic/querying#basic-examples)
> feat(snowflake): Support SEMANTIC_VIEW

- sqlglot/dialects/snowflake.py
- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #5426 
**DOCS**
[Snowflake ALTER TABLE ADD](https://docs.snowflake.com/en/sql-reference/sql/alter-table#table-column-actions-tablecolumnaction)
> fix(snowflake): ALTER TABLE ADD with multiple columns

- sqlglot/parser.py
- tests/dialects/test_snowflake.py
Fixes #5432 
**DOCS**
[Snowflake ALTER TABLE](https://docs.snowflake.com/en/sql-reference/sql/alter-table#table-column-actions-tablecolumnaction)
> fix(snowflake): ALTER TABLE ADD with IF NOT EXISTS

- sqlglot/dialects/duckdb.py
- sqlglot/tokens.py
- tests/dialects/test_duckdb.py
https://duckdb.org/docs/stable/sql/statements/set.html#reset
> Feat(duckdb): Add reset command for duckdb

- sqlglot/dialects/sqlite.py
- tests/dialects/test_sqlite.py
Fixes #5459
**DOCS**
[sqlite ATTACH](https://www.sqlite.org/lang_attach.html)
[sqlite DETACH](https://www.sqlite.org/lang_detach.html)
> feat(sqlite): support ATTACH/DETACH DATABASE

- sqlglot/dialects/teradata.py
- sqlglot/expressions.py
- tests/dialects/test_teradata.py
Add support for Teradata locking statement  -> https://docs.teradata.com/r/Enterprise_IntelliFlex_VMware/SQL-Data-Manipulation-Language/Statement-Syntax/LOCKING-Request-Modifier/Usage-Notes/Using-LOCKING-ROW
> feat(teradata): Add support for Teradata locking select

- sqlglot/dialects/duckdb.py
- sqlglot/parser.py
- tests/dialects/test_duckdb.py
- tests/dialects/test_snowflake.py
> fix(parser)!: more robust CREATE SEQUENCE

- sqlglot/dialects/dremio.py
- tests/dialects/test_dremio.py
add some dremio parsers and tests for DATE_FORMAT, TO_DATE, and TO_TIMESTAMP
> Feat(dremio): handle `DATE_FORMAT`, `TO_DATE`, and `TO_TIMESTAMP`

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[DAYOFWEEK](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/dayofweek/)
> feat(singlestore): Added generation of DAYOFWEEK_ISO function

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
Documentation:
* [WEEKDAY](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/weekday/)
* [DATE_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-format/)
> feat(singlestore): Added parsing of WEEKDAY function

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[DAY](http://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/day/)
> feat(singlestore): Fixed generation of DAY_OF_MONTH function

- sqlglot/dialects/doris.py
- sqlglot/expressions.py
- tests/dialects/test_doris.py
https://doris.apache.org/docs/sql-manual/sql-statements/table-and-view/async-materialized-view/CREATE-ASYNC-MATERIALIZED-VIEW
> feat(doris): add support for BUILD and REFRESH properties in materialized view

- sqlglot/dialects/doris.py
- sqlglot/expressions.py
- tests/dialects/test_doris.py
https://doris.apache.org/docs/table-design/data-partitioning/manual-partitioning
> Feat(doris): add support for PARTITION BY LIST

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[RLIKE](https://docs.singlestore.com/cloud/reference/sql-reference/regular-expression-functions/rlike-and-regexp/)
> feat(singlestore): Fixed generation of exp.RegexpLike

- sqlglot/dialects/singlestore.py
- sqlglot/expressions.py
- tests/dialects/test_singlestore.py
[JSON_ARRAY_CONTAINS_<type>](https://docs.singlestore.com/cloud/reference/sql-reference/json-functions/json-array-contains-type/)
> feat(singlestore)!: Added parsing/generation of JSON_ARRAY_CONTAINS function

- sqlglot/dialects/singlestore.py
- sqlglot/expressions.py
- tests/dialects/test_singlestore.py
[APPROX_PERCENTILE](https://docs.singlestore.com/cloud/reference/sql-reference/aggregate-functions/approx-percentile/)
> feat(singlestore): Fixed generation/parsing of exp.ApproxQuantile

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[VAR_SAMP](https://docs.singlestore.com/cloud/reference/sql-reference/aggregate-functions/var-samp/)
> feat(singlestore): Fixed parsing/generation of exp.Variance

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[INSTR](https://docs.singlestore.com/cloud/reference/sql-reference/string-functions/instr/)
> feat(singlestore): Fixed parsing/generation of exp.Contains

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[CHAR](https://docs.singlestore.com/cloud/reference/sql-reference/string-functions/char/)
> feat(singlestore): Fixed generation of exp.Chr

- sqlglot/optimizer/scope.py
- tests/fixtures/optimizer/qualify_columns.sql
> fix(optimizer): qualify columns for AggFunc with DISTINCT

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[JSON_PRETTY](https://docs.singlestore.com/cloud/reference/sql-reference/json-functions/json-pretty/)
> feat(singlestore): Fixed parsing/generation of exp.JSONFormat

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[DATE_FORMAT](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/date-format/)
> feat(singlestore): Implemented generation of exp.DateToDi

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[STR_TO_DATE](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/str-to-date/)
> feat(singlestore): Implemented generation of exp.DiToDate

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[CONVERT_TZ](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/convert-tz/)
> feat(singlestore): Implemented generation of exp.FromTimeZone

- sqlglot/dialects/dremio.py
- tests/dialects/test_dremio.py
https://docs.dremio.com/current/reference/sql/sql-functions/functions/REGEXP_LIKE/
https://docs.dremio.com/current/reference/sql/sql-functions/functions/REGEXP_MATCHES/
> feat: add dremio regexp_like and alias regexp_matches

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[DATEDIFF](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/datediff/)
[TIMESTAMPDIFF](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/timestampdiff/)
> feat(singlestore): Fixed generation of exp.DateDiff

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[DATEDIFF](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/datediff/)
[TIMESTAMPDIFF](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/timestampdiff/)
> feat(singlestore): Added generation of exp.TsOrDsDiff

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[RLIKE](https://docs.singlestore.com/db/v8.1/reference/sql-reference/regular-expression-functions/rlike-and-regexp/)
[LOWER](https://docs.singlestore.com/cloud/reference/sql-reference/string-functions/lcase/)
> feat(singlestore): Fixed generation of exp.RegexpILike

- sqlglot/dialects/hive.py
- tests/dialects/test_hive.py
> fix(hive): DATE_SUB to DATE_ADD use parens if needed

- sqlglot/optimizer/qualify_columns.py
- tests/test_optimizer.py
Fixes https://github.com/TobikoData/sqlmesh/issues/5262
> fix(optimizer): Do not qualify columns if a projection coflicts with a source

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
[CURRENT_TIMESTAMP](https://docs.singlestore.com/cloud/reference/sql-reference/date-and-time-functions/current-timestamp/)
> feat(SingleStore): Implemented generation of CURRENT_DATETIME

- tests/fixtures/optimizer/annotate_functions.sql
Add tests for endswith function.
Documentation: https://docs.snowflake.com/en/sql-reference/functions/endswith
> feat(snowflake): add tests for endswith function

- sqlglot/dialects/snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake LEFT, RIGHT and SUBSTRING. Add tests.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/substr
https://docs.snowflake.com/en/sql-reference/functions/left
https://docs.snowflake.com/en/sql-reference/functions/right
> feat(optimizer)!: annotate type for snowflake LEFT, RIGHT and SUBSTRING functions

- sqlglot/dialects/singlestore.py
- tests/dialects/test_singlestore.py
SingleStore doesn't support special prefix for national strings.
> feat(singlestore): Fixed generation of exp.National

- tests/fixtures/optimizer/annotate_functions.sql
Add tests for snowflake NOT ILIKE and NOT LIKE functions.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/ilike
https://docs.snowflake.com/en/sql-reference/functions/like
> feat(optimizer): Add tests for snowflake NOT ILIKE and NOT LIKE functions

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Documentation: https://docs.snowflake.com/en/sql-reference/functions/ai_summarize_agg
> feat(optimizer): annotate types for Snowflake AI_SUMMARIZE_AGG function

- sqlglot/dialects/snowflake.py
- tests/dialects/test_bigquery.py
https://docs.snowflake.com/en/sql-reference/functions/bitnot
> feat(snowflake): Add mapping of BITNOT

- sqlglot/dialects/clickhouse.py
- tests/dialects/test_clickhouse.py
> fix(clickhouse)!: parse tuple

- sqlglot/parser.py
- tests/dialects/test_presto.py
Fixes #5919
This was caused by the refactor #4094
> fix(parser): NULLABLE as an identifier

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
> fix(snowflake): parse DAYOFWEEKISO

- sqlglot/dialects/snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Links https://fivetran.atlassian.net/browse/RD-1036727
Documentation: https://docs.snowflake.com/en/sql-reference/functions/insert
> feat(optimizer): annotate type for Snowflake INSERT function

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Links https://fivetran.atlassian.net/browse/RD-1037152
Documentation: https://docs.snowflake.com/en/sql-reference/functions/jarowinkler_similarity
> feat(optimizer)!: annotate type for Snowflake JAROWINKLER_SIMILARITY function

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Links https://fivetran.atlassian.net/browse/RD-1038147
Documentation: https://docs.snowflake.com/en/sql-reference/functions/rtrimmed_length
> feat(optimizer)!: annotate types for Snowflake RTRIMMED_LENGTH function

- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake regexp function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/regexp
> chore(optimizer): Annotate type for snowflake regexp function

- sqlglot/dialects/snowflake.py
- sqlglot/expressions.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Links https://fivetran.atlassian.net/browse/RD-1038076
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/regexp_count
https://docs.databricks.com/aws/en/sql/language-manual/functions/regexp_count
> feat(optimizer)!: annotate type for Snowflake REGEXP_COUNT function

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake SOUNDEX function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/soundex
> feat(optimizer): Annotate type for snowflake SOUNDEX function

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake TRANSLATE function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/translate
> feat(optimizer): Annotate type for snowflake TRANSLATE function

- sqlglot/dialects/snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Links https://fivetran.atlassian.net/browse/RD-1038084
Documentation: https://docs.snowflake.com/en/sql-reference/functions/regexp_instr
> feat(optimizer)!: annotate type for Snowflake REGEXP_INSTR function

- sqlglot/dialects/snowflake.py
- tests/dialects/test_snowflake.py
- tests/fixtures/optimizer/annotate_functions.sql
Annotate type for snowflake STRTOK_TO_ARRAY function.
Documentation:
https://docs.snowflake.com/en/sql-reference/functions/strtok_to_array
> feat(optimizer)!: Annotate type for snowflake STRTOK_TO_ARRAY function

- sqlglot/tokens.py
- sqlglotrs/src/tokenizer.rs
- tests/dialects/test_duckdb.py
> Fix: handle unicode heredoc tags & Rust grapheme clusters properly
